### ISSUE TITLE
Allow Federal Users to See and Access Submitted APDs in Dashboard

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/eAPD#1012]
Now that we have the app flow up and working, we need to create a different experience for Federal and State users. State users need to be able to see only their state's work, while federal users need to be able to see and access all submitted APDs (by all states). 

This can be the same dashboard that we have, but for federal users it shows all of the submissions in a big "tracker" (list). Then from there, a federal user can click on any of the APDs, and use that as a launching point to comment and review. 

### This task is done when...
 - [ ] Federal users can see submitted APDs from states
 - [ ] Federal users can click on submitted APDs to open them for viewing.

**Comment by jeromeleecms** [comment]
Closing this so we can stand up a Federal reviewer experience based on the current state of the app.
