### ISSUE TITLE
Document the research process in the wiki

### ISSUE THREAD

**Issue by lauraponce** [CMSgov/eAPD#1130]
Add the UX research process to the [wiki](https://github.com/18F/cms-hitech-apd/wiki) in the research documentation section. 

### This task is done when...
 - [x] Research timing/frequency recommendations are added to the wiki (some of the work was started in #1084)
 - [x] The research process we've been utilizing has been clearly documented in the wiki

**Comment by beparticular** [comment]
This has been completed in the wiki. I'll take a look at it again for any edits when onboarding a new designer. 

https://github.com/CMSgov/eAPD/wiki/User-research-process
