### ISSUE TITLE
[Proposal] Extract budget calculations into a 3rd module

### ISSUE THREAD

**Issue by mgwalker** [CMSgov/eAPD#1183]
I suggest that at some point in the future we spend a little time to extract the budget calculation logic from the web app into a separate, standalone component and publish that separately from everything else.  The primary benefit is that we can then have that exact same logic in multiple apps without having to reinvent anything.

For example, right now the backend doesn't do any budget calculations - it relies on the frontend to create and store the budget tables.  That's not a good data practice long term - it's risky to accept data from the frontend blindly.  If the API could build the budget tables itself, that would be ideal.  With an "APD budget" module, the frontend and backend could use the exact same logic and then we could make the API the source of truth for the tables.

**Comment by thetif** [comment]
OBE
