### ISSUE TITLE
Implement End-To-End Tests

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#1243]
Currently, the app does not have end-to-end testing, but it is worth exploring if and when this should be included. From a discussion with Greg, this might be a worthwhile to model how to implement for future projects as well.

As a suggestion, the team could validate the work done by Nick in his sample APD and that could form the basis for an end-to-end test.

### This task is done when...
 - [x] Explore implementing end-to-end tests
 - [ ] Document what is needed to implement and the level of effort
- [ ] If appropriate, a separate issue is spun up to track the dev process

Please feel free to edit this description if more specifics are needed.

**Comment by eStar386** [comment]
Cypress is the defacto end to end test automation tool based on prior research.  @NAretakis @jeromeleecms Can a link be provided to the sample apd.

**Comment by thetif** [comment]
Being addressed in separate tickets
