### ISSUE TITLE
Determine the error style and interaction on the account management pages

### ISSUE THREAD

**Issue by lauraponce** [CMSgov/eAPD#1478]
On the account management pages (Create account and Manage account), the errors appear at the top of the page like this:

<img width="552" alt="Screen Shot 2019-04-17 at 2 49 58 PM" src="https://user-images.githubusercontent.com/21222704/56374696-aa447280-61b8-11e9-8159-94ed17a8d967.png">

This can be a problem because the page doesn't automatically scroll back up to the top where the error/success message is visible if users aren't on a large screen.

There are probably a few ways to solve for this, one option is to use the same type of error handling as the app with the notification appearing near the button:

![Screen Shot 2019-04-18 at 9 02 58 AM](https://user-images.githubusercontent.com/21222704/56374848-f7284900-61b8-11e9-980c-053ca6219f36.png)
![Screen Shot 2019-04-18 at 9 03 05 AM](https://user-images.githubusercontent.com/21222704/56374849-f7284900-61b8-11e9-9007-25e8ecf09ef3.png)

Another option would be to scroll back up to the top of the page after a user clicks the Save changes button. There are also probably other ways to solve for this, so this issue is to determine the best way to handle this from a design perspective.

### This task is done when...
 - [ ] The errors/success messages are clearly visible for everyone on the account management pages

**Comment by beparticular** [comment]
Closing this since we won't be creating accounts in our system, but in EUA/Okta.
