### ISSUE TITLE
Complete VPAT for CMS 508 Testing

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#1529]
While we may be able to go to pilot without 508 testing, we will still be required to pursue 508 testing. 

Per the CMS 508 team, we will be required to complete a VPAT to move forward with 508 testing in preparation for release beyond the pilot:

https://www.itic.org/policy/accessibility/vpat

The document may be submitted to the 508 team before we request a formal 508 review from CMS.

### This task is done when...
 - [x] VPAT completed
 - [x] VPAT submitted to 508 team for review

**Comment by jeromeleecms** [comment]
We received an OK from the 508 team that we can run the pilot without 508 testing as long as we run work on getting 508 tested concurrently with the pilot (and before scaling).

**Comment by jeromeleecms** [comment]
Will follow-up with MITRE to look at next steps. May need to reassign to them in the future.

**Comment by jeromeleecms** [comment]
Rohit Paul from MITRE is working on this.

**Comment by nicholeweems** [comment]
Per update from Rohit during sprint refinement, this story may be close upon completion of #2501.

**Comment by rohitpaul** [comment]
508 team accepted VPAT.
