### ISSUE TITLE
Request / Complete CMS 508 Testing

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#1531]
As part of the condition for the team to scale the eAPD to users beyond the pilot, we need to concurrently perform and complete 508 testing. 

### This task is done when...
 - [x] Request 508 testing to be scheduled from the CMS IT Help Desk
 - [x] Complete 508 testing with the CMS IT Help Desk

**Comment by nicholeweems** [comment]
Test has been scheduled and waiting for results which inform future issues to create on the board.
