### ISSUE TITLE
Explore progress indicator design

### ISSUE THREAD

**Issue by lauraponce** [CMSgov/eAPD#1788]
From the update experience usability testing, it came up that there was a user need for marking items as done/reviewed, needing to see how much work still remains, and needing to know what has been completed/reviewed so far.

The CMS design system has a step pattern that could potentially work here: https://design.cms.gov/patterns/step-list/ 

### This task is done when...
 - [ ] Research has been completed on how folks keep track of their completed and needed work. Might happen in the foundational research for update experience.

**Comment by beparticular** [comment]
@jeromeleecms as we start to explore the error check for validation, is a progress indicator something we still want to hang onto in the backlog?

**Comment by jeromeleecms** [comment]
I'm open to it if this will help build a framework for validation and eventually into the MES expansion. Let's chat a little more to establish what we think would be a reasonable scope.
