### ISSUE TITLE
Get CMS access to the AWS environment

### ISSUE THREAD

**Issue by mgwalker** [CMSgov/eAPD#1908]
Currently our AWS environment is administered by 18F. Someone from CMS should take ownership of that. It doesn't need much attention, but _someone_ has to be in control of it!

### This task is done when...
 - [ ] someone from CMS has AWS credentials
 - [ ] ☝️ that person has access to the eAPD resources

**Comment by jeromeleecms** [comment]
@cthulhuplus To provide @jeromeleecms and @NAretakis template for access.

**Comment by cthulhuplus** [comment]
This is the ticket that I opened to get AWS access to our AWS account, I'm not sure what access you need/want, it's probably different than the access level of a DevOps Engineer.

https://jiraent.cms.gov/browse/CLDSUPSD-5881

**Comment by NAretakis** [comment]
So... @cthulhuplus  this looks like it might be done from that jira ticket, yes?

**Comment by cthulhuplus** [comment]
@NAretakis does someone from CMS have access to the AWS environment? If yes, then I would consider this to be done.

**Comment by NAretakis** [comment]
Pretty sure I do. Let me check, lol.
