### ISSUE TITLE
Explore use case where a state would need to print sections of the APD

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2115]
There will likely be instances where states need to print and distribute only certain sections of the APD, while keeping other sections protected from view.

### This task is done when...
 - [ ] Use case(s) have been provided for review and discussion.
 - [ ] A decision has been made about if/when/how to address the need.

**Comment by CSwartzHMA** [comment]
Use Case - When a state uses an external vendor for work described within one activity of the APD, that section may need to be reviewed by the responsible vendor and possibly updated in future iterations by that vendor. Other areas may need to be protected from view as they are not relevant to that vendor's work. Printing the entire APD may not be necessary and may not always allow for page breaks where needed. An option to select certain sections for printing may be a nice-to-have. Other solutions may also be possible.

**Comment by jeromeleecms** [comment]
We should consider this at a higher level where components are visible vs. just printing components.
