### ISSUE TITLE
Review "no content" errors in activity cost sections

### ISSUE THREAD

**Issue by mgwalker** [CMSgov/eAPD#2151]
When an activity's state personnel, non-personnel expenses, or private contractor costs are empty, we display an error alert (which is truly not an error):

![screenshot of the error alert, reading "There are no personnel resources for this activity"](https://images.zenhubusercontent.com/5707ce4abf93871ccd9917fb/dd185b59-fbcd-4c29-a2d2-280d783af59f)

Is this the behavior we want? [Jerome noted](https://github.com/18F/cms-hitech-apd/pull/2148#pullrequestreview-385688306) that it makes it look like he did something wrong, when this is actually just the default state for new APDs and new activities.

Also, it would make sense for the button to say something different since there aren't any personnel yet. "Another" is probably the wrong word. :stuck_out_tongue:

### This task is done when...
 - [x] we've decided what to do

**Comment by beparticular** [comment]
@jeromeleecms since we've changed the content in these areas, the errors are no longer correct in what they note is missing. 

Since we're moving forward on proper validations, can we revisit this ticket either to make the "errors" have the right language, or to not show the "errors".

**Comment by jeromeleecms** [comment]
Sounds good - I also heard in the user testing that one of the states actually like the way this content was displayed.

**Comment by beparticular** [comment]
@jeromeleecms 

Let's keep the error design as is for now, but use better language as described below to match the headers and content in these sections. 
We should also accurately say what is happening - nothing is "missing"  and we can't say no resources exist, they have just not been added. 

Error 1 on page should be: 
State staff have not been added for this activity. 

Error 2 on page should be:
Other state expenses have not been added for this activity. 

![Screen Shot 2020-08-12 at 10.55.15 AM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/cecf9b4b-7ca5-451a-a183-422a463aaba6)


For consistency, we'll also need to update this error on the private contractors cost page
Error should be: 
Contracts or contractors have not been added for this activity. 
![nocontractors.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/e1c47f9c-c22e-4612-ab9b-7da28c7057cb)

**Comment by beparticular** [comment]
@thetif do you need a mock up, or is this info ok? 
Seems like it would be best to add creating errors for the OKRs and Milestones section here in this ticket with the other errors. Once #2152 is complete, errors will need to be shown in the same pattern as the above errors. So I believe when this becomes a dev issue, it will be blocked by #2152. 

Error text 1: 
Objectives have not been added for this activity.

Error text 2: 
Milestones have not been added for this activity.

**Comment by jeromeleecms** [comment]
@beparticular If we are aiming for consistency in the language, for private contractors, it seems the language should read

"Private contractors have not been added to this activity."

Other than that, this looks fine.

**Comment by thetif** [comment]
This one was blocking #2152 so I'll just move these decision over there and it will be unblocked.

**Comment by thetif** [comment]
I updated the ticket to include the image of the error message and these updates to the text

- State Cost Categories - State staff: State staff have not been added for this activity.
- State Cost Categories - Other state expenses: Other state expenses have not been added for this activity.
- Private Contractor Costs: Private contractors have not been added for this activity.
- Objectives & Key Results (OKR): Objectives have not been added for this activity.
- Milestones: Milestones have not been added for this activity.

Did I miss anything?

**Comment by beparticular** [comment]
@thetif this looks like everything. thanks!
