### ISSUE TITLE
Allow users to delete the last activity cost entry

### ISSUE THREAD

**Issue by mgwalker** [CMSgov/eAPD#2152]
Currently we do not allow the user to delete the last cost entry from the activity state staff, other state expenses, private contractor costs, or OKRs lists. Now that activities start with none of those costs, should users also be able to remove them?

New activities currently get a single empty objective and milestone on the Objectives & Key Results (OKR) page.  But they get zero State Staff and Other State Expenses entries (on the "State Cost Categories" page) and zero "Private Contractor Costs" entries.

Each of these items has "edit / remove" next to it, unless it's the last one, in which case it only has "edit".  This change will allow the last one to be removed, which will return us to the state when the activity was first created.  In the case of objectives and milestones, when the last one is "removed" we will probably need to leave a single empty one in place (need to research this).

When last entry is removed an error message should appear like this:

![image.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/45ad9c93-7ee2-4e17-9831-2f44a48b2003)

The error messages should read:
- State Cost Categories - State staff: State staff have not been added for this activity.
- State Cost Categories - Other state expenses: Other state expenses have not been added for this activity.
- Private Contractor Costs: Private contractors have not been added for this activity.
- Objectives & Key Results (OKR): Objectives have not been added for this activity.
- Milestones: Milestones have not been added for this activity.

### This task is done when...
 - [ ] users are allowed to delete the last activity cost entry in activity state staff, other state expenses, private contractor costs, or OKRs lists
-  [ ] error messages have been added if there are no items left in the list and they have the correct wording

**Comment by thetif** [comment]
@beparticular should I make this ticket dependent on #2151?

**Comment by beparticular** [comment]
@thetif yeah, let's do that so we have a record that we need to chat about #2151 next week
