### ISSUE TITLE
Add "Potential Foreseeable Risks" section in Activities

### ISSUE THREAD

**Issue by lauraponce** [CMSgov/eAPD#2168]
Thinking about the oversight role of CMS reviewers in determining if the state's projects have a high likelihood of succeeding, it could be helpful to have states consider any risks to their activities.

We have a question about `Alternative Considerations` which talks about alternatives, but it seems like there is room for states to think about risks to the option they chose. And if they can't come up with any risks, it might be a sign that they haven't thought about it hard enough (and maybe should)? 

To take it one step further, if there are risks, they should be able to explain how they're mitigating them. 

(Author note for what sparked this issue: talked to Nikki Lee about her work on the CMS oversight project.)

### This task is done when...
 - [x] Explore the feasibility of adding a Risks question in Activity Overview for each activity
 - [x] Make a decision on moving forward with this or not (or tabling it for later)
 - [x] Alternative Conditions design is reviewed by Comms (as requested in the last comment below)
 - [x] Foreseeable Risks field(s) are created 
 - [x] Updates to Alternative Considerations and Foreseeable Risk

**Comment by jeromeleecms** [comment]
Just to document our action item on this, we are going to short term:

1) Ensure Help text is in the alternative analysis section of the APD (#2171)
2) Review whether or not we need to have a separate section to call out the risk analysis at a separate point within the application.

**Comment by jeromeleecms** [comment]
For the MES expansion, this could be included in the requirements in 45 CFR 95.610that asks for: 

(3) A requirements analysis, feasibility study and a statement of alternative considerations including, where appropriate, the use of service-orientated architecture and a transfer of an existing system and an explanation of why such a transfer is not feasible if another alternative is identified;

(4) A cost benefit analysis;

Will need to consider how to bring this into the app.

**Comment by beparticular** [comment]
@CSwartzHMA will look at the regulation and suggest some fields we would include to capture this information .

**Comment by CSwartzHMA** [comment]
As a consideration: My understanding is that this will not replace the current Statement of Alternative Considerations field, nor will it be in the same section. 
If this is to be at the Project level, possible wording for a field that could address this:

Describe your risk analysis, including any requirements analysis, feasibility study, sustainability considerations and a cost benefit analysis, including, where appropriate, the use of service-orientated architecture and a transfer of an existing system and an explanation of why such a transfer is not feasible if another alternative is identified.

This captures the regulatory language without being duplicative, if we are to keep the Alternative Considerations field separate. I added something about sustainability, which may not belong here, but might help prompt states to think about things they talk about and include today in their APD.

**Comment by CSwartzHMA** [comment]
Also, noting that this regulation applies to IAPDs.

**Comment by CSwartzHMA** [comment]
The current (? the one I have is dated 2015, so I will verify this) template for E&E includes: 
_If a requirements analysis was conducted for the work to be completed via this funding request,
then the state should provide a summary of the results. If the state did not conduct a
requirements analysis, then it should explain why not. Also, the state should indicate whether
a requirements analysis is waived by law or is not required in regulation.

If a feasibility study was conducted for the work to be completed via this funding request, then
the state shold provide a summary of the results. If the state did not conduct a feasibility study,
then it should explain why not. Also, the state should indicate whether a feasibility study is
waived by law or is not required in regulation. Note that CMS regulations only allow 50 percent
Federal financial participation (FFP) for feasibility studies.

The state should describe any alternatives that the State Medicaid Agency considered regarding
implementing work to be completed via this funding request. Where differing alternatives and
approaches were studied or assessed, the state should provide a brief description of each
option considered, and a justification should be provided for the approach or option that was
ultimately selected._ 

This is a lot, but I think we could use some of this for help text, particularly the last sentence.

**Comment by akuas** [comment]
@CSwartzHMA  in the prototype, Statement of Alternative Considerations does not replace Foreseeable risks but the field for alt. considerations is on the same page and above the foreseeable risks. Right now, it's at the activity level but it will be insightful to find out from users what they feel about that.

**Comment by akuas** [comment]
@CSwartzHMA thanks, the second comment is particularly helpful. We will probably have to edit it down so that there isnt a huge block of text but the language does allow smaller states that do not have a robust cost benefit analysis laid out to put as much information as its appropriate. I think ill include this text for our design sync and we can work from there.

**Comment by NAretakis** [comment]
Adding language for this section. In the reg these are sort of all combined into one section so we have to think about how to present it in the eAPD. Might be 1 field, could be 4 fields, or somewhere in between. All sort of under the header of this "section".

If a requirements analysis was conducted for this activity, then the state should provide a summary of the results. If the state did not conduct a requirements analysis, then it should explain why not. Also, the state should indicate whether a requirements analysis is waived by law or is not required in regulation.

If a feasibility study was conducted for this activity, then the state should provide a summary of the results. If the state did not conduct a feasibility study, then it should explain why not. Also, the state should indicate whether a feasibility study is waived by law or is not required in regulation. Note that CMS regulations only allow 50 percent Federal financial participation (FFP) for feasibility studies.

The state should describe any alternatives that the State Medicaid Agency considered regarding this activity. Where differing alternatives and approaches were studied or assessed, the state should provide a brief description of each option considered, and a justification should be provided for the approach or option that was ultimately selected.

The state must consider sharing, leverage and reuse of Medicaid technologies, including custom open source development, reusing systems that already exist within the state, reusing systems built for other states available under 45 CFR §95.617, licensing or purchasing COTS software or SaaS, or engaging in collaboration with other states.

**Comment by beparticular** [comment]
@CSwartzHMA @NAretakis for Content review - 

The Activity Overview page has been broken down into three screen, one being the Alternative Considerations and Foreseeable risks page.

Original solution - The page would have one field that require users to explain the alternatives they exhausted and the costs, benefits, and risks of each option.

Current idea - Since we are enforcing that users conduct feasibility studies, cost benefit analysis, requirements analysis, and alternative analysis(or at least explain why they are exempt), we have opted breaking down the one field into four. 
**But the page has a lot of copy and I wonder if we can shorten it somehow. Also, design needs guidance on what fields to include for foreseeable risks.**

### This task is done when...
 - [ ] Alternative Conditions is reviewed by Comms
 - [ ] Foreseeable Risks field(s) are created 
 - [ ] Updates to Alternative Considerations and Foreseeable Risk
 
Alternative Considerations and Foreseeable Risks:
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=2630%3A1

**Comment by akuas** [comment]
[Considerations Analysis and Risks Design](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=2630%3A1)

**Comment by akuas** [comment]
@CSwartzHMA  for reference, here is a png of the Considerations Analysis, feel free to comment to it on figma or respond here.![Forseeable Risks and Alternative Considerations.png](https://images.zenhubusercontent.com/601acfa212e5437689f6079c/84eedd49-8354-4eda-b0c9-0560f5b0b5ed)

**Comment by CSwartzHMA** [comment]
Potential edits for consideration:
Change Considerations Analysis and Risks to Analysis of Alternatives and Risks
Change "The Considerations Analysis and Risks gives context to an activity and the alternatives explored and exhausted to reach a set decision." to "Provide context on the process for selection of the approach described in this activity and alternatives considered."
Keep "If this a previously approved activity, only use this section to discuss alternative considerations
made for substantive changes/decisions made during the implementation of the project. Don’t include historical considerations in this current activity. "
Edits to help text: The state must consider opportunities to share, leverage and reuse Medicaid technologies, including custom open source development, reuse of systems that already exist within the state, reuse of systems built for other states available under 45 CFR §95.617, licensing or purchasing COTS software or SaaS, or engaging in collaboration with other states."
Keep: Alternative Analysis
Edits: Describe any alternatives considered regarding this activity, including how each potential approach was studied or assessed. Provide a brief description of each option considered, and a justification for the approach or option that was ultimately selected.
Keep: Cost Benefit Analysis
Edit: Explain consideration for costs and benefits of each option described above. As applicable, include how
the selected approach supports the economic and efficient management of the Medicaid program.
Keep: Feasibility Study
Edit: If a feasibility study was conducted for this activity, provide a summary of the study and the results. If no feasibility study was conducted, explain the reason. If a feasibility study is waived by law or is not required in regulation, explain the exception. 
Keep: Requirements Analysis
Edit: If a requirements analysis was conducted for this activity, provide a summary of the analysis and the results. If no requirements analysis was conducted, explain the reason. Indicate whether a requirements analysis is waived by law or is not required in regulation. 
Keep: Foreseeable Risks
Edit: Describe any foreseeable risks associated with your proposed solution, including the strategy for mitigation of the identified risk(s). 
Edit Example: A potential risk to the proposed solution is system outage and downtime.  The state has determined the risk can be minimized when proper precautions are in place and a plan for communications for outages has been established. The state accepts this risk and will oversee the mitigation efforts through monitoring and oversight of contract service level agreements.

**Comment by akuas** [comment]
@CSwartzHMA Thanks for the thorough feedback, Ill include the edits today.

**Comment by NAretakis** [comment]
this looks good to me.

**Comment by beparticular** [comment]
This issue is done as far as design goes for the prototype. It will be tested the week of April 19. If there are any additional changes after testing, this issue can be re-opened as needed to help with continuity of the design and to hand off final designs to dev in one issue.
