### ISSUE TITLE
Arrows in the side nav should be consistent

### ISSUE THREAD

**Issue by pphillips-fearless** [CMSgov/eAPD#2188]
Arrows that expand the sections in the side navigation are inconsistent as to when they appear (always vs. just when the nav item is selected).  Research why the inconsistency occurs, decide how it should be, and implement a fix

### This task is done when...
 - [x] we understand why it's inconsistent
 - [ ] we've decided on how it should appear, which is a visual indication that there is sub-navigation within a section, not that the section would be displayed
 - [ ] we've implemented a fix

**Comment by jeromeleecms** [comment]
Also for reference, the Design System has the arrows persist:
https://design.cms.gov/components/vertical-nav/

**Comment by beparticular** [comment]
1. In the design system, the Introduction Section in their navigation has no arrow as it has no sub nav. 

2. Another difference between our nav and the design system nav is that in the design system the top navigation doesn't take you to a page, it just opens the sub nav menu. 
So, the arrows are used to indicate that another menu is being opened. 

In our system, we currently only have the arrows appear when a sub nav menu is clicked on and opens the nav and page at the same time. 

The more ideal choice for us would be to show the arrows for sections when there is a sub nav that can open and not show an arrow when clicking on an item will open a page with no sub nav options.

**Comment by radavis** [comment]
Example of arrows being "inconsistent":
- navigate to an APD
- select the "Key State Personnel" list item from the VerticalNav
- note that the "Program Activities" list item does not indicate there are sub-items within that section via a '⌄' Chevron Down Arrow.

![Screen Shot 2020-05-28 at 11.38.06 AM.png](https://images.zenhubusercontent.com/5e62a052e57324bfda300f92/492fa220-a92d-4d15-bff4-26b6be7883f8)

> The more ideal choice for us would be to show the arrows for sections when there is a sub nav that can open and not show an arrow when clicking on an item will open a page with no sub nav options.

To restate the ask: We want to add the '⌄' Chevron Down Arrow to the VerticalNav sections that have sub-sections when not selected/unexpanded.

**Comment by pphillips-fearless** [comment]
Yes, I think you've captured the essence of the issue.  @beparticular can you please confirm?

**Comment by beparticular** [comment]
@radavis that's a great write up. thank you!

**Comment by radavis** [comment]
We now understand how the VerticalNav is inconsistent. I see value in hiding these subsections from the user until this information is relevant (when the user is working on that section). What is the business value for showing the subsections at all times within the VerticalNav?

**Comment by pphillips-fearless** [comment]
do we need to have business need for things like consistency, being well organized, looking nice?

**Comment by radavis** [comment]
I'm trying to nail down the second item in our "This task is done when..." list: "we've decided on how [the VerticalNav] should appear." I see value in consistency. I also see value in hiding details until they are relevant.

**Comment by beparticular** [comment]
2nd item seemed like it was answered by "We expect to see a '⌄' Chevron Down Arrow for each unexpanded VerticalNav item that has sub-items."

There was not an intent of showing the subsections at all times. 

The business value here is consistency through using the design system.

**Comment by radavis** [comment]
![eapd-v2.2.0.png](https://images.zenhubusercontent.com/5e62a052e57324bfda300f92/7374b07b-9c07-4bb4-94b3-409a93067e34)

Release v2.2.0 shows the previous desired behavior of the VerticalNav. (Using @cmsgov/design-system v1.32.1)
