### ISSUE TITLE
State Permissions: Create new APD functionality/button on splash page

### ISSUE THREAD

**Issue by jjames521** [CMSgov/eAPD#2196]
Create new APD functionality and button needs to be fleshed out on what we might do if a user doesn't have access. 

This is spun off of issue #2146 

This pertains to several "states" or entities that would be interacting with the eAPD app.  

Including but not yet fleshed out:

State

- State w/ permission

- State w/o permission

- State reviewer

### This task is done when...
 - [x] Decide what permissions we need at release

 - [ ] Figure what entities will need what permissions and the functions of those permissions

- [ ] What to do with the entities if they need to gain access or if we need to hide functionality all together

**Comment by beparticular** [comment]
@jjames521 from our convo earlier

The structure for the mock up would be:

FFY 2020
Activity 1 (use data provided by state, add KP example)
Activity 2 (duplicate Activity 1 for example)

Combined Activity 
HIT (combined data provide by state + duplicate example) 
HIE (no information, an indication that this is not live for this mockup)
MMIS (no information, an indication that this is not live for this mockup)

FFY 2021
Activity 1 (use data provided by state, add KP example)
Activity 2 (duplicate Activity 1 for example)

Combined Activity 
HIT (combined data provide by state + duplicate example) 
HIE (no information, an indication that this is not live for this mockup)
MMIS (no information, an indication that this is not live for this mockup)

**Comment by jjames521** [comment]
@beparticular 

Just to document what I have so far on this,

Looks like three users can be identified clearly and have the following "powers"

w/permissions

- Able to create new

w/o permissions

- Unable to create new, needs to request from admin for establishing powers

- Clickable button but pop up comes up to issue an alert on what actions need to take place

Reviewer

- Not able to create new, no button present

- Establishing of review link on individual APD's that are up for review, only able to see what is sent up to them.

These are the mockups of the experience I have so far 

![State Dash Splash.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/7a177c3c-8bae-4806-9944-8fc12c170dc9)

![NotAuthVer1.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/a4dca7a3-faf7-4d04-8766-dd3685a94225)

**Comment by jeromeleecms** [comment]
After thinking through this some more, can we scope this issue further down to just do an assessment of what role we'll need for our initial release? Open to feedback.

**Comment by beparticular** [comment]
@jjames521 as we move into the new designs around log in and authentication, can this issue be closed?
CC @jeromeleecms

**Comment by beparticular** [comment]
Closing this as it's not relevant with where we're going for release. Will address more holistically when we get to more granular permissions.
