### ISSUE TITLE
Federal Permissions: Create new APD functionality/button on splash page

### ISSUE THREAD

**Issue by jjames521** [CMSgov/eAPD#2197]
This task relates to #2196 and reflects the same ideas on permissions for Federal roles.

Also relates to #2146 for context

### This task is done when...
 - [ ] Figure out permissions for Federal roles
 - [ ] What to do in terms of functionality

**Comment by beparticular** [comment]
Closing this as it's not relevant with where we're going for release. Will address more holistically when we get to more granular permissions.
