### ISSUE TITLE
Transfer 18F Repository to CMS eAPD Repository

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#2203]
Transfer 18 F repository to CMS repository

### This task is done when...

- [x] Make sure "all" code is commited to 18F repository
- [x] Freeze commits to 18F repository

**GitHub**

- [x]  Transfer 18F repository to CMS eAPD repo
- [x]  Confirm all issues, branches, labels, epics, and organization data came over
- [x]  Confirm all parties have appropriate privileges and access of new CMS eAPD repository

**CircleCI**
- [x]  Upon transfer to CMS eAPD repo the CMS CircleCI begins automated tests
- [x]  Automated tests succeed

**ZenHub**
- [x]  Issues, Epics, Labels, etc... are in CMS ZenHub account

**CodeCov**
- [x]  See CodeCov report in CMS eAPD CodeCov

**Slack**
- [x]  Message successfully sent to CMS Slack #cmcs-dsg-dss-eapd from CircleCI

- [x] Make sure "all" collaborators switch to the CMS eAPD

**Comment by jeromeleecms** [comment]
Blocked by CMS/GitHub team; Currently needs action on Jira ticket in order for this to move forward.

**Comment by cthulhuplus** [comment]
I figured out how to get a different view of the ticket, the default help desk view did not allow me to take people or add Jerome to the ticket. The new view, which is the normal Jira ticket type view, allowed me to take both of the Jira people who had previously posted in the ticket and add Jerome to the ticket.

**Comment by cthulhuplus** [comment]
https://jira.cms.gov/browse/WHSD-27625

**Comment by cthulhuplus** [comment]
Still no movement on: https://jira.cms.gov/browse/WHSD-27625 despite Jerome being added to the ticket and asking for an update.

**Comment by cthulhuplus** [comment]
The Migration is complete, there have been additional tickets added to this Epic to reflect the ongoing work.
