### ISSUE TITLE
Subheading visibility on page

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2204]
Subheading selected in side nav should be visible on page.

### This task is done when...
 - [ ] Heading is visible when selected in side nav

**Comment by CSwartzHMA** [comment]
In Program Activities sections, subheading selected in side nav is visible at the top of the page:

![image](https://user-images.githubusercontent.com/45497254/80998462-005e7500-8e11-11ea-8de4-b502bdb25b79.png)

In all other sections of the side nav, the landing spot on the page hides the selected subheading:

![image](https://user-images.githubusercontent.com/45497254/80998605-3865b800-8e11-11ea-9452-27b3e4e897c0.png)

**Comment by beparticular** [comment]
This was fixed when @radavis fixed the nav. Closing.
