### ISSUE TITLE
Explore the design of the MMIS table

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2218]
With the implementation of the non-rounded numbers across the app, there are just a handful of places in the app where this may cause a readability issue for tables and numbers. This screenshot is the MMIS table on the Executive Summary. 

<img width="1396" alt="Screen Shot 2020-05-08 at 3 03 42 PM" src="https://user-images.githubusercontent.com/5957354/81441318-92cb8500-913f-11ea-85d5-a4d8bd6e82fb.png">

Let's explore of a new way to show the data in this table that is readable for large numbers, doesn't break the page, and meets any regulations with the approval letter. 

### This task is done when...
 - [x] We understand what is regulatory about this table and what can or cannot be changed (it has to look like the approval letter in the export, which we do have room for, but not in the builder)
 - [x] We understand all the things this table is calculating in all directions 
 - [ ] If things can be changed, an approved by design/product mock up of the new table design

**Comment by beparticular** [comment]
@jeromeleecms can you share the approval letter and information about what cannot be changed here? thx!

**Comment by jjames521** [comment]
@beparticular 

Looked at this on Friday and conferred with Jerome and Laura.  The solution that Laura and I found out at the end of the day is I think the most promising.

This instance could either initiate when an overflow of integers is high enough or be a state that always occurs.

![Screen Shot 2020-05-18 at 1.02.42 PM.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/6cc4ccdd-34ea-4969-904c-927215dabfb8)

The alternative is a scrollable version that initiates when the integers are too long.

![Screen Shot 2020-05-18 at 12.54.46 PM.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/2117a7e4-b0b7-42c8-b5e6-583c3201d441)

**Comment by beparticular** [comment]
Per separate conversations with Jerome and Jesse, this table is there to help verify your acceptance letter information and matches to a table in the acceptance letter. If it doesn't match, it is an indication that something is wrong that needs to be traced back to the budget summary table. 

If this is a a point of connection between the acceptance letter and data entered by the user, it would be great if we could make this work without breaking it up, and without the scroll. Currently there are no scrolling issues in the export view, only the builder. 

Let's hold this to look at while moving forward on the update experience. The question I think is - will folks be looking at the export view or the builder to compare this to the acceptance letter, and what will that look like, or what will folks be instructed to do in the future based on our research.

**Comment by jeromeleecms** [comment]
Per discussion, this isn't a priority issue right now and we will fold this into the update experience research.

**Comment by jeromeleecms** [comment]
Closing this in favor of when we do the MDBT content/functionality with MMIS.
