### ISSUE TITLE
Nav bar does not indicate correct location with launch of different APD 

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2223]
When you have an APD open and then go back to the dashboard and select a different APD, you are dropped into the Key Personnel page, but the nav bar continues to highlight the page you were on in the previous APD before you went to the dashboard until you begin to scroll.

### This task is done when...
 - [ ] Dev has reviewed to see if this is a bug
 - [ ] Upon opening a new APD the nav bar indicates the correct landing page

**Comment by beparticular** [comment]
We're also seeing this in 2226/2182 when you use the new "back to APD" link, it takes you back to the beginning, which is fine, but the highlight on the nav remains on the Export label.

**Comment by CSwartzHMA** [comment]
I am also seeing this when I use the browser back and next buttons. The focus remains on the previous page.
