### ISSUE TITLE
Document YAML field types, what they do, and when to use them

### ISSUE THREAD

**Issue by pphillips-fearless** [CMSgov/eAPD#2225]
Document the field types we use in the YAML files, what they do (how they appear on the page), and when to use them

### This task is done when...
 - [ ] the YAML field types are documented
 - [ ] a decision has been made about whether to convert from YAML to something else and follow up tasks have been created

**Comment by nicholeweems** [comment]
@pphillips-fearless to update done when criteria.

**Comment by mgwalker** [comment]
The lack of clarity around how the YAML and the app interacts was a big driver for originally spinning up a [Storybook](https://storybook.js.org/). The YAML was created to serve two purposes:

1. Primarily, we once had the idea that the app would be translated into other languages, so we built out infrastructure to support that based on the user's browser language settings.
2. Secondarily, it was helpful to allow our content designers to edit the text directly without having to wait for dev to do work.

As part of digging into how this YAML works, I think it might also be worth considering whether the YAML ought to be deprecated and content lazily migrated into the app code.

**Comment by nicholeweems** [comment]
Closing as another issue #2427 includes initial intent of this issue.
