### ISSUE TITLE
The click area for the yes/no buttons for hourly resource extends too far

### ISSUE THREAD

**Issue by lauraponce** [CMSgov/eAPD#2232]
The click area for the yes/no buttons in the Private Contractor Costs subsection for entering an hourly resource extends pretty far out to the right of the radio buttons and could be accidentally clicked.

### Hourly resource section

![Screen Shot 2020-05-21 at 2 07 02 PM](https://user-images.githubusercontent.com/21222704/82606869-a679e100-9b6c-11ea-91cc-1fe94ef60c21.png)
_____________________________
### Clickable space to the right

![Screen Shot 2020-05-21 at 2 07 38 PM](https://user-images.githubusercontent.com/21222704/82606872-a8dc3b00-9b6c-11ea-9789-af0fba6be7e0.png)

### This task is done when...
 - [ ] The selectable area is contained to just the text and radio buttons

**Comment by akuas** [comment]
The click area for the FFY and Program Type checkboxes extends too far. This bug might lead users to accidentally select or deselect options they did not intend. Also, users might not realize that the field input changed.
https://images.zenhubusercontent.com/113234315/ab9c92cf-9232-49eb-af01-bd300d431630/checkbox_bug.mov
