### ISSUE TITLE
Style OKR's objective page to mimic milestone section

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2242]
Objectives section should match Milestones section

### This task is done when...
 - [ ] Design for updated page has been created
 
Desired design: 
![image.png](https://images.zenhubusercontent.com/5c6b0f0776215728ef10b52f/fb5376eb-c313-4d45-b7ca-464e24872fef)

Check heading size.
Remove subheading.
Add separator line after instructions and between objectives.
Number objectives and update text style.
Add button to remove?
![image.png](https://images.zenhubusercontent.com/5c6b0f0776215728ef10b52f/da04ea47-57cc-4154-a218-83a5d7e4ec38)

**Comment by CSwartzHMA** [comment]
Also consider #1694 .

**Comment by CSwartzHMA** [comment]
Note from content review for clarification: For consistency – make "Objective" (H3) and add descriptor prior to the numbered listing of the objectives (similar to Milestone section).

**Comment by CSwartzHMA** [comment]
Consider #1694 in this update.

**Comment by beparticular** [comment]
#2446 is related to this issue, consider what changing to Outcomes and Measures means for this issue when it's time to address it.

**Comment by beparticular** [comment]
Closing as this doesn't make as much sense with the design of outcomes and metrics in #2446
