### ISSUE TITLE
CircleCI Slack Integration

### ISSUE THREAD

**Issue by pphillips-fearless** [CMSgov/eAPD#2271]
When our last production release failed we got an email from CircleCI about it, but no slack notification.  Greg said that the build script will send a notification if the last stage fails, but this was an earlier stage.  He said that CircleCI has a slack integration available but it's not being used.  So that should be turned on.

Another thing that happened is that in order to fix the build I removed the version tag from the  master branch, created a commit with the fix, and then applied the version tag to the new commit.  In the process that switched the release on github from released mode into draft mode.  please look into why that happened and if we can get a notification about that happening in the future

### This task is done when...
 - [ ] set up CircleCI slack integration
 - [ ] set up notifications for github releases that backtrack into draft mode

**Comment by jeromeleecms** [comment]
Moving to GitHub Actions
