### ISSUE TITLE
Enhanced Admin UI for user roles

### ISSUE THREAD

**Issue by pphillips-fearless** [CMSgov/eAPD#2276]
Add the ability within the UI for for administrators to maintain user roles and the activities associated with the roles.

### This task is done when...
 - [ ] administrators can view, add, update, and delete user roles
 - [ ] administrators can view, add, update, and delete activities associated with each role

**Comment by jeromeleecms** [comment]
From conversation with team during parking lot, we may need to utilize this so we can address how we will manage user permissions for the ATO.

**Comment by beparticular** [comment]
This has been handled in multiple other tickets, so closing. Currently in design in #2506
