### ISSUE TITLE
Error saving APD after auth token expires

### ISSUE THREAD

**Issue by radavis** [CMSgov/eAPD#2294]
![Screen Shot 2020-06-12 at 5.18.08 PM.png](https://images.zenhubusercontent.com/5e62a052e57324bfda300f92/b724ed39-405f-4342-bd15-e2996a2ac474)

### Steps to reproduce

- log in
- wait X minutes (`SESSION_LIFETIME_MINUTES` value)
- change APD
- save error is displayed, 401 Unauthorized response from API

The old behavior was to redirect-to/display the login page, if I remember correctly.

### This task is done when...
 - [ ] making requests w/ an expired auth token redirects-to/displays the login page (or does something better than generate a save error)

**Comment by jeromeleecms** [comment]
@radavis @pphillips-fearless @thetif Based on our discussion around use of cookies for authentication and Okta, does this potentially have a dependency / tie to this issue?

**Comment by thetif** [comment]
Fixed as part of #2720

**Comment by jeromeleecms** [comment]
Fixed.
