### ISSUE TITLE
Replace the “Cost Allocation and Budget for FFY 2020” table with part of the new "Summary Budget by Activity” table

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2306]
On the Activity (Program Activities) > Budget and FFP page, the "Activity 1 Budget for FFY 202X" table (and table for each subsequent activity) is essentially the same as the new tables that were created under Proposed Budget > Summary Budget by Activity > Activity Breakdown tables. 

The only difference between the tables is - the new table contains the "other funding" amount calculations broken down by section). This Activity Breakdown table is the most current table that handles this data. 

A decision was made to Replace the “Activity X Budget for FFY 202X” tables on the Activities > Budget and FFP page with the new Proposed Budget > Summary Budget by Activity > Activity Breakdown tables so that we only have to maintain the one table, but use it in two different places. 

Old Table
<img width="1002" alt="Screen Shot 2020-10-14 at 2 26 25 PM" src="https://user-images.githubusercontent.com/5957354/96029961-5b1ce380-0e29-11eb-88a8-50c0ea88c0b4.png">

New Table
<img width="996" alt="Screen Shot 2020-10-14 at 2 26 48 PM" src="https://user-images.githubusercontent.com/5957354/96029967-5eb06a80-0e29-11eb-8f7b-aa5b366f7f5d.png">

### This task is done when...
 - [ ] we replace the “Cost Allocation and Budget for FFY 2020” table with the more recent "Summary Budget by Activity” tables

**Comment by nicholeweems** [comment]
The blocked by reference for #2217 will include an subsequent dev issues which are created as a result of completing 2217.

**Comment by radavis** [comment]
@beparticular, The names of pages and headings have changed since this ticket was created, and I'm having a little trouble figuring out which table components are being called out to be changed. Would it be possible for you or someone to clarify this tasks with a couple of screenshots?

**Comment by beparticular** [comment]
@radavis wow, yes you are right. I'm working on updating the original comment to reflect all of the other updates we've made.

**Comment by beparticular** [comment]
@radavis let me know if the new original comment and screenshot reflects the current state of the app and helps this issue make more sense.
