### ISSUE TITLE
Change order of fields and field/title names on Cost Allocation and Other Funding + Budget and FFP pages.

### ISSUE THREAD

**Issue by pphillips-fearless** [CMSgov/eAPD#2322]
Update text and layout on the newly re-titled Cost Allocation and Other Funding and Budget and FFP pages according to the attached mockups.  Original design task is #2217

For clarity on mock up I've cut off the mock at Estimated Quarterly Expenditure because no further changes in the sequence are made after that.

_**Builder Views:**_

![CostAllocationBuilderViewVar2Edit3.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/781e9d32-aa75-432a-816c-e126ae2f069c)

![FFP and BudgetEdit2](https://user-images.githubusercontent.com/62292793/89582942-77881880-d807-11ea-956a-c33b94801296.png)

_**Export View:**_

![Budget and FFP Export View.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/2be992c3-bce8-4462-ae93-31860ee02437)

### This task is done when...
 - [x] Switched over _Other Funding Amount_ to _Cost Allocation and Other Funding_ page,
 - [x] Changed nav link from _Cost Allocation_ to _Cost Allocation and Other Funding_
 - [x] Changed title from "FFP and Budget" to "Budget and FFP"
- [x] Changed title "Description of Cost Allocation Methodology" to title caps for consistency
 - [x] Changed titles in export from "Description of Other Funding" to "Other Funding Description"
 - [x] Added "FFY XXXX" to both builder view and export view in _Cost Allocation and Other Funding_ page
 - [x] Changed the section header "Cost allocation and Budget for FFY XXXX" before each table to "Activity X Budget for FFY XXXX" (Depending on what Activity and FFY)
 - [x] Added help text for _Other Funding_ and changed over description text fields from content review. The sections changed are _Other Funding Description_ and _Other Funding Amount_.
 - [x] Changed "FFP and Budget" Nav Link to "Budget and FFP"
 - [x] Added in description text over Federal-State Split section and changed it from Blue Help Box to regular text for clarity and consistency.
 - [x] Removed first sentence in 4th bullet in Cost Allocation section instructions.

**Comment by CSwartzHMA** [comment]
Noted a redundancy in the 4th bullet of the Cost Allocation section instructions. Added task for completion as part of this issue.

**Comment by jjames521** [comment]
@pphillips-fearless Jenn noticed that other funding was dependent on FFY so added in text headers for  each FFY and added additional Other Funding field for that subsequent year.

**Comment by beparticular** [comment]
@thetif small changes are being made to the mock up right now from decisions in #2373 

@jjames521 will update the mock ups and information in this ticket. @jjames521 also add in the change to the title and the addition of the section header into "this is task is done when" in this ticket.

Decisions made in content/design convo -
1) The title of this page should be "Budget and FFP"
2) The section header before the each table should be "Activity X Budget for FFY XXXX"
3) At this time no help text should be added above the table.

**Comment by beparticular** [comment]
@jjames521 oh and we need a mock up for the export view... good times!

**Comment by jjames521** [comment]
@beparticular @thetif 

Uploaded new mockups, descriptions of these changes and export views.  The executive summary will follow the same flow as the export view except "Activity 2 Budget for FFY 2020" table is in full color.

**Comment by radavis** [comment]
See latest mockups, here: https://github.com/CMSgov/eAPD/issues/2217

Updating this task list for clarity.



**Changes @ `/apd/activity/:index/cost-allocation`:**

- [ ] Move 'Other Funding Amount' form section (instruction, help text, dollar field, and table) from the 'FFP and budget' page, to the 'Cost Allocation and Other Funding' page.

- [ ] Change Nav link text from 'Cost Allocation' to 'Cost Allocation and Other Funding'.

- [ ] Change 'Description of cost allocation methodology' to Title Case Capitalization.

- [ ] Remove first sentence in 4th bullet in Cost Allocation section instructions. ~"Ensure cost allocations are current."~

- [ ] Add 'Other Funding Description' instruction text. Remove help text box.

- [ ] Update 'Other Funding Amount' instruction and help text.



**Changes @ `/apd/activity/:index/ffp`:**

- [ ] Change heading from "FFP and Budget" to "Budget and FFP"

- [ ] Change "FFP and Budget" Nav Link to "Budget and FFP"

- [ ] Change heading above tables to: 'Activity Y Budget for FFY 202X'. (Should 'Y' be number or name, or both?)



**Changes @ `/print`:**

- [ ] Change "Description of Other Funding" to "Other Funding Description"



**Other/Unprocessed/Unclear:**

- Add "FFY XXXX" to both builder view and export view in Cost Allocation and Other Funding page (Where, exactly?)
- Add in description text over Federal-State Split section and changed it from Blue Help Box to regular text for clarity and consistency. (Done, already?)
- Other funding description to title case?

**Comment by radavis** [comment]
@beparticular, @jjames521, @CSwartzHMA, where can I find the updated content for these pages? Or, should I just type it out?

**Comment by beparticular** [comment]
@radavis I believe the only blocks of text that are changing are located in #2281 (Explains other funding) and #2283 (FFP help text)
