### ISSUE TITLE
Update areas in the app where "total computable" should be used

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2324]
Total Computable cost is a term used in the new tables and should be consistently applied throughout the app.

### This task is done when...
 - [ ] The app has been reviewed and areas where "total computable" should be used have been identified
 - [ ] The team is in agreement on changes to identified areas

**Comment by CSwartzHMA** [comment]
Here is the list of areas where the term "Medicaid Share" should be replaced with "Total Computable". @jeromeleecms Please confirm that these should all be changed.

Examples of current use: 
Example 1: Results of Previous Activities>Actual Expenditures>HIT + HIE Table: Total computable (Federal + state)
Example 2: Proposed Budget>Summary Budget by Activity: Total Computable Medicaid Costs used in instruction and in table headings

**Suggested Consistent Use** Should be Total Computable Medicaid Costs throughout. Team should decide whether shortening to Total Computable in some places would be sufficient.

1. Results of Previous Activities>Actual Expenditures>HIT + HIE Table: Total computable (Federal + state) - Suggest leaving this one since it is the first reference and  provides definition
2. FFP and budget>Cost Allocation and Budget table>Bottom Row: Change "Activity Total Computable Medicaid Cost" to "Activity Total Computable Medicaid Cost"
3. FFP and budget>Other Funding Amount table>Bottom Row: Change "Medicaid Share" to "Activity Total Computable Medicaid Cost"
4. FFP and budget>Federal-State Split table>Top Row: Change "Medicaid Share" to "Total Computable Medicaid Cost"
5. FFP and budget>FFY Totals (narrative at the bottom of the page): Change "total cost to Medicaid" to "total computable Medicaid cost"
6. Proposed Budget>Summary Budget Table>Instructions: Change "Medicaid Total Computable" in the first sentence with "total computable Medicaid cost" and change "total Medicaid cost" in the last sentence with "total computable Medicaid cost". Replace "Medicaid Total Computable" throughout this table with "Total Computable Medicaid Cost". (This one might be ok as is, but added it to highlight opportunity to be more consistent.)
7. Executive Summary>Activities Summary>within each Activity Summary: Change "Medicaid share" (three places in each summary) to "Total Computable Medicaid Cost"  
8. Executive Summary>Program Budget Tables>last column throughout - Change "Medicaid Total" to "Total Computable Medicaid Cost"

I did not review the export view, because I believe this is being covered as part of the change management process, but let me know if I should also review it for additional instances where this change should be made.

**Comment by jjames521** [comment]
7th bullet point from above is resolved through ticket #2255 @CSwartzHMA

**Comment by jeromeleecms** [comment]
For number (3), the help text in this section also refers to Medicaid share:

Other funding consists of funds that are not directly tied to the CMS grant and the matching state funds for this activity. This funding may come from another federal source, another state agency, and/or contributions or donations from a third party. Other funding will be deducted from the total cost of the activity prior to calculating **the Medicaid share.**

Also for #7 (#2255), the mockup only refers to "Total Computable" instead of "Total Computable Medicaid Cost" if we are seeking consistency...

**Comment by CSwartzHMA** [comment]
Team has decided to use "Total Computable Medicaid" in all of the instances identified above.

**Comment by pphillips-fearless** [comment]
@thetif here's another design issue that's ready to become a dev issue.  It might be clear enough to just re-purpose this one, or you might want to make a new one and close this one.
