### ISSUE TITLE
Update Key Personnel and Program Management page instructions and help text

### ISSUE THREAD

**Issue by pphillips-fearless** [CMSgov/eAPD#2325]
Update the Key Personnel and Program Management page instructions and help text according to the screenshot below.  This is based on original design task #2250

![image.png](https://images.zenhubusercontent.com/5e6a4b048168d5a15258c7d1/2f964950-2041-41eb-be55-45b2d7efb18b)

Here's the new text for copying and pasting. Any other text already exists and just needs to be moved.

1.  Key personnel are individuals involved with all activities within this APD, or are directly involved with governance, coordination, stakeholder decision-making, oversight, and/or performance of the activities as they affect the state’s Medicaid program.

2. Personnel whose responsibilities apply only to specific activities should be included within Program Activities, rather than in this section.

3. Key personnel costs are included in Activity 1, Program Administration, at the 90/10 split.

Example: Program Managers and Directors who provide oversight to all projects would be included here. Personnel who support individual activities should be included in the State Cost Categories section for each associated activity or activities.

### This task is done when...
- [ ] Moved help text starting "Personnel listed in this section..." to below the "Primary APD Point of Contact" header inside the "edit" area (or when adding a new person) on Key Personnel section on both the primary point of contact AND on additional personnel 
- [ ] Changed the text on all bullet points within the ordered list and moved it out of the blue example box
- [ ] Changed the text within the example box to be an example

**Comment by beparticular** [comment]
@beparticular 
In addition, the blurb "Personnel listed in this section must be assigned to APD by name, role, time commitment, and cost, where applicable." needs to appear when you add someone who is not the main point of contact. This is when you add another person, or have another person on the APD in #2 (or greater) spot on Key Personnel. 

I'm adding this to the "this task is done when" list as well. 

![Screen Shot 2020-07-02 at 11 09 13 AM](https://user-images.githubusercontent.com/5957354/86376212-a9302180-bc54-11ea-8926-3553794fbd4b.png)
