### ISSUE TITLE
Move Results of Previous Activities to be part of each activity 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2336]
Move Results of Previous Activities to be part of each activity. 

Considerations - 
1) Scope, time, cost are what we want people to share and cost is most challenging for states to come up with. On the initial pass, we we not require the fields as they might not be able to report it as they start using the eAPD. As time goes on, we'll want to show this is part of reporting and will eventually look to require the fields. 
2) Moving the nav as is will create another level of nav inside the activities. See if there is a way to handle this without adding another layer. 
3) What to call this? If it's in an activity, it's not a previous activity anymore. 

Consideration for dev - a change in the nav will require a change in the labels under the previous/continue buttons

### This task is done when...
 - [ ] Double check with product to learn about any other considerations or use cases
 - [ ] Work with product on where to add this into the navigation within an activity
 - [ ] Design interactions for potential use cases: first time entering APD info, and update to an activity, a new activity
 - [ ] A mockup or prototype is created to show the design in builder and export views
 - [ ]  Design is approved by product

**Comment by beparticular** [comment]
Moving this back to the fridge and adding as part of the update experience epic. 

From conversation today 
1) This needs to be part of Cake Layer 2, to be discussed potentially after the versioning conversation. 
2) This needs to appear whether an APD is new or whether it is an update
3) We need to determine if this will be it's own section in the nav or if it will fit into another section
4) Potentially it could be part of OKRs, typing outcomes together

**Comment by beparticular** [comment]
Revisited this in our workshop on 9/14. Some decisions still need to be made that will counter some of the notes above. Will move those considerations into this issue, but wanted to know this could and should be moved to the prioritized backlog .

**Comment by beparticular** [comment]
Based on SO feedback and current state of outcomes and metrics we'll move this back to the update experience.

**Comment by jeromeleecms** [comment]
Closing this out as we explore how the update experience will function.
