### ISSUE TITLE
Support for DE update to eAPD submission

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2347]
Creating this so we have a place to track activities relating to Delaware's request to update their previously submitted eAPD.

### This task is done when...
 - [x] Team has set parameters and expectations for how the updates will be made
 - [x] Mary and Peggy have been made aware of parameters and expectations
 - [x] Any needed support has been provided to allow Mary to update and submit the eAPD
 - [x] The eAPD has been submitted successfully
 - [ ] Debrief with Peg a little while after submission
 - [x] Debrief with Mary a little while after submission
- [x] The team has debriefed on the process, lessons learned and whether additional research is needed relating to the experience
 - [x] Resulting issues have been identified in road map, murals, and any new tickets.

**Comment by CSwartzHMA** [comment]
@beparticular please review and update as needed.

**Comment by CSwartzHMA** [comment]
A meeting has been scheduled with Mary and Peggy for 7/17/2020.

**Comment by beparticular** [comment]
Documenting the plan here
https://docs.google.com/document/d/1mmorE0bFaUMy4S2PXF--BtqrOvV_gxPB_NCiHz_ddns/edit

**Comment by CSwartzHMA** [comment]
Mary's suggestion based on her experience updating the Results of Previous Activities>Actual Expenditures section does not update for the most relevant prior 3 years when the FFYs are selected. It seems that 2017, 2018 and 2019 always show.

When FFYs 2021 and 2022 are selected in Program Summary>Program Overview, we would expect to see Results of Previous Activities show FFYs 2018, 2019 and 2020, but that is not what is currently provided on the page.

Current Program Overview:
![image](https://user-images.githubusercontent.com/45497254/89929832-cce17280-dbd7-11ea-8b23-e23008e9e883.png)

Current Actual Expenditures:
![image](https://user-images.githubusercontent.com/45497254/89929982-00240180-dbd8-11ea-90c8-9260dbca05cb.png)


**Results: 2020 is unaccounted for.**

**Comment by CSwartzHMA** [comment]
@beparticular @jeromeleecms Feedback from our MeT reviewer:

_I didn’t realize when I first started the review that it was the new eAPD template.  I noticed it was really different from last year’s submission.  Delaware was probably a good one to start with since they do not have a lot of different activities.

Here are some general thoughts:

1.	In the beginning it seemed really repetitive but once I realized it was the template and looked at the format overall, I understood it. 
2.	I’m used to seeing the IAPDs separated out by Appendices and although it does show what Appendix topic (HIT, MMIS, HIE) the project is in, it is a different order that HITECH and in some places it’s HIT – HIE – MMIS and others it’s HIT – MMIS – HIT – HIE  Could this be just the way DE entered their projects into the system? 
3.	There did not seem to be as many details about the projects as I normally see.  Are the states limited to the number of words/characters they can include in each section?
4.	This is probably just me, but in the Executive Summary, it lists FFY 2021: $1,480,590 | Medicaid share: $1,480,590 ($1,332,531 Federal share) – I viewed Medicaid Share as the State Medicaid amount, but this is the total cost being requested.  Others may not think of it this way.
5.	State Personnel Section – For DE this is fine, but some of the IAPDs we review have a TON of staff and this section could be really long for some states.

These are just my initial thoughts.  Overall I think it will be good, just a different format to get used to._

**Comment by CSwartzHMA** [comment]
@beparticular I haven't heard back from Peg after a few attempts at scheduling time to debrief. All of the things Mary brought up have been addressed in other issues, and I don't believe anything noted from the MeT reviewer (comment above) is an issue with the builder. I am going to close this and we can follow up with Peg if she wants to chat with us later.
