### ISSUE TITLE
Map user roles for ATO and use in system

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2350]
For ATO we will need to map the user roles we intend to have in the system. 
This would be whether there is one single admin or for the states as their own admins. 
This would also be used as our own information for building out the ability to have multiple users/roles in an account 

We need to include:
Governance rules
Contingency/bus rule plans
How we intend to monitor usage
User caps per account/state
Where does the process start
How should users be vetted
Admin for states has to have an admin account (not sure what this meant exactly)
How are passwords reset 
What happens if they have an EUA account
What happens if they don't have an EUA account
Anything else we uncover as part of the process

### This task is done when...
 - [ ] User roles are agreed upon with the team
 - [ ] A visual document with user roles mapped is provided to the ATO team

**Comment by jeromeleecms** [comment]
Working Document to add eventually update the Wiki:

https://docs.google.com/document/d/1_XNJGlTqGwwJYuHvcGOx3Cv_vfeLOvCuVLBEFuU7hOU/edit#

**Comment by jeromeleecms** [comment]
Made updates looking for more immediate needs; starting page 8 of the above reference document

**Comment by jeromeleecms** [comment]
Per Standup 12/17/2020 - @thetif will be updating the Wiki to reflect the changes we are going to production with and that will close this out.
