### ISSUE TITLE
Accessibility Audit

### ISSUE THREAD

**Issue by pphillips-fearless** [CMSgov/eAPD#2358]
I was playing around with the WAVE and aXe browser plugins and saw some issues in our app, so I thought it would be a good idea to do an acessability audit, going through each page an identifying things to fix (generating new tasks to fix them, not necessarily fixing them under this task).

### This task is done when...
 - [x] an accessibility audit has been done and new tasks generated to fix the issues.

**Comment by nicholeweems** [comment]
Please reference artifact containing preliminary review findings in the team's Google Drive, [Preliminary Accessibility / 508 Review](https://docs.google.com/document/d/1qxJkF9iVjv3FfA6JHzVy2P5YfqieahKcq9Qiq-WvhI8/edit#)
