### ISSUE TITLE
Create process for requesting/getting access to an eAPD account

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2361]
Create a process for requesting and getting access to an account at Cake Layer 1 release time

Considerations: 
Who is allowed to have an account and who will give them access? 

How many users will have access once we add E&E and MMIS (CA has 200 authors)  (At minimum 3... X each state)

Structure of state teams, be aware of who is joining the conversation - contractors who do APD writing
How will states handle access for contractors? 

What is our/state liability/security around keeping accounts current? 

### This task is done when...
 - [ ] A process is written and approved by product/leadership
 - [ ] A process is written that satisfies any ATO requirements

**Comment by jeromeleecms** [comment]
Mural started - had meetings with Okta team to discuss. Need security clarification on separation of duties.

**Comment by jeromeleecms** [comment]
Link to the Mural board is in our Mural Index titled "Login and Authentication Flow"

**Comment by cthulhuplus** [comment]
@beparticular and or @CSwartzHMA How are we feeling about this? Is it ready to close out?

**Comment by beparticular** [comment]
@cthulhuplus In the context of Okta, yes. In the context of deciding who is the state admin and how they get access, I'm not sure we have that yet. @jeromeleecms do you want us to assign this to you so we can solidify that plan?

**Comment by cthulhuplus** [comment]
#2598 will pick up the rest of this work
