### ISSUE TITLE
Document a process for supporting users after Cake Layer 1 release

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2363]
Decide who do we support, where do we want to support them, how do we want to capture issues, who responds, how bugs and issues are reported, documented and prioritized, etc

### This task is done when...
 - [x] A plan for support is written and agreed upon by the team
 - [x] More criteria TBD or tickets will spin off to create the process
 - [x] Create scripts for the CMS helpdesk, where CMS helpdesk support is expected
 - [x] Plan is ATO-Ready

**Comment by CSwartzHMA** [comment]
Per team contingency planning discussion Caryn will begin to develop a workflow of how users will use the app and start to develop structure and framework for support planning.

**Comment by beparticular** [comment]
If there is something here for release, make sure it's represented, or it can be closed out.

**Comment by CSwartzHMA** [comment]
@jeromeleecms @beparticular I believe we have determined that there is very little need for the CMS help desk to provide support. They would primarily help with EUA-related questions. Would we need scripts for any of those scenarios?

**Comment by CSwartzHMA** [comment]
@cthulhuplus Is there anything ATO-related that we need to address? It sounds like we have wrapped up all of the loose ends with that, but let me know if there is anything more to discuss in anticipation of our go-live user support plan.

**Comment by cthulhuplus** [comment]
@CSwartzHMA We've been given ATO, so it's just maintaining the that posture. Keeping things up to date when they change.

**Comment by jeromeleecms** [comment]
This looks done per Sprint Planning.
