### ISSUE TITLE
Remove the word "another" from all buttons 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2366]
Remove the word "another" from all buttons 

Re: Another isn't always true, and it's extraneous wording in small buttons

### This task is done when...
 - [x] A list of all buttons that need to be changed and what page they are on is added to this issue (e.g Activities List > add another X) 
 - [ ] The issue is flipped to dev for implementation

**Comment by eStar386** [comment]
Pages with another in the button
**Key State Personnel** ->  Add Key Personnel  

On Activities homepage   -> add another activity 
Within the actual activity aka **Activities** 
**Outcomes and milestones** -> add another outcome / add another milestone 
**State staff and state expenses** -> add another state staff/state expense
**Private contractor costs** -> add another contractor
**Budget and FFP** -> add another activity

**Comment by eStar386** [comment]
@thetif @beparticular Please let me know if I did the handoff correctly. According to the wiki, I assign it to the dev lead.

**Comment by beparticular** [comment]
@eStar386 yay for this being done! 
Tagging dev lead is correct, and also we've been putting it or leaving it in the Ready for Review pipeline for the handoff. @thetif is that still ok with you, or would you prefer them go ahead and be put back in new? or something else?

**Comment by thetif** [comment]
yes, that works, I'll get this created. Sorry that I missed it yesterday

**Comment by thetif** [comment]
created dev task #3009
