### ISSUE TITLE
Change "Objectives and key results" Nav Bar title to match contents of page

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2368]
When nav bar titles do not adequately guide users to important content. Updating the nav bar will help users find what they are looking for.

### This task is done when...
 - [ ] Change "Objectives and key results" to "Objectives and Milestones"

**Comment by radavis** [comment]
Question, should I change the title of this page, as well?

![Screen Shot 2020-08-11 at 12 45 16 PM](https://user-images.githubusercontent.com/1299034/89925014-cd2a3f80-dbd0-11ea-87ee-4a0f45039655.png)

**Comment by radavis** [comment]
Ok, I get it now. 

The page deals with OKRs and Milestones, and not just OKRs
