### ISSUE TITLE
Designate location(s) of logo within application

### ISSUE THREAD

**Issue by nicholeweems** [CMSgov/eAPD#2369]
A logo has been in the works, but we need to document where it may live in the application and on which pages

### This task is done when...
 - [ ] The logo location in the app is mocked up and approved

**Comment by jjames521** [comment]
@beparticular @CSwartzHMA


These are a few places that I think work for our logo.

I have a few different variants, I also decided to remove the APD document icons from the document listing in Variant 2 and 3 while I was mocking up the placement of the logo, gives a cleaner aesthetic in my opinion.

**Dash Splash Screen**

_**Variant 1**_

![DashFileIntroeAPDLogoPlacement.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/92f59e1b-205d-4fec-adc5-b4db8db79fac)

_**Variant 2**_

![DashFileIntroeAPDLogoPlacementVar2.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/df0251ea-28ee-4c33-94fe-02ccd4d52479)

_**Variant 3**_

![DashFileIntroeAPDLogoPlacementVar3.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/3d5e5551-bbe9-45e1-8047-9b7ed3d48e3d)

**Export/Print View**
I changed a few things here, mostly the addition of a Bold header _**"American Samoa 2020 APD"**_
![ExporteAPDLogo.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/4aa809c4-a759-475b-b3e4-5991d35f0b4b)

**Comment by jjames521** [comment]
Spoke to @beparticular this is ready to go. @thetif 

As always, let me know if you need any additional clarity in change log.

**Change Log:**

- In export/print view Bold header "American Samoa 2020 APD" to match new eAPD logo.

- Add Logo to header in print view

- Add full color logo centered to dashboard splash screen.  Take out "My State Dashboard" header title.


_**Dashboard Splash**_
![DashFileIntroeAPDLogoPlacementVar4.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/e1b3f7d8-abc9-4a45-86f4-e81902b13c19)


_**Export/Print View**_
![ExporteAPDLogo.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/307cf5be-8e93-438d-b11b-6bb0a8491dff)
