### ISSUE TITLE
Dividing lines inconsistently presented across pages

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2370]
Some pages show a double line or no line at all in the header section. All pages should have a single dividing line.

### This task is done when...
 - [ ] All pages show only one dividing line in the header section.

**Comment by CSwartzHMA** [comment]
![image](https://user-images.githubusercontent.com/45497254/88113971-e8c99980-cb80-11ea-9ff1-4d368c8b2561.png)


Example of double line.

**Comment by CSwartzHMA** [comment]
Example of single line: 
![image](https://user-images.githubusercontent.com/45497254/88114047-0bf44900-cb81-11ea-8850-62c7a923ebca.png)

**Comment by eStar386** [comment]
@jeromeleecms Can you take over the accessibility testing for this one?

**Comment by jeromeleecms** [comment]
Sure thing @eStar386. Also let's move the conversation about the accessibility testing to the PR (started a comment over there already).
