### ISSUE TITLE
Use Title case for all Nav Bar and section titles throughout

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2371]
During content review, it was identified that title case and sentence case are both used in section titles and nav bar. It was determined that title case is preferred.

### This task is done when...
 - [ ] All nav bar and section titles that do not currently use title case have been captured here.
 - [ ] Change log has been created for dev.

**Comment by CSwartzHMA** [comment]
List of identified titles to be udpdated:

**In the Nav Bar:**
All third level sections: Program Activities>Activity XX:XXXX>Activity **o**verview, Objectives and **k**ey **r**esults, State **c**ost **c**ategories, Private **c**ontractor **c**osts, Cost **a**llocation and FFP and **b**udget

**Section Headings:**
Key State Personnel: Medicaid **d**irector, Email **a**ddress, Phone **n**umber, Medicaid **o**ffice, Address **c**ontinued, Total **c**ost
Results of Previous Activities: Grand **t**otals
Program Activities>Activity X: XXXX: Activity **n**ame, Funding **s**ource, Start **d**ate, End **d**ate, Statement of **a**lternative **c**onsiderations and **s**upporting **j**ustification
Program Activities>Objectives and key results: Objective>Key **r**esult (here and when editing), Target **c**ompletion **d**ate (here and when editing)
Program Activities>State cost categories: State **s**taff, Edit >Personnel **t**itle, Cost with **b**enefits, Other **s**tate **e**xpenses, Training and **o**utreach, Hardware, **s**oftware and **l**icensing
Program Activities>Private contractor costs: Contract **t**erm (is ok when editing)
Program Activities>Cost allocation: Description of **c**ost **a**llocation **m**ethodology, Other **f**unding **d**escription


@beparticular I did not include buttons or tables here. Should they be?

**Comment by CSwartzHMA** [comment]
@beparticular Is there anything we need to do on this for the export view or will it update automatically?

**Comment by jeromeleecms** [comment]
Instead of Title casing things on a case-by-case basis - can we just apply a function to title case things that come into the Nav? 

There must be a prebuilt library that can handle this (we just need to know where/how to apply it)...

Plus it's a solved problem too... here's an example:
https://www.freecodecamp.org/news/three-ways-to-title-case-a-sentence-in-javascript-676a9175eb27/

@thetif ?

**Comment by thetif** [comment]
We can look into some way to do it programmatically. It shouldn't be a big deal.

**Comment by beparticular** [comment]
@CSwartzHMA I still don't have a strong handle on what automatically updates in the export view and what doesn't. I'd hope that the text would update, but I'm sure that would be covered in whatever way we address it programmatically? 

I think we decided that buttons are ok as is, but tables should also be included I believe.

**Comment by CSwartzHMA** [comment]
@thetif Would that also apply to sections headings and other areas on pages or just to the nav bar?

**Comment by thetif** [comment]
https://github.com/blakeembrey/change-case/tree/master/packages/title-case

**Comment by thetif** [comment]
We can apply it to where ever we need.

**Comment by jeromeleecms** [comment]
@beparticular @CSwartzHMA Are we aligned that all Nav bar + Section titles should be title cased? If that's the case, can we move this issue to dev?

After that the buttons/table review can be discussed in a separate issue?

**Comment by beparticular** [comment]
@jeromeleecms @thetif definitely nav bar and section titles. I'd be comfortable adding tables to that, but not buttons. 

I did a quick look at tables and we generally use Title case there, but I can see one exception that should be changed, which is "Total cost" on the Estimated Quarterly Budget table on FFP and budget page. So if we can do this across all tables, I'm good with that as well.

**Comment by CSwartzHMA** [comment]
@jeromeleecms @beparticular @thetif I agree with Jenn's note. Good to go from my perspective.

**Comment by thetif** [comment]
@beparticular Just to make sure I'm not missing anything, we just want to force title casing on all Nav Items, Section Titles, and Table Headers, right?

**Comment by beparticular** [comment]
@thetif yes, that's right. thanks!
