### ISSUE TITLE
Review FFP and Budget page for consistency with the formatting of other pages

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2373]
The FFP and Budget page begins with double headings and a table, which is inconsistent with other pages.

### This task is done when...
 - [ ] Headings and a description for the table have been developed
 - [ ] Mock ups for the changes have been created and reviewed by the team

**Comment by beparticular** [comment]
@CSwartzHMA In the export view, it appears that the page has a title of "Federal Financial Participation (FFP) and Cost Allocation" and the table is called "Cost Allocation and Budget for FFY 2020". 

I think what we wanted to do here was make sure the page is clear on what is a heading for the page and what is the title or section for the table? The export view threw me off a little.

**Comment by beparticular** [comment]
This change will be implemented in #2322, @jjames521 will update the mock ups and information in that ticket. @jjames521 also add in the change to title and the addition of the section header into "this is task is done when" in the #2322 ticket. 

Decisions made  in content/design convo - 
1) The title of this page should be "Budget and FFP"
2) The section header before the each table should be "Activity X Budget for FFY XXXX" 
3) At this time no help text should be added above the table.

**Comment by beparticular** [comment]
Closing as this information has been added into dev ticket #2322
