### ISSUE TITLE
Update Activities Summary section in Executive Summary

### ISSUE THREAD

**Issue by pphillips-fearless** [CMSgov/eAPD#2376]
Following content review, a few updates to this section are needed to provide consistency.  Original design task was #2255

![image.png](https://images.zenhubusercontent.com/5e6a4b048168d5a15258c7d1/6306addb-1d9c-4bea-b777-cfa5662e2600)

### This task is done when...
 - [ ] Change the order from activities, sequence goes;

Start/End Date
Total Cost of Activity
Total Computable Medicaid
Federal Share

This is duplicated in Total Cost with the caveat of "Federal Fiscal Years Requested" being at the top and "Total Funding Request" being in lieu of "Total Cost of Activity".

 - [ ] Changed for consistency to title case

**Comment by thetif** [comment]
OBE
