### ISSUE TITLE
Determine what identifying info needs to be gathered to name an APD

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2379]
With multiple submissions and multiple APD types, APD names will have to not all be the same as they currently are in the system. 

Considerations:
State identifier vs federal identifier
Federal naming convention was on submit date
Anything we have to pair approval letter

Types of APDs
HITECH
iAPD, iAPD-U

MMIS, E&E 
pAPD, pAPD-U
iAPD, iAPD-U
oAPD, oAPD-U

### This task is done when...
 - [x] Requirements are gathered for what needs to be/can be in a name
 - [x] A flow/artifact for naming APDs is created to foster dev/design/product discussion and solidify requirements

**Comment by beparticular** [comment]
@jeromeleecms From our design convo this afternoon, this issue might not be "allow states to name APDs" so much as "we need to NOT call every APD by the same name on the dashboard", or "have a way to identify one APD from another in the dashboard", however that ends up shaking out. 

We've determined that we need to allow for naming to satisfy the following needs:  storage, sorting, and submission. 

Are there any other high level needs (preferably that start with S) that we need to take into consideration around giving our APDs names?

**Comment by beparticular** [comment]
Requirements have been gathered and this ticket could be closed. Except it's an epic. 
@jeromeleecms @nicholeweems so should it just stay open until the other issues are complete? 

![Screen Shot 2020-08-20 at 10.10.57 AM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/30e3354d-bb6f-4083-b68e-41301e8b0f81)

**Comment by jeromeleecms** [comment]
We shouldn't close epics until the dependent issues are completed.

**Comment by beparticular** [comment]
@jeromeleecms should it just live in Ready for Review until the rest are complete, or is there somewhere better?

**Comment by jeromeleecms** [comment]
We never settled on a specific process on how to track epics, but my gut feeling is that it should live in the pipeline with the related issue that has the least amount of work attached to it. So if something is still in the prioritized backlog, the epic should hang out there. But def. open to discussion on this!

**Comment by beparticular** [comment]
Changing this from an epic to a ticket and closing. The epic should probably go under 1823 or a new ticket, will decide today.
