### ISSUE TITLE
Consider adding automated testing for 508 compliance

### ISSUE THREAD

**Issue by radavis** [CMSgov/eAPD#2382]
I came across this tool, which could help us catch some egregious accessibility issues. 

https://github.com/nickcolley/jest-axe

### This task is done when...
 - [ ] evaluate automated a11y/508 checking tools
 - [ ] add one of these tools, if we deem it beneficial

**Comment by eStar386** [comment]
Researching and using various accessibility web checkers. For instance https://www.accessiblemetrics.com/ can access the site. Additionally, I have added various chrome extensions for accessibility will repeat with firefox one a defined method of automation has been configured.

**Comment by eStar386** [comment]
Using the jest-axe library, accessibility tests was added with the refactor login #2891 and added to apart of the development code.

**Comment by thetif** [comment]
Accessibility tests added to login components

**Comment by eStar386** [comment]
Refining the accessibility test approach to include a definitive test strategy or script within the PR or in the Google wiki. Additionally, this will help me ensure that it is tested quickly and can be reproduced using other environments. Additionally, it will highlight cross-browser differences or any tools that aren't optimal for the application.

**Comment by thetif** [comment]
We have added jest-axe to the front-end. It is implemented for some components but needs to be added to the rest as we go.
