### ISSUE TITLE
Results of previous activities fields are missing in export view

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2391]
On the Results of Previous Activities Page: 
The Prior Activities Overview field label is missing from the export view. (Screenshot shows no label or field, but if there is text in the field, it does show on the export view, we're just missing the field label.) 

![previousdeleteme.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/6ec1acdd-f8ce-47a6-8ee3-7c8058394e96)

### This task is done when...
 - [x] A mockup is added to the issue to show what the export view should look like
 - [ ] This is changed to a dev issue and put back into the new issues pipeline
 - [ ] The Prior Activities Overview field label is added to the export view

**Comment by jjames521** [comment]
@beparticular 

**Change log:**
Addition of _Prior Activities Overview_ in Results of Previous Activities section in the export view

![Results of Previous Activities Summary](https://user-images.githubusercontent.com/62292793/89052797-3d5cd980-d324-11ea-99d7-e305cb7ce117.png)

**Comment by beparticular** [comment]
@thetif this can be moved into or turned into a dev issue now 

As a note - the incorrect/correct screenshot above shows the Prior Activities Overview field missing entirely, but Jesse and I discovered that if there is text in the Prior Activities Overview field, it is showing in the export view, it's just the field label that is missing from the export. 

![Screen Shot 2020-08-03 at 11 34 47 AM](https://user-images.githubusercontent.com/5957354/89200008-6af08f80-d57d-11ea-9757-db1ab4c380f9.png)
