### ISSUE TITLE
Apply consistent styling to OKRs section across builder and export view

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2392]
In the OKRs section, the styling needs to be consistent between the builder and the export view. 

Incorrect: bullet view in export view
Correct: non bullet view in builder 

Incorrect: the display of the objective text in the builder view 
Correct: the display of the objective text in the export view 

![OKR.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/b794e442-95c5-458b-ae73-a54fbad42b93)

### This task is done when...
 - [x] A mockup is added to the issue to show what the builder and export views should look like
 - [x] This issue is changed to a dev issue and put back into the new issues pipeline
 - [ ] The Objective styling is updated in the builder 
 - [ ] The Key results styling is updated in the export view

**Comment by jjames521** [comment]
@beparticular 
@CSwartzHMA 


**Change Log:**

 _Export_ view to follow suit with _Builder_ view
_Builder_ view changed Objective line to match _Export_ view

**Export View**

![OKRExportView.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/36307d8d-1f72-4abf-86c8-d99a9df79f48)


**Builder View**

![OKRBuilderView.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/a0a65673-d397-46d8-bf56-aaa30a6308c8)

**Comment by beparticular** [comment]
@jjames521 this looks good to me
@CSwartzHMA if no objections, this is ready to move forward

**Comment by CSwartzHMA** [comment]
@jjames521 @beparticular We need to account for when there are multiple key results associated with one objective.

**Comment by jjames521** [comment]
Good consideration @CSwartzHMA 

We would need a clear break between the objectives imo by a light line.


![OKRExportView2](https://user-images.githubusercontent.com/62292793/88962849-04196080-d275-11ea-8010-a96504e00cf9.png)

**Comment by jjames521** [comment]
@thetif @beparticular 

**Change log:**

_Export_

Include light divider line in export view to separate the objectives.
Take bullets out of export view and reflect the style of current builder view.

_Builder_

Move up Objective statement to align with "Objective:" and decrease bold on statement for builder view (currently export view shows this if any reference is needed for styling).  I've provided a "Before" for clarity.

![OKRExample.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/4e271e06-376a-41b9-a76c-e6b918c4d95e)

_**Builder View Mockup**_

![OKRBuilderView.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/914464d3-3cb6-4377-9d2e-d26c8d09f233)

_**Export View Mockup**_

![OKRExportView2.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/d9837a25-2872-40c5-b41f-97dd2a923f27)

**Comment by beparticular** [comment]
@thetif this is ready to become a dev issue
