### ISSUE TITLE
Migrate Mailing Lists from 18F -> MeT

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#2398]
As part of our move from 18F systems, we need to migrate the mailing lists maintained by 18F. Currently, the plan is for MeT to maintain these new lists.

@CSwartzHMA 

### This task is done when...
 - [x] Current mailing lists and recipients of the 18F mailing list are identified
 - [x] Decision is made on what to do with each of them
- [x] Appropriate mailing lists are spun up and cataloged internally

**Comment by CSwartzHMA** [comment]
Document creation is in process and MeT has been alerted to the need for the creation of new ListServs for eAPD communications and for the Ship Mail.

**Comment by CSwartzHMA** [comment]
Current Mailing Lists have been compiled, but I am working on tracking down the list of Ship Mail recipients.

**Comment by CSwartzHMA** [comment]
Lists have been compiled and team discussion about what to do with each of the lists is being scheduled.

**Comment by CSwartzHMA** [comment]
All tasks are completed and lists are ready to be used when needed.
