### ISSUE TITLE
Support ID to update the eAPD for submission

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2399]
Creating this so we have a place to track activities relating to Idaho's request to update their previously submitted eAPD.

This task is done when...
 
- [x]  Any needed support has been provided to allow Emily to update and submit the eAPD
- [x]  The eAPD has been submitted successfully
- [x] Get a copy of the submission to review and compare back to the app field requests
- [x] We get word on the CMS review team's response
- [x] Interview Jonathan Jackson, federal reviewer
- [x]  The team has debriefed on the process, lessons learned and whether additional research is needed relating to the experience
- [x]  Resulting issues have been identified in road map, murals, and any new tickets.

**Comment by CSwartzHMA** [comment]
Support has been provided and we are awaiting confirmation that the eAPD was successfully submitted.

**Comment by CSwartzHMA** [comment]
eAPD was submitted.

**Comment by beparticular** [comment]
@jeromeleecms could we get a copy of the submitted APD?

**Comment by beparticular** [comment]
Will review the submission in design sync 8/18

**Comment by beparticular** [comment]
@CSwartzHMA do we want to close this, or do we need to keep it open to follow up on the new export that was sent to the reviewers?

**Comment by CSwartzHMA** [comment]
I think we are fine to close this now and will add new issues for any concerns identified later.
