### ISSUE TITLE
Give users the ability to choose FFYs before entering their Key Personnel 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2403]
We noticed this in working with DE on their beta submission this year. 

The ability to choose the years that are represented in the APD is located on the Program Summary page in the app. 

However, when you enter your Key Personnel, which comes before Program Summary, you're entering Key Personnel for the default years of the APD as the APD is initially created. 

So if you add a year in Program Summary, the Key Personnel information is now blank for the added year. 
You'd have to notice in the summaries and tables later that your KP doesn't cover all the years represented in the tables. 

I can see us going potentially two directions with this: 
1) Possibly an easy way, but not the most ideal - Move Program Summary above Key Personnel entry on the application
2) What would be the way that might make more sense to users -  Add the Key Personnel entry to Activity 1, Program Admin, since that is the Activity is it calculated under. DE was expecting to see Key Personnel in all the Activity staff tables, since it appears to be an APD wide field as it's presented now.

Additional considerations - scalability. What implications does adding MMIS and E&E have for this change? 

### This task is done when...
 - [x] A decision is made on which direction to go in
 - [x] Designs are created and approved by product

**Comment by beparticular** [comment]
@jeromeleecms 
for HITECH, KP costs are added to the Program Admin costs (activity 1) 
for E&E and MMIS, where are the costs for KP expected to be rolled into in the current process (not in the app)?

**Comment by jeromeleecms** [comment]
Was thinking about this earlier - once we remove Activity 1, we might have to spin up a separate table that lives in the summary budget section that pulls out the key personnel and make that shift across the board for the entire app. Not sure where else we would be able to capture it. Does that make sense? Other thoughts?

**Comment by beparticular** [comment]
@jeromeleecms do you have an example of where they add the Key Personnel now in the current paper process or what they are used to seeing?

**Comment by jeromeleecms** [comment]
I can try to find one, but in the existing format, the key personnel would be included in the personnel resource statement with an explanation for that person's role.

**Comment by jjames521** [comment]
@jeromeleecms were you able to find an example?  I'd like to take a look.

**Comment by jeromeleecms** [comment]
Funny you should ask - I just got one yesterday where I had coached the state on where to put it in the template. Will upload that to our Google Drive example APD folder.

**Comment by beparticular** [comment]
@thetif I spoke with Jerome today and option 1: Moving the Program Summary page/nav above Key Personnel works for release without causing any issues or complications for Cake Layer 2. So the app would start with Program Summary and the second option on the nav would be Key Personnel. Let me know if you see any issues with that as you or @radavis get into it. 

Re: in the future Key Personnel tables don't have to be part of Program Administration activities - it can live elsewhere if that makes more sense. Likely they will for simplicity.
