### ISSUE TITLE
Explore what additional features of a rich text editor would be good for users on narrative fields

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2404]
In our session with the state of ID, it was noted that the formatting of the text copied and pasted into the narrative fields doesn't always match because the information is gathered from multiple sources, and multiple people who are using different fonts/formats in different Word docs, tables, PDFs, etc. In some cases, the formatting cannot be cleaned up to be consistent. 

We should at minimum allow for states to be able to consistently format the text, a possibility could be a feature in tinymce that allows for styling to be cleared, or allows for a clean copy/paste from Word/documents. 

The formatting holds in the export view, so whatever is pasted in and cannot be edited for styling appears in the export view and sent to reviewers. 

Limit scope: not currently considering styling for behaviors around updating an APD, but it could be relevant in the future. 

### This task is done when...
 - [x] We discover what features are available, and decide what features are necessary for our users on release. 
 - [x] We discover if another editor might have better formatting options that are free/open source.

**Comment by beparticular** [comment]
There are some great features we could use, some of which might help us have a mini update experience until we can build things out? @jeromeleecms @jjames521 @thetif let's plan to talk and check these out at design sync tomorrow. 

Things that would be great to implement now (basics) - 
Bullet Points
Text Color
Highlights
Power Paste (solves issues pasting from Word) https://apps.tiny.cloud/products/powerpaste/?_ga=2.237679753.827982155.1597073637-1256076199.1597073637

For updates - 
Permanent Pen (a special setting to write in a different format to show changes) 
Checklists - could be an interesting way for folks to note what needs to be changed
Comments - for folks working together within the same APD

For fed experience - 
At Mentions/Comments (would we need to put this through ATO if we provided a list of account users) 

Other future things to look into - 
Real time collaboration

**Comment by beparticular** [comment]
@jeromeleecms just wanted to check if you have any further thoughts on this before I move it officially to dev?

**Comment by jeromeleecms** [comment]
Would the "format" option just sit as a separate dropdown? Should we include the "Edit" as well? 

I'm OK with waiting for the power paste functionality - seems like we could get this in and see how it falls shorts for users. Maybe sneak that into a user research debrief?

**Comment by beparticular** [comment]
@jeromeleecms 
The only options under Edit are undo, redo, and select all, which are all already possible, so I don't think we would need to include Edit. 

I think dev could explore redundancies in the toolbar and the format menu and see what options we have for moving those around in the code? For instance, can we pull out the most important ones to the toolbar, and not repeat them under format? Or could format be on the same line as the toolbar, etc? @thetif

**Comment by jeromeleecms** [comment]
If we can pull that functionality into the toolbar/in the same line, that would be ideal - I didn't like the idea of a single item by itself in that space where "Format" looks more a title to the box and not dropdown - by having the edit there, the user would know that there is more "options" there.

**Comment by beparticular** [comment]
@jeromeleecms it looks like we can add whatever we want as the titles for the menu, i'm just not sure how things can be split up. i'd like to pass this on to dev and work with @thetif so that we can have a better idea of what's possible. 
for instance, could we name menus that call out things we'd want folks to do in an update with redlining or something before we have the update experience.

**Comment by nicholeweems** [comment]
Ready for Dev ticket

**Comment by beparticular** [comment]
Some of this is being take care of in #2521 

For progress on this issue, we're looking into the Powerpaste feature again and seeing if the costs make sense.

**Comment by beparticular** [comment]
Had a meeting with TinyMCE to get pricing. They are sending over some information. 
Also looking at other editors like CKEditor (used by CMS OC - have a call in to CKEditor about pricing), Summernote, quill, and others. 

TinyMCE power paste works really great, similar to summernote. 

CKEditor has the ability to do comments, real time collab, and good copy/paste formatting, and tracking changes. I imagine the pricing would reflect this, but what would the trade off be if we didn't have to build that piece out and could focus on other things. Will do more research on this. 


Taking a break from this issue until we have some pricing details gathered. 
We're ok to release with TinyMCE as is, so no rush on this.

**Comment by beparticular** [comment]
Concluded with product, we're good for release. Will add a new ticket to explore and research TinyMCE vs CKEditor and whether the paste issue is something worth paying for, or switching for.
