### ISSUE TITLE
Validation Considerations

### ISSUE THREAD

**Issue by jjames521** [CMSgov/eAPD#2405]
This task is to identify and capture future considerations for validation of errors.  We have already established a planned deployment of Inline Instant Error Validations with #2346 but need to consider other fields such as description boxes etc.

Some thoughts and considerations so far;

- How are we handling empty fields in the export view? 
- Do they make sense to reviewers as intentionally empty, or missing info?

Related issues/tickets:
#2346
#3317

The mural is located here: https://app.mural.co/t/cmsmural6360/m/eapd5455/1588781600846/74a95a2db5d0b3e72c73cc7a96e6b501f40dcbd1

### This task is done when...
 - [x] We have decided on error validations to roll out.
 - [x] Product/Design agrees

**Comment by jjames521** [comment]
@beparticular new error validation consideration ticket

**Comment by jeromeleecms** [comment]
Complete scope of this ticket. Dev issues for implementation will be tracked separately.
