### ISSUE TITLE
Update "unable to save" warning to use modal pattern

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#2406]
Update the "unexpected error saving" message to use the modal pattern provided by design.cms.gov

Update the text on the save changes error pop-up

Header: Unable to save changes!

Body: Your changes aren't being saved. Try saving your changes again in a few minutes by clicking on the save button. If you refresh your browser without saving backing up your changes, changes made after this message appeared will be lost.

### This task is done when...
 - [x] Old message pattern is removed
 - [x] "Unexpected error saving" now uses the modal pattern
 - [x] Update the text in the modal to the above header/body text

**Comment by beparticular** [comment]
Here is the language from the closed design ticket to use on this modal. I'm not sure what the corresponding dev ticket is and didn't find a duplicate. 

Header: Unable to save changes!

Body: Your changes aren't being saved. Try saving your changes again in a few minutes by clicking on the save button. If you refresh your browser without saving backing up your changes, changes made after this message appeared will be lost.

**Comment by eStar386** [comment]
QA Passed: Verified that the modal appeared when applicable at the top of the header/body text.

**Comment by eStar386** [comment]
Please use the test script when testing in addition to any personal methods https://drive.google.com/file/d/1cazcjKnuzwWaipu5iHaooZDsbYJG9wJr/view?usp=sharing
