### ISSUE TITLE
Add help text to Contract Term field

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2407]
During user research we have heard several questions around how to complete the Contract Term fields. Help text should be added to guide users.

### This task is done when...
 - [x] Team has agreed on help text verbiage
 - [x] Change log has been created with mock up, if needed

**Comment by CSwartzHMA** [comment]
@jeromeleecms @beparticular 

**Suggested help text to be added to Private Contract Costs>(Edit)>Contract Term:**
Provide the start and end dates for this contract. Contracts may extend beyond the FFY(s) included in this APD. 

I am actually thinking this should be in the form of instruction, similar to the way it is presented in the Activity Schedule section, and not in a blue box.

**Comment by jeromeleecms** [comment]
This looks fine. I also agree that this should be in the instruction, from a consistency standpoint, I've been leaning towards using the blue box specifically to give concrete examples, but hopefully that's what you and @beparticular have also been doing...

**Comment by beparticular** [comment]
Yes, we've been doing that with instruction vs examples. 

@jeromeleecms We'd also mentioned potentially removing "Provide the start and end dates for this contract." because its' redundant to the fields we show. 
The thought behind it is that removing that redundant text might highlight that contracts can extend beyond this FFY in the help. Thoughts?

**Comment by jeromeleecms** [comment]
Provide the total cost of the contract, not the total amount you are requesting for the FFYs. Total contract cost will not be added to your FFY request.

**Comment by beparticular** [comment]
@jeromeleecms @CSwartzHMA like this? 

![Screen Shot 2020-08-05 at 2.08.34 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/7ecf8d9f-af05-466f-a291-2d216a6a62ae)

**Comment by jeromeleecms** [comment]
This fine. Did you want to include the language for the contract term we discussed in this mockup too?

**Comment by beparticular** [comment]
@jeromeleecms yes - do you still have that draft handy that you can share here? i'll add to the mock up

**Comment by jeromeleecms** [comment]
Here's the content from Caryn's draft above, removing the language for "Start and End date" as proposed...

"Contract term may extend beyond the FFY(s) included in this APD."

**Comment by beparticular** [comment]
@thetif this is ready for dev! 

Change log - 

- Help text added under Contract Term heading: 
Contract term may extend beyond the FFY(s) included in this APD.

- Help text added under Total Contract Cost heading: 
Provide the total cost of the contract, not the total amount you are requesting for the FFYs. Total contract cost will not be added to your FFY request.

![Screen Shot 2020-08-06 at 8.10.29 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/0ed6c1f5-6790-4f6c-a90f-d43eca8dfb94)
