### ISSUE TITLE
Communication Plan to support release planning

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2409]
This is to capture all activities relating to communications around the release

### This will include
 - [x] FAQs
 - [x]  ListServ
 - [x] Trainings and Toolkits
 - [x] Webinars
 - [x] Document storage plan and procedure for updating and refreshing stored documents

**Comment by CSwartzHMA** [comment]
Plan has been drafted at a high level [here](https://docs.google.com/document/d/11N4H84Qwk44XxSusmaH6gSJiCTChN8raY_zdyk7N6Ug/edit?usp=sharing). Mural board in process.

**Comment by beparticular** [comment]
Mural board 
https://app.mural.co/t/cmsmural6360/m/cmsmural6360/1619115882654/7e266614f1e14f0908697c7958cc8c5c25d1da8e

**Comment by CSwartzHMA** [comment]
FAQ draft is under review and will be posted and updated as needed.
