### ISSUE TITLE
Clicking on the navigation places you right below the anchor point

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#2410]
Clicking the navigation should place you in the right place in the builder:

Incorrect: 

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/6d13a167-13ed-422e-b3a3-161440d5234d)

Correct: 

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/8df430d9-489b-4c4d-ada5-e49d22a3dcf0)

### This task is done when...
 - [ ] Clicking on the nav bar puts you at the anchor point within the application
 - [ ] 
 
*Add a LABEL (design, dev, compliance, BUG, etc) before submitting.

*If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for PRODUCT to prioritize.

**Comment by beparticular** [comment]
just uploading a very loosely related image for the wiki 
![Screen Shot 2021-01-27 at 3.50.23 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/37124b98-ba98-4ee0-b02b-63a68496da00)
