### ISSUE TITLE
Warn users about lost data before they uncheck a FFY

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2416]
If a user unchecks a FFY on the Program Summary page, any data in the APD that is FFY specific is deleted. This is not stored and does not come back if a FFY is rechecked. This deletion is immediate. 

We should use the current modal option in the system to warn users that unchecking a FFY deletes any FFY specific data in their APD and are they sure they want to do that. 

### This task is done when...
 - [x] A mock up and content is created to show this warning
 - [ ] Addition is approved by product 
 - [ ] This issue becomes a dev task

**Comment by jjames521** [comment]
@beparticular 

Here are two different content variations.

**Variant 1:** _"Unchecking Federal Fiscal Year (FFY) 2020 will permanently delete any FFY 2020 specific data in the current eAPD."_

![FFYDeselectingProgramSummaryVar1.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/2dc1a781-1921-4206-8d30-dedaed405d68)

**Variant 2:** Changing _"Unchecking"_ to _"Deselecting Federal Fiscal Year (FFY) 2021 will permanently delete any FFY 2021 specific data in the current eAPD."_

![FFYDeselectingProgramSummaryVar2.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/304c1a33-dca6-4c02-81f6-5c520e5282a9)

**Comment by beparticular** [comment]
@CSwartzHMA I think unchecking is the better way to go, more plain language, less techy. For the end of the statement "the current eAPD" is that the best way to describe the APD you're working in right now or do we need to be more or less specific. For instance - 

"Unchecking FFY 2020 will permanently delete any FFY 2020 specific data you've previously entered."

**Comment by CSwartzHMA** [comment]
@beparticular I think I like "the current eAPD" since I am afraid "previously entered" may be more likely to make someone think this may mess up an older eAPD. Or maybe even consider "Unchecking FFY 2020 will permanently delete any FFY 2020 specific data already entered in other sections of this eAPD."

**Comment by CSwartzHMA** [comment]
@beparticular Also, is this true? I thought it was a limited amount of data that would be lost.

**Comment by beparticular** [comment]
@CSwartzHMA 

Ok great on the "current APD" that's helpful. 
I think "FFY 2020 specific data" is accurate. 

With those things in mind, I think Jesse's original ""Unchecking Federal Fiscal Year (FFY) 2020 will permanently delete any FFY 2020 specific data in the current eAPD."" is accurate and ok to use.

**Comment by beparticular** [comment]
@jjames521 per our convo, make "ok" on the modal "delete"

**Comment by jjames521** [comment]
@beparticular 

**Change Log:** 

- Chrome modal pop up with text "Unchecking Federal Fiscal Year (FFY) "Y" (Y being the FFY unchecked) will permanently delete any FFY "Y" specific data in the current eAPD."
- Designate _"Cancel"_ the default highlighted button
- _"Cancel"_ and _"Delete"_ as button text

**Mockup:**

![FFYDeselectingProgramSummaryVar1.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/076597bd-1f96-4018-b202-f6b60c90dbe5)

**Comment by beparticular** [comment]
@jeromeleecms want to do a final check before we pass to dev?

**Comment by jeromeleecms** [comment]
Just two notes:
1) Here’s my mental model for how we refer to and how we have been referring to things in the app: eAPD is the name of the product, the output of the eAPD will be an APD.  So in the warning box, we should refer to it as an “APD” instead of an “eAPD.”
2) Also, I didn’t see it explicitly called out here, but the FFY should reflect the FFY that is been “unchecked” - I’m assuming that’s the case, but just wanted to level set. 

Other than that this looks great.

**Comment by beparticular** [comment]
@jjames521 I added Jerome's thoughts to the change log. 

@thetif this is ready to become a dev ticket. Summary is correct on comment https://github.com/CMSgov/eAPD/issues/2416#issuecomment-673705543
