### ISSUE TITLE
Apply consistent styling to OKRs section across builder and export view

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2419]
Update the export view:
- Include light divider line in export view to separate the objectives.
- Take bullets out of export view and reflect the style of current builder view.

Update the builder view:
- Move up Objective statement to align with "Objective:" and decrease bold on statement for builder view (currently export view shows this if any reference is needed for styling). I've provided a "Before" for clarity.

Original design task is #2392

### This task is done when...
 - [ ] The Objective styling is updated in the builder
 - [ ] The Key results styling is updated in the export view
 
![image.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/f250e1f9-0331-454a-80da-835951502f92)
![image.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/19d27995-cf50-41d4-a38e-4bf62ef63cc0)
![image.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/914464d3-3cb6-4377-9d2e-d26c8d09f233)
![image.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/d9837a25-2872-40c5-b41f-97dd2a923f27)

**Comment by beparticular** [comment]
Closing as this will be taken care of in #2446
