### ISSUE TITLE
Estimated Quarterly Expenditure table is overwriting across Activities

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2421]
Actual Bug - 
On APD creation, Activity 1 doesn’t have any % break down in the Estimated Quarterly Expenditure table. 
When Activity 2 is created, both Activity 2 and Activity 1 now shows a 25% break down across the FFY table. 
Both Activity 1 and Activity 2 overwrite each other and all other activities when the % is changed in the table. 
This happens per FFY, the figures don’t interact across FFYs 

----------

History - we thought this was the bulk of the problem, but see above for the actual bug. 

On the FFP and budget page > Estimated Quarterly Expenditure table, the behavior is supposed to be that the quarterly amounts are automatically split at 25% across the table as shown here 
![Screen Shot 2020-08-05 at 1.18.15 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/a1603dfe-2be6-4f14-91a8-0ff995949db6)

In Activity 1, the split is defaulting to 0%. It should be defaulting to 25% across each quarter. 
![Screen Shot 2020-08-05 at 1.17.55 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/bf1e559d-b9e1-4dbc-89d4-2418b0e3497e)

Steps to reproduce: 
Create New APD
Look at Activity 1 > FFP and budget > Estimated Quarterly Expenditure table > no % is split
Create a new activity > FFP and budget > Estimated Quarterly Expenditure table > the table is split at 25% 

### This task is done when...
 - [ ] The table is splitting the numbers across quarters at 25%

**Comment by beparticular** [comment]
Discovered in testing that entering % into Activity 1 overwrites the % in all the other activities. Need to fix before release.

**Comment by radavis** [comment]
Seems like the `UPDATE_BUDGET` action is updating all activities within an APD. So, I've narrowed the issue down to being somewhere within our redux code.

![Screenshot from 2020-12-30 15-26-25](https://user-images.githubusercontent.com/1299034/103379524-e403fc80-4ab3-11eb-99fc-7f777ce7dd0e.png)
