### ISSUE TITLE
Remove "Summary" from instances of Activity Schedule Summary 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2425]
As we're wrapping up our nav content review, we'd like to simplify nav labels whenever possible so that the navigation is more scanable and readable. 

For instance - Activity Schedule Summary = Activity Schedule 
There was no determined need for the word Summary 

### This task is done when...
 - [ ] change the Activity Schedule Summary to Activity Schedule on the nav
 - [ ] change the title of the current Activity Schedule Summary page to Activity Schedule
 - [ ] change "Schedule Summary by Activity" to "Schedule by Activity" 
 - [ ] while we're on this page: the help text under Schedule (Summary) by Activity looks like it was added by mistake as it is a repeat of the content on the Milestones tables. Remove the content "The following tables aggregate the activities, milestones, and dates based on the individual milestones described for each activity." 
- [ ] Don't forget export view

**Comment by beparticular** [comment]
In our recent testing, folks were having some issues with differentiating between where you add the Activity Schedule in Activities and the Activity Schedule Summary. This might be a bigger issue than just changing a label. It goes along the lines of how I keep thinking about input vs output. Keeping this in the icebox for now until we can further explore that idea.

**Comment by jeromeleecms** [comment]
We will review this at a higher level to establish the flow of the app and clarity
