### ISSUE TITLE
Warn users about lost data before they uncheck a FFY

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2445]
**Change Log**:

- Chrome modal pop up with text "Unchecking Federal Fiscal Year (FFY) "Y" (Y being the FFY unchecked) will permanently delete any FFY "Y" specific data in the current APD." (This would refer to whichever FFY they have unchecked. Only one would be able to be unchecked at a time, so multiple FFYs are not needed in this alert.)
- Designate "Cancel" the default highlighted button
- "Cancel" and "Delete" as button text

**Mock up**
![image.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/2a421b48-a4a5-4ce8-a5f4-17e41ec4dace)

Original design task #2416

### This task is done when...
 - [ ] a Chrome modal pop up appears when a user unchecks a FY 
 - [ ] the modal is wired into the deletion process

**Comment by beparticular** [comment]
@tbolt in the browser modal, can we change the text from "ok" to "delete" ?
