### ISSUE TITLE
Rename Objectives and Key Results to Outcomes and Metrics

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#2446]
Per our discussion with Nick, we should rename the OKR section of the app to line up with the CMS' new language. The description of Outcomes and Metrics are described below:

Outcomes – These describe the measurable improvements to a state’s Medicaid program that result from the delivery of a new module or enhancement to an existing system. Outcomes should support the priorities of the Medicaid program, be directly enabled by the state’s IT project, and be stated in the Advance Planning Document (APD). CMS will partner with states to ensure that project outcomes are correctly scoped to the project. These include CMS-required outcomes, aligned to the applicable regulatory requirements, and state-proposed outcomes, which describe program improvements the state desires to achieve with the implementation of the new module or delivery of new systems functionality. If a project has an already-approved APD that does not include applicable outcomes, CMS will work closely with the state to identify and validate outcomes for that project as part of the APD-Update (APD-U) process or during preparation for a review.
Metrics – Metrics support both CMS-required and state-proposed outcomes, and are comprised of underlying data. In accordance with 42 CFR §433.112, states are required to report on the system’s performance to CMS as a condition for receiving enhanced funding. Reporting of metrics (and underlying data) enhances transparency and accountability of IT solutions in meeting regulatory requirements as well as the state’s program goals. State reporting also gives states and CMS early insight into program evaluation and opportunities for continuous improvement.

### This task is done when...
 - [x] Mockup for Navbar is provided
 - [x] Mockup for OKR section has been provided
 - [x] Review of help text has been completed + with Mockup if needed
 - [x] Export view is done

**Comment by beparticular** [comment]
@jeromeleecms @NAretakis 

Before I rope Caryn in to double check the content, is this along the lines of what you were thinking and still make sense in context? 

![OKRtoOutcomesandMetrics.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/8d011bb3-a396-4d44-9489-1208e7fcae2f)

![OKRtoOutcomesandMetricsEdit.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/94288c51-93f3-4e4a-82b4-87ce3e49ef55)

**Comment by jeromeleecms** [comment]
We should remove the time dimension/references in the example metrics. So "Complete SLR Modifications by 11/1/18" should probably be some more along the lines of "Modify SLR to support CMS regulatory and subregulatory guidance." 

In terms of the help text, there is a lot, but because this is a relatively new concept, I think more comprehensive may be better.

@NAretakis Is much closer to the overarching move to Outcomes and Metrics, so looking a bit in his direction if there something that I might be missing.

**Comment by NAretakis** [comment]
**Here is our current guidance on Outcomes and Metrics**
Outcome - a discrete and measurable improvement to Medicaid program management, monitoring, or administration, resulting from the delivery of IT system functionality

Metrics - measures that would demonstrate whether a system is meeting an outcome

Data - production information for the agreed-upon metrics that states provide to CMS to demonstrate whether a system is meeting the agreed-upon outcomes

![image.png](https://images.zenhubusercontent.com/5c536083d11206601037eb29/f9418354-1f8c-493b-a327-16c23d5c5d99)

![image.png](https://images.zenhubusercontent.com/5c536083d11206601037eb29/ec20a3ee-8e29-49ca-8f10-a82bab4290ad)
![image.png](https://images.zenhubusercontent.com/5c536083d11206601037eb29/418ebb27-0f8e-4110-a03c-8f25cb04704a)

![image.png](https://images.zenhubusercontent.com/5c536083d11206601037eb29/acba8253-5f31-4138-aba4-ab5b8c1a3c1a)

**Here are some example outcomes and metrics, the above looks good, but maybe let's sub in some of these examples:**

- Outcome - Improving insight into Medicaid services by identifying utilization of ED and hospital admissions and gaps in services to inform Medicaid’s program administration and providers on Medicaid population’s health.
- Metric - Ability to generate a report to Medicaid detailing beneficiary hospital utilization (ED, inpatient, readmission) and key prevention quality indicators (PQIs)
<br>
- Outcome - Support state mandated reporting of reportable diseases for public health surveillance and disease control activities.
- Metric - Counts of reports from providers by reportable condition reported from the system per quarter. 
<br>
- Outcome - Support providers for increased capture of infectious disease surveillance data and exchange of data between data senders and receivers.
- Metric - Number of providers by specialty and county reporting electronically to the system. 
<br>

**Comment by davidkoppel-cms** [comment]
whoever made these slides is good

**Comment by beparticular** [comment]
@NAretakis do we still want to leave Target and Baseline in as we make the move over to Outcomes and Metrics?

**Comment by beparticular** [comment]
@NAretakis and @CSwartzHMA for your review - 

Looking for comments on 
- The first paragraph that describes Outcomes and Measures
- The design of the summary of outcomes and measures
- The content on the edit view 
- The design of the edit view 

Still in progress - determining what example we'd like to show

**Comment by CSwartzHMA** [comment]
In the instructions, rather than "as described above" should we say as described in the Activity Overview section? Also, I think there will be questions about CMS-required outcomes if we reference them here. @NAretakis Is there a current list of these that we could provide? Might be a good FAQ if we can't link to something here that would be up to date.

Suggest formatting the blue box like we have in other sections, so no bold text and start with "Example". For this, maybe we could start with "Example Description:", then list the outcome and metric below that.

The edit view text is good.

**Comment by beparticular** [comment]
@CSwartzHMA good catch on the "as described above" that was a hold over from a copy/paste. I took that out. 

I'll also add example into the blue box. I left Outcomes and Metrics in bold in the example box since the design is in bold in the summary. Thoughts on keeping that matched? 

(Also, we're pretty inconsistent in our use of "Example" and using the box as an example. I'm going to jot that down for later.)

@NAretakis when you get a chance, if you have the example you want to use and/or any feedback let me know and I can button this one up. Thanks!

**Comment by CSwartzHMA** [comment]
I don't have strong feelings about the use of bold text. I was looking at the sections within Program Activities for comparison and didn't see bold there, but probably something we can clean up later. the content is really more important for now. I am good with what you have here.

**Comment by beparticular** [comment]
Per Nick, all is well and an example will be provided. Issue on hold til then.

**Comment by NAretakis** [comment]
Here is a good example that we can use. Let me know if you think it needs to be word-smithed at all. 

**Outcome**
- Develop and implement an MES Module to coordinate and improve public health and environmental services for children exposed to lead.

**Metrics**
- Percentage of children in Medicaid that are receiving lead screening at 12 and 24 months of age.
- Percentage of children in Medicaid that receive timely public health case management and environmental services based on the Childhood Lead Poisoning Prevention Protocol for lead-exposed children.
- Percentage of children in Medicaid with lead poisoning that had timely follow-up testing by providers.

**Comment by beparticular** [comment]
Update screenshots and a change log - @NAretakis do you want to take a quick glance at the new examples. they look good to me. 

@jjames521 can you glance at the change log and see if I missed anything? 

![Outcomes and Metrics - Presented for Review 2.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/f10e3071-89fa-4d2f-ba9b-6bd3a9842656)


Change log : 
 1) Changed “Objectives and Key Results header to “Outcomes and Metrics” 2) Changed main help text to  ”Please describe how you will achieve the stated purpose of this activity in terms of Outcomes and Metrics. 

An Outcome is a discrete and measurable improvement to Medicaid program management, monitoring, or administration, resulting from the delivery of IT system functionality. Outcomes should support the priorities of the Medicaid program and be directly enabled by the state’s IT project.

A Metric is a measure that would demonstrate whether a system is meeting an outcome. Metrics support both CMS-required and state-proposed outcomes, and are comprised of underlying data. In accordance with 42 CFR §433.112.”  3) Changed example text to:
“Example:
Outcome:  Develop and implement an MES Module to coordinate and improve public health and environmental services for children exposed to lead.
 Metrics:   1. Percentage of children in Medicaid that are receiving lead screening at 12 and 24 months of age.
2. Percentage of children in Medicaid that receive timely public health case management and environmental services based on the Childhood Lead Poisoning Prevention Protocol for lead-exposed children.
3. Percentage of children in Medicaid with lead poisoning that had timely follow-up testing by providers.”

4) Added an additional separator after example and before the Outcome/Metrics summary
5) Changed Edit/Remove on summary to Edit | Delete, matching the Activity List 
6) Changed button to “Add another outcome”


7) Removed Target and Baseline from entry fields and summary
8) Changed help text on Outcome field to “Describe a discrete and measurable improvement for this system.”  9) Changed “key results” field to “Metric” 
10) Changed help text on Metrics field to “Describe a measure that would demonstrate whether this system is meeting this outcome.” 
11) Allows for multiple metrics 
12) Allows for deletion of metrics
13) Changed button to “Add another metric”

**Comment by NAretakis** [comment]
Rock and roll, good to go!

**Comment by beparticular** [comment]
@NAretakis thanks! 
@thetif this is ready to move to a dev issue. I've got the most recent mockup, text, and change log in the above comment.

**Comment by jjames521** [comment]
@beparticular Change log looks good, looks like everything is there.
