### ISSUE TITLE
Fix table related page breaks in the export view

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2461]
This isn't a high priority if the fix is large. But if the fix is small, it could go a long way to a better export. 

In the export view, the header/label for tables is frequently on the page before the tables. Let's determine why this is happening and what fixes might be available. 
Re: To make reading the export view easier, and to cut down on the number of pages that needs to be printed. 

![Screen Shot 2020-08-21 at 9.39.06 AM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/3ed9a08a-68d1-43a6-b248-fa353d6e72dd)

In this screenshot, the entire page below "Cost Allocation and Budget for FFY 2021" is blank and the table starts on a new page. 
![Screen Shot 2020-08-21 at 9.39.31 AM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/b1c612b5-f22e-4835-97f4-6130890bf6a9)

### This task is done when...
 - [ ] The cause of the page break is identified and shared with design (if any decisions are needed)
 - [ ] A solution is agreed upon
 - [ ] The page breaks between headers and tables is eliminated (hopefully this is possible!)

**Comment by thetif** [comment]
Will be fixed as part of custom PDF
