### ISSUE TITLE
MS Edge v84 browser is unsupported :(

### ISSUE THREAD

**Issue by radavis** [CMSgov/eAPD#2465]
I get the following page when visiting the eAPD app with MS Edge v84:

![Annotation 2020-08-21 105912](https://user-images.githubusercontent.com/1299034/90923304-720c0000-e3bb-11ea-91c4-8ee62ca56df0.png)

### This task is done when...
 - [x] MS Edge is supported by the app

Using `detect-browser` npm package. `browser.name` reports Edge v84 as `edge-chromium`. Update code in `src/util/browser.js` to handle this case.

**Comment by beparticular** [comment]
@radavis 

If we're using the same graphic this should work for mobile: 

! Mobile not supported
It looks like you might be using a mobile browser, but mobile browsers are not supported at this time. Please use one of these browsers on your desktop to use the Centers for Medicare & Medicaid Services (CMS) eAPD site.

**Comment by radavis** [comment]
Confirmed I can visit eapd.cms.gov w/ MS Edge v86.
