### ISSUE TITLE
Export view creates hyperlinks back to app when hyperlinks are incorporated into text boxes

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2473]
### This task is done when...
 - [ ] Team is in agreement on whether/how to address the issue
 - [ ] Next steps have been described in change log or in separate issues

**Comment by beparticular** [comment]
@CSwartzHMA can you note the steps to replicate this, or is it any link that gets added to the editor is just redirected to the app? 

I'm wondering if add more robust options into the editor in #2404 might fix this

**Comment by CSwartzHMA** [comment]
I am not sure whether the editor updates will allow for hyperlinks, as this may be an export issue. I cannot access the Idaho APD that was recently completed, but my understanding is that the content contained links to other websites (often states link to their SMHP or their state website), but the export converted these to link back to the app. 
![image](https://user-images.githubusercontent.com/45497254/91643363-aeb1aa00-ea00-11ea-9ba2-5cb35878a174.png)

I was not able to reproduce this in Staging. When adding a hyperlink, the link appears to be directing the user to the correct location in the export:
![image](https://user-images.githubusercontent.com/45497254/91643476-84142100-ea01-11ea-83c8-ee6323701e8c.png)

**Comment by CSwartzHMA** [comment]
@beparticular So now I am stumped.

**Comment by beparticular** [comment]
@CSwartzHMA is it any link that gets copied in that is getting striped and pointed back at the eAPD link?

**Comment by beparticular** [comment]
Next step - @CSwartzHMA to circle back with Emily and see what those links are since we can't make a link fail yet.

**Comment by beparticular** [comment]
Still unable to make copying links fail. We'll hold this one until we finish #2521 (updating tinymce for formatting options) and see if issues arise.

**Comment by beparticular** [comment]
We haven't been able to replicate this, but we do know that there are ongoing issues with formatting in TinyMCE when content gets pasted in from various sources. We're addressing this formatting problem as a whole on #2404
