### ISSUE TITLE
Users need to be aware of scheduled and unscheduled system down time.

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2478]
As part of the communications plan, we should develop a plan for notifying users of planned and unplanned system down time.

### This task is done when...
- [x] Determine how much lead time we’d like to give, if possible before planned system downtime. 
- [x] Determine who is responsible for posting comms via Slack, email, and system (for unexpected downtime, follow the on call schedule?)  
- [x] Write comms for expected downtime for Slack, email, and system message (log in page screen, log in error message). 
- [x] Write comms for unexpected downtime for Slack, email, and system message (log in page screen, log in error message). 
 - [x] Team has discussed options for communicating down time
 - [x] Communications plan has been updated to incorporate agreed upon approach
 - [x] Team has discussed what is shown to the end user within the application

**Comment by nicholeweems** [comment]
Per team discussion on 8/31/2020, this along with the blocked issue will be a collaborative team effort. An upcoming working session will kick off discussion and subsequent planning.

**Comment by beparticular** [comment]
Slack?
Email to state admins? 
In app? - does the header alert for FFY #3202 give us a way to set an alert in the system?  - how would we put something on the log in page?

**Comment by beparticular** [comment]
Notes from parking lot. 

If downtime is expected, what happens in the app?  
Communicating out ahead of time via email to state admins and Slack in a good amount of time. 
Follow rules below. What does that exactly mean? 

If downtime is unexpected, what happens in the app? 

In app if they are logged in, what happens? 
Right now you get the not save error if you're in the APD. 
Other places you might want to know the system is down: requesting a state, admin panel changes, exporting an APD. 
Need to handle 502 error correctly on the front-end. What does correctly look like? 
There is a ticket in where you can log out if you get the not saved modal. Can you log out when the system is down? 

On ticket 
Do we show something on the log in screen before they try to log in? 
Yes - needs design. 
Do we have special error when they try to log in and we aren't there? - ticket exists to try and get the message updated so it's correct. (What is this ticket #?) 
Yes - does this need design?

**Comment by CSwartzHMA** [comment]
We may want to create standard messaging for email and slack and define who is responsible for posting/sending.

**Comment by jeromeleecms** [comment]
Does this overlap at all when a user is offline? When you are offline and try to create an APD, it just takes you to "Loading your APD." 

Does that mean than that "unexpected system downtime" = whenever a user can't take the next action they requested?

**Comment by beparticular** [comment]
Jerome - creating an APD would be another good place to show the not saved modal. I'll add that. 

Unexpected system downtime technically refers to "whenever a user can't save or create something in our system because of something we did". If we do add the not saved modal to other areas for this reason/issue, it would be an added help that they would also be notified when they can't create or save something because their connection is down.

**Comment by jeromeleecms** [comment]
@beparticular Is this ready to close? We can discuss when you are back.

**Comment by beparticular** [comment]
I think this is a question for @CSwartzHMA re: comms. 

I do see that we closed the issues regarding the log in screen alerts, but I'm not sure what else we've done while I was out to meet the acceptance criteria above? 

Also, should I remove myself from an assignee on this since it's mostly comms now?

**Comment by jeromeleecms** [comment]
For the scheduled System Downtime (slight tweak + potential impact for using the system at the time):
The eAPD system will be unavailable from XX/XX/XXXX XX:XX ET until XX/XX/XXXX XX:XX ET for maintenance. If you are logged in at that time, your work will not be saved. We apologize for this inconvenience.

Do we also need a "completion" email to go out as well? Something like
Maintenance on the eAPD system has been completed and is available for normal use.

For unscheduled (I think this is fine, though I'm on the fence about "Please try back later" and adding something about we will let you know when the system is back online): 
The eAPD system is currently unavailable. We are actively working to resolve the issue. _Please try back later_. We apologize for this inconvenience.

Do we also need a resolution email to go out as well? Something like
The eAPD system outage has been resolved and is available for normal use.

**Comment by CSwartzHMA** [comment]
SCHEDULED: I like your message and will add that our tracking and indicate it goes to Slack and via email one week prior to anticipated maintenance window. I will also add the resolution email, although I am thinking we have this covered since we include a start and end time in the original message. For Slack, we would want to be sure to add the resolution message as a new message, rather than in a thread for the original message, so that it is quickly seen. Do you agree?

UNSCHEDULED: The message that will be posted on the log in page when the system is unavailable reads: The eAPD system is currently unavailable. The support term is aware and working to resolve the issue as quickly as possible. More details and updates, when available, will be posted to the eAPD User Support Slack channel.

I think we will want to be consistent with this message, so I suggest: The eAPD system is currently unavailable. The support term is aware and working to resolve the issue as quickly as possible. More details and updates, when available, will be posted here.

I agree with your resolution email statement, and we can also use that same statement in Slack.

@thetif @cthulhuplus @beparticular Please review and let me know if you have any thoughts. I am particularly interested in your thoughts around our ability to include a start and end time for scheduled down time.

**Comment by beparticular** [comment]
@CSwartzHMA this looks good to me

**Comment by cthulhuplus** [comment]
@CSwartzHMA same as ^^^

**Comment by thetif** [comment]
agreed
