### ISSUE TITLE
Use September MES APD CoP to initiate communications about the release

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2487]
The APD CoP audience represents a good portion of potential eAPD users. This month's CoP timing is right to start to share and gather information with this audience.

### This task is done when...
 - [x] Draft content has been reviewed and approved by leadership
 - [x] CoP deck has been updated to incorporate eAPD release communications.
 - [ ] Feedback has been collected and shared with the team following the CoP.

**Comment by nicholeweems** [comment]
Meeting occurred on 10/2/2020
