### ISSUE TITLE
Create instructions for user (states only) to gain access

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2494]
### This task is done when...
 - [x] Instructions have been drafted for three groups (state user with EUA, state user without EUA)
 - [x] Location and method for distributing instructions has been identified
 - [x] Instructions are distributed/posted

**Comment by CSwartzHMA** [comment]
@beparticular @jjames521 I created a high level overview to incorporate into training materials and access instructions, but wanted to get your feedback from a design perspective. https://docs.google.com/presentation/d/1N1TDoXzboyUotvOblrNi8KXQdbKLfSj7NHd4_R_p3OQ/edit?usp=sharing

Here is an example with the content incorporated:  https://docs.google.com/document/d/1bK4oOO4pYGT0CpC5tv1YYIUvtnkL-CZWkKPJ7ErnfIg/edit?usp=sharing

**Comment by CSwartzHMA** [comment]
State user instructions are here for your review @beparticular @thetif @tbolt @jeromeleecms. Please let me know if any screens are now outdated. I will coordinate with @tbolt to get updates, where needed. Note that I have left the multi-state user note in but indicated the feature is coming soon. We can take it out but I know there will be questions about this and I thought this might let people know it will be an option. Either way, we will need to update this doc once the feature is added.

https://docs.google.com/document/d/1t4YFtNF9KO-8nwUIv6qksFzilkWJo4QZJhgidsVDa6Q/edit?usp=sharing

**Comment by CSwartzHMA** [comment]
Separating federal user access to a new issue to be completed when this feature has been added.

**Comment by jeromeleecms** [comment]
Made some suggestions/minor changes to the eAPD Access Process. I can't access the more recent link in your last comment @CSwartzHMA

**Comment by CSwartzHMA** [comment]
@akuas There is just one question for you in the document. Once that is resolved, this one will be ready to close.

**Comment by akuas** [comment]
We don't currently have a ui in place for when users select a state affiliation by mistake. Also, we aren't allowing users to select multiple states at this time, but we plan to in the future. In this first iteration, users they will see the state admin's email, they could email them if they did it wrong and ask them to deny it.

**Comment by CSwartzHMA** [comment]
The instructions are complete and have been posted. Updated needed prior to go-live will be addressed as they are identified.
