### ISSUE TITLE
Consider the use of a Slack channel for eAPD Users

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2500]
A slack channel could serve as a point of communication and a repository for training and communication materials, if well utilized by state and federal users.

### This task is done when...
 - [x] Leadership has approved the used of/designation of a slack channel for eAPD users
 - [x] The Team has decided how best to utilize the channel
 - [x] The issue will be updated with additional steps once these decisions have been made.

**Comment by CSwartzHMA** [comment]
Slack Channel has been created. Caryn to develop proposal on use of the channel for team to react to.
Users will need job code "SLACK_P_USER" in EUA to access channel. Channel is private.

@NAretakis Will you have to approve anyone requesting access?

**Comment by CSwartzHMA** [comment]
Proposed use of the eAPD user support slack channel for team consideration:
(FYI - Shortcuts takes you to workflows, which I don't think we will need to use at this time)
Channel Topic: Announcements and support for eAPD users
Pinned Items: 

- Welcome Message and Orientation (also to included in initial outreach)
- How to use this channel (parameters, where to find information, DM vs. general comments, threads, etc.)
- Scheduled Downtime (to be updated, as needed)
- Need Help? Who to contact

Files:

- How to access the application
- FAQs
- Webinar walkthrough and companion sample APD
- Tip Sheets

Additional opportunities to discuss: Post ship mail here? Post release notes here? Link to helpdesk here?

**Comment by beparticular** [comment]
@CSwartzHMA I think anything we send out as communications could also be added to the Slack channel to make it a useful place for folks to be. 

As we talked about, I'm working on some ideas around using emoji in Slack to call out official announcements, notices, etc.

**Comment by CSwartzHMA** [comment]
Slack channel has been created and use has been defined. Remaining issues are covered elsewhere in the Communication Planning epic.
