### ISSUE TITLE
Design communication templates

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2507]
As part of our communication plan for the release (and after), we need a set of templates to use. The new logo, eAPD email address and eAPD phone number will be incorporated.

### This task is done when the following templates are created...
 - [x] Signature for email
 - [x] Template for a Word doc
 - [x] Slide/presentation template for webinars or trainings
 - [x] full title page for presentation deck, with full logo and URL/contact info
 - [x] wrap up page for presentation deck, with full logo and URL/contact info

**Comment by jjames521** [comment]
@CSwartzHMA @beparticular 

Here are the template URL's and files I've been working with

https://docs.google.com/document/d/1e0_dF6ReIO0--PX6C9DJkfYrggoHhvFqRpyUQilf5kA/edit

https://docs.google.com/presentation/d/1jhJB0IgjzR905ulOMThgJ4JkOSoWdkthgzrZDcpBIWY/edit#slide=id.g98af35b05d_1_145

Slide Footer
![SlideFooter1.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/ecd782b1-e5e7-4a60-ab94-585dc350b02a)
Document Footer/Email Footer
![DocumentFooter.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/95291678-801c-44f0-94bf-02e29efc8138)

**Comment by beparticular** [comment]
@jjames521 can we see what the doc and slide templates would look like with the full logo? 

Also, I think we could put in the URL on the slide template for stronger identification. Might also just place in a spot for a date or presenter name as well. 

@CSwartzHMA thoughts? we can talk more at design sync today too.

**Comment by beparticular** [comment]
@jjames521 need a full title page and wrap up page for info with full logo (added to done criteria above)

Variant 1 selected for email footer initially to show branding and eAPD visibility

**Comment by beparticular** [comment]
@NAretakis do we need to incorporate any other logos or information on these templates (like a CMS logo or anything?)

**Comment by jjames521** [comment]
@beparticular @CSwartzHMA 

Here are the last assets, attached to the template as well.



![eAPDSlideIntro01.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/a0f40cc7-05e1-4c99-a15d-0bbb56b7112d)


![eAPDSlideOutro02.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/5fe8e160-67eb-4699-ae23-4a895d766c7c)

**Comment by beparticular** [comment]
@caryn - i like these additions if you do! if you're good feel free to use these and close out this issue.

**Comment by CSwartzHMA** [comment]
@jjames521 Is there any way to make the footer on the Word doc repeat? I added a page break so I could drop the email footer there for future retrieval and I noticed the footer does not appear on page 2.

**Comment by CSwartzHMA** [comment]
These templates have been adopted for use in communications.
