### ISSUE TITLE
Create SLA/O/I Document

### ISSUE THREAD

**Issue by nicholeweems** [CMSgov/eAPD#2510]
Create a DRAFT SLA/O/I Document that outlines our Service Level Agreements (nothing), Objectives, and Indicators. 

### This task is done when...
 - [ ] Service Level Indicators are identified
 - [ ] Service Level Objectives are identified
 - [ ] SLA/O/I Document is created

**Comment by cthulhuplus** [comment]
https://docs.google.com/document/d/1v7QOdLMM4yaLRF70DGvM1HaAbLYJn4Cc2Zn-uwImzdI/edit?usp=sharing
