### ISSUE TITLE
Workshop what is contained in an MES i-APD

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2516]
### This task is done when...
 - [x] We take the HITECH APD and mark it up to show what would need to change for an MES i-APD template in the eAPD system 
 - [ ] We know what needs to be changed
 - [x] We know what doesn't need to be changed to support MES expansion
 - [ ] Break down the difference between what is needed for MMIS and E&E (could branch off into a separate issue)
 - [ ] Any additional issues are created to support the design needs and specific changes for expansion (e.g. #2518, #2336, #2372, #2303)

**Comment by beparticular** [comment]
Progress - we have a lot of this done, next week or so we need to focus on what we really need to make the MDBT table happen

**Comment by beparticular** [comment]
Status: Product is giving this one more glance to see if we've missed anything and we should be able to close out this issue and move forward with designs and other APD types next!

**Comment by NAretakis** [comment]
On it, will review today.

**Comment by NAretakis** [comment]
Mural board looks good. Lots to do, but its so exciting! This is ready to close out from Product's point of view. You may fire when ready. @beparticular
