### ISSUE TITLE
Standards and conditions fields should match in builder and export views

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2531]
Update the standards and conditions fields so that how they were generated in the export view is less confusing. There should not be a default selection. The explanation field shouldn't appear until a selection has been made.

Design task #2519

Builder
![image.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/fd6d7a38-3029-4bd3-b4c6-78da529addc3)

![image.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/a10b9638-1b9e-45e4-b45e-b549f250f584)

Export
![image.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/b90d47de-09cf-44de-9294-c537aca41591)

### This task is done when...
 - [ ] the standards and conditions field is updated
 - [ ] the text in the explanation field changes based on yes and no
 - [ ] the export view is updated to match the new field

**Comment by beparticular** [comment]
closing this issue because the answer can be yes and no on the same activity and we need to think of another solution.
