### ISSUE TITLE
Consider the use of a central email account for user support/communications

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2536]
Users and the CMS helpdesk may need to reach out to the team for assistance and we may also need a mechanism for communicating out to users through an account multiple team members can access.

### This task is done when...
 - [x] Options for creation of a group email account have been explored
 - [x] Action items stemming from the decision above have been address in new issues.

**Comment by CSwartzHMA** [comment]
@NAretakis will look in to:

1. Allowing additional access to the existing account (CMS-EAPD@cms.gov) for use in regular communication with users.
2. Creation of a new account to be used by DevOps and others for technical support and for communications with the Help Desk.

@cthulhuplus Is there more to add for context for #2?

**Comment by cthulhuplus** [comment]
A shared email account that we can send our alerts to can allow us to do a rotation of responsibility for people checking the ops/support email.

**Comment by jeromeleecms** [comment]
Adding @NAretakis to help him keep track of this. Last update related to this was Nick was going to check in with Eg.

**Comment by jeromeleecms** [comment]
@NAretakis has submitted a helpdesk ticket to add the team to the central mailbox. Pending a response.

**Comment by CSwartzHMA** [comment]
@NAretakis @jeromeleecms Update: I have completed the eQIP and fingerprinting requests and will keep an eye out for information on next steps.

**Comment by NAretakis** [comment]
Workaround has been put in place. I have setup an auto-forwarding rule so that the shared eAPD mailbox forwards any incoming emails to the eAPD team. This doesn't cover everything, but is viable for the short term. Nick and Jerome can still manage the eAPD mailbox directly.
