### ISSUE TITLE
Design in app notification for account permissions approval or denial

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2539]
When an account is approved by a state admin, a notification will need to show in the user account to alert the coordinator or contractor that their account has either been:
Allowed
Denied
Revoked

Content should contain:
Status of account (per state or for each state)
Permissions granted (what they can do in the account)
If they have questions, pls contact their state admin for more info (not sure if we should tell them who this is based on who denied or approved their account, or if it should be a generic message) 

### This task is done when...
- [x] Notifications are designed for single state
- [x] Notifications are designed for multiple states access
- [x] Notifications messages are written 
- [x] Product agrees on design

**Comment by jjames521** [comment]
@beparticular @thetif @radavis 

Log In Flow w/notification flow:

Includes annotation for review.

https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=787%3A8
