### ISSUE TITLE
Enablement in preparation for upcoming Table Top exercises

### ISSUE THREAD

**Issue by nicholeweems** [CMSgov/eAPD#2541]
In preparation for the upcoming Table Top exercise, participants should complete several enablement tasks including

### This task is done when...
 - [ ] acquiring SSH key 
 - [ ] becoming acclimated to [Dev Ops Contingency Plan](https://docs.google.com/document/d/1Zv9ctPWvi_UfXoBDJ0h1RrPwv771kP_Ri8Q1v-bVGyg/edit?usp=sharing)

**Comment by cthulhuplus** [comment]
Tif & Richard have both created SSH keys in AWS. Waiting for an update from Ty.

**Comment by cthulhuplus** [comment]
Ty has now confirmed that he can create an SSH Key in AWS.
