### ISSUE TITLE
Create a beta testing plan 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2557]
Per product, we can go ahead and start planning beta testing as user research. 
It will be necessary to represent any accounts as test accounts and test data  - we will not be able to migrate data over from the test to the official account that they'll have to get for EUA. 
Recruiting - New users, and some who

The following issues need to be complete before folks can be in the system and test accurately. 
2446
2306
2509
2432
2324
2459
2431
2528
2521

### This task is done when...
 - [x] We know when we will start testing (what features have to be ready)
 - [x] A recruiting matrix is created (who do we want to talk to) 
 - [x] The issues above are complete and closed
 - [x] A protocol is written 
 - [x] Issues are created for recruiting, conducting and analysis of beta tests
 
*Add a LABEL (design, dev, compliance, BUG, etc) before submitting.

*If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for PRODUCT to prioritize.

**Comment by CSwartzHMA** [comment]
@beparticular What communications and training materials will you want to have ready for this round of testing? I can build those in as priorities, based on timelines once established.

**Comment by beparticular** [comment]
@CSwartzHMA is writing a recruiting email
