### ISSUE TITLE
Create user status screens

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2568]
When a user is waiting on approval/denied access/access revoked, the users should see a different message on the dashboard. If the user was approved, the first time they login afterwards, then they will see the approved screen.

Pending Approval
![Screen Shot 2020-10-13 at 12.10.14 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/71684c55-cb86-4916-a82b-04d8c9b4f349)

Approval Denied
![Approval Denied](https://user-images.githubusercontent.com/2279260/99263951-d9d0bc00-27ed-11eb-9abe-d591980a0cd9.png)

Approval Revoked
![Screen Shot 2020-10-13 at 12.18.40 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/847d4bf8-ee95-4ff7-b111-9fd14ae0bddd)

Approved
![Screen Shot 2020-10-13 at 12.18.27 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/b104d9b3-21cb-4ee3-bd65-82d7cc660896)

### This task is done when...
 - [ ] a Pending Approval screen displays when the user is pending
 - [ ] a Approval Denied screen displays when the user is denied
 - [ ] a Approval Revoked screen displays when the user has their access revoked
 - [ ] an Approved screen displays when the user logs in the first time after they are approved

**Comment by tbolt** [comment]
This was completed as part of the okta integration
