### ISSUE TITLE
Create notification side panel

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2580]
Create a notifications side panel to display notification of request statuses

![Screen Shot 2020-10-13 at 1.08.25 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/6387666e-e9d6-4f76-b9fb-3b920389c38c)

![Screen Shot 2020-10-13 at 1.08.13 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/b07d96eb-025b-4c39-9f74-a4a2b000d0ba)

![Screen Shot 2020-10-13 at 1.08.33 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/05976d9a-98e4-4f75-bb89-7181a1c9dfd8)

![Screen Shot 2020-10-13 at 1.08.41 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/d79747fb-20a7-4a73-9c31-1eba1d6580ce)

### This task is done when...
 - [ ] the Pending Notification is visible
 - [ ] the Approved Notification is visible
 - [ ] the Denied Notification is visible
 - [ ] the Revoked Notification is visible

**Comment by beparticular** [comment]
This may need another pass through design when we are able to add notifications.

**Comment by jeromeleecms** [comment]
Side panel is being developed as part of Validation Considerations.
