### ISSUE TITLE
Add ability for a user to select one of their approved/requested state affiliations

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2581]
After the user has entered their MFA code, if they have previously requested or received access to multiple states, they will see a state affiliations page to select which state to view. If the user only has access to one state and doesn't have any pending requests for other states, then they will skip this page.

![Screen Shot 2020-10-13 at 1.18.23 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/3c9f88e1-e1ff-443d-b83d-c35044f700e1)
**Note - not needed to put the status in this page**

From the dashboard, the user can chose to switch states in the dropdown menu. This will take them back to the state affiliation selection page.

![Screen Shot 2020-10-13 at 1.18.34 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/d86596e4-1177-4f77-afb0-dd2d74e62920)

### This task is done when...
 - [ ] the State Affiliation selection form is created
 - [ ] the dropdown menu has an option to switch states
 - [ ] clicking the switch states button takes the user back to the State Affiliation selection form

**Comment by beparticular** [comment]
Per convo with @tbolt this ticket is a good place to also decide what is shown to the user on their first visit when they request access to two states. Is it this screen that would show right after they choose, before they are approved?

**Comment by beparticular** [comment]
@tbolt for release - just to clarify from convos today per Nick, when a user gets logged out, we'll want them to choose their state when they log back in, rather than drop them into the default state. 

Then the cookies thing can happen after release.

**Comment by beparticular** [comment]
@tbolt @knollfear per stand up conversation today, we'll go with path of least resistance and go with asking folks which state they want to work in each time they log in. We'll leave it open later for improvements if it becomes a pain point.
