### ISSUE TITLE
State Admin dashboard

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2583]
Create a state admin dashboard where the admins can see requests for access for their state and the status of their current and previous state users. Allow admin to view/approve/deny/revoke user access for their state.

![Screen Shot 2020-10-13 at 2.43.10 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/074c3cdf-6f46-43f8-bac9-9f15b7247169)

![Screen Shot 2020-10-13 at 2.43.57 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/67c20458-fcac-4b4c-9d0f-8f233c045990)

![Screen Shot 2020-10-13 at 2.45.04 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/c55a1ad1-cbc8-4ed3-8a31-3644e82e9d74)

![Screen Shot 2020-10-13 at 2.45.11 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/1a6cf983-04cc-4e4f-88df-27e6636f595d)

![Screen Shot 2020-10-13 at 2.45.25 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/b787bdd8-3c00-4f7e-9f7b-7069d956d1b6)

### This task is done when...
 - [ ] the State Admin dashboard is created
 - [ ] the admin can select a user to view and manage
 - [ ] the admin can revoke a user's access to their state
 - [ ] the admin can approve a user's access request
 - [ ] the admin can reject a user's access request
 
*Add a LABEL (design, dev, compliance, BUG, etc) before submitting.

*If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for PRODUCT to prioritize.

**Comment by tbolt** [comment]
Note: We're changing these screens to have tabs: Requests, Active, Inactive. Each tab will contain a table with the data/actions
