### ISSUE TITLE
State Admins will need to understand how to manage user accounts (new, active, inactive, closed)

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2599]
State admins will need instructions on their tasks.

### This task is done when...
 - [x] Admin instructions are drafted (to include alerting, managing and monitoring responsibilities in the system).
 - [x] Team has reviewed and is in agreement with instructions.
 - [x] Instructions have been made available (slack pinned post).

**Comment by CSwartzHMA** [comment]
Draft document can be found [here](https://docs.google.com/document/d/1262fUK4RqV1Klq7fhAuqI1GX1RgvQBRMsHsYixYpny8/edit?usp=sharing).

**Comment by CSwartzHMA** [comment]
@beparticular @akuas Can you take a look at the comment in this doc about the titling of this page and let me know your thoughts?

**Comment by beparticular** [comment]
@CSwartzHMA I updated the Figma file to match staging which just says "NV state admin" and doesn't say portal or panel

**Comment by akuas** [comment]
It looks good to me and Jenn resolved the discrepancy on figma.
