### ISSUE TITLE
Add federal program logos to the eAPD footer

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2627]
The application and all external communications should reflect consistent program logos. 

### This task is done when...
 - [x] Team agrees on correct logos to include according to the CMS branding guidelines. 
 - [ ] CMS logo has been added to footer area on application, along with other changes defined by above

**Comment by beparticular** [comment]
We should probably match what MACPro is doing. Checking in with them to see what we should do.

**Comment by beparticular** [comment]
When this is done, make sure all the branding templates are updated and added to all docs

**Comment by beparticular** [comment]
Seems like what need to do is 

DHHS logo > CMS logo > MACPro logo > eAPD logo in that order according to branding guidelines. 

Do we need to have the Medicaid.gov logo in our footer? 

@NAretakis can you weigh in cc @jeromeleecms

**Comment by NAretakis** [comment]
No, we don't need Medicaid.gov logo in our footer. Branding guidelines above seem right, but I confirmed we just need to be in the same family. @beparticular

**Comment by beparticular** [comment]
@NAretakis thank you! 
cc @jeromeleecms for final approval

The footer logos should be in this order. 
![Screen Shot 2020-12-02 at 12.11.55 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/9842c664-6c30-430f-a28e-a0d27ff55c82)

In the screenshot I have the logos bottom aligned.

The logos need to have 50px of space between them. 

Our logo needs to be resized to be about the same size as the MACPro logo. 

The CMS logo needs to be slightly larger than the MACPro and eAPD logos. In the screenshot CMS = 150 wide, MACPro and eAPD = 100. I think that should match to the size of the DHHS logo we're already using and match branding guidelines. If that looks weird let me know and we'll try something else. 

CMS Logo is the only one that doesn't exist in our system yet - 
![CMSlogrebrnd2coltagline.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/cee5167b-4349-4b40-8871-5b37e3954d29)

**Comment by jeromeleecms** [comment]
Is there padding on the MACPro and eAPD logos? In the image, it doesn't look like the text on these items line up against the bottom text of the CMS/HHS logos. 

Overall, if this aligns with the branding requirements, I'm fine with this.

**Comment by beparticular** [comment]
@jeromeleecms Let's get it into code and then make sure everything lines up as needed. i think it'll be slightly different than the screenshot out of Figma. 

@thetif moving forward to a dev issues for ya
