### ISSUE TITLE
Track Official CircleCI Account

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#2630]
In order to address Docker limiting anonymous pull CMS is looking into acquiring an Enterprise license for CircleCI. Once that is acquired we will need to add Docker authorization to our CircleCI pipeline. 

### This task is done when...
 - [ ] Enterprise CircleCI is acquired

**Comment by cthulhuplus** [comment]
https://jira.cms.gov/browse/WHSD-31699

**Comment by cthulhuplus** [comment]
In https://jira.cms.gov/browse/WHSD-31699 they mention a new ticket has been opened (https://jira.cms.gov/browse/TOOLS-3616), but I can not view that ticket.

**Comment by jeromeleecms** [comment]
Going to tag @NAretakis into this ticket just to help him keep track of the request to follow up on the new ticket that Bill mentioned.

**Comment by jeromeleecms** [comment]
It looks like GitHub Actions is looking more promising. Closing for now.
