### ISSUE TITLE
Refactor login code

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2632]
Refactor the login code to use a login specific router so that everything isn't maintained in the Login file.

Feature -  
The Login.js file is getting to be very complicated with all of the new auth logic. The routing should be taken out and put in a separate file to make it cleaner.

### This task is done when…
This could include:
 - [ ] update login code to make the login routes more understandable
 - [ ] update the wiki documentation to match the new authentication flow

**Comment by tbolt** [comment]
Additional item TODO: Refactor status pages (Approved, Revoked, Denied, etc..) into its own component.
