### ISSUE TITLE
[Dev] Create ability for user to select multiple states to request access to

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2638]
Currently users can only select one state at a time to request access for.

Feature -  
Change the dropdown in the state request to be an autocomplete field that allows users to select multiple options.

### This task is done when…
This could include:
 - [ ] change dropdown to an autocomplete

**Comment by tbolt** [comment]
@thetif Based on @beparticular 's feedback, we want to keep this to "Select your State Affiliation" instead of "Select Affiliation." Let's catch up when you get back because I had started to move away from calling things "State Affiliation."
