### ISSUE TITLE
Implement Official CircleCI Account

### ISSUE THREAD

**Issue by nicholeweems** [CMSgov/eAPD#2639]
In order to address Docker limiting anonymous pull CMS is looking into acquiring an Enterprise license for CircleCI. Once that is acquired we will need to add Docker authorization to our CircleCI pipeline. 

### This task is done when...
 - [ ] eAPD credentials for authorized pulls have been acquired
 - [ ] Credentials have been added to our CircleCI pipeline
 - [ ] Functionality of the pipeline is confirmed

**Comment by jeromeleecms** [comment]
Moving to GitHub Actions
