### ISSUE TITLE
[Dev] Refactor backend auth flow

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2640]
Streamline how the user object is created in the backend.

Feature -  
Identify and implement streamlining of creating the user object (profile, state, roles, activities)

### This task is done when…
This could include:
 - [ ] streamline the creation of the user object

**Comment by radavis** [comment]
Note to self, add details to this story.

**Comment by radavis** [comment]
* Move `/apds` api routes to `/states/:stateId/apds` - we need to restrict user access to APDs dependent upon the user's affiliation with a state. `auth_affiliations(user_id, state_id, role_id, status)`.
* Update frontend to use `/states/:stateId/apds` routes.
* Augment the `can` middleware to check against a user's permissions (aka - activities) for that `stateId`, when the `stateId` is present in the request params.
* Remove unnecessary fields from the `req.user` object.

**Comment by thetif** [comment]
OBE
