### ISSUE TITLE
Investigate Sporadically Failing OWASP Zap Scan

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#2643]
Both Richard and I had failing OWASP Zap Scans that then succeed without intervention. Try to identify the underlying reason for these failures and remediate if possible.

### This task is done when...
 - [ ] Investigation is complete
 - [ ] Remediation is complete (if possible)

Failed OWASP Zap Scans:
https://app.circleci.com/pipelines/github/CMSgov/eAPD/2669/workflows/b9b44a5f-34e4-4d7f-9698-f561b28b68f7
https://app.circleci.com/pipelines/github/CMSgov/eAPD/2669/workflows/3dd20bb8-7b04-4e9d-852b-0c745cef9c23
https://app.circleci.com/pipelines/github/CMSgov/eAPD/2653/workflows/939ebb41-d004-47da-b80a-75592aac24e1

**Comment by radavis** [comment]
To get the full benefit of this security scan, we should provide credentials via the Authorization header. 

https://www.zaproxy.org/blog/2017-06-19-scanning-apis-with-zap/

https://github.com/zaproxy/zaproxy/issues/4332

**Comment by radavis** [comment]
Running owasp zap without a config seems to skip the following two scans:

* [100000] [Alert_on_HTTP_Response_Code_Errors.js](https://github.com/zaproxy/zaproxy/blob/master/docker/scripts/scripts/httpsender/Alert_on_HTTP_Response_Code_Errors.js)
* [100001] [Alert_on_Unexpected_Content_Types.js](https://github.com/zaproxy/zaproxy/blob/develop/docker/scripts/scripts/httpsender/Alert_on_Unexpected_Content_Types.js)
