### ISSUE TITLE
[Dev] Combine Authenticators in MFA selection

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2648]
Because Google and Okta Authenticators look the same and can actually be used by any authenticator, combine the two options into just one.

Feature -  
Combine Google Authenticator and Okta Authenticator options into just Authenticator. Figure out what the provider comes back as and adjust as needed.

### This task is done when…
This could include:
 - [ ] combine authenticator options into one fix the authentication error causing blank screens from multiple tabs or browsers.

Notes for Testing: Using various authentication methods confirm that the user is prompted or the system automatically handles the error.  Please note Amanda duplicated with #2928 but includes the steps to reproduce the error, I will update and delete one of them once I merge them.

**Comment by jeromeleecms** [comment]
@thetif Just to clarify - is the plan for this issue to just have the label as "Authenticator?" We are updating the system access guidance doc now.. 

cc: @CSwartzHMA

**Comment by eStar386** [comment]
Failed Functional Testing 
Description: A new user created with OKTA cannot access the eAPD application. The push notifications and manual codes only allow access to https://test.idp.idm.cms.gov/ and not to the actual eAPD.

Steps to Reproduce: 
1. Create a new user on https://test.idp.idm.cms.gov/ or with an existing user change to OKTA. 
2.  Login with the credentials for the user to the eAPD;
3. Using the code generated, Verify your Identity.
Actual Result: The user is rejected and isn't allow to login. They are trapped on the verify your Identity screen. 

Expected Result: The new google user with Google  setup in test.idp.idm.cms.gov can scan the QR and gains access to the eAPD following the above steps.
