### ISSUE TITLE
[Dev] Research best way to handle current state

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2667]
Users may have access to multiple states, their role and activities are determined by the state.

Research -  
Determine the best way to store/pass the user's currently selected state in the backend. Research different options (Okta, database, url param) and pick the best one.

### This task is done when…
This could include:
 - [ ] determine the best way to manage user's currently selected state

**Comment by radavis** [comment]
Use the `user.state` property to store a user's selected state. Allow the user to update this via `PATCH /me?stateId=id`.
