### ISSUE TITLE
Migrate all icons from font awesome to material-icons

### ISSUE THREAD

**Issue by tbolt** [CMSgov/eAPD#2670]
Per the design specifications we should migrate all existing icons to use material icons version. 

Once complete we should consider removing font awesome

### This task is done when...
 - [ ] Font awesome icons replaced with material-ui icons
 - [ ] Font awesome icons/npm package removed from app
 
*Add a LABEL (design, dev, compliance, BUG, etc) before submitting.

*If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for PRODUCT to prioritize.

**Comment by jeromeleecms** [comment]
For future discussion: USDWS uses a subset of Font Awesome (https://designsystem.digital.gov/components/icons/), before migrating to Material Design icons, we should evaluate which direction we should go and what to do in the case where icons are not available.

@beparticular for Design sync?

**Comment by jeromeleecms** [comment]
After design sync, we will try and be consistent with USDWS and stay with font awesome. We will try a similar icon in font awesome or remove icons entirely, depending Ty's sensibility.
