### ISSUE TITLE
[Dev] Establish new front-end file structure

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2689]
It is currently hard to figure out where the code you need to change is. Design a better file structure that is more inline with the route path. Create a plan for implementing the file structure change.

### This task is done when…
 - [ ] a new file structure has been created
 - [ ] there is a plan in place for updating the code to the new file structure
 - [ ] there is an epic with tickets created to change to the new file structure

**Comment by thetif** [comment]
https://create-react-app.dev/docs/importing-a-component/#absolute-imports

**Comment by tbolt** [comment]
Thoughts
* Love having redux spelled out and its own section
* ArrowLeftIcon and ArrowRightIcon should prob be moved under Icons but that's minor and not really scope of this ticket
* I don't love having routes/Routes. Seems redundant and it would be nice to have it be flatter if possible. I think we could do another ticket where we spend more time with the routes. The "PrivateRoute" stuff might not make as much sense anymore.
* All the APD changes are great, I never understood the state-profile but that's likely just vestigial

Nice work. looking forward to these updates

**Comment by mirano-darren** [comment]
Looks good to me! Good stuff
