### ISSUE TITLE
Investigate Better CodeCov Reporting

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#2693]
It has been awhile since we've received updates/notifications from CodeCov. I need to investigate why that is and make sure that it is still functioning as it should be. We are still linked and it is still showing that we have 90%+ coverage.

### This task is done when...
 - [x] Create/Recreate CodeCov reporting mechanism

**Comment by cthulhuplus** [comment]
CodeCov is reporting to PRs

**Comment by eStar386** [comment]
There is an issue with the functionality for refactor login #2891 because it predates the fix. @cthulhuplus does it need to be rebuilt to improve the code coverage numbers? Also for refactors, like the one mentioned above is code coverage required?

**Comment by cthulhuplus** [comment]
I believe the reason the code coverage report is not showing in #2891 is that #2891 predates the initial CodeCov fix. I believe that we don't have hard requirements for the code coverage report and that it is informational.

**Comment by eStar386** [comment]
QA Passed -The code coverage reports is fixed and reports shows on the tickets.

**Comment by beparticular** [comment]
@cthulhuplus what if anything should I be looking for to review this?

**Comment by cthulhuplus** [comment]
@beparticular I do not think that there is a design component/feature for this piece of work, but as always I welcome whatever thoughts or ideas you may have.

**Comment by jeromeleecms** [comment]
No action for Jenn or I to take on this.
