### ISSUE TITLE
Create logistics webinar for Go-Live

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2697]
A second webinar will be created to provide users with information needed to support go-live access and define expectations.

### This task is done when...
 - [x] Agenda/outline has been created 
 - [x] Team agrees on agenda/outline
 - [x] PPT has been developed and approved (Jerome, Nick, Anyone else?)
 - [x] Webinar is scheduled
 - [x] Invites have been sent
 - [x] Webinar has been completed

**Comment by CSwartzHMA** [comment]
Draft agenda:

- Dates and how users will know when the system is live
- How to access the system (URL, EUA, Okta, Chrome, etc.)
- Who can access the system
- What you can do in the system
- What you can't do in the system
- Where to go for help

**Comment by CSwartzHMA** [comment]
@jeromeleecms @NAretakis Please review this draft webinar invite language. I believe the most efficient way to get this out is to add our HITECH contacts and State Officers to the meeting I have already created, along with this message. There are also a few MeT team members who would like to attend the webinar. Is this an appropriate approach?
I am also coordinating with Benita to see if we can use the MeT CoP webinar team to support the call.

In anticipation of the upcoming release of the eAPD for use by states in creating HITECH APD's, the eAPD is hosting a webinar to review logistics relating to accessing the system and provide some basic instructions for users. We encourage all state HITECH team members who anticipate using the eAPD system to attend. The eAPD will also be available to answer questions at the end of the presentation.
Topics covered during this webinar will include: 

- How to access the system 
- Who can access the system
- Basic functionality
- Where to go for help

The webinar recording and presentation will be made available, so if you cannot attend, you will still have an opportunity to review the information.

**Comment by jeromeleecms** [comment]
Overall this looks fine to me. @NAretakis any thoughts?

**Comment by CSwartzHMA** [comment]
Draft PPT is [here](https://docs.google.com/presentation/d/1t578oX9SVRAHQLojjk6W8BjO5j1VdLujQoL7W6kevdg/edit?usp=sharing).

**Comment by CSwartzHMA** [comment]
Webinar completed 7/15/21.
