### ISSUE TITLE
Splunk Dashboards

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#2699]
Once we have been onboarded into Splunk, we will need to develop Dashboards for error/health tracking and reporting.

### This task is done when...
 - [ ] Needed Dashboards have been identified (gather requirements from all parties; devs, design, leadership, etc...)
 - [ ] Needed Dashbaords have been developed (might need to be converted to an Epic

**Comment by cthulhuplus** [comment]
@jeromeleecms is this something that needs to be pursued? Do you have a desire to use Splunk? We need to push our logs to Splunk since "the Enterprise" uses it, but I look at logs in AWS, so if there is no desire to use Splunk it doesn't make sense to me to build out Dashboards.

**Comment by jeromeleecms** [comment]
If we are are already submitting the data to Splunk and we don't need the dashboards (and you get the data from AWS consoles), then I don't see the need to build dashboards at this time -- unless we are asked from CMS Enterprise to do so.
