### ISSUE TITLE
Selecting "Cancel" during the state affiliation selection puts the user into a blank screen

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#2706]
While testing a PR, I noticed that cancelling during the state affiliation selection screen drops the user back to a blank screen. Refreshing the page pushes the user back to the blank screen (likely because they are authenticated, but there is nothing to display - i.e. not state dashboard because they are unaffiliated). 

The "painful" work around is allow the Okta token to expire after 15 minutes (which then allows the user to log back in and try to select their state affiliation again) OR empty out their cookies.

Tagging design here first in case they have a different path they want the user to follow.

### This task is done when...
 - [ ] User should be navigated back to the login screen when selecting cancel during the state affiliation selection
 - [ ] User should be logged out to allow user to log them back in

**Comment by radavis** [comment]
Holding off on this until #2754 is merged.

**Comment by beparticular** [comment]
@thetif @eStar386 is this an accurate recap?

Discussion in parking lot: 
For accessibility, the cancel button can't log someone out. 

To address this and new direction for this issue: 
Remove the cancel button on state affiliation (address the need for a cancel button later when we do multi-state select)
Change the cancel button on the mfa page to Return to Log In

Needs new ticket: Once folks get to state access, they are logged in. Provide a log out.

**Comment by eStar386** [comment]
Yes, exemptions to the PR documented above.
