### ISSUE TITLE
EUA Job Code Created

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#2713]
As part of the authentication process, we need to have a EUA job code created for the eAPD project to allow access to the app through Okta. The request for the job code was submitted and rejected, but @NAretakis was able to follow-up and resubmit again. 

### This task is done when...
 - [x] Job Code Created
 - [x] Job Code can be requested and access granted to user

**Comment by NAretakis** [comment]
Second attempt was not rejected. Status is below which means I am waiting to connect with the EUA team to map this to our App. Will continue to push.

![image.png](https://images.zenhubusercontent.com/5c536083d11206601037eb29/aa560b10-8bb8-424e-92e7-35fb0c7bf0fd)

**Comment by NAretakis** [comment]
It's working!

EAPD_P_USER now works as a job code to grant access to the app!
