### ISSUE TITLE
Program summary and executive summary are confusing users

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2722]
From beta testing - 
Findings: We’ve seen some light confusion around Program Summary vs Executive Summary. Users eventually correct, but it would save a lot of work for folks and help them understand sooner if we make some minor changes. 

Consider that with Executive Summary below the “fold” coupled with the help text “This information is similar to the content from the IAPD executive summary template section.” we may be causing an issue here that leads folks to believe this is their new Executive Summary. 

Recommendations: Before release: remove the confusing help text 
After release: continue to monitor feedback and look for others ways to improve if needed

### This task is done when...
 - [x] the help text is written
 - [x] the help text is approved
 - [x] the help text is changed in a dev ticket

**Comment by beparticular** [comment]
@jeromeleecms this is ready to review per our conversation yesterday. 

![Screen Shot 2020-12-22 at 5.13.21 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/454d71c7-a7d3-46d1-ac71-8ae1441cbd31)

Changes made - 
1) Navigation changed to APD overview. 
2) Page header changed to APD overview.
3) The paragraph of help text at the top of the page is removed
4) The redundant "Program Overview" heading was removed
5) Program Summary heading was changed to "Introduction"
6) The paragraph of help text for the Introduction field was changed to - 
"Provide a brief introduction to the state program. Include context for this funding request by providing information such as current size of the program and how the program is positioned within the state. You might also include a high-level look at the history and context of the program and the state’s future vision for it."

**Comment by jeromeleecms** [comment]
This looks fine.

**Comment by beparticular** [comment]
@thetif ready for dev
