### ISSUE TITLE
Results of Previous Activities Actual Expenditure Table has confusing headings

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2723]
Findings:  Results of Previous Activities Actual Expenditure Table has confusing headings

Recommendations: Before release: Make the table headings match up to what we’re showing there. 

Info: 1st column is total computable | 2nd column is total with FFP

### This task is done when...
 - [x] it is determined what columns are related to which headings
 - [x] a mock up is created
 - [x] a mock up is approved

**Comment by beparticular** [comment]
@jeromeleecms here is a mock up with language changed and the second header removed as we discussed. Here for final approval. 

![Screen Shot 2020-12-22 at 4.50.31 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/15e9ac6b-6289-4b44-bf2e-32afd63925e7)

This is only showing one table, but this would apply to all tables on the page according to their FFP selection,  except for the Grand Totals table at the end.

**Comment by jeromeleecms** [comment]
Headers - what do you think "Approved Total Computable Medicaid," "Approved 90% FFP," "Actual FFP Expenditures" .... the words Approved and Actual are modifying the phrases "Total Computable Medicaid," "90% FFP", and "FFP Expenditures." Moving the word approved to the front is more consistent with our use of language. The structure for the headers looks much clearer. 👍 

Do we need to review the help text at all? "Provide the most recently approved Total Computable Medicaid funding and the actual FFP expenditures. The application will calculate the approved FFP based on the listed match rate." This would be consistent with our instruction style language in the app for "Provide [this specific items for the fields."

**Comment by beparticular** [comment]
Great suggestions - how does this look/work? @jeromeleecms 

![Screen Shot 2020-12-23 at 9 48 14 AM](https://user-images.githubusercontent.com/5957354/103008998-fd310a00-4503-11eb-89c1-dd4a70eae810.png)

**Comment by jeromeleecms** [comment]
Grammatically, the table headers don't cause my brain to do a double take so 👍 and help text looks good. On to dev unless there is something else I'm missing!

**Comment by beparticular** [comment]
Yay! 

@thetif this is ready for dev! 
Changes - 
Removed the first header
Changed the text as shown in the last screenshot on this issue.

This is only showing one table, but this would apply to all tables on the page according to their FFP selection, except for the Grand Totals table at the end.

**Comment by beparticular** [comment]
For my own brain and historical purposes, here is a before screenshot. 
![Screen Shot 2021-01-14 at 5 25 29 PM](https://user-images.githubusercontent.com/5957354/104656582-8f54aa00-568d-11eb-8f0f-59d61bc060ab.png)
