### ISSUE TITLE
Outcomes and metrics interactions are inconsistent between activities. 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2725]
The first entry in Outcomes and Metrics has a different interaction than the first state staff or private contractor entries. This causes a blank Outcome and Metric to show on the export view, and folks are going back this area to delete the blank Outcome and Metric that shows when they enter this section or they don't notice the first entry and add a second metric, leaving the first blank. This could be confusing for reviewers as well. 

Further investigation: check to make sure all “add” buttons have the same interaction as appropriate.

### This task is done when...
 - [ ] Design investigates that the other interactions are consistent
 - [ ] A mock up is made and approved if needed (design/dev can decide)
 - [ ] This becomes a dev ticket

**Comment by beparticular** [comment]
It does not put a default Outcome/Metric in Activity 1, but does put a default Outcome/Metric in Activity 2.

**Comment by radavis** [comment]
@beparticular I am unclear as to what the desired change should be, here. Could I get some acceptance criteria, please?

**Comment by radavis** [comment]
Pinging @thetif, too, since she might have some useful context that I do not have.

**Comment by thetif** [comment]
@beparticular should there be a default in activity 1 too? Or no default in any activities?

@radavis if it's missing from the first one then it needs to be added to that apd seed code on the backend

**Comment by thetif** [comment]
Activity 1 has the correct functionality it should show and error message if nothing has been added.
![good](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/0e0c00b2-c13c-4db1-b57e-1ee349429de4)

Currently, when you add a new activity it creates a a default first outcome and metric and a default first milestone. It should be behaving like the Activity 1
![bad](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/ed3ae3b1-bc17-4c49-9c05-d1fef6200bcc)

**Comment by radavis** [comment]
```
given
  - auth'ed user viewing apd activities
when
  - a new activity is added
then
  - warning messages should be present: "Outcomes, Milestones have not been added..."
  - no entries for Outcomes
  - no entries for Milestones
```
