### ISSUE TITLE
Be clear in the export view about what was chosen in Assurances and Compliance

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2728]
Findings: Assurances and Compliance:
If Assurances and compliance are unchecked in the builder view, but no text was added as a reason - we’d want something to show in the export view that notates that a choice was not made in the builder view. 

See Figma for comparison of Builder vs Export View
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=3558%3A26790

Current behavior:
Unchecked - unchecked in export
Checked yes - check mark in export
Checked no - X in the export
If no reason given, no text is shown
If reason given, shown: “Explanation: reason” in export

Further investigation: Is this fully represented in the validation ticket?

### This task is done when...
 - [x] Determine if we want to add this to the before release epic  
 - [x] It is determined how we want to show selections from assurances and compliance
 - [x] A mock up is created
 - [ ] A mock up is approved

**Comment by beparticular** [comment]
@akuas per 1:1 conversation

- [ ] Icons need to match between X and checks. 

Problem to solve - 
When a reviewer comes to this page in the export, and no circles have been Xed or checked, what do these circle icons mean to them? Is it clear it's an unchecked box, or does it appear to be a stylized list? How does the reviewer know what assurances and compliances the state is trying to get across. 

Solution - 
Show in the export view that a choice was not made in the builder view in a way that is clear to reviewers. 
Perhaps try and bring the export view closer to the builder view. 
TBD how

**Comment by akuas** [comment]
Current updated [activities page](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=3650%3A0). 

Updates Made:
- Removed Activity name from each activity sub-header
- Removed divider in-between page section
- Revised Standards and Conditions copy (this section is subject to change when we redesign the Standards and Conditions in the builder view)
- Added a side nav indicating which activity the user is looking at
- Made the activity name or the start of an activity more scannable
- Added hyperlinks to jump to different parts of the activity section
- Reorganized outcomes and metrics to allow for branching

**Comment by akuas** [comment]
[Assurances and Compliance Mockup](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=3612%3A0)

**Comment by beparticular** [comment]
@thetif this is ready for dev. To try a user story for ya
As a reviewer of an APD, I want to see clear answers to the attestations of assurances and compliances on the document I review, to understand if a state is complying with needed regulations, OR I want to see if they did not select an answer a to a question. 

Figma File
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=3612%3A0

There are three possible answers to each question: Yes, No (with a reason), and No response was provided. 

Notes for @tbolt when you get to this - some of the regulation links currently look broken or like they are not links in staging. This redesign should take care of those broken links. 

Also it is ok to play around with the design of the field for the narrative response when "no" is selected.
