### ISSUE TITLE
Change header on Unable to save changes error

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2729]
Finding: Not saved error message has a header that does not convey that information is not saved

BEFORE (illustrating which error): 
![Screen Shot 2020-12-16 at 2.45.05 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/dd98f72d-1974-4f4f-a09b-173d49ccdcc6)

### This task is done when...
 - [x] Before release: Change the header to: "Unable to Save Changes"
 - [x] Find out from dev what actually happens when this error occurs and if it's possible that changes could ever be saved after waiting a few minutes. 
 - [x] The error text is written
 - [x] The error text is agreed upon

**Comment by beparticular** [comment]
People could get this error when they lose their internet. 

"Unable to Save Changes. 
Your changes aren't being saved. You can try again in a few minutes, but if you continue to see this message you will need to refresh your browser to continue. If you refresh your browser, changes made after it stopped saving will be lost."


Other issue - they can continue to make changes while this error is up. Consider changing this to a modal where they can't interact with the system until they acknowledge the message. Work with dev on 508 concerns with modals or errors.

**Comment by beparticular** [comment]
@jeromeleecms @CSwartzHMA what do you think of this as the final language for this error: 


Header: Unable to save changes! 

Body: Your changes aren't being saved. You can try to save your changes again in a few minutes by clicking on the save button. 

If that doesn't clear this message, back up the changes you made on this page and refresh your browser. If you refresh your browser without saving or manually backing up your changes, changes made after this message appeared will be lost.

**Comment by jeromeleecms** [comment]
@beparticular - small suggestion + a question...

Body: Your changes aren't being saved. _**Try saving your changes**_ again in a few minutes by clicking on the save button.

For the second part of the content: 

_**If that doesn't clear this message, back up the changes you made on this page and refresh your browser.**_ If you refresh your browser without saving or manually backing up your changes, changes made after this message appeared will be lost.

When using to app, the modal should appear as soon as this issue appears and they won't be able to save/back up anything. What/how would the user back up changes?

**Comment by beparticular** [comment]
@jeromeleecms agree on body text, will make that change. 

Regarding back up - they would be able to copy/paste the changes they made on that page into a text file for instance.

**Comment by beparticular** [comment]
Final wording decision @thetif ready for dev  

Header: Unable to save changes!

Body: Your changes aren't being saved. Try saving your changes again in a few minutes by clicking on the save button.

If that doesn't clear this message, back up the changes you made on this page (for instance, if you just wrote a long narrative, save it into a text file or word doc) and refresh your browser. If you refresh your browser without saving backing up your changes, changes made after this message appeared will be lost.
