### ISSUE TITLE
Help text around FTE number or percent is confusing or unclear 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2730]
Findings: In Key Personnel  1 = FT or 100% is confusing, folks aren't sure if they can enter a number, a percent, a decimal, or all of the above.
Recommendation: Before release, Potentially change to 1 = FT = 100% as this could change calculations that would delay approval
Consider being explicit that folks can enter .5 or something here. 

.5 = .5 FTE = 50%

### This task is done when...
 - [x] It is determined the best way to let users know what we're looking for here, or what can be entered into the field
 - [x] A quick mock up is made
 - [ ] Changes are agreed upon

**Comment by beparticular** [comment]
@jeromeleecms ready for review

Questions - 
1) Add e.g. or no? 
2) Instead of on the same line as the field label, should we turn this into help text like the formatting hint under the date field for instance? 

Changed  (1 = 1 FTE or 100% time) to  (e.g. .5 = .5 FTE or 50% time) 

![Screen Shot 2020-12-22 at 4.44.52 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/245a2370-3026-4ef1-bbac-0a0894ac8d97)

**Comment by jeromeleecms** [comment]
1) Let's add the leading 0 (e.g. 0.5 = 0.5 FTE or 50% Time) because that's how the app will format the decimals. 
2) I'm fine with converting it to help text (with the blue box, right?). The pattern we've been following has been text for directions, the blue help box for specific examples. If we do convert it, then we shouldn't need "e.g." then.

**Comment by beparticular** [comment]
I think the blue box is for examples of content we're looking for vs examples of formatting we'd like in number fields. For instance: 

![Screen Shot 2020-12-23 at 9 43 54 AM](https://user-images.githubusercontent.com/5957354/103008625-6e23f200-4503-11eb-92eb-8d21c3262bd7.png)

With the date fields we also use "For example" so we could follow that pattern. Let me know and I'll update the mock up and pass to dev. 

@jeromeleecms

**Comment by jeromeleecms** [comment]
That works for me. For the end date, does it make sense to use an alternative date that's beyond the start date? Other than that, once you mock it up, good to go.

**Comment by beparticular** [comment]
We haven't seen any issues with that example, so I'd say it can live as is. 

@thetif 
This can move to dev - 

Changes needed: 
1) Remove 1 = 1 FTE or 100% time on both FTE Allocation field labels 

2) Add in "For example 0.5 = 0.5 FTE = 50% time" in the same pattern we use for the start/end date example as shown above
