### ISSUE TITLE
Consider different examples for metrics in help text

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2732]
Look at some of the APD examples and guidance from CMS to determine if the examples for the Outcomes and Metrics section could show the level of granularity we'd like to have in this section for future updating/data purpose. 

We really want folks to give one metric per field, but some are currently adding multiple bullet points in to the small field that is provided. 

Would we want different examples for MES types when we expand?

### This task is done when...
 - [ ] TBD
 - [ ] criteria 2

**Comment by jeromeleecms** [comment]
This is good to close, the outcomes and metrics GitHub repo is included in the help text for create APD and we can revise the help text in the MMIS IAPD (V1) work.
