### ISSUE TITLE
Determine helpful changes to Key Personnel help text and fields

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2733]
During beta testing, folks still struggled with who to add under Key Personnel. 

Considerations
1) The header (bold) help text says to identify staff who will be involved in all activities, but that's not really what we want here. (see Caryn comment in dovetail) 
We want
a) the medicaid director
b) the key point of contact who the state officer would regularly be in touch with
c) folks who if they left the project, the project would be in jeopardy

2) For each new KP, we're saying "Additional APD Point of Contact" but that's not really what we are looking for. Do we need to have a third type of person we add here, a KP who is not a point of contact. 
The key point of contact doesn't really need to have costs attributed to them. Could doing so differentiate and make clearer the information we're trying to capture? It would help us break up the wall of help text. 

In the future, the first two can be at the project level, and all other staff can be at the activity level - but we still need a good way to show folks who are on multiple activities. This is not the problem we are solving before release. 

### This task is done when...
 - [x] design the best way to do this
 - [x] then determine what we can do before release to improve this part of the UI
 - [x] make mock ups if needed
 - [x] approve changes that need to go out before release vs after

**Comment by beparticular** [comment]
Recommendations - 

![Screen Shot 2021-01-08 at 11.09.00 AM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/6393dc37-f229-4e63-b4e0-5342fb4ceeb5)
1) Remove the help text from under the Key Personnel heading as it’s not immediately relevant/correct at this time (referencing updates), vague (list relevant state contacts) and folks don’t need to be prompted in help text to review information to make sure it’s correct. 

![Screen Shot 2021-01-08 at 11.17.29 AM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/97554ecf-3659-495e-b8d4-eab42c0f1b40)
2) Remove the first line of text under KP and PM header as it may be misleading. 

3) Change and reduce the help text under KP and Program Management. 
- Rearranged the text under point 1 to focus first on what a KP is vs how many activities they will be involved in.
- On point 2 changed “individuals” to “staff” and used most direct language about where to add staff.
- One point 3 I referenced the budget in Activity 1 and changed the format of Activity 1: Program Administration to match the UI. 
- Reduced the example to only what should be added in KP and removed what shouldn’t be added here. 

4) Change "Additional APD Point of Contact" to "Additional Key Personnel"

5) Double checking that we have to use this language "Personnel listed in this section must be assigned to APD by name, role, time commitment, and cost, where applicable." as there aren't fields for all of these things listed. I remember that we had to use some language like this in lieu of required fields, but is there something else we can say here that is less confusing or helps folks understand what we're asking for or what is required? 

Text shown in the screenshot: 
	1.	Key personnel are individuals who are directly involved with governance, coordination, stakeholder decision-making, oversight, and/or performance of the activities as they affect the state’s Medicaid program. They may also be individuals who are involved with all or most activities within this APD vs one single activity. 
	2.	Staff whose responsibilities apply only to specific Activities will be entered directly in each relevant Activity. 
	3.	Key personnel costs entered here are represented in the budget in Activity 1: Program Administration, at the 90/10 split.

Example: 
Program Managers and Directors who provide oversight to all projects would be included here.

**Comment by jeromeleecms** [comment]
@beparticular - comments/some suggested text changes

1) Remove help text: OK
2) Remove first line of text: OK
3) 
-Suggested text change in the second sentence of 1) -- "These individuals may also be involved with all or almost all of the activities within this APD." 
- 2) is OK, but unclear why we are capitalizing Activities / Activity since we don't do it in the previous sentence?
- 3) Suggest text change: "Key Personnel costs entered in this section will be included in the budget for Activity 1: Program Administration, at the 90/10 split."
- For the example, we could simplify this further as "Program Managers and Directors who provide oversight to all projects."
4) Changing to "Additional Key Personnel": OK
5) For this section, how about: "Provide the name, email, and role for personnel listed in this section. If applicable, provide the individual's total annual cost (including benefits) and their allocation to the overall project work in this APD in decimal form (e.g. 0.5 = 50% time). The application will automatically calculate the costs by FFY."
- Not sure how else to convey "in decimal form" (better way to write that)

**Comment by beparticular** [comment]
@jeromeleecms 

3) Fixed the capitalization consistency

Example - I think it’s fine as is, with the additional change of projects —> activities.

5) How about 
"Provide the name, email, and role for this key personnel. If applicable, provide the individual's total annual cost (including benefits) and their allocation to the overall project work.”
Ending there, as we will tell them about the decimal form if they select yes under “does this person have costs”.

**Comment by beparticular** [comment]
Example text:
Program Manager, Director, HIT Coordinator

5) Ok as Jenn wrote in the last comment. 

Next step - Jenn to write a summary and pass to dev.

**Comment by beparticular** [comment]
@thetif this is ready for a dev ticket - here is the summary of changes needed - 

1) Remove this help text from under the Key Personnel heading:
"List relevant state contacts. If this is updating a previously submitted APD, the information will be prepopulated. Review to ensure that it is correct."

![Screen Shot 2021-01-08 at 11.09.00 AM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/6393dc37-f229-4e63-b4e0-5342fb4ceeb5)


-------------------------------------------------

2) Remove this first line of text under KP and PM header as it may be misleading. 
"Identify key state staff who will be involved in all activities listed in this APD."

3) Change bullet points to this text: 

1. Key personnel are individuals who are directly involved with governance, coordination, stakeholder decision-making, oversight, and/or performance of the activities as they affect the state’s Medicaid program. They may also be individuals who are involved with all or most activities within this APD vs one single activity. 
2. Staff whose responsibilities apply only to specific activities will be entered directly in each relevant activity. 
3. Key personnel costs entered here are represented in the budget in Activity 1: Program Administration, at the 90/10 split.

Change example text to:
Program Manager, Director, HIT Coordinator

(The text above is the new correct text and updated from this screenshot.)
![Screen Shot 2021-01-08 at 11.17.29 AM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/97554ecf-3659-495e-b8d4-eab42c0f1b40)

-------------------------------------------------

4) After you choose "add key personnel" change the header "Additional APD Point of Contact" to "Additional Key Personnel"

5) After you choose "add key personnel" change the help text to: Provide the name, email, and role for this key personnel. If applicable, provide the individual's total annual cost (including benefits) and their allocation to the overall project work.
