### ISSUE TITLE
Plan and conduct research study with State Officers

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2734]
This sprint (before holidays): Write up an outline of a research plan to get feedback from state officers 
https://docs.google.com/document/d/1akL84HkhO5KUDQtvpMHAqaICpo4C3sizXGD4zYyS1D0/edit#

Next sprint: get feedback on the plan, and add issues for conducting and analyzing this study 

### This task is done when...
 - [x] A draft plan outline is written 
 - [x] A plan outline is shared with team/leadership 
 - [x] The draft plan is revised and reviewed 
 - [x] Communications are written for the regular Tuesday SO meeting on 1/12 
 - [x] A google form is created for participants and is reviewed/approved
 - [x] A guide/protocol is created for interview participants and is reviewed
 - [x] Interview participants are recruited (suggested by TLs) and scheduled for debriefs
 - [x] Email communication/instructions are written for participants who will have access to the google form only
 - [x] Email communication/instructions are written for participants who will have access to the google form AND participate in interviews
 - [x] New issue is created for analyzing
 - [x] All sessions are complete and debrief with team for takeaways

**Comment by CSwartzHMA** [comment]
Interview participant outreach has been sent to facilitate scheduling interviews.
