### ISSUE TITLE
Request GitHub_Editor Job Code in EUA starting 1/1/2021

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#2737]
CMS is migrating to SSO and the non-CMS team members will need to request the appropriate GitHub Editor job code in EUA. 

### This task is done when...
 - [x] @beparticular has requested the job code
- [x] @CSwartzHMA has requested the job code
- [x] @cthulhuplus has requested the job code 
- [x] @nicholeweems has requested the job code
- [x] @radavis has requested the job code
- [x] @rohitpaul has requested the job code
- [x] @tbolt has requested the job code
 - [x] @thetif has requested the job code

 
*Add a LABEL (design, dev, compliance, BUG, etc) before submitting.

*If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for PRODUCT to prioritize.

**Comment by CSwartzHMA** [comment]
Job code successfully added to my account.

**Comment by cthulhuplus** [comment]
I have requested and received the job code.

**Comment by beparticular** [comment]
Same, appears the job code has been approved for me.
