### ISSUE TITLE
Determine steps in process for hosting docs on S3 in order to make system access instructions available

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2756]
Will need to define and test the process for uploading, storing, accessing and linking to docs in S3. Also, we want to understand the process for making future updates.

### This task is done when...
 - [x] Process has been defined for initial upload and future updates.
 - [x] Docs have been uploaded.
 - [x] Docs have been linked in login screens.
 - [x] Process has been captured in comms plan

**Comment by cthulhuplus** [comment]
S3 Pricing
https://aws.amazon.com/s3/pricing/?nc=sn&loc=4

We are storing less than 50 TB
![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/c4f3baa2-99f2-4e18-9041-e6717d586f06)

Transactional charges:
![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/61a60f03-0f4d-40e2-bac4-474c6d0192bb)

**Comment by CSwartzHMA** [comment]
@jeromeleecms Are we ok with testing this option? Google published docs don't appear to be an ideal option.

**Comment by jeromeleecms** [comment]
Yes, let's explore this option.

**Comment by CSwartzHMA** [comment]
Test file has been PDF'd and sent to @thetif and @cthulhuplus for testing.
