### ISSUE TITLE
[Dev] Determine how staging and production got out of sync

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2767]
The manage account link was properly removed from production, but it was still present in staging. How was it rolled back on staging?

### This task is done when…
 - [ ] we understand how staging and production got out of sync
 - [ ] we can prevent it from happening in the future

**Comment by jeromeleecms** [comment]
Another issue -- the cost allocation bug has also reappeared. Clicking on the cost allocation link in any activity (including activity 1), now takes you to a blank page.

**Comment by thetif** [comment]
@jeromeleecms Which environment is this happening in and on which APD?

**Comment by thetif** [comment]
After doing some research, it appears that it was a timing issue with git. Two people were working on the same file. The one that removed the link was merged first, but since the other one was edited afterwards, when they were merged, it overwrote the changes and re-added the link. We will have to communicate and plan better to make sure this doesn't happen in the future.
