### ISSUE TITLE
Allow users to email state admin from all relevant dashboards

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2771]
Users should be able to email state admin from the pending dashboard using a mailto: link that pulls from the database the holds the state admins we've approved. 
![Screen Shot 2021-01-12 at 5.53.03 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/2ef07707-c6d6-4436-8c0b-2e15f19dc054)

For release, we'll only allow one state admin per state therefore one state admin to pull into this link. 

### This task is done when...
 - [ ] a user is able to email their state admin from their dashboard
 - [ ] Displays approved, denied, and revoked

**Comment by radavis** [comment]
Moving from small to medium since user information (email) doesn't exist in our database.

**Comment by beparticular** [comment]
@jeromeleecms I'm not sure this made it into the issue as it might have been a later decision, but were we going to have a message when the state admin isn't set up yet to be able to email the eAPD email address? 

cc @radavis

**Comment by jeromeleecms** [comment]
@beparticular I vaguely recall that we had decided that if the state admin was not present, that the app would default to the eAPD email address... am I remembering that incorrectly?

**Comment by radavis** [comment]
What I'm hearing is that we want to default this to `mailto:CMS-EAPD@cms.hhs.gov` when no State Admin is present, correct?

**Comment by beparticular** [comment]
@radavis yes, that is correct. I checked with Jerome last week and this is how we want to move forward. do you want to do this as part of this PR, or to make a new issue for it?

**Comment by radavis** [comment]
Not necessary to create a new ticket. Will change PR #2838

**Comment by thetif** [comment]
moving this back to in progress so I can add it to denied and revoked as well
