### ISSUE TITLE
Allow users to contact the right state admin(s) for their needs

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2772]
Once we have multiple state admins in a state, users will either need to alert/email multiple admins or alert/email the right admin for their needs. This could be done similar to #2771 - the original issue for being able to email one state admin, or it could be a notification in the account, plus an email alert to all admins that a new request has been made. All TBD when we get closer to needing this functionality. 

Putting it in the able to distinguish types epic for now, but will likely branch off to another at some point. 

### This task is done when...
 - [ ] TBD (to be designed), users will be able to contact the intended state admin

**Comment by beparticular** [comment]
Let's start with this option in the account dropdown menu, just above the log out option. 

![Screen Shot 2021-07-22 at 4.56.08 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/5b72b296-4ced-4a7f-8572-fd73937e11a6)

This would open an email to the state admin for the state the user is logged into. If there is more than one state admin for a state, this will behave in whatever way we've decided for the state admin contact on the pending/revoked dashboards. (Or if we haven't decided that, we'll need to decide that at some point.) 

The icon is the same icon on the submit button on the export page. 

@jeromeleecms @akuas @thetif @tbolt any concerns about this approach?

**Comment by beparticular** [comment]
@jeromeleecms bumping this one up for your review

**Comment by tbolt** [comment]
No concerns here on that approach

**Comment by jeromeleecms** [comment]
No concerns here - if I recall correctly, this reflects what we had discussed on one our design meetings, but now has a mock-up to go along with it. Thanks for bump!

**Comment by beparticular** [comment]
@tbolt @thetif please let me know if you need anymore information on this one, but I do believe it's ready for dev.

**Comment by thetif** [comment]
created development issue #3372
