### ISSUE TITLE
Warn users before deleting an APD 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2774]
After accidentally deleting an APD this morning, I realized it's too easy to delete a whole APD. And while users are unable to name APDs at this time, it makes it a little confusing which you might need to delete if you really do need to delete an APD. 

Like #2445 for warning users before deleting a FFY, we should also have a warning for folks when they delete an APD to avoid major data loss. 

Chrome modal pop up with text "Are you sure you want to delete this APD?"
Designate "Cancel" as the default highlighted button in the default browser modal
Use "Cancel" and "Delete" as button text

**Comment by tbolt** [comment]
This issue is resolved. There is an existing alert/confirmation before deleting an APD
