### ISSUE TITLE
Consider a published Google doc for storing access instructions

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2775]
Rather than using S3, a published Google doc is an option for storing access instructions for states to access via a link on the main eAPD page.

### This task is done when...
 - [x] A sample doc has been published
 - [ ] State access has been verified
 - [ ] Team agrees to adopt this approach
 
https://support.google.com/a/users/answer/9308870?hl=en

**Comment by CSwartzHMA** [comment]
@beparticular The doc has been published and can be accessed here.

https://docs.google.com/document/d/e/2PACX-1vQgaxT9KLfp9QtEDDTUcnOMTBmQTFyFCGm2BBjzUjaGl7X90OWkXO1FVCmr8qgncmteyN738tPD5HEx/pub

Note there is still one comment which I left so that we can text to see what happens when the doc is updated. Can you please access the file now and then once I know you can get there with this link I will remove the comment and test again. Once we confirm, I will ask Mary to see if she can get to the page.

**Comment by CSwartzHMA** [comment]
@jeromeleecms @beparticular @thetif Do we need to publish this as a PDF? I don't think anyone can edit it in its current state, but are there any reasons we need to use certain file types for linking in the app?

**Comment by beparticular** [comment]
@CSwartzHMA I can definitely see it, but the formatting is a little wonky at different screen sizes. 
@jeromeleecms are you seeing that too? I'm looking on Chrome/MAC.

**Comment by CSwartzHMA** [comment]
@beparticular @jeromeleecms I agree. It is weird that it converts it all to a single page and there is a ton of white space. I will see if I can play around with settings. On the positive side, all of the links work!

**Comment by CSwartzHMA** [comment]
Update: I don't see any way to improve the appearance and Google does not support publication of PDFs. Should we test S3 and compare the two?

**Comment by beparticular** [comment]
@CSwartzHMA that's a bummer. If we can entertain the paid option, we probably should for better readability

**Comment by CSwartzHMA** [comment]
The team has decided this is not the ideal option. Closing Issue.
