### ISSUE TITLE
Rename Tab Title and Header label to read "CMS eAPD"

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#2780]
The highlighted sections should read "CMS eAPD"

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/7bab6263-10cd-4f64-99e7-e49c5e09d353)

### This task is done when...
 - [ ] Tab title reads "CMS eAPD"
 - [ ] Header label reads "CMS eAPD"
- [ ] Design Signs Off
- [ ] Product Signs Off

**Comment by tbolt** [comment]
These updates were addressed in the  #2736 / #2790  tickets / PR
