### ISSUE TITLE
Revisit Git Branch/Deployment Strategy

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#2784]
Revisit the process that we are currently using to roll deployments up through our environments. 

### This task is done when...
 - [x] Discuss current process
 - [x] Pitch improvement ideas
 - [x] Decide on improvements, if any, that we want to impliment

**Comment by cthulhuplus** [comment]
master should be the branch the reflects what is deployed to master, (we could lock down merges to master to just @thetif and/or @jeromeleecms since it will be a releases only branch)

There should be a new staging branch that reflects what is in staging and is treated as master/production like (protections, reviews, etc...)

Dismiss stale pull request approvals when new commits are pushed
New reviewable commits pushed to a matching branch will dismiss pull request review approvals.

Best Practices for Protected Branches:
https://github.community/t/best-practices-for-protected-branches/10204

**Comment by cthulhuplus** [comment]
Moving out of in progress, waiting to restart this when Richard is back.

**Comment by thetif** [comment]
I would also like a test branch that is pre-staging, since we have actual users trying out stuff in staging sometimes. That way would could also keep staging demo ready while still working on things.

**Comment by cthulhuplus** [comment]
Jerome and Tif both agreed on adopting a strategy that ensures that master is reflective of what is deployed to Prod and the creation of a development branch that would fill the role that master is currently filling.
