### ISSUE TITLE
Left navbar not updating when adding new activities or providing a name

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#2785]
When adding an activity, the left navbar is not updating with the new activity unless you click into the activity OR you click away from the activity navbar.

Additionally, the navbar activity name does not update after providing a name within the activity overview.

Steps to reproduce:

1. Add new activity
2. Left navbar does not update with new activity

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/01f7cd52-3a12-4b69-ad33-d2ea7cf878f0)

3. Click anywhere else, sidebar now updates with the new activity
4. Go back into activity overview for the new activity and type a name
5. Sidebar does not update to include new name (even after clicking away)

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/397eb12f-07c7-492a-bab4-589b0cc61cdf)

6. Only way for the new name in the left navbar to appear seems to be navigating away from the builder (dashboard or export view) and then coming back in to the builder.

Does not affect the export view/output, so putting this as a Sev 3.

### This task is done when…
This could include:
 - [ ] Adding an activity should also add an activity to the left navbar
 - [ ] Adding the activity name should update the left navbar 
- [ ] Design has signed off
- [ ] Product has signed off

**Comment by eStar386** [comment]
@tbolt This activity is in the fridge says it's a medium [https://github.com/CMSgov/eAPD/issues/2414](url) but could be doable and it's easy to test with the current cases.
