### ISSUE TITLE
Update/unify all modals

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2786]
We're using the design system modal in some areas and the browser modal in other areas. Let's work to get all modals following the design system or a modification of the design system, tbd 

### This task is done when...
 - [x] all modals are identified
 - [x] a common component is selected for all modals and examples are mocked up

**Comment by beparticular** [comment]
Known modals - 
When deleting an activity
When deleting a contractor resource
When deleting a non-personnel cost
When deleting an outcome and metric
When deleting an activity milestone
When deleting a state personnel entry
When deleting an APD
When deleting a FFY

**Comment by beparticular** [comment]
Add a modal when a connection is lost: 
replacing #2729

**Comment by akuas** [comment]
**Existing Browser Notifications**
![Deleting an activity 1.png](https://images.zenhubusercontent.com/601acfa212e5437689f6079c/fda3de75-daeb-4451-8b65-0ddf0508703e)
![Deleting contractor resource component.png](https://images.zenhubusercontent.com/601acfa212e5437689f6079c/011d0052-f5fe-4bb5-af06-9ec9a498ca3c)
![Deleting non-personnel cost component.png](https://images.zenhubusercontent.com/601acfa212e5437689f6079c/2dc0534b-ee54-4f06-bab7-d82bbe2e2c02)
![deleting outcome and metrics 2.png](https://images.zenhubusercontent.com/601acfa212e5437689f6079c/e64ed05a-8b9c-4bb0-af28-f3a88a466de7)
![Deleting activity milestone component.png](https://images.zenhubusercontent.com/601acfa212e5437689f6079c/91b0815f-6a15-4979-a7de-31f6cee083de)


**Existing Modals**
I will be brainstorming what modal design we should be using soon and figuring out whether to use the CMS design system's modal dialog component or one of our existing modal designs on Figma. But as it stands now, I am weary of using the CMS Design System's static alert style for the Auth Time out modal. Users who use different CMS products might be expecting a different behavior from what they are experiencing. 
![Auth Time Out.png](https://images.zenhubusercontent.com/601acfa212e5437689f6079c/2dff84ff-41c9-426e-a011-2f141974f5fc)
![Connection Lost.png](https://images.zenhubusercontent.com/601acfa212e5437689f6079c/7e5b4c86-6f55-4d2c-8762-8c21d6996d51)

**Comment by akuas** [comment]
Modal Mockup
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=297%3A124

**Comment by jeromeleecms** [comment]
Made some comments in the Figma @akuas - let me know if you want to talk through them.

**Comment by beparticular** [comment]
@thetif this is ready to move to dev 
Here's a link that goes directly to the modals for this particular issue.
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=2282%3A21333
