### ISSUE TITLE
Analyze research findings for State Officer Early Access

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2788]
### This task is done when we are finished with analysis of: 

 - [x] findings provided in the google form
https://docs.google.com/forms/d/1Lb6Q2hHbHE9d96TkJglQLymh7E5mgZdvDwwV-D7w-Yk/edit

 - [x] feedback provided directly to Nick or Jerome
 - [x] interviews once they are conducted

### Additional markers of done: 
 - [x] interviews are uploaded to dovetail for transcription
 - [x] interviews are tagged in dovetail 
 - [x] findings are shared with the team
 - [x] issues are created for prioritization
 - [ ] findings are added to the wiki

**Comment by beparticular** [comment]
@jeromeleecms documenting that this needs a review in Dovetail before moving into the wiki

**Comment by jeromeleecms** [comment]
I completed the review my Dovetail - didn't see anything that stood out and beyond what we have already discussed. Did you want to tag @CSwartzHMA on the review as well?

**Comment by beparticular** [comment]
@CSwartzHMA if you want to take a look, I've added the findings to the wiki, and they can of course still be commented on or adjusted if anything looks off. Thanks! 

Findings added to wiki, so closing this issue. Hooray! 
https://github.com/CMSgov/eAPD/wiki/User-research-findings#study-state-officer-early-access-for-cake-layer-1
