### ISSUE TITLE
[Dev] Change header on Unable to save changes error

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2803]
Update the text on the save changes error pop-up

Header: Unable to save changes!

Body: Your changes aren't being saved. Try saving your changes again in a few minutes by clicking on the save button.

If that doesn't clear this message, back up the changes you made on this page (for instance, if you just wrote a long narrative, save it into a text file or word doc) and refresh your browser. If you refresh your browser without saving backing up your changes, changes made after this message appeared will be lost.

### This task is done when…
 - [ ] the header has been updated to "Unable to save changes!"
 - [ ] the body has been changed to "Your changes aren't being saved. Try saving your changes again in a few minutes by clicking on the save button.

If that doesn't clear this message, back up the changes you made on this page (for instance, if you just wrote a long narrative, save it into a text file or word doc) and refresh your browser. If you refresh your browser without saving backing up your changes, changes made after this message appeared will be lost."

**Comment by beparticular** [comment]
@tbolt nope, wait. here is the duplicate :) 
If we're going with the modal, we can probably close this one and use the modal issue as the source of truth on this.

**Comment by tbolt** [comment]
Yep @beparticular I was thinking the same thing.

I will take the acceptance from this story and move it to #2406
