### ISSUE TITLE
[Dev] Create a frontend for the Federal Admin panel

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2812]
Use the mockups from #2963 to create the Federal Admin panel. It will use the new endpoints specific to federal admins for retrieving affiliations and changing affiliations. Federal Admins should be sent directly to the Federal Admin panel when they login because they will not have a state and therefore won't have a state admin panel. Federal admins can see all users in the system. They can approve roles from Federal Admin and below. They can edit all roles in the system

![IMG_0315.jpg](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/1f4cc056-6126-4dd5-8976-156d96d91b36)

Additions to federal admin from state admin:
1. For someone requesting access to multiple states, they will have one row with a sub row. Both the row and sub row will show the role, state, and actions options. Name, email, phone will only be shown on the row (not on the sub row)
2. Add a State column 
3. Change order of columns to match the above sketch
Name, email, phone, role, State, actions

History of decisions:
https://cmsgov.slack.com/archives/CUAMFAP9P/p1616422559066500

### This task is done when…
 - [ ] a Federal Admin can see all of the users in the system
 - [ ] a Federal Admin can approve/deny/revoke access for all roles from Federal Admin and down (except themselves)

**Comment by tbolt** [comment]
Based on 7/14 design sync, we decided this will ticket/solution will serve as an interim solution. An upcoming design will be used to handle additional workflows pieces.

**Comment by tbolt** [comment]
Additional ticket created to not include system admins -
https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/cmsgov/eapd/3295

**Comment by tbolt** [comment]
7/21 - Updated this ticket to split out the filter feature: 
https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/cmsgov/eapd/3305
