### ISSUE TITLE
Add links from main login page so new users can access account creation instructions

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2821]
Once docs are available in S3, we will need to add two links to the main login page - One for EUA Account instructions and one for System Access for new users who already have an EUA Account.

### This task is done when...
 - [x] Mock up has been created based on agreed upon approach
 - [ ] Links have been created and tested

**Comment by beparticular** [comment]
@CSwartzHMA do you have an idea of what the content should be for these links?

**Comment by CSwartzHMA** [comment]
@beparticular I was thinking we might want to structure it with a quick intro then two links, but not sure that works in the space available. Maybe something like:

New users will need to obtain an EUA Account before requesting an eAPD Account.
Link 1 text - Already have an EUA Account? Start Here.
Link 2 text - Need to request an EUA Account? Start Here.

**Comment by beparticular** [comment]
@akuas see the log in page in Figma for where to add these links! :)

**Comment by akuas** [comment]
@CSwartzHMA 
I was wondering for Link 1 , if they already have an EUA account, cant they login or do they have to get an additional access to login to eADP. Also what link were you imagining for link 1?

**Comment by CSwartzHMA** [comment]
@akuas They need to have the EUA job codes added and then they would need to create an eAPD account. I shared the instructions document this morning. Let me know if that helps define the process or if you need more context. 

I think I was just thinking we would have a hyperlink that is the text. Maybe something similar to the way we display the forgot password information on the log in screens.

**Comment by akuas** [comment]
Login Mockup 
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=2036%3A21068

**Comment by beparticular** [comment]
@jeromeleecms and or @CSwartzHMA can you take a look at this today? thanks!

**Comment by CSwartzHMA** [comment]
Rather than "Check out how" should the second link say "Review the process"?

Otherwise, this looks great to me!

**Comment by jeromeleecms** [comment]
1. Password reset link looks good.
2. The header of the content seems a bit incongruent with text below it, suggested alternate copy if the focus is on New Users only:

### New Users 
New users must have an EUA account with the correct job codes before logging into the system.
Need an EUA account? How to Get Started.
Have an EUA account? How to Access the eAPD.

Still need help? Email Us at CMS-EAPD@cms.hhs.gov

Certainly open to additional revisions.

**Comment by akuas** [comment]
@jeromeleecms Thanks Jerome. I have now updated the design to reflect the new copy.

**Comment by jeromeleecms** [comment]
If @CSwartzHMA and @beparticular are good - this is ready to transition to dev.

**Comment by beparticular** [comment]
@jeromeleecms Looks good to me! We will transition to dev in design 1:1 this morning.

**Comment by CSwartzHMA** [comment]
Looks good to me, as well!
