### ISSUE TITLE
Research CircleCI Caching

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#2824]
Research CircleCI caching and if it's right for us.
https://circleci.com/docs/2.0/optimization-cookbook/#using-caching-to-optimize-builds-and-workflows

Thoughts:
Cache passed scans/tests for subsequent runs of same job for a short time

### This task is done when...
 - [ ] I've determined if and where using CircleCI caching is right for us

**Comment by cthulhuplus** [comment]
Test Splitting:
https://circleci.com/docs/2.0/optimization-cookbook/#test-splitting-to-speed-up-pipelines

**Comment by jeromeleecms** [comment]
Moving to GitHub Actions
