### ISSUE TITLE
TEMPORARILY Provision Preview Instances in Prod/Staging VPC

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#2832]
This morning CMS announced that on Friday, Februrary 5th, they will be destroying all default VPC and all resources located within. As a TEMPORARY solution I am moving preview deployments to our PRODUCTION/Staging VPC. We are actively pursing a new AWS Account to provision our preview instances in to.

### This task is done when...
 - [x] ~~Preview Instances are provisioned into the PRODUCTION/Staging VPC (until we get the new AWS Account)~~ Preview instances are provisioned into the new CMS provisioned VPC.
 - [x] Preview Instances are performing as if there was no change

**Comment by cthulhuplus** [comment]
This ticket has dramatically changed since it started. I manually created a new VPC for preview deployments and they began deploying there while waiting for either our new AWS accounts and or a new VPC in our current account. A new VPC was provisioned in our account.

**Comment by eStar386** [comment]
Reviewed the temporarily provision preview Instances in Prod/Staging VPC with Bill during a short demo. All the instances are running.
