### ISSUE TITLE
Discuss/Plan SELinux Context Verification Tests

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#2844]
Discuss and plan to implement SELinux context verification tests.

### This task is done when...
 - [ ] @cthulhuplus and @eStar386 have met and discussed SELinux context verification tests
 - [ ] The above persons have developed an implementation plan for the new tests

**Comment by jeromeleecms** [comment]
@mirano-darren Interesting in taking a look at this?

**Comment by mirano-darren** [comment]
Yea sure! I'll do some research on it
