### ISSUE TITLE
[QA] Exploratory Testing

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2859]
Perform exploratory testing on the system. Create a

### This task is done when...
 - [x] Provide a clear view of what tests need improvement and or more coverage
 - [x] A better understanding of the system as a whole

**Comment by eStar386** [comment]
Found different types of bugs, creating a strategy to organize the new/existing bugs, and improve the workflow. Current strategy is to add blockers to the current ticket that prevents it from moving out of QA into ready to review.

**Comment by eStar386** [comment]
Documenting authentication errors handling fixed in refactor login.

**Comment by eStar386** [comment]
Created a test script template from exploratory testing and test scripts. The first version is available within the testing folder and the updated version will be completed soon.

**Comment by eStar386** [comment]
Created the QA Roadmap and updated within the [Workflow Documentation (Roadmap 2.0) ](https://drive.google.com/file/d/1kkQCbDt14U5xfy7aQQib2tjMYC64iLwx/view?usp=sharing).

**Comment by eStar386** [comment]
Established test plans and scenarios within https://drive.google.com/drive/folders/1-mIqOepO-AYgni6T0L59r5AulLXurThG?usp=sharing. Created documentation-including a test-template(currently on v2) to be used by QA for current issues that will aid test automation.
