### ISSUE TITLE
[Dev] Logout issues

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2864]
Bug - 
Currently when you logout sometimes it redirects oddly or it doesn't clear out the session tokens so it's hard to log back in.

### This task is done when…
 - [ ] timeout logs you out correctly
 - [x] selecting logout from the dropdown logs you out correctly
 - [ ] session tokens are cleared out of local storage

**Comment by thetif** [comment]
from slack:

Amanda Evans Mar 17th at 2:28 PM
Potential Issues for the login locked out feature #2864, I think the text should say Account Locked for one hour. It looks like a timer but it never counts down. It just waits the 60 minutes and it’ll display 60 minutes even when its 10 minutes left. Also, it states !Verify your identity => ! Account Locked.

Amanda Evans  5 days ago
Didn’t see this thread, so the issue it looks like a timer but it’s just static text. if this isn’t  essential the text can just read Account Locked -  It will reset in an hour.

**Comment by eStar386** [comment]
Exemption documented in PR - #2974
