### ISSUE TITLE
Create AWS Alarm that Reports to Slack

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#2868]
https://medium.com/pixelpoint/how-to-send-aws-cloudwatch-alarms-to-slack-502bcf106047
What channel? New channel? cms-dsg-eapd-alerts eapd-aws-alerts something else?

### This task is done when...
 - [ ] Alarm Created that Reports to AWS Alarms to Slack
 - [ ] Alarms are received in Slack

**Comment by cthulhuplus** [comment]
Created cloudwatch-to-slack KMS key for CloudWatch to Slack

**Comment by cthulhuplus** [comment]
https://github.com/terraform-aws-modules/terraform-aws-notify-slack

**Comment by cthulhuplus** [comment]
I would like to walk through the Slack parts of this with you @jeromeleecms during our sync.

**Comment by cthulhuplus** [comment]
Met with Jerome on Friday. He created an app for the eAPD CloudWatch Alarms, but creating webhooks as a part of that app require creating a ticket with the HelpDesk.

https://jira.cms.gov/browse/WHSD-34544

**Comment by NAretakis** [comment]
Since we have webhooks URL now, what else do we need to do for this ticket? @cthulhuplus

**Comment by cthulhuplus** [comment]
As we discussed; I was waiting for all of the webhook and AWS permissions to be in place before beginning the coding piece. This is currently "in progress" and I will begin work on it shortly.
