### ISSUE TITLE
FedAdmin role and 40x error

### ISSUE THREAD

**Issue by eStar386** [CMSgov/eAPD#2890]
This relates to a current sprint item [2550](https://github.com/CMSgov/eAPD/issues/2550), this will be an issue for a newer fed admin user (possibly). If they click the create new button it just spins without providing any feedback on the issues.

![image.png](https://images.zenhubusercontent.com/6019ab5a4e513ffb21b40c96/b93e50fd-af05-4009-a72c-9a23333242c5)
### This task is done when...
 - [ ] Remove the create new APD button from Federal Reviewer.
 - [ ] Possibly fixed by 2550 because the user will know it's a 401 error.

**Comment by tbolt** [comment]
The pull request is here #2948
https://github.com/CMSgov/eAPD/pull/2948

Not sure why zenhub didn't take the linked ticket.
