### ISSUE TITLE
Design how a user will select their APD type and funding source

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2895]
We need to allow a user to create a new APD > choose HITECH vs MES > choose the APD type and program funding source

Quick sketch - this doesn't have to be multiple screens. 
- The questions are broken out in boxes to represent what fields drive branching questions in the eAPD system
- The selections in the third box only represent the MES Expansion work, not changes to the HITECH eAPD
![Paper.Testing.4.PNG](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/43b3ac1d-7168-4f1b-805d-fffb92061275)

Considerations:
How would someone edit this information? 
Could someone edit this information if the APD is already created and there is already data in the fields that could get erased? 
Should they? 
If not, how do we make it clear what is possible or that they need to start a new APD to choose a new type or source? 

### This task is done when...

 - [x] designs are created to show how a user will select their APD type
 - [ ] identify 508 considerations and/or recommendations
 - [x] note what to include or change in the export view if anything
 - [x] product signs off on designs
 - [ ] if there is a long discussion, summarize changes for dev in last comment before transfer

**Comment by akuas** [comment]
@jeromeleecms attached are my designs, I am still going through my notes yesterday and implementing some of the changes we talked about but I wanted to show you the designs now since you might be getting deployed soon. There is no rush to look over this now though.

https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=2449%3A0

**Comment by jeromeleecms** [comment]
Thanks @akuas! Added some comments/thoughts in Figma - some are meant to be conversation starters and not "this is the only way." Let me know if you have any questions.

**Comment by beparticular** [comment]
General comment for scope - 
This also includes new fields for the APD Overview as shown on the MES Mural. 
When this is ready to implement, we can break this up into two issues (at least). 

This will be tested with users before it's sent to dev for implementation.

**Comment by beparticular** [comment]
This issue is done as far as design goes. It will be tested the week of April 12. If there are any additional changes after testing, this issue can be re-opened as needed to help with continuity of the design and to hand off final designs to dev in one issue.
