### ISSUE TITLE
Capture Requirements for Go Live Tabletop Exercise

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#2899]
Capture Requirements for Go Live Tabletop Exercise; Dev, DevOps, Design, QA, Comms, everyone

### This task is done when...
 - [x] Capture the requirements for Go Live for each discipline

**Comment by NAretakis** [comment]
Requirements captured! https://app.mural.co/t/cmsmural6360/m/cmsmural6360/1618234344009/c9a82447628c57e850c97f260f19d0d2c16a3427

I am now taking items from this board and populating zenhub with issues for the "must do" items.
