### ISSUE TITLE
Users will need to know how to reset a forgotten password

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2900]
Provide a link and instructions for resetting a forgotten password.

### This task is done when...
 - [x] Link has been added to the log in page
 - [x] FAQ has instructions on how forgotten password

**Comment by akuas** [comment]
Forgot password mockup : https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=2217%3A142

**Comment by akuas** [comment]
After you left, we concluded that we would keep the forgot password with context next to the password field so that the information at the bottom of the screen would be new user specific.

**Comment by CSwartzHMA** [comment]
@akuas This looks great! I will incorporate this into the FAQs. Thanks!

**Comment by CSwartzHMA** [comment]
FAQs have been updated to reflect the path for resetting a forgotten password.

**Comment by CSwartzHMA** [comment]
@thetif I think this one is ready for dev. Let me know if we need to have a quick meeting to discuss implementation of these links.

**Comment by thetif** [comment]
included in #2935
