### ISSUE TITLE
Users need to know how to change their MFA selection

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2902]
### This task is done when...
 - [ ] User instructions for changing MFA selections are drafted
 - [ ] Team has reviewed and agrees with documented steps in instructions
 - [ ] Instructions are posted to Slack channel

**Comment by CSwartzHMA** [comment]
@thetif Can you please drop the link to the Okta site where users can update their MFA selection here so I can use it for the instructions? I think it is in Slack somewhere, but I didn't find it doing a quick search.

**Comment by thetif** [comment]
If they login here https://idm.cms.gov/, then they can manage their Okta account (change password, change MFA, etc)

**Comment by beparticular** [comment]
This will be part of the FAQ and has been captured on the FAQ doc to include.
