### ISSUE TITLE
[Dev] Add automated accessibility testing into CI/CD

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2911]
Add more automated accessibility tools into CI/CD

### This task is done when…
 - [x] add jsx-a11y/strict to eslint on web
 - [x] add jest-axe to web
 - [ ] add Lighthouse to CircleCI/GitHub Actions

**Comment by jeromeleecms** [comment]
Let's just close this out Bill and Tiff will talk about Lighthouse.
