### ISSUE TITLE
[Dev] Resolve Login Styling Issues

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2915]
Fix styling issues with login (refer to the original login page for how this should look)

When logging in initially the password field has a red border to represent invalid password/etc-
![image](https://user-images.githubusercontent.com/2279260/109714878-f01e4000-7b70-11eb-9060-b6fcf6c07d65.png)
It should not have that state-
![image](https://user-images.githubusercontent.com/2279260/109715130-42f7f780-7b71-11eb-85b5-d088a8334aa5.png)

On the "Verify Your Identity" page the background should be grey, it's currently the same color as the box
Incorrect:
![image](https://user-images.githubusercontent.com/2279260/109715086-32e01800-7b71-11eb-91fd-cfa43211b3a2.png)

Correct:
![image](https://user-images.githubusercontent.com/2279260/109715179-573bf480-7b71-11eb-8c4c-12ec2c860374.png)

### This task is done when…

 - [x] the login page should not show the red alert state for the password when the form isn't submitted
 - [x] add the grey background to the "Verify Your Identity" page

**Comment by tbolt** [comment]
Both of these looks resolved now.

For reference here is the verify login page as of 4/6/2021 (on master branch)-
![image.png](https://images.zenhubusercontent.com/5f43eb2204d6d70d8324232c/022c23b5-5312-4b84-8471-17f8af6d5ec6)
