### ISSUE TITLE
Consider changes to the order of information in the export view 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2918]
In the State Officers research study, we uncovered some areas where the export view could be improved for better readability and scanability for folks reviewing APDs. 

Ares of interest in relation to changing the order of information. 
- SOs might not have understood where the executive summary ended and where the other APD details began as they noted they kept viewing the sample APD as a "summary report"
- Potentially, the activity schedule could be moved higher in the export view
- Potentially, the proposed budget aggregate could be moved ahead of the activity schedule and details in the export view. 
- There was a request for the state share to be shown in the executive summary alongside the FFP amounts. 
- It was also requested that Results of Previous Activities be moved closer to the executive summary. 

(All other issues originally reported in this issue around readability of the export view will be spun off into new issues.)

### This task is done when...
 - [ ] We determine what if any changes we'd like to make to the order of information in the export view. 
 - [ ] Designs are created if necessary including needed changes for builder view if any
- [ ] Look at the differences between the builder view, the review view, and the PDF view. 
 - [ ] Product signs off

**Comment by beparticular** [comment]
Note: watch out for feedback on the export view after release. If there are issues, let's prioritize this higher. If not, this can be removed from the post-release EPIC.

**Comment by jeromeleecms** [comment]
That's fine - if you look at some of the sample APDs in Drive, you'll see that Results of Previous Activities follows right after the executive summary. Much of the initial content we capture in the app and display is actually captured in a cover page or page that follows before the executive summary.

**Comment by jeromeleecms** [comment]
Keep in mind there is a general flow for the way the APD is structured (outside of the executive summary): 

1) What are you doing? (High level explanation of the Medicaid program and the driver for why this project/funding requests exists)
2) What have you done in the past? (Previous Activities)
3) How are you going to do it (or keep working toward it)? When are you going to do it? (Activities) 
4) How much is it going to cost? (Budget)

Each section is intended to help convey a narrative that builds upon the previous section. Let's chat about how the proposed sequence aligns with this.

**Comment by jeromeleecms** [comment]
I'm going to reassign to @thetif -- I'll setup some time (or maybe parking lot?) to discuss how to scope this out. Also, let's loop in @RichFixes in that conversation to see if we can take some more immediate action on getting QA/QC to consider test cases earlier on.

**Comment by akuas** [comment]
@jeromeleecms Thanks, sounds good.

**Comment by thetif** [comment]
I just want to make sure that this is the final order:

1. APD Summary and Executive Summary
2. Key State Personnel and Program Management : Includes Medicaid Director and Address
3. APD Overview
4. Results of Previous Activities
5. Activities
6. Activity Schedule Summary
7. Proposed Budget
8. Assurances and Compliance

I don't think I need to break this ticket up. I will make the dev ticket once I get confirmation on the order.

**Comment by thetif** [comment]
created tickets #3583, #3584, #3585, #3586, #3587
