### ISSUE TITLE
Change language in Outcomes and Metrics help text

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2920]
Two State Officers had very strong reactions to the word “discrete” and felt like it was asking the Outcomes and Metrics to be secret or hidden, not out in the open. Language closer to “outcomes statements need to be brief and concise” or “a specific and measurable improvement.” would be clearer.

### This task is done when...
 - [ ] Decide on correct language
 - [ ] Approval by product and leadership

**Comment by thetif** [comment]
Could we reference [SMART](https://www.smartsheet.com/blog/essential-guide-writing-smart-goals) goals to make this more understandable?

**Comment by jeromeleecms** [comment]
We actually had that before @thetif but the way we are using outcomes and metrics are not intended to have super precise numbers. For example, a SMART goal would put something like "Decrease the number of bugs by 25% by 2015," for our context the outcome would be "Decrease the number of bugs to minimize manual fixes in the database." The metric may be "1. # of bugs in the system and 2. # of manual fixes in the database."

**Comment by beparticular** [comment]
@jeromeleecms @CSwartzHMA 

Would "distinct" be on ok substitute for "discrete"? 

Discrete means "not physically attached to another unit"

Distinct means "recognizably different in nature from something else of a similar type." or "being not of the same kind" like "two distinct approaches to the same problem"

**Comment by jeromeleecms** [comment]
That seems like a reasonable change and makes more sense in the context of the ask, @beparticular

**Comment by beparticular** [comment]
@thetif this is ready for dev. 

In this paragraph in Outcomes and Metrics, change "discrete" to "distinct". 

"An Outcome is a discrete and measurable improvement to Medicaid program management, monitoring, or administration, resulting from the delivery of IT system functionality. Outcomes should support the priorities of the Medicaid program and be directly enabled by the state’s IT project."
