### ISSUE TITLE
Improve field labels and help text on private contractor page

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2925]
1. The text in the example box isn't an example - 
a. let's remove the example box 
b. and move " If the vendor or contractor name is unknown, generalize by resource name. (For example, computer resources/TBD)" into help text under Contractor Name

2. The next field label asks for only "Description of Services". 
The field needs to collect the description of services, how the contract was chosen, etc 
Determine if a new field label is appropriate

### This task is done when...
 - [x] Help text is written to meet the needs above
 - [x] A quick mock up is made 
 - [ ] Help text is approved

**Comment by beparticular** [comment]
@jeromeleecms the field that is currently labeled "Description of Services" - what information do we want to ask users to provide in this field until we can add the proper fields after release?

**Comment by jeromeleecms** [comment]
Under description of services we should see

1) What is the scope of their work
2) How was the contract procured (until we have a dedicated field)
3) If the contract was not procured through competitive process, why not? (Justification)

"Procurement Methodology and Description of Services" <- title?

**Comment by beparticular** [comment]
@jeromeleecms what do you think? 

"Provide information on how this contractor was procured and the scope of this contractor's work. If this contract was not procured through competitive process, explain this exception."

![Screen Shot 2021-03-05 at 2 58 33 PM](https://user-images.githubusercontent.com/5957354/110167130-513d5200-7dc3-11eb-9c29-eb0d8acaed70.png)

**Comment by jeromeleecms** [comment]
I think this should make it generic enough to account for any contractors which have not yet been selected: 

"Explain the procurement process for the contractor and the scope of their work. Provide justification for any non-competitive procurements."

Thoughts?

**Comment by beparticular** [comment]
That sounds good to me! Here's the overall page with the suggested edits. @jeromeleecms this is with you to approve now. It looks like a lot, but it's just a very detailed changelog. 

Changes: 

![Screen Shot 2021-03-05 at 4 09 32 PM](https://user-images.githubusercontent.com/5957354/110173832-366fdb00-7dcd-11eb-8c5c-8a8de7886aee.png)

![Screen Shot 2021-03-05 at 4 20 54 PM](https://user-images.githubusercontent.com/5957354/110174853-c82c1800-7dce-11eb-92ea-076b2db8d8da.png)

1. Removed the header that instructed to "outline contracts by contract or vendor name" to reduce redundancy.  (This may have created some extra whitespace in the screenshot, re: chrome dev tools skills)

2. Removed the example box (no examples were included)

3. Changed field label from Contractor Name to "Contractor or Vendor Name"
3.5 This will also need to change once "done" is selected and the summary is showing
3.75 This will also need to change in the export view

4. Moved help text from example box under the Contractor or Vendor Name field label
"If the vendor or contractor name is unknown, generalize by resource name. (For example, computer resources/TBD)"

5. Change "Description of Services" to "Procurement Methodology and Description of Services"
5.5 This will also need to change once "done" is selected and the summary is showing
5.75 This will also need to change in the export view

6. Added help text to the Procurement Methodology and Description of Services field as agreed upon above to 
"Explain the procurement process for the contractor and the scope of their work. Provide justification for any non-competitive procurements." 

7. I'm not sure why this text is wrapping and the other text isn't, might be my chrome dev tools skills. Just verify that the help text all wraps the same on this page. It's also wrapping on the Total Contract Cost help text, not sure why it's not consistent.
 
![Screen Shot 2021-03-05 at 4 22 33 PM](https://user-images.githubusercontent.com/5957354/110175063-248f3780-7dcf-11eb-937f-c305a17d6ca0.png)

8. In the export view, the field for Procurement Methodology and Description of Services isn't showing in the export view if nothing is added to that field. This needs to match the summary above. If this needs to be a separate dev issue, that's cool, but thought since the export view had to be changed anyways, it might be appropriate here.

**Comment by jeromeleecms** [comment]
Couple thoughts:

3) Instead of "Contractor or Vendor Name" what do you think about "Private Contractor or Vendor Name" to make it consistent with the header? I would also be fine with keeping, but ... consistency.
4) In the help text: "Provide the name of the private contractor or vendor. For planned procurements, generalize by resource name. For example, Computer Resources/TBD"

Everything else looks good.

**Comment by beparticular** [comment]
@jeromeleecms that looks good

@thetif this is ready for dev, prioritized before release 
The summary and screenshots are in the comment above
https://github.com/CMSgov/eAPD/issues/2925#issuecomment-791720478
