### ISSUE TITLE
[Dev] Update/unify all modal

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2926]
Development task for #2786

Update warnings in the system to use consistent looking modals instead of a mix of browser notifications, hidden elements, and modals.

As a user, I would prefer to see consistent warnings, so that the issue is clear and I understand how to address it.

##Update the following warnings:

- deleting an activity (currently a global.confirm in web/src/actions/editActivity/activityLists.js)
![DeleteActivity.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/e5aa890e-f2e2-4892-afa2-ef437aedbb67)

- deleting a contractor resource (currently a global.confirm in web/src/actions/editActivity/contractorResources.js)
![DeletePrivateContractor.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/c53c7918-5320-4feb-b9f3-d408baaf7a56)

- deleting a non-personnel cost (currently a global.confirm in web/src/actions/editActivity/nonPersonnelCosts.js)
![DeleteOtherStateExpense.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/05f73eb8-5668-456a-90ae-b174b467d59c)

- deleting an outcome and metric (currently a global.confirm in web/src/actions/editActivity/outcomes.js; 
probably need to make a second one that is just for metric)
![DeleteOutcomeAndMetrics.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/003b98ee-d9b9-4fad-a4fd-f72fa004de4d)

- deleting an activity milestone (currently a global.confirm in web/src/actions/editActivity/scheduleAndMilestones.js)
![DeleteActivityMilestone.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/3d9b9d09-0340-4778-bf7b-28d2e73350e2)

- deleting a state personnel entry (currently a global.confirm in web/src/actions/editActivity/statePersonnel.js)
![DeleteStateStaffExpense.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/8a32bdb4-902b-4496-9d7e-225ec816e384)

- delete a key personnel entry (currently a global.confirm in web/src/actions/editApd/keyPersonnel.js)
![DeleteKeyPersonnel.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/1243696b-a293-4243-a530-be34e0a9e0f9)

- deleting an APD (currently a global.confirm in web/src/containers/StateDashboard.js)
![DeleteAPD.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/08ff4483-8a6b-475f-ab86-c04f092bd68a)

- deleting a FFY (currently a window.confirm in web/src/containers/ApdSummary.js)
![DeleteFFY.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/8981a27b-28fc-4ca1-bef7-d7b89ac7edcd)

- auth time out (component in web/src/containers/SessionEndingAlert.js)
![YourSessionIsExpiring.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/8c0641d9-2f91-4810-a8b8-1539746899a5)

- connection lost (component in web/src/containers/UnexpectedError.js)
![UnableToSaveChanges.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/596e28ba-d777-4ce7-9916-f183ec93f502)

### This task is done when the following modals are updated according to the snapshots above
 - [x] deleting an activity
 - [x] deleting a contractor resource
 - [x] deleting a non-personnel cost
 - [x] deleting an outcome and metric
 - [x] deleting an activity milestone
 - [x] deleting a state personnel entry
 - [x] deleting a key personnel entry
 - [x] deleting an APD 
 - [ ] ~deleting a FFY~ See #2996
 - [x] auth time out
 - [ ] ~connection lost~ See #2997

**Comment by beparticular** [comment]
For records on decisions that were made on this issue, refer to Slack for more details. 
We did decide as shown in the screenshot below to include a second line question on the modals. 

In this thread in Slack we decide that the name of the thing being deleted would be populated on the second line question and only there. 
<img width="756" alt="Screen Shot 2021-04-15 at 2 01 16 PM" src="https://user-images.githubusercontent.com/5957354/114916666-129fac00-9df3-11eb-9520-dd424d119bc1.png">

https://fearless.slack.com/archives/CUW6LHPC5/p1616686691000900
