### ISSUE TITLE
Okta Authentication Error causing blank screen.

### ISSUE THREAD

**Issue by eStar386** [CMSgov/eAPD#2928]
When the user opens a tab and leaves it opens. Afterwards, they reopen the link on another tab in the same or different browser to the same eAPD. The second tab or browser shows a blank screen without any error message. 

Steps to Reproduce 

1. Access an eAPD and performs some actions. 
2. Using a new tab or browser, open the same eAPD link as above. 

Result: 
![Oautherror.png](https://images.zenhubusercontent.com/6019ab5a4e513ffb21b40c96/190f7c73-609a-44f8-890d-0cb291334e8d) 

### This task is done when...
 - [ ] On the second tab or another browser: an error message prompts the user informing them of multiple tabs or browsers are open.
 - [ ] The error message prompts the user to perform an action ie to use this new link they - close the initial tab or browsers.  Otherwise, the system performs an action - close other logins for the user and allow them to login within the new tab automatically.
 - [ ] Design has signed off
 - [ ] Product has signed off

**Comment by tbolt** [comment]
As noted by @eStar386 this ticket is resolved in another PR. Closing this ticket and we can re-open if the issue returns.
