### ISSUE TITLE
Research potential paths for all user types and authentications to access the eAPD 

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2932]
Some users may not be able to gain EUA access and there may be multiple ways a user can be authenticated.

### This task is done when...
 - [ ] All user types have been mapped to potential authentication paths
 - [ ] Mapping has been vetted with Eg for any corrections
 - [ ] Any findings have been addressed in the creation of new issues

**Comment by CSwartzHMA** [comment]
Noting @jeromeleecms will start the mapping document for Eg's review.

**Comment by jeromeleecms** [comment]
Going to tag @NAretakis into this ticket - he's going do some research on this as well.

**Comment by NAretakis** [comment]
@CSwartzHMA 

So, we have a path for state admins and state staff. The only one missing is state contractors right? If so, we can close this ticket and spin up a new one to test adding a state contractor using the EFI/EUA process. Does that sound OK to you?

**Comment by CSwartzHMA** [comment]
Works for me. Closing and will create a separate issue to track process for state contractors.
