### ISSUE TITLE
[Dev] When a state admin's access is revoked, do not let them see the State Admin page

### ISSUE THREAD

**Issue by tbolt** [CMSgov/eAPD#2934]
Currently when a State Admin has their access revoked/denied they are still able to see the state admin page.

### This task is done when…
 - [ ] State Admin's are only able to see the state admin page when they have an "approved" status

**Comment by tbolt** [comment]
Note: This was identified as an issue with the backend sending the wrong permissions down.

@thetif Feel free to edit/update this ticket as needed.

**Comment by beparticular** [comment]
@thetif will check on this to see if it's still a thing

**Comment by tbolt** [comment]
Just tested this and there may be an issue on the frontend as well. I was able to navigate to the State Admin page as `norole` by just adding `/state-admin` to the url. I think we need to check that they're authenticated but also:
1. They have an ACTIVE status for their respective state
2. AND they have role = state_admin for their respective state

**Comment by tbolt** [comment]
Looking into it here is what I concluded:
Anyone can manually navigate to the `/state-admin` URL and it will successfully load the page with the title and the tabs. However, only if you have the correct permissions will the data load in the tables. 

Discussing this with @thetif's we are OK with this behavior so I am closing it.
