### ISSUE TITLE
[Dev] Add links from main login page so new users can access account creation instructions

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2935]
Once docs are available in S3, we will need to add two links to the main login page - One for EUA Account instructions and one for System Access for new users who already have an EUA Account.

Dev task for #2821

Feature -  
Users need more information about how to handle problems with their account on the login page. Links need to be added to help the user reset passwords, create an EUA account, request EUA job codes, and get general help.

![Screen Shot 2021-03-09 at 9.17.58 AM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/fedeeb41-e060-4a03-a045-55efca41af6d)

Add link under password input:
Forgot password? [Reset password at EUA](https://eua.cms.gov/iam/im/pub/cui7/index.jsp?task.tag=forgottenpasswordreset)

Add new users help text:
**New Users**
New users must have an EUA account with the correct job codes before logging into the system.

Add a link to getting started doc:
Need an EUA account? [How to Get Started.](<API_URL>/docs/account-registration)

Add a link to access eAPD doc:
Have an EUA account? [How to Access the eAPD](<API_URL>/docs/system-access)

Update the support email link text to:
Still need help? Email us at [CMS-EAPD@cms.hhs.gov](mailto:CMS-EAPD@cms.hhs.gov?subject=Password%20Recovery%20Request%20for%20eAPD)

### This task is done when…
 - [ ] there is a reset password link
 - [ ] there is help text for new users
 - [ ] there is a link to the getting started doc
 - [ ] there is a link to the access eAPD doc
 - [ ] updated the text for the support email

**Comment by thetif** [comment]
Reference #2900 for more information about Forgotten Password

**Comment by tbolt** [comment]
The mailto currently has a subject that will prepopulate in a mail client when clicked:
mailto:CMS-EAPD@cms.hhs.gov?subject=Password%20Recovery%20Request%20for%20eAPD

I kept that in, let me know if we want to take it out @thetif @beparticular

**Comment by beparticular** [comment]
@tbolt that's fine with me
