### ISSUE TITLE
Update State Admin Panel to be state-independent and support an All States View

### ISSUE THREAD

**Issue by tbolt** [CMSgov/eAPD#2936]
During work on the federal admin panel I noticed that we don't have a way to differentiate state admin requests vs. other state roles (when a user signs up they select their state but not their role). Therefore we can't easily have a federal admin panel where we are only showing "state admin" requests.

The solution we came up with is to update the state admin panel such that it can accommodate both Federal and State Admins needs:
* When a federal admin is viewing the State Admin Portal they will see ALL requests across ALL states
* When a state admin is viewing the State Admin Portal they will see ALL requests for ONLY their states (this will make it easy to handle multi-state Admins)
* Remove the specific state name from the navigation and page title
* Add State field as a column to the table

### This task is done when…
This could include:
 - [ ] a list of changes to be made
 - [ ] the description of what a user might be able to accomplish once this is done
 - [ ] identify 508 considerations and/or recommendations
 - [ ] any tangible deliverable(s) that need to be created
 
*Add a LABEL (design, dev, compliance, BUG, size, etc) before submitting.

*If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for PRODUCT to prioritize.

**Comment by jeromeleecms** [comment]
@ty will there be any way to filter down the tables so when we get a signed request for an admin we can quickly filter down to the user we are looking for? Example of something I've used this plugin in the past to allow some quick functionality (not sure how it supports react): https://datatables.net/

If we see all the user requests it potentially could be unwieldy to track down people as Federal admin looking to approve state admins.

**Comment by tbolt** [comment]
@jeromeleecms This is something I talked about with @beparticular and @thetif. We were thinking that it would be a good idea to have the ability to sort and filter. We talked about filtering by state but if we used a tool/library like the one you mentioned it should be pretty easy to have the quick filter feature. 

Otherwise, how does this direction sound?

**Comment by jeromeleecms** [comment]
Sounds good as long we have a way to filter and sort folks.

**Comment by thetif** [comment]
this is covered in #2812 and #2963
