### ISSUE TITLE
[Enhancement]: User Navigation for Activities 

### ISSUE THREAD

**Issue by eStar386** [CMSgov/eAPD#2937]
As previously discussed, subitems within the navigation link to the first section of the webpage. However, navigation changes within the activity menu. The first item of the activity turns into a dropdown menu. For consistency within subitems - the activity name should link to the activity overview page. 

<img width="1440" alt="UserActivityNavigation" src="https://user-images.githubusercontent.com/71447081/110530832-e05ea880-80e8-11eb-824c-850f00611664.png">

### This task is done when…
 - [ ] The user navigates to the activity overview for selected activity.

**Comment by beparticular** [comment]
Related: this is how we wanted to address the issues with the nav drop downs. 
https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/cmsgov/eapd/2414

This is different from how the design system currently does their nav. Our system is currently implemented to match the design system. (@tbolt and @radavis double checking it's all implemented according to design system at this time?). In the design system, each item under the menu header is a separate page, where in our system we have one page with multiple anchors (is that still the right word, or did I time travel to the 90s?) represented in the nav. 

See history 
https://github.com/CMSgov/eAPD/issues/2188

Hopefully this gives more context as to how we got to here and where we want to go with potential navigation changes in the future.

**Comment by beparticular** [comment]
This will be addressed in the existing ticket #2188 when it's time to prioritize it.
