### ISSUE TITLE
[Dev] Add eADPSystemAccess document to backend

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2938]
The eAPDSystemAccess.pdf file needs to be added to s3 on Staging and Production. 
The file should also be added to api/test-data/files and api/__files with the same name that it has in s3.
Once the file is in place, an endpoint should be created in api/routes/docs to retrieve the file locally or from s3.

### This task can be verified by...
 - [ ] using Postman to try to download the file from the PR api location

### This task is done when…
 - [x] the file is up on Staging s3
 - [x] the file is up on Production s3 (waiting on permission from AWS)
 - [x] the file is stored locally in the api/test-data/files folder
 - [x] the file is stored locally in the api/__files folder
 - [x] there is an endpoint to retrieve the file (no restrictions should be placed on this endpoint)
 
[eAPDSystemAccess.pdf](https://app.zenhub.com/files/113234315/e6823cd2-40b8-4476-a2f4-deae0043f225/download)

**Comment by thetif** [comment]
Bill and I do no have access to the files folder on s3. We have tickets in to get access. Once we have access, one of us will add the file.

**Comment by eStar386** [comment]
Approved document is on staging and production.
