### ISSUE TITLE
Review help text on dashboard screen

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#2946]
The help text on the dashboard is outdated and should be reviewed before we go live.

Current Help Text:

The CMS HITECH APD app is the new way to create and manage your state’s HITECH Advanced Planning Documents (APDs). Follow the steps to fill in the required information, and the app will generate a completed APD you can submit to a CMS State Officer for review.

All your state’s APDs are listed here. Save your work in progress and come back to a draft at any time. When you’re ready to submit an APD, download a PDF and email it to CMS at MedicaidHITECH@cms.hhs.gov just like you’ve done before.

Proposed Help Text (open to feedback of course):

The eAPD is designed to help you create and manage your HITECH Advanced Planning Documents (APDs). Create a new APD or edit an existing one, the app will help you generate a completed APD that you can submit to CMS for review. When you are ready to submit your APD, download a PDF, and email it to CMS at MedicaidHITECH@cms.hhs.gov just like you've done before.

### This task is done when...
 - [ ] Copy has been revised/approved by Design
 - [ ] Copy has been approved by Product

**Comment by beparticular** [comment]
@CSwartzHMA do you have any thoughts on this language for the dashboard?

**Comment by CSwartzHMA** [comment]
@beparticular Is the intent to keep this HITECH specific at this time?

**Comment by beparticular** [comment]
@CSwartzHMA yes, this is just for release

**Comment by CSwartzHMA** [comment]
@beparticular How about this: 

The eAPD is designed to help you create and manage your HITECH Advanced Planning Documents (APDs). Create a new APD or select one already in progress to edit. The eAPD will capture required information needed to generate a completed APD that you can submit to CMS for review. When you are ready to submit your APD, export the APD to a PDF, and email it to CMS at MedicaidHITECH@cms.hhs.gov just like you've done before.

**Comment by beparticular** [comment]
@CSwartzHMA that's good. do you think we need to state more clearly where they go to export to PDF since it's not on this page?

**Comment by CSwartzHMA** [comment]
@beparticular I do, actually, now that you mention it. I change it to say export, but we can be more clear. Let's change the last sentence to: 
When you are ready to review and submit your APD, use the export function to save the APD as a PDF, and email it to CMS at MedicaidHITECH@cms.hhs.gov just like you've done before.

**Comment by beparticular** [comment]
@thetif this is ready for dev 

The eAPD is designed to help you create and manage your HITECH Advanced Planning Documents (APDs). Create a new APD or select one already in progress to edit. The eAPD will capture required information needed to generate a completed APD that you can submit to CMS for review. When you are ready to review and submit your APD, use the export function to export the APD as a PDF, and email it to CMS at MedicaidHITECH@cms.hhs.gov just like you've done before.
