### ISSUE TITLE
[Dev] Update description for Outcomes and Metrics

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2950]
development task for #2920

Two State Officers had very strong reactions to the word “discrete” and felt like it was asking the Outcomes and Metrics to be secret or hidden, not out in the open. Language closer to “outcomes statements need to be brief and concise” or “a specific and measurable improvement.” would be clearer.

 ![Screen Shot 2021-03-12 at 3.07.39 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/577d62b9-694e-4bd2-adbf-fb02e1ce0f71)

Updated the highlighted text to: 

An Outcome is a distinct and measurable improvement to Medicaid program management, monitoring, or administration, resulting from the delivery of IT system functionality. Outcomes should support the priorities of the Medicaid program and be directly enabled by the state’s IT project

### This task is done when…
This could include:
 - [ ] the text has been updated as described

**Comment by tbolt** [comment]
I'm also going to update this in the form field:
![image.png](https://images.zenhubusercontent.com/5f43eb2204d6d70d8324232c/16b1d211-82db-41ae-a638-bd35e42134cb)
