### ISSUE TITLE
Recruit and schedule state participants for research study for MES expansion design ideas

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2953]
Sessions should be scheduled with state E&E and MMIS APD SMEs

### This task is done when...
 - [x] Recruitment comms have been developed
 - [x] ListServ message has been submitted for clearance
 - [x] ListServ Clearance has been received
 - [x] Email has been sent via listserv
 - [x] Sessions have been scheduled with 4-5 states

**Comment by CSwartzHMA** [comment]
Draft outreach message can be found at https://docs.google.com/document/d/1rdiyjUvEJELQoT1zlkz-WB4Q5h2lrtPKZrw1ZxTQb6I/edit#

**Comment by beparticular** [comment]
@akuas if you want to take a look at Caryn's draft email above and give feedback, please do!

**Comment by akuas** [comment]
Hi Caryn, it looks great to me. It is worded in a way that we can use this for other upcoming MES research sessions. I suppose we are not including any State Officers right?

**Comment by CSwartzHMA** [comment]
@akuas That is correct. I believe we are just looking for feedback from state users at this time.

**Comment by beparticular** [comment]
@CSwartzHMA I was wondering if it might be worth talking to one or two state officers. maybe after we hear author feedback?
