### ISSUE TITLE
Update log in designs in Figma

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2954]
The log in screens were created in fall of 2020. The implementation has been mostly to this design, but with some improvements. 
For continuity as we add in the remaining pieces of the log in process (multiple states, multiple state admins, etc) and for QA accuracy, let's update the screens in Figma to match the current implementation. 

https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=2493%3A22276

In keybase there is log in information for different cases and roles (to trigger MFA, to trigger lock outs, etc). 
e.g I know we've changed the error messages when a password is wrong, or when someone is locked out. 
Let's make sure we have all these cases represented in the designs in Figma. 

### This task is done when...
 - [ ] log in flows are reviewed in staging or production (whichever Tif or QA suggests) what's the most up to date
 - [ ] the figma file is updated to match all cases that are in production, including improvements, additions, or subtractions
 - [ ] design lead has reviewed (no product review needed as it's not going into production)

**Comment by eStar386** [comment]
@akuas @thetif @beparticular, I will attend the upcoming design sync so we can review/update cases. However, please let me know if anything is needed in the interim?

**Comment by beparticular** [comment]
These designs are close enough to what is implemented at this time. Closing.
