### ISSUE TITLE
Create a prototype for MES Expansion Research Round 1

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2955]
Research Plan Issue - #2486

The Research study is scheduled to start 4/12. The prototype should be ready for final approval by 4/2 (as Design Lead will be out of office 4/5 - 4/9), but work should be collaborative and check ins often throughout the creation process. 

Prototype Creation Details
Create a prototype to test designs from #2895, #2372, #2984, and #2168 as the first round of testing for how folks will create an MES type APD, changes to the APD and Activity overviews, inclusion of risks, alternative, etc. 

Prototype needs and designs will be documented in Figma
#2895 + APD Overview https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=2449%3A0
#2372, #2984, and #2186 https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=2522%3A0

Step one - review 2895 and give to dev for initial work
Step two - Caryn and Nick determining fields for 2186
Step three - provide new flow and page designs for 2372 and 2168 to dev for prototype implementation

### This task is done when...
 - [x] A clickable prototype is created for research study participants to use (as of now, in code vs Figma) as described above and in subsequent comments
 - [x] Design lead approves prototype
 - [x] Product approves prototype

**Comment by tbolt** [comment]
The bulk of this work has been completed as of 4/5. We will target 4/19 as the new date to have final approval and no new changes/updates beyond that date.

**Comment by beparticular** [comment]
I spent some time with the prototype yesterday while writing the protocol and have a few updates that need to be made. 

Changes needed - 

In Figma only - @akuas 
- [ ] The program funding selections should be updated on the Figma file to match the current implementation on the prototype (proper options grayed out, HITECH help text, etc) 
- [ ]  Standards and Conditions - the help text and content on the first screen needs to match the other two screens
- [ ] Standards and Conditions - Yes answer needs to include only one field and ask how the activity will or will not support S&C

Prototype only - @tbolt 
- [ ]  Add Activity needs to be Activity Dashboard
- [ ]  Continue to activity (and back to Add Activity) needs to be Activity Dashboard
- [ ]  Add another activity needs to be “Add activity”
- [ ]  The activity screen needs to not have an activity already created, it needs to be the empty state from issue 2984
- [ ]  Add another milestone needs to be “Add a milestone”
- [ ]  Update the language on Standards and Conditions (TBD in design sync) 

Figma and Prototype - @tbolt and @akuas 
1) “Currently not available” - they won’t ever be available so remove the word currently
2) Scope of APD Project help text is out of sync and I’m not sure which is right @
Ty and Akua should work with Caryn/Nick to determine which is right cc @CSwartzHMA @NAretakis

**Comment by akuas** [comment]
I asked Caryn how we can reword the Scope of APD project help text and changed the copy to  "Provide a brief overview of the scope of this funding request and how it fits into the MES vision described above. Include a summary of achievements that will enhance the effective and efficient administration of the Medicaid program."

**Comment by tbolt** [comment]
Those updates should be available in the PR build now @beparticular

**Comment by beparticular** [comment]
@tbolt here are the updates that need to be made to the prototype for testing today

- [ ]  Fix typo under Activity Snapshot 
"You can speak on THE purpose..."
![Screen Shot 2021-04-20 at 5.59.44 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/ac4abe05-12cd-499d-925d-db7bd026a807)

- [ ]  Cost benefit analysis typo "include HOW the selected approach..." (not hown)
![Screen Shot 2021-04-20 at 6.00.48 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/8fac35c7-7288-4714-b8c8-a5dfd470f826)

- [ ]  On the Analysis of Alternatives and Risks page, remove the example box and example
![Screen Shot 2021-04-20 at 6.02.21 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/3b4a2597-486a-4471-b011-676dfe733b0a)

- [ ]  On the Enhanced Funding Qualification page, remove the first sentence under EFQ
Take out "Indicate whether the selected FPP...." sentence 
![Screen Shot 2021-04-20 at 6.06.00 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/5ff5405f-174b-42a7-bba2-6dd21011d938)

- [ ]  Update the language on Enhanced Funding Qualification page 
Change the help text under the yes choice under enhanced funding justification to "Describe how this activity will or WILL NOT support the Medicaid Standards and Conditions 42 CFR 433.112.") 
![Screen Shot 2021-04-20 at 6.01.54 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/9b0cc7b9-ffe3-4f59-8d68-9d715997bfca)

**Comment by tbolt** [comment]
Those updates should be in the latest build now. Thanks

**Comment by beparticular** [comment]
@tbolt I'm leaning toward not making many changes to the prototype before the next session, but I'm going to sleep on and consider if we need changes for Friday or for the sessions scheduled next week. 

That means for Friday's session, all we need to change right now is the RTE issue and the language under Scope of APD. 
This is the correct language: 
"Provide a brief overview of the scope of this funding request and how it fits into the MES vision described above. Include a summary of achievements that will enhance the effective and efficient administration of the Medicaid program. (2-3 paragraphs)"

Please let @thetif know when those are in so she can update the users after the changes are made
And @thetif let me know what the new link is for the prototype. 

Thanks!

**Comment by beparticular** [comment]
@tbolt @thetif 
Let's go ahead and 

- [ ] remove the Compliance to Fed Regulations field from the Activity Overview page ahead of Monday's interview. Thank you! 
- [ ] Alphabetize the MES Modules options 

Please let me and Tif know when it's done so we can get the user accounts added. Thanks! 

Thanks!

**Comment by tbolt** [comment]
@beparticular @thetif Those changes have been made and new build is available. Let me know if anything seems off.
https://ec2-18-233-210-18.compute-1.amazonaws.com/
