### ISSUE TITLE
[Dev] Investigate why rich text editor is losing formatting after page reload

### ISSUE THREAD

**Issue by tbolt** [CMSgov/eAPD#2961]
It seems that some of the formatting from the rich text editor is being lost after the page is refreshed.

Bug - 
Before 
![image.png](https://images.zenhubusercontent.com/5f43eb2204d6d70d8324232c/a2e673d2-327a-4c53-bfad-6e77f8ce70a7)

After (page is reloaded)
![image.png](https://images.zenhubusercontent.com/5f43eb2204d6d70d8324232c/9ed33147-9083-4a6e-a8f7-a96be30b3e3e)

**Comment by thetif** [comment]
this might be an issue with the sanitizer stripping out that stuff on the backend

**Comment by tbolt** [comment]
That was my suspicion as well @thetif. I wonder if some of the formatting options could be removed @beparticular @akuas

**Comment by thetif** [comment]
I think we can loosen some of the restrictions on the backend while still maintaining our security
