### ISSUE TITLE
[Design Issue] Design Federal Admin Panel

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2963]
Design - 
Design the UI for the Federal Admin panel. It should look similar to the State Admin panel, but it should be able to show users' states and users that have multiple roles in multiple states. The Federal Admin should be able to see all of the users in the system. Federal Admins should be able to approve all status from Federal Admin and below. Also, Federal Admins should be able to edit all roles in the system.

### This task is done when…
 - [ ] mockups for the Federal Admin panel have been created

**Comment by beparticular** [comment]
@tbolt added in an updated sketch and details. Let me know if you need anything else! 

![IMG_0315.jpg](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/1f4cc056-6126-4dd5-8976-156d96d91b36)

Additions to federal admin from state admin:
1. Filters on the Name and State columns
2. For someone requesting access to multiple states, they will have one row with a sub row. Both the row and sub row will show the role, state, and actions options. Name, email, phone will only be shown on the row (not on the sub row)
3. Add a State column 
4. Change order of columns to match the above sketch
Name, email, phone, role, State, actions


History of decisions:
https://cmsgov.slack.com/archives/CUAMFAP9P/p1616422559066500

**Comment by beparticular** [comment]
@thetif just FYI this one is probably ready for dev unless y'all need anything else.

**Comment by thetif** [comment]
Added this information to #2812
