### ISSUE TITLE
Design Debt: Create eAPD system in Figma

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2973]
As we take on new design tickets, let's make sure we're taking the time to build and use the right components from the design.cms.gov UI file to build a good foundation for creating all designs in the future. 

This will include -
Using the design system UI kit to work on current issues and corresponding pages as we encounter them
Using the design system UI kit to work on other pages in Figma that might not actively be in redesign
Marking new vs old work as such with dates of work, related ticket numbers, or archiving outdated pages
Talk about how to facilitate design conversations within Figma vs Mural

### This ticket is done when
- [x] Reviewed all the pages in Figma and set priorities for needed designs
- [x] New vs old work is archived or marked with dates of work, related ticket numbers, etc
- [x] Built out designs by priority and needs listed in this google doc
https://docs.google.com/document/d/14US5lWoPfIpYSwHx8DG0TQVZJqIk5Pay4GRo3NWqc7E/edit

**Comment by akuas** [comment]
List of needed designs
https://docs.google.com/document/d/14US5lWoPfIpYSwHx8DG0TQVZJqIk5Pay4GRo3NWqc7E/edit

**Comment by beparticular** [comment]
Also part of this #2954

**Comment by akuas** [comment]
[Results of Previous Activities](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=2875%3A333)

**Comment by beparticular** [comment]
Progress report: have most of the current work implemented into Figma - will keep going between other priorities as time allows according to the check list on google doc.

**Comment by akuas** [comment]
Hi @beparticular I added links to the design debt document and unchecked them so you can check the work as you go through and if a page needs more work you can add it there, if you like. I also added a date to the designs I worked on  so that it is easier to identify.
https://docs.google.com/document/d/14US5lWoPfIpYSwHx8DG0TQVZJqIk5Pay4GRo3NWqc7E/edit

**Comment by beparticular** [comment]
@akuas thank you for adding that and the links! 
The one thing that may still be missing is the private contractor costs page when the user is in the edit area. There's a screenshot to represent that now, but we could use a built out page for that for an upcoming issue with the MES expansion. Otherwise I think this is a great foundation for us in Figma. Appreciate it!

**Comment by akuas** [comment]
Okay, I will create that state for the private contractor. @beparticular

**Comment by akuas** [comment]
Okay, I included the design for the expanded private contractors field. I feel that when there are multiple private contractors, we probably want some sort of divider between the default private contractor state and the edited one.

**Comment by beparticular** [comment]
Hooray! Thanks for your work on this!
