### ISSUE TITLE
[Dev] File is viewable in Dev and PRs

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#2977]
The eAPDSystemAccess.pdf file should also be added to api/test-data/files and api/__files.
Once the file is in place, an endpoint should be created in api/routes/docs to retrieve the file locally.

### This task is done when…
 - [ ] the file is stored locally in the api/test-data/files folder
 - [ ] the file is stored locally in the api/__files folder
 - [ ] there is an endpoint to retrieve the file (no restrictions should be placed on this endpoint)

**Comment by eStar386** [comment]
@thetif  Can you provide the endpoint?
