### ISSUE TITLE
Add activity label on nav isn't accurate

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2982]
### **History/Problem We're Solving**
When we changed the label on the nav from Activity List to Add Activity, it was to help people find where to add a new activity after observing folks struggle to find that option within the side nav subgroups, pages and sections. 

The problem with that quick fix is that it's not just adding an activity that happens. It's adding an activity, entering an activity, seeing a list of activities, and deleting an activity. 

We opted not to use Manage Activities, because you manage the activities within an activity and can also get to the activities through the sidebar, so we didn't want to take away from that. 

### This task is done when...
 - [ ] Team agrees on a new nav label

**Comment by tbolt** [comment]
Couple random ideas:
1. Call it "Activity List"
2. Call it "Activities" similar to how the "Results of Previous Activities" nav is
![image](https://user-images.githubusercontent.com/2279260/112153615-d1ccc280-8bb9-11eb-9de7-fb2f603baa1c.png)

**Comment by beparticular** [comment]
That's what it used to be, but folks couldn't figure out where to Add an Activity. When it said Activities or Activities List, they thought it was a header for the Activities in the navigation.

**Comment by beparticular** [comment]
What do folks think of "Manage Activities". Technically you manage the activity in the Activity, but I could be convinced that I'm being pedantic. 

Or "Add and Delete Activities" could be an option?

**Comment by eStar386** [comment]
User-friendly Random Ideas: Call it Activities Manager, Activity Creator,  Activity Documenter, something with an -er.
Otherwise without the -er: Activities Overview, Activities Homepage, Proposed Activities, Create an Activity (a merge of the Activities Homepage and Activity Manager).

**Comment by CSwartzHMA** [comment]
Another random option: Activities Dashboard

**Comment by beparticular** [comment]
Actually @CSwartzHMA that might work. There is a chance that in the future, there will be some aggregated info about Activities that would need a Dashboard. @NAretakis what do you think? I know we've changed this a couple of times, but I think we might have hit a good spot with Activities Dashboard. 

<img width="998" alt="Screen Shot 2021-03-25 at 4 46 28 PM" src="https://user-images.githubusercontent.com/5957354/112541502-d8119900-8d89-11eb-9f16-efd6687dd670.png">

**Comment by eStar386** [comment]
I really like Activities Dashboard, kudos @CSwartzHMA!

**Comment by NAretakis** [comment]
Activities Dashboard is good by me. I think in one version it was "Activity List", but dashboard gives actually more info.

**Comment by beparticular** [comment]
@NAretakis when it was List, people couldn't figure out how to add an activity. i'm hoping that with Dashboard, that findability  won't be lost.

**Comment by beparticular** [comment]
@thetif this is ready for dev

**Comment by thetif** [comment]
created design task #3010
