### ISSUE TITLE
[Dev] Update the delete process for FFY

### ISSUE THREAD

**Issue by knollfear** [CMSgov/eAPD#2996]
Feature -  
Update FFY delete process.  Many delete modals have been updated, but this one has not been aligned yet.  See #2926 for background details.
![image.png](https://images.zenhubusercontent.com/60538024593ffba0e82f15b2/47a59a24-b6fc-4cfb-a107-0c41d3aaa462)

### This task is done when…
This could include:
 - [ ] deleting a Fiscal year from an APD shows the desired delete modal
 
*Add a LABEL (design, dev, compliance, BUG, size, etc) before submitting.

*If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for PRODUCT to prioritize.

**Comment by tbolt** [comment]
Review / QA Notes
* Logged in with norole and manually approved access to create APDs
* Removed a FFY, verified that the alert does prompt
* Verified that the design matches the proposed specification provided by the screenshot
* Checked all FFYs, removed all FFYs
