### ISSUE TITLE
[Research] QAOps

### ISSUE THREAD

**Issue by eStar386** [CMSgov/eAPD#3002]
Defining the QA pipeline and creating QAOps.  QAOps is a process of integrating QA activities into the CI/CD pipeline.

### This task is done when…
This could include:
 - [ ] a plan to create a QA DevOps process

**Comment by eStar386** [comment]
Creating a strategy to begin implementing automated test cases utilizing the regression test cases from #2971 and the refactor to build regression and/or smoke test suite.

**Comment by eStar386** [comment]
The initial strategy is to: 1. Create small test cases and increment to build a robust test suite. 2. Perform automated cross-browser testing 3. [Performance-based testing ](https://techbeacon.com/app-dev-testing/how-do-web-performance-testing-google-lighthouse-cypress) - this is the current technology being implemented and the reference for the overall QAOPS pipeline

**Comment by eStar386** [comment]
Based on the meeting DEVQAOPS can formalize itself:   https://docs.google.com/document/d/135h4YzGEkehpgWV4IrwJLVVBogfqKhM0UZx92DQeiNE/edit?usp=sharing

**Comment by cthulhuplus** [comment]
@eStar386, as mentioned in my email response, I feel like we can just follow the current Dev/QA process. If we need to change/iterate on the process for DevOps/QA we can do that at a later point.
