### ISSUE TITLE
[Comms Issue] Standards and Conditions : Content Review

### ISSUE THREAD

**Issue by akuas** [CMSgov/eAPD#3006]
**Standards and Conditions needs a content review because it one of the more content heavy pages for my design and I want to make sure that the help text is clear and concise. This story has a dependency on #2372** 

### Moving text on a page or large text change

*One of the main things i want reviewed on the Standards and Conditions page is the sub-headers. I want to make sure users know that they first state if their activity qualifies for enhanced funding then list/explain out the ways it supports or doesn't support the Standards and Conditions for Enhanced funding regulation.
* Want to make sure that the standards and conditions description clearly explains the purpose of the page 
* Want to know if there are other content issues that wasn't considered before on the page and how to make it more understandable

### This task is done when…
This could include:
 - [x] Standards and Conditions is reviewed for clarity
 - [x] Design updates copy in Figma

Standards and Conditions Design:
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=2522%3A0

**Comment by CSwartzHMA** [comment]
Suggest this section be updated to say:

Review Medicaid Standards and Conditions for Enhanced Funding regulation for the criteria that qualifies activities for enhanced funding that pertains to various FFP rates.  [LINK]

Enhanced Funding Qualification
Indicate whether the selected FFP for this activity has a match rate of 75-25 or 90-10. Provide justification of how the activity supports Medicaid initiatives and warrants the selected match rate.

In the extended (check yes) version, we can provide the example, but no need to reiteration the reference to the regulation.

@akuas Let me know if you want to set up some time to discuss.

**Comment by akuas** [comment]
Thank you Ill include those. Are you saying "Review Medicaid Standards and Conditions for Enhanced Funding regulation for the criteria that qualifies activities for enhanced funding that pertains to various FFP rates." should be the whole link?
