### ISSUE TITLE
[Comms] Review content in Alternative Considerations and Forseeable Risks and create fields for Forseeable Risks

### ISSUE THREAD

**Issue by akuas** [CMSgov/eAPD#3008]
The Activity Overview page contains have been broken down into three screen, one being the Alternative Considerations and Foreseeable risks page.

Original solution - The page would have one field that require users to explain the alternatives they exhausted and the costs, benefits, and risks of each option.
Current idea - Since we are enforcing that users conduct feasibility studies, cost benefit analysis, requirements analysis, and alternative analysis(or at least explain why they are exempt), we have opted breaking down the one field into four. But the page has a lot of copy and I wonder if we can shorten it somehow. Also, design needs guidance on what fields to include for foreseeable risks.

### This task is done when...
 - [ ] Alternative Conditions is reviewed by Comms
 - [ ] Foreseeable Risks field(s) are created 
 - [ ] Updates to Alternative Considerations and Foreseeable Risk
 
Alternative Considerations and Foreseeable Risks:
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=2630%3A1

**Comment by akuas** [comment]
Related story: I was unable to add this as a dependency
https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/cmsgov/eapd/2168

**Comment by beparticular** [comment]
Added this information to existing issue #2168 and adjusted the name of that issue to reflect that we are working on adding that to the Activities section.
