### ISSUE TITLE
[Dev] Add activity label on nav isn't accurate

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3010]
based on design task #2982

Currently:
![image](https://user-images.githubusercontent.com/2279260/112153615-d1ccc280-8bb9-11eb-9de7-fb2f603baa1c.png)

Change to:

<img width="998" alt="Screen Shot 2021-03-25 at 4 46 28 PM" src="https://user-images.githubusercontent.com/5957354/112541502-d8119900-8d89-11eb-9f16-efd6687dd670.png">

### This task is done when…
 - [ ] Add Activity has been changed to Activities Dashboard
 
**History/Problem We're Solving**
When we changed the label on the nav from Activity List to Add Activity, it was to help people find where to add a new activity after observing folks struggle to find that option within the side nav subgroups, pages and sections.

The problem with that quick fix is that it's not just adding an activity that happens. It's adding an activity, entering an activity, seeing a list of activities, and deleting an activity.

We opted not to use Manage Activities, because you manage the activities within an activity and can also get to the activities through the sidebar, so we didn't want to take away from that.

**Comment by beparticular** [comment]
@thetif 
Per 1:1 conversation with Tif, with the constraints we have with the nav+header being consistent, and the activities section being slightly different in intent than the rest of the sections, it's ok in this case for the first sub nav under Activities to not match the header on that page. 

Sub nav should be Activities Dashboard, and the header on the page can remain Activities. 

Also pending - likely changes to the Activity Dashboard after this round of research, so let's not spend a lot of time solving this problem right now.
