### ISSUE TITLE
On the state affiliation selection page, give users an option to exit

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3011]
In the log in refactor ticket #2706, we determined that once folks get to where they choose their state affiliation, they are effectively logged in to the system and need a way to exit this screen. 

### Current implementation 
![Screen Shot 2021-03-31 at 6.22.12 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/97f2b7ed-3167-46fa-b36b-f5a0a10554c0)

### Possible solutions 
We could do one of two things - 
~Show the regular header at this point and provide a log out~
We decided on. - * Match the "Back to Login" link that we're using in other parts of the system

Example - 
![Screen Shot 2021-03-31 at 6.26.25 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/477d98f6-b68f-4555-bb66-a2bd0c61ead5)

### This task is done when...
 - [x] a decision has been made on which direction to go in
 - [ ] Decision is: add the Back to log in link on the State Affiliation page
 - [x] this direction is approved by product

**Comment by knollfear** [comment]
This looks good.  Tested in multiple browsers and with keyboard only navigation.
