### ISSUE TITLE
[Content Issue] State Admin Notification

### ISSUE THREAD

**Issue by eStar386** [CMSgov/eAPD#3012]
Content - 
Outdated description - For the role: State admin when approving permissions state coordinator was used instead of state staff.  

? Also, should the title of the page match the functionality i.e. Edit Permissions -> Approving State Roles (name TBD if needed)

![contentQuestion.png](https://images.zenhubusercontent.com/6019ab5a4e513ffb21b40c96/6530038c-74ae-4951-93b5-5dc659995089)

attaching slack thread: https://cmsgov.slack.com/archives/CUAMFAP9P/p1617285453039500

### This task is done when…
This includes:
 - [ ] text matches user roles in dropdown menu

**Comment by beparticular** [comment]
@CSwartzHMA for this issue, is this text ok for the help text? Specifically around state staff being someone who is *generally* a state employee, knowing that some folks designate a contractor in that kind of role, complete with a state email address? 

"eAPD State Staff is someone who works for a state, generally a state employee. eAPD State Contractor is someone who works for a vendor on behalf of the state."

### Updated screenshot with proposed language
Header changed to role
Help text changed to above
![Screen Shot 2021-04-13 at 3.34.38 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/a8c6e5c4-5641-4604-9944-675bc3e4f9bf)

**Comment by CSwartzHMA** [comment]
@beparticular I would suggest we keep it more straightforward. eAPD State Staff are state employees. eAPD State Contractor is someone who works for a vendor on behalf of the state. They can make exceptions to the selection on their end, if they choose, but at least we have offered a structure for clear designation.

**Comment by beparticular** [comment]
@CSwartzHMA how about this? 

"eAPD State Staff is a state employee. eAPD State Contractor is someone who works for a vendor on behalf of the state."

Updated screenshot with proposed language
Header changed to role
Help text changed to above
![Screen Shot 2021-04-15 at 10 28 05 AM](https://user-images.githubusercontent.com/5957354/114886206-58e61280-9dd5-11eb-964a-a43f362949c8.png)

**Comment by CSwartzHMA** [comment]
@beparticular I think it looks great!

**Comment by beparticular** [comment]
@thetif ready for dev!
