### ISSUE TITLE
Investigate state admin dashboard not showing correct requests/active users

### ISSUE THREAD

**Issue by tbolt** [CMSgov/eAPD#3018]
Adding a placeholder for now. I noticed that with my local build I was seeing some strange behavior with the state admin dashboard. When logged in with the em@il.com account I was able to see the AK State Dashboard. When viewing that page the initial requests is empty, but after going to the active tab and then back to requests, there was a full list of users. 

### This task is done when...
 - [ ] criteria 1
 - [ ] criteria 2
 
*Add a LABEL (design, dev, compliance, BUG, etc) before submitting.

*If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for PRODUCT to prioritize.

**Comment by thetif** [comment]
No longer happening
