### ISSUE TITLE
API Gateway Audit

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#3027]
Address this security finding:
```
us-east-2: No Stage name found for hitech-staging
```

### This task is done when...
 - [x] "us-east-2: No Stage name found for hitech-staging" has been addressed

**Comment by cthulhuplus** [comment]
"us-east-2: No Stage name found for hitech-staging" was not being used and was outside of authorized AWS regions, it has been removed.

**Comment by NAretakis** [comment]
👍  good by me.
