### ISSUE TITLE
Check Last Minute Go-Live Design Needs

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/eAPD#3040]
Per our go-live table top: Double check with dev if there are any last design needs

### This task is done when...
 - [x] Review prioritized backlog
 - [x] Check with Tif before go-live epic and agree on what's left, design/UI wise
 - [ ] Create child design issues for any changes that are needed

**Comment by beparticular** [comment]
Talked to Tif in 1:1 and we're all good between design and dev for release.
