### ISSUE TITLE
One more look at the export view for Go-Live

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/eAPD#3041]
Per out go-live tabletop: Design to do one more look at the export view for go-live.

### This task is done when...
 - [x] Check to see if the options we allow in the RTE go through to the export view (e.g. images, colors, styling) (Akua)
 - [x] Check to see how the export looks if information is not entered for a field (Akua)
- [x] Document the export views in Figma - include side by side of what it looks like when it's filled out and what it looks like when it's empty - (also look at when dates are partially entered, or different options in non narrative fields, all the options on the different fields), TBD on how the side by side is done (field by field or page by page, etc)  (Akua)
- [x] After the review is documented, look to  #2918 and #2728 for possible known issues or solutions
 - [x] Take a look at how styling is done (dev tools) and see if there's anything useful or helpful to making the export more readable (Jenn and Akua)

**Comment by beparticular** [comment]
@akuas  can you write up a bug ticket for the issue where the export view doesn't load if all FFYs are unchecked? Include screenshots to show what's happening. Thanks!

**Comment by beparticular** [comment]
@akuas based on 1:1 convo - next steps 
Annotate where you think changes should be made
Annotate what the lines are doing in the activity part of the export view
Make a better design for activities 
Make a better design for assurances (as noted in #2728)

**Comment by beparticular** [comment]
This look at the export view has been completed and new issues have been added to the board. They will be discussed in refinement and design sync for prioritization.
