### ISSUE TITLE
Confirm alerts from prod are working as expected

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/eAPD#3042]
Per our go-live tabletop: we want to confirm alerts from prod are working as expected

### This task is done when...
 - [x] Cause backend to fail
 - [x] Check Cloudwatch / Slack / Splunk (Bonus Points)
 - [x] Confirm in this issue that alerts are working as expected. If not, create child issues as necessary to fix.

**Comment by cthulhuplus** [comment]
500 errors causing backend to fail are being properly reported. 

Created a Dev bug ticket to capture the other type of error that is generating 500 errors:
https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/cmsgov/eapd/3176
