### ISSUE TITLE
Provide state users access information

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/eAPD#3054]
Per the tabletop go-live exercise we wanted to Provide state users access information.

### This task is done when...
 - [ ] Finalize decision about changing states
 - [ ] Update instructions doc
 - [ ] Post doc and incorporate into comms plan

**Comment by beparticular** [comment]
Instructions are written and ready to send. Represented in the Mural https://app.mural.co/t/cmsmural6360/m/cmsmural6360/1619115882654/7e266614f1e14f0908697c7958cc8c5c25d1da8e
