### ISSUE TITLE
Get Slack channel ready for Go-Live comms (between users and for users)

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/eAPD#3055]
Per the tabletop go-live exercise, we wanted to set up Slack channel for comms (between users and for users).

### This task is done when...
 - [x] Finalize list of comms to be posted
 - [x] Finalize/Create agreed upon docs
 - [x] Post/Pin Docs to channel
 - [x] Pin Channel Intro/User Welcome Message

**Comment by NAretakis** [comment]
@CSwartzHMA can you help us tackle items in this task?

**Comment by CSwartzHMA** [comment]
Absolutely. Its on the Release Comms plan.

**Comment by NAretakis** [comment]
@CSwartzHMA  can you add a link to the release comms plan? We might be able to close out this issue if it covers the items described in the issue description.

**Comment by CSwartzHMA** [comment]
@NAretakis Of course!
[Comms Plan document](https://docs.google.com/document/d/11N4H84Qwk44XxSusmaH6gSJiCTChN8raY_zdyk7N6Ug/edit?usp=sharing)
[Mural Board](https://app.mural.co/t/cmsmural6360/m/cmsmural6360/1619115882654/7e266614f1e14f0908697c7958cc8c5c25d1da8e)

**Comment by CSwartzHMA** [comment]
Proposed list of docs to be pinned to this channel:

- EUA Account Instructions
- eAPD Access Instructions
- FAQ Document
- Logistics Webinar recording (?)
- Webinar Walkthrough Recording (?)
- Sample APD
- State Admin Account Management Instructions (?)

**Comment by NAretakis** [comment]
Pinned the message in the slack channel and put placeholders for the documents still under construction.
