### ISSUE TITLE
Webinar for logistics around access and support

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/eAPD#3056]
Per the go-live tabletop exercise, we wanted to setup a webinar for logistics around access and support.

### This task is done when...
 - [ ] Draft outline for team approval
 - [ ] Begin approval process for outreach
 - [ ] Develop/review slides
 - [ ] Plan date/time/speakers
 - [ ] Send comms/invite
 - [ ] Hold webinar

**Comment by CSwartzHMA** [comment]
Duplicate of #2697. Closing as we will track this action on other issue.
