### ISSUE TITLE
 Test adding a state contractor using the EFI/EUA process

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#3061]
Since we have not yet had a state contractor go through the EFI/EUA process, we want to keep an eye on this and make sure current instructions apply to them.

### This task is done when...
 - [ ] Identify a state who uses contractors to support APD writing process.
 - [ ] Recruit the state's contractors to go through the EFI/EUA process using current instructions.
 - [ ] Track their progress and any feedback or hurdles identified.
 - [ ] Troubleshoot, as needed.
 - [ ] Amend instructions, as needed.

**Comment by beparticular** [comment]
We've decided not to do this at this time. Assume for now that they can get through until we know for sure otherwise. 
Closing for now.
