### ISSUE TITLE
Create accounts for research sessions participants

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3062]
In the research sessions starting on 4/21, each participant will need their own username and password to access the test environment. The username and pw would be deleted after each session to make sure folks aren't going into the test link during other sessions or on their own. 

Right now we definitely need 5 accounts, potentially 7 if we are able to have any State Officers participate. 

### This task is done when...
 - [ ] 5-7 user accounts are created
 - [ ] A list of accounts is shared with design before testing so they can be added to the protocol

**Comment by thetif** [comment]
PR environment set up at: https://ec2-3-222-243-20.compute-1.amazonaws.com/login

added the following users:
testerCO1
testerCO2
testerKS1
testerKS2
testerPA1
testerPA2
testerSC1
testerSC2
testerWY1
testerWY2

I sent @beparticular the passwords on keybase.
