### ISSUE TITLE
Document all example boxes in system

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3070]
We should go ahead and document all the example boxes, in context, that are in the system. 
It should be determined if the content contained within is actually an example, or if it's help text. 

This would be in preparation for a content review of the example boxes where we would determine if we'd move the help text elsewhere, reduce the help text, create an example if it's really needed, or leave the example as is if it's the correct information. 
In this stage, we would also determine if we wanted to use something standard from the design system as the example box, vs the custom box that appears now. 

### This task is done when...
 - [x] A page is created in Figma that documents all of the example boxes and whether they are examples or help text
 - [x] A new task is written to represent the content work that will be needed (to be prioritized after the release training and comms have been completed - including officers hours and FAQ)

**Comment by beparticular** [comment]
I'd like to do this one to get back into the system and get some reminders of the application. I could work with @CSwartzHMA on this.

**Comment by akuas** [comment]
@beparticular Sounds good.

**Comment by beparticular** [comment]
The example boxes are now documented here in Figma
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=8349%3A25980

Next steps: Review the content for the following
Which non-examples need to be moved to help text?
Should examples be added in place of the removed help text?
Should we have components or styles for the following: Help Text, Directives, Policy Information, Examples, etc

@jeromeleecms I can put in tickets to ask for a content review, and a separate linked ticket for determining if we want to have particular design styles for these and other help texts in the system, if that's cool.

**Comment by beparticular** [comment]
Next steps documented in #4050
