### ISSUE TITLE
[Dev]Private Contractor Builder vs. Export view

### ISSUE THREAD

**Issue by eStar386** [CMSgov/eAPD#3086]
There is a difference between the export view and the builder view. The export view shows the dates both in the review on screen and in the PDF but the builder view shows the text date not specified.

Related Information:
Browsers: Chrome, FireFox UserRoles:All applicable roles (excludes login error roles and fed admin)

Steps to Reproduce:
1. Navigate to any activities and proceed to the private contractor page.
2. Select the add a private contractor button and improperly add dates to the Contract start date field. For example 11/2019 or any invalid combo of MM/DD/YYYY (like 99/99/9999)

Expected Behavior/Result: Validation occurs on the date field and the user is asked to create a date in a certain format. Date is changed and shows as entered in both the builder and export view. 
Actual Results: If the user doesn't change the date to a valid date range, this produces on the builder view "date not specified". Entering into the edit area still shows the invalid dates. The invalid dates show on the export view. 
Unknown and TBD - what should the system behavior be when the user doesn't enter a valid date? 

Export (PDF VIEW)
![exportView.png](https://images.zenhubusercontent.com/6019ab5a4e513ffb21b40c96/e2f009db-77ec-49a9-a0ea-7934d0140eec)
User View(EAPD app)
![userview.png](https://images.zenhubusercontent.com/6019ab5a4e513ffb21b40c96/61efad8b-1d29-4237-ae2c-68bb76b907fb)

This is done when 
- [ ] Design determines - what should the system behavior be when the user doesn't enter a valid date? 
- [ ] Dev implements that decision.

**Comment by knollfear** [comment]
This looks great.  Good job.

**Comment by knollfear** [comment]
Tested via test plan found at https://docs.google.com/spreadsheets/d/1hZdN-_z5qcpHxxjGFejbxz4dgeVZrLGe0OsqDFX85rI/edit#gid=1830914760  Please request access if you are blocked.
