### ISSUE TITLE
[Bug] 502 Error Message

### ISSUE THREAD

**Issue by eStar386** [CMSgov/eAPD#3092]
Bug -  When the system has trouble with the accessing the server causing a 502 error - "an invalid response from an inbound server it accessed while attempting to fulfill the request" - quoted from google . 

Resource: 
https://www.exai.com/blog/502-bad-gateway

Environment: Test, Staging 

Actual Result: The error message pictured below. 
<img width="1433" alt="502" src="https://user-images.githubusercontent.com/71447081/117316636-c1656400-ae56-11eb-8a9e-2b33dff143ba.png">

Expected Result: The system handles 500 errors by notifying the user that login isn't possible. 

Steps for Verification:  
Based on the 502 and 404 errors: 
- [ ] Verify a log is created for each type of error above

### This task is done when…

 - [ ] the user isn't prompted to try again on any 500 errors. 
 - [ ] the website administrator receives an alert the system is down
 - [ ] other users are notified that there is error and when the system is ready for access.

**Comment by thetif** [comment]
fixed in #3223
