### ISSUE TITLE
Backend Crash Tracking

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#3095]
At some point during the night ours of May 5th or morning of May 6th the backend went down across all of our environments; Prod, Impl, and Test. The server logs did not contain useful information and the application logs were largely empty, application error logs were completely empty.

Theory: Okta disconnected during the window that the backend went down. When backend loses connectivity to Okta, it crashes.

Looking to answer: Why is the backend crashing & why all the environments crashed at once & why does it present as a CORS issue?

### This task is done when...
 - [ ] This ticket is simply for tracking, ticket is done when action items have been generated

**Comment by cthulhuplus** [comment]
7/28/2021
9:07 PM - Okta Agent sbess-00544fd0ce5287806.hcqis.org stopped connecting.
9:15 PM - ALARM: "Prod-UnHealthyHostCount" in US East (N. Virginia)

**Comment by cthulhuplus** [comment]
We believe that the crashes are being caused by a combination of the CMS Patch Group restarting our instances and npm audit vulnerability findings. If there is a security finding when the patching happens, when the instance/application is restarted, if a vulnerability is found the application fails to come back up.

**Comment by cthulhuplus** [comment]
In order to address the above, we have added a calendar reminder the day before our CMS Patch Group dates. This will allow us to get ahead of any sort of vulnerability and avoid future unexpected downtime.

@thetif is there anything I have missed or that you want to add before we close this out?

**Comment by thetif** [comment]
Nope, that covers it.

**Comment by cthulhuplus** [comment]
@NAretakis is there any other actions or questions you'd like around this?
