### ISSUE TITLE
[CI/CD] Add a mongo server to the prod environment

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3102]
Stand up a MongoDB server on the prod environment. Add the connection string to an environment variable called PRODUCTION_MONGO_URL. Update the build pipeline to import that variable as MONGO_URL so that it is available inside the api. Add logging to CloudWatch and Splunk.

### This task is done when...
 - [x] a MongoDB server is available on the prod environment
 - [ ] add connection string to CircleCI as PRODUCTION_MONGO_URL
 - [ ] update build scripts to ingest PRODUCTION_MONGO_URL into the api as MONGO_URL
 - [ ] add logging to CloudWatch
 - [ ] add logging to Splunk
 - [ ] add command to migrate mongo to build scripts

**Comment by cthulhuplus** [comment]
Merged into https://github.com/CMSgov/eAPD/pull/3656
