### ISSUE TITLE
[CI/CD] Add a mongo server to the staging environment

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3103]
Stand up a MongoDB server on the staging environment. Add the connection string to an environment variable called STAGING_MONGO_URL. Update the build pipeline to import that variable as MONGO_URL so that it is available inside the api. Add logging to CloudWatch and Splunk.

### This task is done when...
 - [ ] a MongoDB server is available on the staging environment
 - [ ] add connection string to CircleCI as STAGING_MONGO_URL
 - [ ] update build scripts to ingest STAGING_MONGO_URL into the api as MONGO_URL
 - [ ] add logging to CloudWatch
 - [ ] add logging to Splunk
 - [ ] add command to migrate mongo to build scripts

**Comment by cthulhuplus** [comment]
Merged into https://github.com/CMSgov/eAPD/pull/3656
