### ISSUE TITLE
[CI/CD] Add a mongo server to the preview environment

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3104]
Stand up a MongoDB server on the preview environment. Add the connection string to an environment variable called PREVIEW_MONGO_URL. Update the build pipeline to import that variable as MONGO_URL so that it is available inside the api. Add logging to CloudWatch and Splunk.

This task is done when...
- [x]  a MongoDB server is available on the preview environment
- [x] add connection string to CircleCI as PREVIEW_MONGO_URL
- [x] update build scripts to ingest PREVIEW_MONGO_URL into the api as MONGO_URL
- [x] add logging to CloudWatch
- [ ] add logging to Splunk
- [ ] add commands to migrate and seed mongo to build scripts

**Comment by cthulhuplus** [comment]
@thetif I feel like this ticket needs to be split. The strategy for deploying Mongo on our current Preview Environment and Staging and Prod... will probably be different.

**Comment by cthulhuplus** [comment]
Created https://jiraent.cms.gov/browse/CLDSPT-11179 to ensure that the the Mongo logs file path makes it to Splunk.

**Comment by cthulhuplus** [comment]
Hardening Mongo:
RBAC
User Authentication
SG doesn't allow open access
- Allow access from Jumpbox
- Allow access from eAPD Production
