### ISSUE TITLE
[Fed Role] - Can't View Printable or Shareable Links 

### ISSUE THREAD

**Issue by eStar386** [CMSgov/eAPD#3119]
Found in [2589](https://github.com/CMSgov/eAPD/issues/2589)

- The federal admin role cannot view printable or shareable links. 

**Steps to Reproduce** 
Precondition: Any state or non federal user.
1.  Sign into the app and create a shareable link using the export submission process.
2.  In another tab or browser copy +  paste shareable link , sign in as a federal or admin users.

**Comment by jeromeleecms** [comment]
This is a nonissue at this point. We have include more specific URL for APDs.
