### ISSUE TITLE
[Dev] Create secret for signing JWT's

### ISSUE THREAD

**Issue by knollfear** [CMSgov/eAPD#3128]
Now that we are issuing JWT's for authentication and authorization they need to be signed with a truly random value.

### This task is done when...
 - [ ] api/auth/jwtUtils.js => getSecret() returns a value from the environment (or other external source)
 - [ ] documentation exists for finding (and setting?) the variable for local environments.   Deployed environments can keep the secret secret for security reasons.
 - [ ] all auth continues to work

**Comment by tbolt** [comment]
I ran through this again and everything looks good so I am going to move it over.

Steps I completed:
* Reviewed code
* Ran tests
* Started docker containers and verified that JWT_SECRET was not set(/blank)
* Shut down docker container, added a JWT_SECRET to my local env
* Verified it was set in the container
