### ISSUE TITLE
Chrome and Okta Issue 

### ISSUE THREAD

**Issue by eStar386** [CMSgov/eAPD#3133]
Frequently, I receive uncaught promise OAuthError using the steps below I was able to create a process to trigger this error. 
Found in #3011 
Role Affected: Personal User Setup a new user in the test.reg.idm.cms.gov/registration.html?appid=eapd

Precondition: Using the link about create a new user.
Browser: Chrome (Private Browser)

Detailed Description of the BUG: The back to login button causes the user to be stuck on the validating your session page.

Steps To Reproduce:

Using a new user or a self created user with no affiliations -> login.
Verify your identity
On the state affiliation selection page, select back to login button. On the backend The new user triggers an OAuthError(except for norolemfa).
Expected Result: Return to the Login Page

Actual Result: Stuck on the validating the page. The user must close the browser to force it close.

https://user-images.githubusercontent.com/71447081/118310078-2145b580-b4bc-11eb-9696-1dfbd177193b.mov
Uploading Chrome Recording 2021-05-14 at 11.09.17 AM.mov…

Please see the following resources:

-  https://github.com/paulmillr/es6-shim/issues/403 
- https://github.com/okta/okta-oidc-js/issues/460
- https://devforum.okta.com/t/the-client-specified-not-to-prompt-but-the-client-app-requires-re-authentication-or-mfa/11165

**Comment by thetif** [comment]
@eStar386 can you try this again with the fixes I made to #3011? I think I might have fixed it.
