### ISSUE TITLE
[Design Issue] Activity Index in the URL

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3135]
The way our url routing current works, the activity is referenced in the url by activityIndex, which is zero based. However, the activities are labeled with a one based convention. Should we use the human readable format or the machine readable format to label the activity in the url? What is the best way for the user to understand which activity they are referencing in the url?

Technical considerations - special characters + 

![Screen Shot 2021-05-17 at 1.49.03 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/9fed17db-a98c-40e8-b64f-2cd9f223b835)

### This task is done when…
 - [x] there is a determination on how to handle activity labels in the url

**Comment by jeromeleecms** [comment]
This is unrelated to MES expansion and we can revisit if user complain about this URL.
