### ISSUE TITLE
[Bug] Timeout modal behavior is inconsistent

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3137]
**I was checking out the time out modal for another issue and experienced some inconsistencies in how the modal behaved.**

**Type of Bug-**

- [ ] Accessibility
- [X] Functional (i think)
- [ ] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-in this case, the three different things I experienced as best I can describe**

1. I logged into the em@ account on staging some time between 9:20 and 10am. I am unsure if I made any edits, but I think I did. I left the tab open till at least 11:30am. I clicked back on the tab where the timeout message was and the time out modal was still up. I don't recall if this was the old or new modal, but the PR for the new modal was merged before this, so it must have been the new one. I was able to click "stay signed in" or whatever the link was, and remained signed in and was able to make changes and save my APD. 

2. This afternoon I logged into the em@ account on staging, made a change to the APD, saw that it saved, then set a timer for ten minutes so the time out modal would appear. The new time out modal appeared. I set another timer for 5 minutes to let the countdown stop. When I went back to the same tab, the time out modal was gone and I was still logged in. 

3. I made another change and waited for the time out modal to appear again, setting a timer for ten minutes. When I returned to the tab after what may have been more than 10-15 minutes, I was logged out. 

4. I will try again and see if I can reproduce any of these behaviors and report back as I can. 

**Role Affected-**
- [ ] All
- [ ] Federal Admin
- [ ] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin
- [X] Unsure

**Browser-**
- [ ] Firefox
- [X] Chrome
- [ ] IE

**Expected results-**
Unsure 100% what the behavior is supposed to be. See comment here where I wanted to outline that. 
https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/cmsgov/eapd/3121#issuecomment-843506908

**Actual results-**
See above

**Related user story/bug-** (if applicable)

**Additional information-** (optional)

**Logs or error output/Screenshot/Video-** (at least 1 of these)

**Comment by thetif** [comment]
@beparticular can you test this against this PR? https://github.com/CMSgov/eAPD/pull/3174 I think the work that Ty did there actually fixed this one too.

**Comment by beparticular** [comment]
@thetif I wasn't able to replicate any of these issues in #3174, so I believe it was fixed.

**Comment by thetif** [comment]
Fixed as a part of #3174, closing as OBE
