### ISSUE TITLE
[Feature] Add sysadmin user to Staging and convert team accounts on Prod

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3142]
**Description and related issues -**
This is follow on work for #2964, once it has been released, we need to use this new role in staging and update team members to have this role in Production. There is a script available in api/seeds/scripts that assists in adding these roles.

**What is the goal or purpose of this ticket?**
We don't want our team members to have State Staff roles for random states once we are in production. So we created a role where they would be able to still log in and checkout all of the states if that was needed, but not be able to edit anything. Once that work in #2964 is released, this is the follow on task to actually use it.

### Acceptance criteria
- [x] Given that you are on the Staging environment, when you login as sysadmin, then you should be able to see the APD list for Alaska.
- [x] Given that you are on the Prod environment, when you login with your EUA id, then you should be able to see the APD list for Alaska.
- [x] Given that you have access to the Staging database, when you search the affiliations table, you should see that sysadmin has the eAPD System Admin role approved for all of the states.
- [x] Given that you have access to the Prod database, when you search the affiliations table, you should see that all of the team members have the eAPD System Admin role approved for all of the states, and they no longer have other roles for other states.
- [x] in production, remove APDs from all of the states except DE
- [x] in production, check Nick and Jerome make sure that they have the Federal Admin role for the fd state

### This task is done when…
- [ ] all acceptance criteria are met

**Comment by cthulhuplus** [comment]
The plan that I'm looking for "approval" on from @thetif @knollfear @tbolt @mirano-darren @chris-miraflor

Hop on the VPN
SSH to the Jumpbox
connect to Staging RDS, collect user_id for sysadmin
Adjust the values in the add-system-admin.sql file
Run updated script against staging database
```
psql -h IP.ADD.RE.SS -p PORT -U username -d databasename -f add-system-admin.sql
```
Confirm it has run successful with 
```
"SELECT * FROM auth_affiliations"
```
Confirm the checkboxes

Repeat for Prod

**Comment by thetif** [comment]
That sounds like a good plan. On prod, we don't have a sysadmin user though, you'll have to update all of our accounts to be sysadmin accounts, except for Jerome and Nick.

**Comment by cthulhuplus** [comment]
@thetif Staging looks good, it looks like a complete list of the States and Territories
