### ISSUE TITLE
[Design Issue] Show in the export view when a state has not entered information into a field

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3145]
Note for grooming - dev would you like us to split this into 3 dev tickets? Also, the small indication is for the design work, since the design work was already done. 

For before release - we've determined three sections where it may be hard for the reviewer to understand whether a state has entered information, or if something is broken in the export view. We'd like to add in an indication that no information has been entered so the reviewer knows a field was left blank. 

## APD Overview
On the APD Overview page it's not clear what the sections are if no information is entered. 
Screenshot of current export view
![APD Overview empty.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/c6b2552f-52af-48cf-bcac-e561b9da2f89)
Screenshot of requested design in export view
![APD Overview new vers..png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/9bc32181-f43f-40c8-ad44-1ad7d0e65960)
Builder view - no changes needed

## Medicaid Director
When the Medicaid Director's name isn't entered, it is not showing on the export view, nor is there an indication that there should be a name if no information is entered. The phone number and email fields appear, but are blank. I think it's safe to assume that the the reviewer could see that the fields aren't filled out if all the fields exist together. In this empty state it does appear slightly broken. 
Screenshot of current
![Screen Shot 2021-05-21 at 4.46.39 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/b5875f83-9915-45ea-85d3-885e09071bb9)
Screenshot of requested design in export view
![Key State Personnel NOT filled in.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/7d40faf1-28f1-4726-a50d-1f78efe84688)

## Key Personnel and Program Management
When no entries are entered under Key Personnel and Program Management, it's not clear that nothing is entered and it looks broken. 
Screenshot of current
![Key State Personnel and Program Management _ empty state.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/78958dbb-d680-4353-88c8-adbdd283a502)
Screenshot of requested design in export view
![Key State Personnel and Program Management _ empty state new.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/7281f593-8675-4aef-862b-d19bac611fa6)

### This task is done when…

- [x] designs are created, taking into consideration multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] Is is determined that these changes have to be made field by field and there isn't a way to just put in "No response was given" any time a field is empty? Or something like this. 
- [ ] changes are approved by product
- [ ] changes are ok'ed by product/dev for before release 
- [ ] An issue has been created that indicates a need for similar improvements in the Activities section that may be fixed by other design choices.

**Comment by thetif** [comment]
@beparticular yes, 3 tickets would be better. Is this at the point that I need to create the tickets now?

**Comment by thetif** [comment]
created tickets #3157 #3158 #3159
