### ISSUE TITLE
[Design Issue] Decide on a consistent way to display information when Activities aren't given a name

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3148]
Untitled Activities show up inconsistently across the builder, review view, and PDF view and across different sections of the application. 

For example - 

## How the list of activities is displayed. 
Builder View
![ActivitiesDashboard.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/787796fd-136d-41ea-8c1c-7709a31b93ec)

Export View
![Activities Review View.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/371885bf-89ef-4957-89b7-b3a9a428d830)

## How an unnamed activity is shown in the Activities section 
Builder View
![Screen Shot 2021-05-21 at 6.04.55 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/66100279-d3d9-497f-8b6a-f20ac869c17e)

Export View
![Screen Shot 2021-05-21 at 6.07.53 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/32fc7fe4-e991-438f-8201-7cf444c565de)

## How an unnamed activity is shown in the Executive Summary
![Screen Shot 2021-05-25 at 10.32.26 AM.png](https://images.zenhubusercontent.com/601acfa212e5437689f6079c/5536ac16-dfb9-40fd-8bd3-ac6aeb687a32)

### This task is done when…

- [ ] Each different design is documented in this issue with a screenshot and information about what view or section that screenshot is taken in. 
- [ ] A design decision is made on which version to go with (or a new version is created), taking into consideration multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] 508 considerations and/or recommendations are reviewed
- [ ] designs are approved by product

**Comment by beparticular** [comment]
Also an issue in Executive Summary. @akuas will add to the list above.

**Comment by beparticular** [comment]
What do folks think of always using **Activity X: Untitled** as the pattern, with X being the activity number when an Activity name needs to be populated, but does not exist? 

We looked to see if we could see all the instances of a populated Activity Name in the code, but it's hard to do so. This is the best estimate above of where all of these instances occur as of 7/23. I'm working on additions below, but can't get into Staging and I'm going off an old set of screenshots so this might not be 100% accurate. 

For devs -  locations are, as best I can tell : 
1) Builder and export view > Activities Dashboard/List
2) Builder and export view > Activity Overview (2X)
3) Builder and export view > FFP and Budget table headers. These don't currently have the title in them, should they? That could make the headers long and awkward. This could be a pattern deviation where we put the name of the activity under it as a second line header? Or would that be obnoxious code wise? 
4) Builder and export view > Activity Schedule Summary 
4) Builder and export view > Milestones Table 
4) Builder and export view > Proposed budget > activity breakdown 
5) Builder and export view > Executive Summary 
6) Builder and export view > Headers for each page/section 
7) Builder view > Side Nav
8) Builder view > Prev/Cont (Back/Next) button text

**Comment by beparticular** [comment]
@jeromeleecms can you give a thumbs up or down on moving in this direction?

**Comment by jeromeleecms** [comment]
👍 This makes sense to me. We already apply the "Untitled" label when adding new activities in the activities dashboard, so this will make it consistent in the other areas that you identified.

Just a note about the "Budget and FFP tables" - it would be a nice to have to include this because it would help orient the reviewer where they are in the export. The Builder view is less concerning because at least the side nav can help remind the user which Activity they are working in, but if it's easier to implement the change all at one, I'm not opposed to it.

For #10, I don't see where the button text includes the activity name.

**Comment by beparticular** [comment]
@jeromeleecms let's discuss in parking lot with @tbolt on the budget tables including the name

For #10 it's the text underneath the button, I believe.

**Comment by beparticular** [comment]
Will spin off Jerome's question about budget tables into another ticket. Maybe need to bring the FFP and Budget Tables and the Proposed Budget tables design closer into alignment.

**Comment by beparticular** [comment]
Spun off #3308 for the budget tables issue. 

For @thetif this is ready to move to dev. 

Use the content "**Activity X: Untitled**" as the pattern for what should be shown when an Activity has not been named. With X being the activity number when an Activity name needs to be populated, but does not exist. 

This will match what is currently shown in the Activities List/Dashboard
![ActivitiesDashboard.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/787796fd-136d-41ea-8c1c-7709a31b93ec)

This is the best estimate of all the places where the Activity Name is shown in the eAPD System. 
1) Builder and export view > Activities Dashboard/List
2) Builder and export view > Activity Overview (2X)
3) Builder and export view > Activity Schedule Summary
4) Builder and export view > Milestones Table
5) Builder and export view > Proposed budget > activity breakdown
6) Builder and export view > Executive Summary
7) Builder and export view > Headers for each page/section
8) Builder view > Side Nav
9) Builder view > Prev/Cont (Back/Next) text below the button

**Comment by thetif** [comment]
@beparticular what should it display in this case

![Activities Review View.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/371885bf-89ef-4957-89b7-b3a9a428d830)

**Comment by beparticular** [comment]
@thetif I think in that case it can just say "Untitled" and then nothing else unless a funding source has been selected.

**Comment by thetif** [comment]
dev task created #3404
