### ISSUE TITLE
[Design Issue] Explore a new design for the Activities section in the export view

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3149]
The Activities section in the export view is hard to read. While we've tried to make it clear what the reviewers are reading, and the use of dividers to establish sections is consistent in matching the builder view, it appears inconsistent to reviewers. It's also hard to understand the hierarchy of the dividers. 

In research some reviewers have commented that they were now in a different section than Activities, when they had reached the Milestones section of Activities. We believe this is because the Milestones section doesn't have the name of the Activity under it's divider as the other sections do. In the same way, Other Funding looks like another area of the APD, rather than part of the Cost Allocation section. 

Let's explore our options for a more readable Activities section in the export view. The most important considerations are that:
 - the reviewer can tell what details of the Activity are related (for instance Outcomes and Metrics)
- the reviewer can tell which Activity they are reviewing (hopefully without needing to repeat the Activity name under every divider)
- the reviewer knows they are still in the Activities section. 

### This task is done when…

- [x] designs are created, taking into consideration multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] 508 considerations and/or recommendations are reviewed
- [ ] designs are shared
- [ ] designs are approved by product

**Comment by beparticular** [comment]
@akuas I really liked the direction of Experiment 3 that we went over in our meeting. As we talked about the current way the export view is rendered prevents us from being able to show the Activity Name at the top of each page, because we don't know where the page breaks will be. But we do want to figure out some way to keep the reviewer oriented to which Activity they are reviewing. 

Figma in progress https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=3628%3A0

**Comment by akuas** [comment]
Current updated [activities page](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=3650%3A0). 

Updates Made:
- Removed Activity name from each activity sub-header
- Removed divider in-between page section
- Revised Standards and Conditions copy (this section is subject to change when we redesign the Standards and Conditions in the builder view)
- Added a side nav indicating which activity the user is looking at
- Made the activity name or the start of an activity more scannable
- Added hyperlinks to jump to different parts of the activity section
- Reorganized outcomes and metrics to allow for branching

**Comment by beparticular** [comment]
Testing Figma link. Ignore please. 

https://www.figma.com/proto/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?page-id=0%3A9833&node-id=4678%3A30803&viewport=252%2C48%2C0.07&scaling=min-zoom&starting-point-node-id=4678%3A30803&show-proto-sidebar=1

**Comment by akuas** [comment]
Also testing out this figma link. 
https://www.figma.com/proto/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?page-id=0%3A9833&n[…]-zoom&starting-point-node-id=4678%3A30803&show-proto-sidebar=1

**Comment by beparticular** [comment]
@akuas 

For what's possible with PDFs
https://www.npmjs.com/package/pdfmake
https://github.com/bpampuch/pdfmake/blob/0.1/examples/pdfs/tables.pdf

**Comment by akuas** [comment]
@beparticular thanks for the resources. 
To address the 2nd bullet point "the reviewer can tell which Activity they are reviewing," we could leverage PDF's table of contents and bookmarks feature. The table of contents would organize the APD content by sections and users can open the bookmarks to see which activity they are in and navigate easily to the next activity.  This option is only helpful when the PDF is not printed out, so we might have to rely on stating the activity name multiple times or use visual cues, such as numbering the sections to indicate fields are related.

**Comment by beparticular** [comment]
@akuas testing the Frame link here in the issue
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=6084%3A39157

**Comment by akuas** [comment]
@jeromeleecms @beparticular @Sun-Mountain Can you please review the design and let me know what you think. Keep in mind that there might appear to be a lot of negative space but much of that space will be filled up with an actual APD with multiple private contractor costs, state staff etc.

**Comment by akuas** [comment]
@jeromeleecms thanks for the notes
1.  We could do that. I would need to redesign it to see if it is too much for the top.
2. Currently, we don't have the totals like the builder, but in the frame to the [side of my proposed design](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=6316%3A39707), I had imagined the totals to be beside the APD Overview fields. I was hesitant to add it to the design for this ticket because it might be a big enhancement to develop.

I will get to the rest of your notes in a bit.

**Comment by jeromeleecms** [comment]
Thanks @akuas - we still need to add back in the the description of the actual activity (not the short description). The language would come from "Include as much detail as is necessary to explain the activity." within the app. Other than that, we can do a final review once that's back in.

**Comment by akuas** [comment]
@jeromeleecms @Sun-Mountain 
@beparticular for visibility
When you get the chance, can you please review this document and let me know if there is anything conflicting with what we planned on working on or any other additional comments. 
https://docs.google.com/document/d/10JDLsKfJvrbE5RZtltH9F_ciXMGoUrG6_xzTfPiAv_s/edit

**Comment by jeromeleecms** [comment]
Made some comments on V2, but V1 seems to be consistent with what we've talked about and I don't see any specific overlap between what's next in V2.

**Comment by thetif** [comment]
Created tickets #3588, #3589, #3590, #3591, #3592

**Comment by akuas** [comment]
@thetif The tickets you wrote accurately cover our discussions on the enhancements. I added a couple comments to a couple of the tickets. Regarding the #3585 ticket, I kind of want to think that design through for the APD at a glance. I need to check the colors and I should message what I have decided upon by the end of today or tomorrow morning. Shouldn't take me long to do.

**Comment by thetif** [comment]
sounds good, thanks!
