### ISSUE TITLE
[Learning] Learning about MongoDB/Mongoose Development

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3152]
This is a research task for Ty to learn more about how to develop with MongoDB and Mongoose.

Here are a couple of helpful tutorials:

- Mongo provides their own free courses such as https://university.mongodb.com/courses/M001/about and https://university.mongodb.com/courses/M100/about

- Robo 3T provides a great GUI for interacting with Mongo and their parent company put together a 2hr tutorial about Mongo https://studio3t.com/academy/.

- https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

### This task is done when...
 - [x] Ty has read/watched some tutorials on MongoDB and Mongoose
 - [x] Ty is comfortable writing queries against MongoDB using Mongoose
 - [x] ticket includes list of tutorials read/watched

**Comment by tbolt** [comment]
Completed the [Introduction to MongoDB course ](https://frontendmasters.com/courses/mongodb/) on 8/6/2021
