### ISSUE TITLE
[Bug]Raw HTML in executive summary view

### ISSUE THREAD

**Issue by knollfear** [CMSgov/eAPD#3156]
**Description-**
On the executive summary view there is some raw HTML showing that does not belong.  It should render the HTML as html using the tags for formatting.
(Shown in our seed data in a new APD)
![image.png](https://images.zenhubusercontent.com/60538024593ffba0e82f15b2/89f1b217-8a1b-437b-af1b-48a9d1d86912)

** environment **

staging and the feature branch for #3086

**Type of Bug-**

- [ ] Accessibility
- [ ] Functional
- [ ] Usability
- [ ] API
- [X ] Regression

**Steps to reproduce-**

1. Go to executive summary page
2. See inappropriate html tags
3. edit the activity summary and see that the HTML tags remain.

**Role Affected-**
- [ X] All
- [ ] Federal Admin
- [ ] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Browser-**
- [ X] Firefox
- [ ] Chrome
- [ ] IE

**Expected results-**
html tags format text in WYSWYG fashion
**Actual results-**
html tags are treated as text.
**Related user story/bug-** (if applicable)

**Additional information-** (optional)

**Logs or error output/Screenshot/Video-** (at least 1 of these)
![image.png](https://images.zenhubusercontent.com/60538024593ffba0e82f15b2/a554c273-c3f1-4993-9a08-926fb5e35357)

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by thetif** [comment]
OBE
