### ISSUE TITLE
[Design Issue] Account for all possible actions on multi-state select

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3160]
Related issue #2582

Currently the functionality for the multi-state select is to show all affiliated states whether they are revoked, approved, or pending. The states can't do anything in this area except to select a new affiliation, or contact their state admin (We should use the same link to email as we do on the dashboard). 

We need to make sure we have final decisions about all possible options for selecting multi-states and a design to represent those decisions. 

Current help text - will need to be updated. 
Current Affiliations
This list includes all states you are currently affiliated with. Including requests and states you are denied/revoked access to. To make updates to these affiliations, reach out to your State Administrator.

Current implementation: 
![Screen Shot 2021-05-25 at 7.49.14 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/03ee083c-3365-45e6-98fa-245863d1ef45)

### This task is done when…

- [x] We determine if all statuses should be shown, aka should we show revoked states - yes
We definitely want to show pending and approved states here. 
- [x] We determine if states can self revoke, aka remove an affiliation on this page - states cannot self-manage, they will need to contact their state admin. 
- [x] We determine if we should match the status colors with the icon colors on the corresponding dashboards.  Green = approved  | Yellow = pending | Red = Revoked
That isn't a final solution as just showing a status by color doesn't meet 508 standards. 
- [x] Write the help text to let users know what is being shown here. 
- [ ] Include a link to email the state admin in the help text (or multi-state admins) for any states shown
- [x] Designs are created to show these decisions (note - we know of someone with 4 or 5 affiliations) 
- [x] 508 considerations and/or recommendations are reviewed
- [x] designs are shared
- [ ] designs are approved by product

**Comment by akuas** [comment]
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=3771%3A146
@ty I shared this design and other option with Jenn and it looks like we are leaning toward this design of having the non-interactive tags below indicating the different submitted affiliations and their status and have users'  unsubmitted affiliations on top of the field.

**Comment by beparticular** [comment]
@tbolt and @akuas 
I was checking this out and since it's so late, I did a quick view of what experiment 5 would look like after the request is submitted. 

@tbolt let me know what you think about this direction

@akuas I was thinking about the need on this for folks to be able to contact their correct state administrator if they have more than one state. I was wondering if it might be too much for this screen and if there should be a way in an account that you should also be able to quickly contact your state admin for whatever state you're logged into. currently I think the only way you can do that is from a pending approval page. this might end up being another issue for zenhub, so maybe we can quickly discuss in design sync next week

@CSwartzHMA can you take a look at the content on this and

**Comment by akuas** [comment]
This might be tricky to have the state administrator contact for each state, selected. But I will try to see how that design will look for an hour and get back to you @beparticular

**Comment by beparticular** [comment]
@beparticular I think it will be too. I don't think it needs to be part of this ticket, but to be discussed in design sync

**Comment by akuas** [comment]
Okay sounds good. This is something we could figure out later and maybe have a have page with all the contacts we could reference @beparticular

**Comment by tbolt** [comment]
> @tbolt and @akuas
> I was checking this out and since it's so late, I did a quick view of what experiment 5 would look like after the request is submitted.
> 
> @tbolt let me know what you think about this direction
> 

I think it works well. I went back and forth on using the Badge-style for the existing affiliations but I think it makes sense and it's easier to digest vs. having them listed as just text (comma separated I would assume). 

We should update the overall design to accommodate the new direction though. Right now it has multiple "Current Affiliations" sections. Maybe i'm just getting ahead though.
