### ISSUE TITLE
[Feature] Update Assurances and Compliances to be more readable

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3169]
Design task for #2728 

As a reviewer of an APD, I want to see clear answers to the attestations of assurances and compliances on the document I review, to understand if a state is complying with needed regulations, OR I want to see if they did not select an answer a to a question.

**Description and related issues -**
If Assurances and Compliance are unchecked in the builder view, but not text was added as a reason - we'd want something to show in the export view that notates that a choice was not made in the builder view.

**Mockups or link to Figma**
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=3612%3A0

Note: it is ok to play around with the design of the field for the narrative response when "no" is selected.

### Acceptance criteria
|Given|When|Then|
|---|---|---|
|User selected yes in the form|in the export view|display **Yes**|
|User selected no in the form and gave a reason|in the export view|display **No** and the reason|
|User selected no in the form and left the reason blank|in the export view|display **No** and "No explanation given"|
|User did not make a selection in the form|in the export view|display **No response was provided**|

### This task is done when…

This could include:

- [ ] the export view is updated to match the mockup
- [ ] all acceptance criteria are met
- [ ] a storybook is added for this component
- [ ] identify 508 considerations and/or recommendations

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by akuas** [comment]
Hi Knoll, did you find your answer about the padding? I agree that all the responses should be left aligned and there should be slightly less space between 'no' and the explanation.

**Comment by knollfear** [comment]
> Hi Knoll, did you find your answer about the padding? I agree that all the responses should be left aligned and there should be slightly less space between 'no' and the explanation.

I think so.  Please feel free to look at the deployed version and make sure it meets your expectations.
