### ISSUE TITLE
[Bug] Allow user to logout if there are save issues

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3179]
**Description-**
Currently, if there are save issues, a user cannot logout. We need a way to allow users to logout or at least leave the APD if there are save issues.

**Type of Bug-**

- [ ] Accessibility
- [ ] Functional
- [X] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

1. Login with a user that can edit APDs
2. Open an APD
3. Use devtools to turn off the network connection to the page

**Role Affected-**

- [ ] All
- [ ] Federal Admin
- [X] State Admin
- [X] State Staff
- [X] State Contractor
- [ ] System Admin

**Environment-**

- [X] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

**Browser-**

- [X] All
- [ ] Firefox
- [ ] Chrome
- [ ] IE

**Expected results-**
The user should be able to dismiss the modal and log out or go back to the dashboard.

**Actual results-**
The user is stuck.

**Logs or error output/Screenshot/Video-** (at least 1 of these)
![Screen Shot 2021-06-02 at 11.15.13 AM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/7ecbaf6a-478c-4da3-8725-1227939efd59)

**Comment by beparticular** [comment]
Keep an eye on any potential user feedback on this to determine priority.

**Comment by beparticular** [comment]
Quick mock up, added the sign out link for this
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=1891%3A13

@thetif ready for dev

**Comment by thetif** [comment]
created issue #3244
