### ISSUE TITLE
[Bug] Images don't load unless you refresh page after logging in

### ISSUE THREAD

**Issue by knollfear** [CMSgov/eAPD#3180]
**Description-**
Images are not loading if you have signed in without refreshing the page
**Type of Bug-**

- [ ] Accessibility
- [X] Functional
- [ ] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**
Prerequisites: an APD with images.  This is trivial to create if you don't have one.
1. Log in as normal
2. (Optional)Open network console for tracking purposes
3. View an APD with images
4. See that images are displayed as broken
5. confirm 401 (unauthorized) status on image requests
6. confirm that image requests did NOT contain any value for the token (gov.cms.eapd.api-token)
7. refresh page
8. View an APD with images
9. confirm images are present
10. confirm images contain token value
11. logout and repeat

**Role Affected-**

- [X] All
- [ ] Federal Admin
- [ ] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [X] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

**Browser-**

- [X] Firefox
- [X] Chrome
- [ ] IE

**Expected results-**
Images are shown on initial page load
**Actual results-**
Images are only shown if the page has been reloaded after login.
**Related user story/bug-** (if applicable)

**Additional information-** (optional)
I think this is caused by when the axios client is initialized and fed the token.  At the time it happens the token is not yet in scope because the user is logged out and then on a refresh the token is in scope and it happens as expected.
**Logs or error output/Screenshot/Video-** (at least 1 of these)
Available on request.

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by thetif** [comment]
This appears to be working locally and on PRs but not on Staging.
