### ISSUE TITLE
[Design Issue] Create an empty state help diagram for dashboard

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3189]
In order to help folks understand the system faster upon their first visit, we'd like to explore the option of some kind of empty state design, help diagram, or graphic on the dashboard that lets people know what to expect in the system. This would replace the current intro blurb on the dashboard. 

What is the least amount of information we can share here to the greatest benefit? We don't want to overwhelm folks, and most of the system is quickly learnable. Perhaps this help would focus solely on the structure of the eAPD system? 

This might include: 
Create APD (and that you can't edit this)
How APDs are linked
Showing the distinction between APD and Activity
Helping folks know they can add more than one activity
Other information based on what we find in the research synthesis

This task would be further down in priority alongside the dashboard, as we'd need to know what all will be contained in the Create APD screen, what's moving from Activities to the APD level, and how APDs will be linked. 

### This task is done when…

- [ ] determine what help is needed on the dashboard based on further research synthesis
- [ ] 508 considerations and/or recommendations are reviewed
- [ ] designs are created
- [ ] designs are shared
- [ ] designs are approved by product
- [ ] This would not need to be in staging or prod for the presentation, we'd just need the designs

**Comment by beparticular** [comment]
@CSwartzHMA  and @akuas after the fed admin ticket #3263 is done, this is the highest priority as we need this ready before the presentation at MESC on 8/9. 

I'm able to help with this as well, but I would like the two of you to take point on it. thanks!

**Comment by beparticular** [comment]
Notes from design sync: 
Start with a diagram for HITECH, it's easier to start creating something like that for a flow we know
Once that is done, we can expand to include info on the MES expansion 
Both of these would need to be done for the MESC presentation. I'd like to review the work at design sync on 8/4 at the latest. Thx!

**Comment by beparticular** [comment]
Suggestion while reading over the research, put something in this about the executive summary being created for you after you add in all the information in your eAPD.

**Comment by akuas** [comment]
Okay, thats a good point. Will do.

**Comment by akuas** [comment]
@jeromeleecms I decided to rework the [design](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4461%3A29967) a bit after showing you and I think this design might be better because it fits in with the eAPD slide deck design. I also got feedback from @beparticular and got the go-ahead. Lastly, the copy is updated based on CSC's suggestions.

![MESC Help Diagram.png](https://images.zenhubusercontent.com/601acfa212e5437689f6079c/266a81ea-84bf-40c0-bebc-e34535dece38)

**Comment by beparticular** [comment]
Next step - note any changes that need to happen from the MESC feedback. 
Decide what to do after that with this ticket. Do we want to do a version for HITECH, or do we want to wait and test this in the next round of testing.

**Comment by beparticular** [comment]
@jeromeleecms before we do more work on this one, do you want to prioritize something like this for HITECH now, or do you want to wait to bring something like this in with MES expansion ?

**Comment by thetif** [comment]
created dev ticket #3448
