### ISSUE TITLE
[Bug] Remove "Back to Login" on Manage Account page

### ISSUE THREAD

**Issue by tbolt** [CMSgov/eAPD#3194]
**Description-**
The Back to Login link/button was added to the affiliation component but it may not make sense to have it on the manage account page since the assumption is they are already logged in-
![Screen Shot 2021-06-08 at 12.59.23 PM.png](https://images.zenhubusercontent.com/5f43eb2204d6d70d8324232c/e0f12f06-c3be-4c69-97b2-f4cf2e5b6d2a)

**Type of Bug-**

- [ ] Accessibility
- [ ] Functional
- [x] Usability
- [ ] API
- [x] Regression

**Steps to reproduce-**

1. Step
2. Step
3. Step

**Role Affected-**

- [x] All
- [ ] Federal Admin
- [ ] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [x] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

**Browser-**

- [x] Firefox
- [x] Chrome
- [x] IE

**Expected results-**

**Actual results-**

**Related user story/bug-** (if applicable)

**Additional information-** (optional)

**Logs or error output/Screenshot/Video-** (at least 1 of these)

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by beparticular** [comment]
Is it possible to still have it on the Manage Account page before they have chosen an affiliation, so they still have their way out of the page (we don't show log out yet at that point because they aren't fully signed up)? 

And then allow them to use the Manage Account page without the back to log in button once they are fully signup and logged in?

**Comment by tbolt** [comment]
@beparticular yep, I wasn't intending on removing the link when you are in the "onboarding" process. Only when you are logged in (which you would have already have/requested an affiliation)
