### ISSUE TITLE
[Feature/Bug] Temporary fix to make the user aware that things will be broken if there are no FFYs

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3202]
Design task #3136

**Description and related issues -**
If a user unchecks all of the FFY options, then the export view and other data related to the FFY won't show up correctly.

When a user deletes the last FFY, they should see the FFY warning as usual. Then an alert should appear above the FFY checkboxes that says "At least one FFY must be selected to continue with your APD." (see the middle mock up in the Figma below.

If the user ignores this warning and continues on, then we should continue to warn them about this issue in case they are confused when they see strangeness. Show the alert  from the design system (content mocked up in the Figma file) at the top of every page

**Mock ups**
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=3751%3A27887

**What is the goal or purpose of this ticket?**
Inform the user that not having an FFY selected will be bad.

### This task is done when…

This could include:

- [ ] the user it warned about an APD needing an FFY if they do not have any selected

**Comment by beparticular** [comment]
From a Slack convo with Tif, I believe we are leaning toward option 1 in the design ticket as a solution.
