### ISSUE TITLE
[Operations] Add environment variables to circle ci for backend tests

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3213]
We've run into some issues on the API unit tests where they need some environment variables to be passed in so they are available. Add JWT_SECRET, MONGO_URL, MONGO_DATABASE to the backend unit tests command in Circle CI.

### This task is done when...

- [x] create placeholder environment variables in Circle CI for MONGO_URL and MONGO_DATABASE
- [ ] add JWT_SECRET, MONGO_URL, and MONGO_DATABASE

**Comment by cthulhuplus** [comment]
MONGO_URL and MONGO_DATABASE already existed for Preview, created MONGO_URL and MONGO_DATABASE for staging and production
