### ISSUE TITLE
[Feature] Update JWT when user requests an additional state

### ISSUE THREAD

**Issue by knollfear** [CMSgov/eAPD#3214]
- As a user I would like to be able to immediately switch into using eAPD for a state that I just selected.  
**Description and related issues -**
In order to do this, the JWT for the user must be updated and reissued when they request access to a particular state.  THis is only for when the user selects the state, not when the state access gets approved.  

**What is the goal or purpose of this ticket?**
Make it so that a user does not have to refresh the page or worse, log out and log back in when requesting access to a new state.
**Mockups or link to Figma**

### Acceptance criteria

| Given | When | Then |
| ----- | ---- | ---- |
|  a logged in user     | that requests access to a new state     |  the JWT payload is updated to reflect the new state    |

### This task is done when…
a JWT is reissued upon requesting access to a new state.

This could include:

- [ ] a list of changes to be made
- [ ] all acceptance criteria are met
- [ ] the description of what a user might be able to accomplish once this is done
- [ ] identify 508 considerations and/or recommendations
- [ ] any tangible deliverable(s) that need to be created

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by thetif** [comment]
This ticket is OBE now because the account management page and the login page get the user's states directly from the backend instead of from the jwt
