### ISSUE TITLE
Remove any/all react devtools console warnings/errors

### ISSUE THREAD

**Issue by tbolt** [CMSgov/eAPD#3225]
Placeholder ticket to address warnings/errors related to react devtools. Possibly consider a method to check before committing or passing CI/CD.

### This task is done when...

- [ ] criteria 1
- [ ] criteria 2

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by jeromeleecms** [comment]
Created in duplicate. Closing in favor of #3228.
