### ISSUE TITLE
[Operations] Add Cypress tests to the CI pipeline

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3227]
follow on task for #3226

Once there is a script for running Cypress tests in CI mode, add the script to the CI/CD pipeline. These tests do not need to be run every build, possibly just run once a day on staging and PRs?

https://docs.cypress.io/guides/guides/cross-browser-testing#Continuous-Integration-Strategies

### This task is done when...

- [ ] Cypress tests are running in CI pipeline

**Comment by jeromeleecms** [comment]
Need to discuss how frequently to run (per Sprint Planning 09/16)
