### ISSUE TITLE
[Documentation] Update the wiki to reflect authentication changes

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3230]
https://github.com/CMSgov/eAPD/wiki/Development-authentication-and-authorization#Authentication
The authentication documentation is a little out of date now. It needs to be updated to reflect the new authentication flow.

### This task is done when...

- [ ] documentation is updated

**Comment by knollfear** [comment]
I have updated the wiki page, including recreating the mermaid diagram in a way that will allow it to be edited by future users.

**Comment by jeromeleecms** [comment]
@knollfear Is someone assigned to reviewing this? This is the last open issue in the go-live epic.

**Comment by thetif** [comment]
I'm reviewing it right now.

**Comment by thetif** [comment]
Documentation looks good
