### ISSUE TITLE
Design system alerts on log in page for system downtime 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3232]
Follow up issue to #2478

We need to design alerts for the log in screen for when the system is down. 

### This task is done when...

- [ ] What does the expected downtime alert look like on the login screen look like?
- [ ] What does the UNexpected downtime alert look like on the login screen look like?
- [ ] What does the log in error message say when someone tries to log in and the system is down? #3223 dev issue has been created for this and this language was decided on in stand up. 
- [ ] Designs are created and shared
- [ ] Designs are approved by content and product

**Comment by akuas** [comment]
I think if we put an alert in the dashboard, we would have to make it a modal because it requires an action, logging out. I don't think a modal in the login page is necessary, just a simple alert. @beparticular does this issue apply to both expected and unexpected downtime?

**Comment by akuas** [comment]
Below are the designs for an unexpected server error/outage for the login page. I will add the design for the dashboard later.The alert copy is essentially filler text, we can change it as soon we find something better. 
[Unexpected Server Outage](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=3996%3A29116)
[Server Outage Restored](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=3996%3A29405)

**Comment by beparticular** [comment]
I don't think an alert on the dashboard would require an action necessarily. I imagine an alert of this kind would allow folks to log out from the dropdown, and it might be placed in the same space as the FFY alert that we're working on. Thoughts?

**Comment by beparticular** [comment]
Also, chatted with @thetif, we wouldn't be pulling to see if the server is back up, they'd just need to refresh to see if that red alert goes away. cc @akuas

**Comment by akuas** [comment]
Do you mean a dropdown to log out within the alert? Also, I am imaging this alert is not just on the dashboard but on whatever page the user is on when the outage occurs. Is that right?
Okay, I can remove the alert for when the system comes back up.

**Comment by beparticular** [comment]
This is just for the log in screen. What will happen in the system is TBD in 3236.

**Comment by akuas** [comment]
Okay, thanks @beparticular

**Comment by CSwartzHMA** [comment]
Sorry I was not able to join the conversation earlier, so please disregard if this has already been determined, but I did have some thoughts about potential verbiage for the alert:
_The eAPD system is currently unavailable. The support term is aware and working to resolve the issue as quickly as possible. More details and updates, when available, will be posted to the eAPD User Support Slack channel._ 

We could possibly even link directly to the channel.

**Comment by akuas** [comment]
Hi Caryn, thanks for the feedback. Do you think we should also add to this copy you posted with 'try again later' because not everyone would want to check the slack after the system is down. @CSwartzHMA

**Comment by CSwartzHMA** [comment]
@akuas I personally think that just adds to frustration unless we can offer a time frame in which they should be able to log in again. Some will just keep trying again on their own, but I don't think we should tell them to.

**Comment by akuas** [comment]
Okay, thanks that is good to know. @CSwartzHMA

**Comment by akuas** [comment]
@beparticular Can you please look at the design for the login and dashboard and let me know what you think?
[Dashboard: Unexpected System Downtime](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4022%3A28315)
[Login: Unexpected System Downtime](https://cmsgov.slack.com/archives/C01BG81MG0Y/p1624471031005200)

**Comment by beparticular** [comment]
@akuas I'm moving the dashboard design work to issue #3236 so this can just be the log in design work

**Comment by CSwartzHMA** [comment]
@akuas I love it! Just a small typo - term should be team.

**Comment by beparticular** [comment]
FYI, I was chatting with Tif about this and we wouldn't necessarily know that the system is down the first time someone tries to log in and can't. Let's keep the language very simple as we talked about in parking lot yesterday for now. #3223 
"The eAPD system is down, try again later."

If we find out any additional details about when we can learn when the system is down, we can address that in #3236 

I'm going to close this and put the updated mock up on #3223 as these tickets with almost the same number are getting confusing.
