### ISSUE TITLE
[Feature] Create JWT with distant expiration dates to use for testing

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3239]
**Description and related issues -**
Some load tests and end-to-end tests would be better tested using shared JWT tokens so that we can bypass Okta. Please create some JWTs for the different user types in the system.

### This task is done when…
- [ ] Document how to create these JWTs, how to update them, and where they are stored
- [ ] Add the users to the affiliation seeder so they will have roles
- [ ] Create JWTs with an expiration date at least a year out for the following user types:
    - [ ] Federal Admin
    - [ ] State Admin
    - [ ] State Staff
    - [ ] State Contractor
    - [ ] Sys Admin
    - [ ] requested role
    - [ ] denied role
    - [ ] revoked role
    - [ ] no role

**Comment by knollfear** [comment]
File will be stored in seeds/test/tokens.json.  To read the file from within the seed directory you can use this snippet:

`
  const rawdata = fs.readFileSync(`${__dirname  }/../test/tokens.json`);
  const tokens = JSON.parse(rawdata);
// log a single token by username
  console.log(tokens.deniedrole)
`

**Comment by thetif** [comment]
merged
