### ISSUE TITLE
[Bug] Information not being filed in for some users

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3242]
**Description-**
I am not seeing the database get updated with the user's information when they login. It's also displaying empty information for the user in the federal admin

**Type of Bug-**

- [ ] Accessibility
- [X] Functional
- [ ] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

1. log in as fedadmin
2. navigate to the Federal Admin portal
3. look at norole user in the requested tab
4. log out
5. log back in as norole
6. log out
7. log in again as fedamin
8. navigation to the Federal Admin portal
9. look at norole in the requested tab

**Role Affected-**

- [X] All
- [ ] Federal Admin
- [ ] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [X] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

**Browser-**

- [X] All
- [ ] Firefox
- [ ] Chrome
- [ ] IE

**Expected results-**
The user's information should be updated in the okta_users table whenever they login.

**Actual results-**
The data is not being updated when the user logs in.

**Logs or error output/Screenshot/Video-** (at least 1 of these)
![Screen Shot 2021-07-02 at 12.50.54 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/ca4400b7-cb94-45e0-b74b-b8a2763cf59e)

![Screen Shot 2021-07-02 at 1.04.21 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/dc42e415-0669-4662-b487-0c70da9c31d1)

**Comment by tbolt** [comment]
Clarification for this: We don't have a "Federal Admin" portal yet. Since we added "Federal" as a state, if you go to the "Federal Admin" panel, you are really going to the "State Admin" panel with the State = Federal.
