### ISSUE TITLE
Resolve warning about the Xmark icon missing

### ISSUE THREAD

**Issue by tbolt** [CMSgov/eAPD#3252]
Seeing an error about `faXmark` missing:

> web_1  | WARNING in ./src/components/Icons.js 30:10-17
web_1  | "export 'faXmark' was not found in '@fortawesome/free-solid-svg-icons'

We should investigate this and make sure we're not missing the icon. If so, we should find out what happened to it and replace it.

### This task is done when...

- [ ] Icon is verified to still be in place and if not, replace it
- [ ] Warning is no longer present

**Comment by thetif** [comment]
resolved with #3272
