### ISSUE TITLE
[Feature] Create endpoint to add authorization record to the State Admin Certification Table

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3257]
**Description and related issues -**
We need an endpoint for adding certifications to the State Admin Certification Table. 

Database design
![image.png](https://images.zenhubusercontent.com/5f43eb2204d6d70d8324232c/b97ec256-8e6b-4e5a-afe4-b64e5c68a2cf)

The endpoint **should**:
- be restricted to 'edit-state-certification' permission
- endpoint should handle the [latest form design](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=5386%3A34533) which includes:
  - State employee to be delegated eAPD State Administrator
  - State
  - State employee email address
  - State employee phone number
  - Name of person who completed the delegation letter
  - Title of the person who completed the delegation letter
  - Email address of the person who completed the delegation letter
  - Signature (printed name on the delegation letter)
  - File URL of the letter
- set the certification date to today and the expiration to a year from today
- update the `state_admin_certifications_audit` table to record the id of the record that was changed in the `state_admin_certification` table

### Acceptance criteria

| Given | When | Then |
| ----- | ---- | ---- |
| a user with  'edit-state-certification' permission  | posting valid data | return 200 |
| a user with  'edit-state-certification' permission | posting invalid data | return 400 |
| user without  'edit-state-certification' permission | posting any kind of data | return 403 |
| not a logged in user | posting any kind of data | return 401 |

### This task is done when…

- [ ] all the requirements are met
- [ ] all acceptance criteria are met

**Comment by tbolt** [comment]
@thetif Would we want to add a new activity `add-state-certification` to make this activity-based vs. role-based? I've been working towards the role-based check but happy to change course.
