### ISSUE TITLE
[Feature] Create audit table for affiliations and create an expiration date for affiliations

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3262]
**Description and related issues -**
1. Create a table called auth_affiliation_audit, it should store affiliation_id, change_date, changed_by (oktaUser), new_role_id, original_role_id, original_status and new_status
3. Update the /states/:stateId/affiliations/:id end point so that when a user is approved/revoked/denied, it adds a row to the auth_affiliations_audit table to record the change.

### This task is done when…

- [ ] there is an audit table that records every time an affiliation is changed
- [ ] the affiliation table no longer has updated_at or updated_by

**Comment by tbolt** [comment]
I believe point #3 was completed in #3298

**Comment by thetif** [comment]
yes, just took that point out
