### ISSUE TITLE
[Design Issue] Design a way for users to search and filter users in the state and fed admin tables

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3269]
Create a way for users to search and filter users in the Admin tables.

Related #3263

### This task is done when…

- [ ] any acceptance criteria (not process oriented, requirements of feature)
- [ ] designs are created, considering that the Federal Admin table are slightly different from the State Admin table, and that it still needs to use the design system table which does not have these features
- [ ] 508 considerations and/or recommendations are reviewed
- [x] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

**Comment by akuas** [comment]
Is there an expectation with this issue to design the federal admin table with the filter?

**Comment by akuas** [comment]
Below are the designs for the filters. The dropdown would behave like the cms design system and the search would display selections as filter chips. 
[Federal Admin Panel](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4445%3A29711)
For the state admin panel (we can workshop that name), all tab all the filters will be enabled, for the requests and delegated admin, the role and delegated user filters would be disabled
[State Admin Panel](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4251%3A29520)
[State Admin Panel with Filter Chip](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4305%3A30083)

**Comment by beparticular** [comment]
These filters are shown in the designs for the fed admin panel. We'll be adding a dev ticket for this ticket through #3263
