### ISSUE TITLE
[Bug] IE doesn't handle return from /heartbeat correctly

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3278]
**Description-**
When you try to log in to the system using IE11, it misinterprets the return from the /heartbeat endpoint. The endpoint correctly returns 204, but the page says it's down and won't let the user log in. IE11 must be in the yellow browsers, so that you can see this issue.

**Type of Bug-**

- [ ] Accessibility
- [X] Functional
- [ ] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

1. open the browser using IE11
2. agree to the consent message
3. see that there is an error message saying the backend is down

**Role Affected-**

- [X] All
- [ ] Federal Admin
- [ ] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [X] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

**Browser-**

- [ ] Firefox
- [ ] Chrome
- [X] IE

**Expected results-**
User should be able to login.

**Actual results-**
User is prevented from trying to login.

**Comment by jeromeleecms** [comment]
IE is a red browser. We will not support this unless told to, but will require additional things to fix as well.
