### ISSUE TITLE
Update Splunk Reporting Mechanisms

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#3294]
cloud.cms.gov offers guidance that differs from how we are reporting to Splunk. Since there seems to be issues with all of our logs making it to Splunk, I am going to update the way we are reporting to be inline with the guidance provided by cloud.cms.gov.

### This task is done when...

- [ ] Logs are being reported in Splunk

**Comment by cthulhuplus** [comment]
Created this ticket to request our production log groups get added to Splunk ingestion:
https://jiraent.cms.gov/browse/CLDSPT-15053

**Comment by jeromeleecms** [comment]
Will work on getting access to Splunk too - thanks for your work on this!
