### ISSUE TITLE
[Design Issue] Allow naming of HITECH APDs

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3308]
Currently our APDs all have the same name. We need to add a field to the APD Overview to allow for the user to name an APD.  

The rest of the information on the Dashboard would remain the same for now. 

When the issues moves to dev, check in the system for any other places the name might appear for QA purposes. 

### This task is done when…

- [x] designs are created, taking into consideration long names, weird names (special characters, etc), and/or the export view if applicable
- [x] 508 considerations and/or recommendations are reviewed
- [x] designs are shared
- [x] designs are approved by product

**Comment by akuas** [comment]
Below is the design for naming APDs in HITECH. This could be implemented in two phases or together, but I was imagining a field titled APD name in the APD Overview, which would be the MVP and an editable text field in the header of each page, kind of like the design for google docs.
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=1598%3A20003

**Comment by beparticular** [comment]
I was having trouble with the Figma link. This one should point to it, I hope. 
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4509%3A30771

I think for MVP, we add the APD Name field into the APD Overview, and when the APD Name moves into the Create APD page, once we have that option, the editing the name will work like it's shown here. That's cool. 

@jeromeleecms any feedback before we move this to dev?

**Comment by beparticular** [comment]
I spoke with @thetif  and it's totally fine to allow for editing the APD name on the top of the page. 

So we can do this as it's shown in Figma here
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4509%3A30771


1) Add APD Name field on the ADP Overview page 
2) Change the header design of the APD Name and the designation of HITECH IAPD | FFY XXXX - XXXX as shown in Figma
3) When the user types in the APD Name, the top of the page will populate, just like it does when the name of an Activity is added or edit on the Activities page. 
![Screen Shot 2021-08-12 at 6.57.43 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/9aa45128-0e5f-4d19-9810-e75cb1a81d56)
4) Allow for editing the APD Name at the top of each page where the APD Name is currently shown. 

@akuas is there anything else that needs to be added to this list ?

@jeromeleecms can you review and give the ok to move this to dev? thanks!

**Comment by jeromeleecms** [comment]
This is good to go on my end - looks consistent with what we discussed.

**Comment by beparticular** [comment]
@thetif this is ready for dev, details in the comment above Jerome's

**Comment by thetif** [comment]
created dev ticket #3405
