### ISSUE TITLE
[Design Issue] Define current goals of validation and lock on submit features

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3309]
We've talked about what the validation and lock on submit features are in the past. Let's revisit those and set the goals for this part of Cake Layer 2.1. 

Existing related validation issues
#3038
#2346
#2405
https://app.mural.co/t/cmsmural6360/m/eapd5455/1588781600846/74a95a2db5d0b3e72c73cc7a96e6b501f40dcbd1

Topics of discussion: 
Is our list of field level validations still ok and current
Should we go ahead and implement those
How do we want to validate that all required fields are complete before submission
What consideration exist if folks can skip a field and submit
What consideration exist around required fields (field level or in a review flow)

### This task is done when…

- [x] a conversation or workshop is held to determine the current goals for these features 
- [ ] goals are defined by dev, design, product for the scope of our validation and lock on submit feature work

**Comment by beparticular** [comment]
@jeromeleecms do you think we got far enough with the validation and submit conversations to consider this done?

**Comment by jeromeleecms** [comment]
Yes, let's close this and spin up the appropriate tickets to track the next steps.
