### ISSUE TITLE
[Design Issue] Revisit editing or viewing Create New APD screens

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3319]
Initially when we designed the Create new APD screens, we did not include a way to view or edit the screen after the "create APD" button has been clicked and an APD created as we needed this information to be locked down once an APD is created.

As we look to add more to this page, like business modules, we need to reconsider this. In our last round of research, we were not able to conclude that users wouldn't need to see this screen, change a business module, or to change their options before they start working on an APD. They quickly passed over this screen, and we assume too fast to notice that they wouldn't be able to return to it. 

While we would still like to lock down the information chosen after information has been added to an APD, there might be times where the create screen does need to be viewed or edited before things are added. This could be something from the dashboard like a fancy pop up to view that opens to a page. But I'm not sure what our technical limitations are with a one page application. 

### This task is done when…

- [ ] designs are created, taking into consideration multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] 508 considerations and/or recommendations are reviewed
- [ ] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by jeromeleecms** [comment]
Close this in favor of 3687 and will revisit this when we move to a broader MES expansion
