### ISSUE TITLE
Add inline validation for Budget and FFP

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3355]
Add inline validation for Budget and FFP

*This validation will happen on the table not in the error check at the end. 

|Field|Content|Consideration|
|---|---|---|
|Federal-State Split|Select a federal-state split.|The drop down isn't automatically selected, the backend does automatically select 100-0 to avoid math issues. |
|Estimated Quarterly Expenditure Table|The quarterly percentages Subtotal should not exceed 100% |Error message: Update the quarterly percentages so that the subtotal does not exceed 100%.<br/><br/>Location: Error text would be under table in any table fields with errors (see screenshot below)|

Picture for table is below (previous picture here was the wrong table)

### This task is done when...

- [ ] Other funding amount has inline validation
- [ ] Estimated Quarterly Expenditure Table has inline validation

**Comment by jeromeleecms** [comment]
![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/0f2290de-c6ce-45c2-aa4c-b836e9e0c9bf)

Here's a screenshot of the budget table for this section. The screen shot in the issue description show EH/EP payments which appears in the proposed budget. The error message would appear as described above.

**Comment by tbolt** [comment]
Updates based on standup
* Fed-State Split will be part of admin check
* Estimated Quarterly Expenditure table not part of admin check
  * Update to validate that, once all fields are entered (per row), the subtotal = 100% (not exceeds)
  * Update the language to reflect the column header (Ex. "State Staff and Expenses"). Call out the specific row that the error is referring to.
