### ISSUE TITLE
[Content Issue] Change help text on Executive Summary

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3364]
### Quick text change

**Current Text**:
"Review this executive summary based on the activity details provided. Program budget tables are automatically included for review."

**Requested Change**:
Based on the content provided in the APD, this Executive Summary is automatically generated. It is structured so the State Officer can quickly review key takeaways contained in the APD to begin the official review.

![Screen Shot 2021-08-05 at 1.44.08 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/642b298c-1c8a-4ee2-bc11-1f9045dcf82b)

**Quick reason why**:
We need to provide more context around how the executive summary is created, and from what information.

**Comment by beparticular** [comment]
Note: will add new content to this issue once we decide on the content in #3189

**Comment by beparticular** [comment]
@jeromeleecms I pulled this language out from the similar language we created in #3189. 
Any objections or thoughts here before I move this on to dev?

**Comment by beparticular** [comment]
@jeromeleecms bumping this request up for review

**Comment by jeromeleecms** [comment]
How about: "This Executive Summary is automatically generated from the short descriptions you provided in each activity. It is structured in a way so your State Officer can quickly assess the APD when starting their review. When the APD is exported, the Executive Summary move to the beginning of the exported file."

This way the user knows (1) where the information was pulled from so they know where to fix it and (2) knows that the executive summary will appear at the beginning of any exports so it aligns with their traditional view of an APD.

Open to revisions/thoughts.

**Comment by beparticular** [comment]
"This Executive Summary is automatically generated from the short descriptions you provided throughout the APD and activities. It is structured in a way so your State Officer can quickly assess the APD when starting their review. When the APD is exported, the Executive Summary will appear at the beginning of the exported PDF."

@jeromeleecms ?

**Comment by jeromeleecms** [comment]
Looks good to me!

**Comment by beparticular** [comment]
@thetif this is ready for dev with the comment above Jerome's being the final content.

**Comment by thetif** [comment]
created development ticket #3429
