### ISSUE TITLE
Plan for a round of Validation Research

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3369]
In addition to getting feedback at MESC on the Required Fields Check at MESC, we'd like to create a fully clickable prototype in Figma for people to run through the Check to see if it makes sense to them as a concept AND that the usability is strong. 

Consideration for prototype - the "exit check" link is at the end of the help drawer. If someone checks too early and has a ton of issues, they won't be able to exit easily. Think about this design again.  

### This task is done when...

- [x] The prototype has been completed
- [x] A research plan is created, shared, and approved by product/team (Consider the OIT HCD format of two columns, one for questions, one for goals, assumptions, things we want to learn, or possibly for note taking)
- [x] Tickets are created for Recruiting, Conducting, and Analyzing Research

**Comment by beparticular** [comment]
Testing Figma link https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4678%3A32149

**Comment by thetif** [comment]
Testing Figma link https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4678%3A32149

**Comment by beparticular** [comment]
Research plan link 
https://docs.google.com/document/d/1HaNoSduMMO3i0sujScPHzPKQzTZyEJVez14u-3R4t4k/edit#
