### ISSUE TITLE
[Bug] Error on adding a new affiliation

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3373]
**Description-**

Seeing an error on adding new affiliations that makes the user get stuck on the Thank you page.

**Type of Bug-**

- [ ] Accessibility
- [ ] Functional
- [X] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

1. log in with norole
2. open a new tab and log in as norole
3. add a state on the original tab 
4. click submit on the original tab
5. switch to the new tab and click "Back to login" (proceeding as normal and choosing a state but then logging out is fine too)
4. click Ok on the Thank You page on the original tab

**Role Affected-**

- [x] All
- [ ] Federal Admin
- [ ] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [ ] All
- [X] Development
- [ ] Staging
- [ ] Production

**Browser-**

- [ ] Firefox
- [X] Chrome
- [ ] IE

**Expected results-**
Should be taken to the Pending Dashboard

**Actual results-**
Nothing happens

**Logs or error output/Screenshot/Video-** (at least 1 of these)

![Screen Shot 2021-08-04 at 3.39.51 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/b3750e8c-5460-42f1-a9f8-a790ca38ba02)

**Comment by knollfear** [comment]
This seems to be related to the fact that sessions are shared across browser tabs.  Using the original repro steps I was not able to reproduce this issue.  However, using the steps provided and use 2 tabs I was able to duplicate the exact error message.  At this time coordinating between 2 tab states is probably beyond what we can support.  If this becomes a bigger issue down the road we can readdress this.
