### ISSUE TITLE
[Bug] Budget for FFY table is displaying wrong in the export view

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3388]
**Description-**
The Budget for FFY table was updated in the builder view but not in the export view. We need to separate the tables a little and add Activity Total Cost header to the table at the bottom of the Budget for FFY table.

It should look like web/src/containers/activity/CostAllocation/OtherFunding.js line 83

Updates should be make to web/src/containers/activity/CostAllocateFFP.js line 138

**Type of Bug-**

- [ ] Accessibility
- [X] Functional
- [ ] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

1. login and open an APD
2. view an Activity Budget and FFP page
3. look at the Budget for FFY tables
4. go to Export view
5. look at the Budget for FFY tables

**Role Affected-**

- [ ] All
- [ ] Federal Admin
- [X] State Admin
- [X] State Staff
- [X] State Contractor
- [ ] System Admin

**Environment-**

- [X] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

**Browser-**

- [X] All
- [ ] Firefox
- [ ] Chrome
- [ ] IE

**Expected results-**
![Screen Shot 2021-08-10 at 5.26.11 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/9c5c2f99-31e5-4c35-a6f4-5df566149877)

**Actual results-**
![Screen Shot 2021-08-10 at 4.47.53 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/a5b4a5d8-3113-425a-9373-63a1249a9a70)

**Comment by jeromeleecms** [comment]
This looks good.
