### ISSUE TITLE
[Design Issue] Create a flow for when a state admin letter is expiring (state admin panel)

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3402]
A ticket exists for devs to add an expiring tab to state admin panel. This is not the same thing. 

All state admin letters expire in June of each year. We need to create a flow and make sure we understand and define all parts of this process. 

### How does auth work around this? 
Someone will be considered expired If job code isn’t active (okta checks job codes) 
Someone will be considered expired If their delegation form is expired (date entered in admin panel, but they generally expire each June. 
Users will get a notice from EUA that their job code and access will expire. They will need to update this annual. 
Need to determine - will the EUA dates of expiration potentially cause multiple expirations through the year? 

### UI
In the state admin panel that federal admins will use, we do not need an expiring tab. A filter will exist for looking at which delegated state admins have expired on the Delegated State Admins tab. Not on requests/matches/all tabs. 

### Administrative/Design/Tech Decisions
Admin - We will need to determine how we will alert State Medicaid Directors (or equivalent) that they need to update their form each year. 

Admin - When they are expired, they are expired - define what this means. 

Tech - In the database, how do we track those records. what is the mechanism to show the change, track the change?
 
*I think this is a catalyst for needing an email option to email admins and other folks. How we can do this may be something we can find out in dev group chats across MACBIS. 

### This task is done when…

- [ ] any acceptance criteria (not process oriented, requirements of feature)
- [ ] document for user instructions that they need to renew code
- [ ] designs are created, taking into consideration multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] 508 considerations and/or recommendations are reviewed
- [ ] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by jeromeleecms** [comment]
Closing this as any unaddressed content is been added to #3446.
