### ISSUE TITLE
[Bug] Activity quarter table bug across multiple activities 

### ISSUE THREAD

**Issue by mirano-darren** [CMSgov/eAPD#3419]
**Description-**
When filling out the quarter table for the Budget and FFP section on an activity. If you go **directly** to the Budget and FFP section on another activity, the values entered will appear in that activities quarter table.
**Type of Bug-**

- [ ] Accessibility
- [x] Functional
- [ ] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

1. Create two activities
2. Go to the Budget and FFP page of activity 1
3. Fill in the quarter budget table
4. Go directly to the 2nd activities Budget and FFP page
5. Quarter table should have the values entered in the 1st activity

**Role Affected-**

- [ ] All
- [ ] Federal Admin
- [ ] State Admin
- [x] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [x] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

**Browser-**

- [ ] Firefox
- [x] Chrome
- [ ] IE

**Expected results-**
Quarter table in the 2nd activity should have blank values
**Actual results-**
Quarter table has values entered in on the 1st activity

**Additional information-** (optional)
If you delete the values in the 2nd activity, they are also deleted in the first activity
**Logs or error output/Screenshot/Video-** (at least 1 of these)
This is what the 2nd activity table looks like
![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/fbc130ec-8a26-4cd7-b29e-fea1507cea02)

**Comment by beparticular** [comment]
Could be related to https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/cmsgov/eapd/2385

**Comment by beparticular** [comment]
Also https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/cmsgov/eapd/2421
