### ISSUE TITLE
[Design Issue] Add a cancel button to the sections that have only a done button

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3433]
In the eAPD system we have sections where multiple entries can be added for one type of item, e.g. Milestones, or Key Personnel. Currently when an entry is started, it is automatically added to the APD. Clicking done is the only way out, but it doesn't cancel anything out. 

We need to add a cancel button to the sections that have a done button that automatically adds an entry, so that people can start to add an entry, but cancel out if they don't want to add it, or don't want to save it. 

As part of this change, the fields inside the entry need to be required. 
(look at each place we need to do this to make sure there aren't any anomalies with what should be required) 
(create mock ups to show these examples - putting a large on this since we need to make multiple mock ups) 

Sections that have this pattern of enter a section, add information, click done to add an entry. 
- Primary Point of Contact (Key Personnel)
- Outcome (metrics not required) 
- Milestone
- State Staff
- State expenses
- Private Contractors (also include moving total fields when yes is selected) 

### This task is done when…

- [ ] any acceptance criteria (not process oriented, requirements of feature)
- [ ] designs are created, taking into consideration multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] 508 considerations and/or recommendations are reviewed
- [ ] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

**Comment by akuas** [comment]
Primary Point of Contact (Key Personnel)
APD Point of Contact and Key Personnel currently has an interaction that differs from our usual pattern. The help text is different in the default unanswered field vs. answered field. For this field, I would recommend we have a toggle for Key personnel to indicate one of the key personnel listed is the primary point of contact, but that is not within the scope of the ticket. In the meantime, we can present an alert, after the error check, indicating at least one key personnel is required, if the field has not been answered at all. If Primary Point of Contact is partially answered, we can have an inline validation for each field within the dependency that is unanswered. 
[Primary Point of Contact Expanded](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=5383%3A34045)
[Primary Point of Contact Unanswered](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=5548%3A36997)
[Key Personnel Unanswered or Primary Point of Contact Partially Answered](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=5548%3A37347)

Milestone
Milestones operates like expected. If there are no milestones and the error check is used, an alert would appear and all the contents of the milestone are required.
[Milestone Expanded](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=3440%3A7951)

State Staff
Most fields are optional in the system with the exception of the cost fields. If you not answer the personnel field, once you select the 'done' button, the personnel title would be "Personnel title not specified". If you do not answer the fields related to costs, they would remain at $0.
But if the fields Costs with Benefits and Number of FTEs are dependent on each other. So, Number of FTEs should be required if you fill out Costs with Benefits and vice versa for the total calculation to work.
[State Staff (expanded)](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=5548%3A38296)


State Expenses
All fields are required within state expenses. 
[State expenses (expanded)](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=5548%3A38296)

Private Contractor Costs
All of the fields are optional but the field this is an hourly resource is already populated with 'no' selected. The fields on costs are dependent on each other however. You cannot calculate the total costs for a ffy if the number of hours and hourly rate is not answered.

**Comment by jeromeleecms** [comment]
Couple questions:
1) When does the validation error appear? Is it only on the check or is it when the user exits the field?
2) For the Private contractor costs, wasn't the "Yes/No" prompt tied to the "This is an hourly resource?" vs. if there are private contractor costs? Were we moving the "Yes/No" prompt for the hourly resource to Yes first and then No?

**Comment by akuas** [comment]
@jeromeleecms 
1. The validation error appears when the user starts the error check and it will stay there until the unanswered fields are complete.
2. I will need to come back to you on the private contractor costs. I'll ask Jenn.

**Comment by akuas** [comment]
@jeromeleecms the yes/no question refers to the hourly resource question. I will revise the design then.

**Comment by akuas** [comment]
@jeromeleecms @beparticular Can you please take a look at this ticket. Please let me know if anything needs clarification.

**Comment by akuas** [comment]
@beparticular Just changed the order of the attestation options to 'yes' first.

**Comment by thetif** [comment]
Created dev tickets #3491, #3493, #3494, #3495, #3496, #3497, #3498, #3499
