### ISSUE TITLE
[Feature] Create e2e tests for Proposed Budget for filled APD

### ISSUE THREAD

**Issue by chris-miraflor** [CMSgov/eAPD#3438]
**Description and related issues -**
Using the filled out APD created in #3326 - #3333, write tests for checking the proposed budget for values previously entered in the activities page.

### This task is done when…

- [ ] should have input values in Proposed Budget
  - [ ] should have input values in Summary Budget By Activity with correct info for each FFY
    - [ ] should display the Combined Activity Costs
      - [ ] should display values for HIT (FFY 2021)
        - [ ] verify that State Staff Total is $488,590
        - [ ] verify that Other State Expenses Total is $74,435
        - [ ] verify that Private Contractor Total is $70,487
        - [ ] verify that HIT Total is $633,512
      - [ ] should display values for HIE and MMIS
        - [ ] verify that State Staff Total is $0
        - [ ] verify that Other State Expenses Total is $0
        - [ ] verify that Private Contractor Total is $0
        - [ ] verify that (HIE|MMIS) Total is $0
      - [ ] verify that Total Computable Medicaid Cost is $0
    - [ ] should display Activity Breakdown
      - [ ] should display values for each type
        - [ ] verify that input staff and other expenses are correct
      - [ ] verify that Total Computable Medicaid Cost is $633,512
  - [ ] should have input values in Summary Budget Table
    - [ ] should display the breakdown by payment vehicle
      - [ ] should display breakdown FFY 
      - [ ] should display Activities Totals (reusable for each FFY and Total)
  - [ ] should have input values in  Quarterly Federal Share
    - [ ] should have HIT and HIE table
      - [ ] should display FFY table with correct info for each FFY
      - [ ] should display Total Table with previous budgets added together
    - [ ] should have MMIS table
      - [ ] should display FFY table with correct info for each FFY
      - [ ] should display Total Table with previous values added together
  - [ ] should have input values in Estimated Quarterly Incentive Payments
    - [ ] should display FFY table with correct info for each FFY
      - [ ] should display EH information
      - [ ] should display EP information
- [ ] should have input values for Proposed Budget in export view
  - [ ] should have input values in Summary Budget By Activity with correct info for each FFY
    - [ ] should display the Combined Activity Costs
      - [ ] should display values for each payment vehicle (reusable for each HIT, HIE, and MMIS)
    - [ ] should display Activity Breakdown
      - [ ] should display values for each type (reusable for each State staff, Other state expenses, Private contractor)
  - [ ] should have input values in Summary Budget Table
    - [ ] should display the breakdown by payment vehicle (reusable for each HIT, HIE, MMIS)
      - [ ] should display breakdown FFY (reusable for each FFY and Total)
      - [ ] should display Activities Totals (reusable for each FFY and Total)
  - [ ] should have input values in  Quarterly Federal Share
    - [ ] should have HIT and HIE table
      - [ ] should display FFY table with correct info for each FFY
      - [ ] should display Total Table with previous values added together
    - [ ] should have MMIS table
      - [ ] should display FFY table with correct info for each FFY
      - [ ] should display Total Table with previous values added together
  - [ ] should have input values in Estimated Quarterly Incentive Payments
    - [ ] should display FFY table with correct info for each FFY
      - [ ] should display EH information
      - [ ] should display EP information

**Comment by thetif** [comment]
resolved as part of #3604
