### ISSUE TITLE
Address any issues surrounding state admins June 30th expiration

### ISSUE THREAD

**Issue by tbolt** [CMSgov/eAPD#3446]
Update: Based on Aug 30th DevSync the best course of action determined is to record the fiscal year. 

Merging Content from #3402

Recap of the business process:
* EUA job codes expire after one year and are recertified by the user through EUA
* eAPD team sent out certification letters to each state to designate a state admin
* Each certification received this year is valid until June 30th 2022
  * This is stated in the document
  * The system is adding this expiration date in the database when a State Admin is "Approved" in the system by a Federal Admin
* Prior to June 30th 2022, eAPD team will re-send certification letters to re-designate a state admin for the following year ( July 1st 2022 - June 30th 2023 )
* Repeat each year 
 
Concerns:
* Currently(or at least coded in ticket #3298) when a State Admin is "Approved" in the system we set their expiration to June 30th of the following year _regardless of when they are Approved_ in the system
  * We are banking on receiving all certifications + doing all the approvals in a specific time window (June - December 31st) 
* The designation letter doesn't have a time-period associated with it
* What is the process for alerting State Medicaid Directors and/or state admins when they need to update the form
* There isn't a way to document the associated time-frame that any given certification letter is tied to

Possible Options:
* Have the system _only_ set the expiration the following year if it is "entered in the system" (ie. a State Admin is "Approved" in the system) July 1st - Dec 31st. The drawback of this is a Federal Admin is restricted from doing Approvals in June. They would have to hold the certification letters until July to enter them. Plus if they're not entered _on_ July 1st, the State Admins will have expired. 
* Have a time period associated when an "Approval" happens in the system (and possibly include this in the delegation letter). 

So if that approval happens January 1st 2021, they will expire June 30th 2022, which is unintended. 

### This task is done when...

- [ ] Above concerns are addressed
- [ ] Solution outlined or additional tickets created

**Comment by jeromeleecms** [comment]
Newsletter will provide instructions on how to recertify their eAPD Admin accounts. Will continue to work with Caryn on this.

**Comment by jeromeleecms** [comment]
@CSwartzHMA Anything else you think we need to address with this? We communicated out the expiration and steps to fix it. It seems like we'll have to troubleshoot issues as they come up - I'm ready to close this if there is nothing else.

**Comment by jeromeleecms** [comment]
@thetif @tbolt For this one, is the explanation for the process for expiration accurate? We did have one user that is authorized for FFY 2022 that had an expiration beyond the 06/30 date.

**Comment by tbolt** [comment]
@jeromeleecms I don't think so. I think this ticket was written before we made the year an option as part of the admin letter. If a user was authorized for FFY 2022 but not FFY 2023, they should be expired and unable to login starting July 1st 2022.

**Comment by jeromeleecms** [comment]
Let's keep this as certification due by June, and the expiration aligns more closely to the end of the FFY.
