### ISSUE TITLE
[Feature] Create HITECH help diagram

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3448]
**Description and related issues -**
Design ticket #3189
Create a HITECH help diagram component with the following considerations:
1) This shouldn't be so big that folks can't easily get to their APDs or see their pending status
2) There needs to be a way to close out of this (accordion or close button, I don't really have a preference)
3) The most important thing about this graphic is the distinction between the top and bottom rows, You give us this, we generate this.
4) This should not be a large graphic but broken down into components/code
5) Responsive is only important to a point, we're not designing for folks using the eAPD system on their phone at this time.

**Mockups or link to Figma**
![Screen Shot 2021-08-30 at 2.30.31 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/023bc34f-47db-432c-ad75-7a3d5c18496b)

https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4949%3A31749

### This task is done when…

- [ ] a component has been created to show users on their first login

**Comment by tbolt** [comment]
9/16/2021- The branch `tbolt/3448-help-guide` has work in progress.

**Comment by beparticular** [comment]
I think we've progressed beyond needing this. The content may be useful in the future if we want to write up some additional help content.
