### ISSUE TITLE
[Design Issue] Design needs for multi-editing 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3458]
Need to create designs to show that someone is editing an APD

Let's show what this would look like:
On the dashboard
On the page or section
Not in the header
Not at the field level

Let's show these variations: 
That SOMEONE is editing
Or that a specific person is editing - by email or name

Consider doing a prototype/quick usability test around this too. 

### This task is done when…

- [ ] designs are created, taking into consideration multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] 508 considerations and/or recommendations are reviewed
- [ ] designs are shared
- [ ] designs are approved by product

**Comment by jeromeleecms** [comment]
Review #3383 for dev write up on Multi User Editing

**Comment by beparticular** [comment]
@akuas @tbolt I've updated the original ticket per  a conversation with Tiff. 
This will be an interesting accessibility challenge, and wanted to give y'all a heads up on that.
