### ISSUE TITLE
[Feature] Update Outcomes and Metrics

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3494]
**Description and related issues -**

If there are no outcomes and metrics, display this message above the Add outcome button
![Screen Shot 2021-12-07 at 3.35.32 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/08f71120-cc68-4d16-ad35-7635e0c6615a)

Hide alert message, it will be handled in #3350

Update the Metrics form
![Screen Shot 2021-12-07 at 3.37.24 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/c9591244-6188-4932-bd99-dc493ba8488c)

Add in-line validation to the Outcomes and Metrics form. The validation should appear after the user hits the Add (previously Done) button. If there are validation errors, the errors should display, nothing should be saved, and it should stay on the form until the errors are fixed.
![Screen Shot 2021-09-27 at 3.02.39 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/e5d44f4e-e14b-4558-a746-8850dd7c5790)

Update the view of Outcomes and Metrics
![Screen Shot 2021-09-27 at 3.34.51 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/c2ddac2b-a2ce-4f58-8f1c-402a4dff0422)

### This task is done when…
- [x] hide red warning
- [x] add in-line validation
- [ ] update to match Figma

**Comment by jeromeleecms** [comment]
This is done - we are moving a different direction with React Forms and Joi
