### ISSUE TITLE
[Feature] Update Other State Expenses

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3498]
**Description and related issues -**
Remove the red warning when there is no Other State Expenses added, state expenses are not required.

If there are no state expenses, display this message above the Add non-personnel cost button
![Screen Shot 2021-09-27 at 3.19.57 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/b8aae4b9-5618-4173-b65d-7abd1431b11a)

---

Add in-line validation to Other State Expenses. The validation should appear after the user hits the Add (previously Done) button. If there are validation errors, the errors should display, nothing should be saved, and it should stay on the form until the errors are fixed.
![Screen Shot 2021-09-27 at 3.29.19 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/92b80210-d282-4dee-8537-16d8295caf30)

---

Update the view of added Other State Expenses
![Screen Shot 2021-09-27 at 3.28.09 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/56b1a5fd-062d-4d91-bb35-757a2e3fe368)

### This task is done when…
- [ ] add message above the Add non-personnel cost
- [ ] remove red warning
- [ ] add in-line validation
- [ ] update to match Figma

**Comment by tbolt** [comment]
Update: Team decision was made to make the validation for dropdowns trigger onChange instead of the onBlur used in other fields.
