### ISSUE TITLE
[QA] Audit existing QA/QC methodologies

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3500]
Gather information about the current QA/QC processes. Investigate existing automated tests. Determine improvements that need to be made to bring the project inline with Fearless' modern agile testing methodologies.

### This task is done when...
- [ ] improvements and suggestions have been determined and are documented

**Comment by RichFixes** [comment]
**_Overall "coaching" objectives_**

- Assess new tooling and resources 
- Use Dev Sync time to get updated/new information in front of Devs.
- Check in to see who needs more pairing/"insight" in a certain testing area 
- "Discover" on 508 compliance and explore its automation**
- "Discover" Visual Regression/Infrastructure Testing

**Comment by RichFixes** [comment]
Relevant Documentation can be seen here: https://docs.google.com/document/d/1nTVhN_DexADm2qqxNJgw0rJ6SgyPcSqoUEsJ_OLP_5k/edit

**Comment by RichFixes** [comment]
[https://app.zenhub.com/files/113234315/48b44630-9df4-44f0-a5d8-27fe15e05aa1/download](https://app.zenhub.com/files/113234315/48b44630-9df4-44f0-a5d8-27fe15e05aa1/download)

**Comment by jeromeleecms** [comment]
Done - discussed during dev sync on 01/19/2022
