### ISSUE TITLE
[Design Issue] Explore lock and submit design/feature needs 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3507]
This issue can focus solely on what happens after the check is started. Where the error check lives and is kicked off from will be explored in #3537. 

### What has to exist
- wouldn't be able to lockdown an APD with validation errors (can export at any time with validation errors)
- a process for state users to be able to lock down a current APD
  - includes some notation that the APD is locked on the dashboard
  - includes some notation that the APD is locked on the APD  
  - includes a read only view
- a process for state users to be able to "unlock" an APD (even after submitted to make requested edits)
  - if it's unlocked it because a new version 
- Export
  - version numbers must exist on export
  - designation of draft on export 
  - language to designate a version that will be submitted
- Versioning
  - keep a snapshot of submitted documents so we can see what was last submitted (also for audits)
  - copy of version that was exported in our files
  - every export would increase the point number and every submit would increate the whole number (0.1 export, 1.1 - submitted)
  - View the version of submitted documents
- Roles and Permissions
  - who can submit and not submit
  - who can unlock an APD

### What can exist 
- Possibility of the sharepoint integration 
- Possibility of emailing to sharepoint directly 
- Data Integrity
  - ability to track some sort of status (related to sharepoint?)
- Highlight was has changed from the submitted document to the current/new document (in system and on export)
  - Export both the clean version and the track changes version

### What doesn't need to exist
- An integration with onemac at this time 
- Internal track changes view is not as important as CMS view at this time

### This task is done when…

- [ ] designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] 508 considerations and/or recommendations are reviewed
- [ ] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

**Comment by beparticular** [comment]
Next steps after design sync on 11/2:
- Team will Review this issue for any updates
- Product/design will break this down into workable design issues

**Comment by aricka-lewis** [comment]
This has been broken into smaller issues.

**Comment by NAretakis** [comment]
@aricka-lewis should we close this issue and defer to the smaller issues?

**Comment by aricka-lewis** [comment]
Yes, I'll close it @NAretakis
