### ISSUE TITLE
[Feature] Create the animation for error check 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3544]
The animation should exist so it's clear the error check is done. 
This happens when all the fields are complete and is shown in the help drawer. 
Consider 508 compliance, an announcement when the check is complete. 

Figma Link
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=5533%3A38088

### This task is done when…

This could include:

- [ ] the animation is created 
- [ ] the animation is approved by product  
- [ ] identify 508 considerations and/or recommendations
- [ ] any tangible deliverable(s) that need to be created

**Comment by tbolt** [comment]
This is resolved in https://github.com/CMSgov/eAPD/pull/4055
