### ISSUE TITLE
[Feature] Key State Personnel - make yes/no checkbox fields consistent

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3545]
Based on Design Task #3487

**Description and related issues -**
Change the order of the yes and no radio fields so that Yes is first.

### Current layout
![Screen Shot 2021-10-14 at 11.57.45 AM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/7c34b3e4-fb7b-49fe-b0fc-8b2cdef555ff)

### Updated layout
![Screen Shot 2021-10-14 at 11.59.48 AM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/69f78e48-2023-47c4-9991-e794e9063296)

### Figma
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=5383%3A34045

### This task is done when…
- [ ] change the order of Yes/No on Key State Personal
- [ ] no option is pre-selected for the user

**Comment by mirano-darren** [comment]
@jeromeleecms @aricka-lewis Ready for review! :) #3429 is also in this change
