### ISSUE TITLE
[Design Issue] Design cover page for the export view

### ISSUE THREAD

**Issue by akuas** [CMSgov/eAPD#3579]
Link or add dependencies to any applicable issues.
Based off[ #3149](https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/cmsgov/eapd/3149)

Folks have mentioned that it is hard to figure out the funding source and other key descriptors of an APD early on and a cover page should help resolve this issue. The contents of the cover page should be defined in this ticket. But, the following could be included.

### What has to exist
1. APD Name
2. Funding Source and APD Type
3. FFY
4. Total Cost
5. FFP
6. eAPD logo

### **What can exist**
1. Author list
2. Version number
3. Indication of draft vs submitted APD
 
### **What doesn't need to exist**
To be determined.

In the future, we could explore making this page the cover letter and fulfilling the requirement of a signed cover letter to make an APD administratively complete. We could also indicate whether an APD is a draft or in its final submitted state and we can include versioning.

Existing Cover Page Design (will attach soon)

### This task is done when…

- [ ] the type of content for this page is decided
- [ ] designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] 508 considerations and/or recommendations are reviewed
- [ ] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

---

**Comment by akuas** [comment]
Below is the cover page design for the current implementation, meaning there is no reference on this page about the status or the version number. @NAretakis I would need some guidance on the sorts of content you would expect on the cover page, I modeled it loosely from an Alaska APD and included some content about the APD that would make it easier for a reviewer to identify one APD over another. 
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=7080%3A44024

**Comment by akuas** [comment]
@thetif @NAretakis @aricka-lewis  Please let me know what you think.

**Comment by aricka-lewis** [comment]
@akuas looks great!

**Comment by akuas** [comment]
Below will be the future enhancement of the cover page design, once we implement version numbers and the APD statuses
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=7020%3A44566

https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=7030%3A44842

**Comment by akuas** [comment]
@NAretakis Can you please take a look at these designs?

**Comment by NAretakis** [comment]
I love it. @akuas this the best looking APD cover page I've seen. Let's make it happen!

**Comment by thetif** [comment]
created tickets #3723, #3724, #3725

**Comment by akuas** [comment]
From our discussion during parking lot, we will change state author(s) to primary APD point of contact.

**Comment by akuas** [comment]
For reference, below is the printer friendly cover page.
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=7347%3A46126
