### ISSUE TITLE
[Feature] Create a table of contents for the export view

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3584]
**Description and related issues -**
Create a table of contents for the export view. Each header should be a link that navigates to that section in the export view.

**Mockups or link to Figma**
![Screen Shot 2021-11-08 at 2.58.59 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/3bc762a1-fcca-4de1-b518-cca7a5144647)
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=7277%3A44719

### This task is done when…

- [ ] a table of contents component has been created
- [ ] component matches the figma mock up
- [ ] a storybook has been created for the component
- [ ] tests have been added for new component

**Comment by akuas** [comment]
Im not sure if this is going to be a separate ticket, but maybe we should include enabling bookmarks into the criteria list. With the table of contents enabled, bookmarks can be used to navigate between sections, on the side bar.

**Comment by thetif** [comment]
We have decided to use the browser's PDF preview tool instead of creating a separate export view, so this is OBE.
