### ISSUE TITLE
[Design Issue] Design table of contents

### ISSUE THREAD

**Issue by akuas** [CMSgov/eAPD#3595]
This issue will focus on the table of contents design that will be done in the V1 (version 1) of the export view redesign. We can create additional tickets for enhancements to be done in V2, which may reflect the changes in structure in MMIS. 

### What has to exist
- An structure based on the agreed upon reorder of the export view
- Table of Contents design
-  Consideration of how a table of contents would look in an export pdf
-  Plan to implement bookmarks
- A discussion on whether the table of contents should be included in the instructional tools Caryn is creating for onboarding 

### What can exist 
- To be determined

### What doesn't need to exist
- An sort of interaction or clickable items within the table of contents 

### This task is done when…

- [ ] designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] 508 considerations and/or recommendations are reviewed
- [ ] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

**Comment by akuas** [comment]
[Table of Contents Design](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=6686%3A41642)
Still in progress @jeromeleecms @NAretakis @thetif for visibility. Please let me know if you see any issues so far.

**Comment by akuas** [comment]
@thetif let me know if it would be helpful for me to design the table of contents with the bookmarks. There are no design considerations needed for the bookmarks I think but the structure will be shaped by the table of content structure.

**Comment by akuas** [comment]
Below are the designs for the table of contents. I have included a page descriptions and would need help reworking them a bit.

**Comment by akuas** [comment]
@aricka-lewis for awareness

**Comment by akuas** [comment]
@CSwartzHMA wrote [descriptions for the pages](https://docs.google.com/document/d/1TrYMJ_O2cj5T1XlNORQ3AN0fqY_HQjrtDr57z5udFw4/edit#) that I have now added to the [design](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=6822%3A43248). We will have have descriptions for just the headers at the moment. @NAretakis Please let me know what you think.

**Comment by akuas** [comment]
Hi @jeromeleecms or @NAretakis , can you please review the table of contents design?

**Comment by jeromeleecms** [comment]
Thanks for clarifying how this is intended to function @akuas during standup. Here's some more formal questions/thoughts about this:

1. For the read only/browser based export view of the Table of Contents: How is this supposed to work in the context of that view? Page numbers don't really mean anything in this context because the web view is just one long page. We could put page numbers prospectively (assuming certain print settings), but that might change once the user is ready to export the document? Or we could just have  table of contents with hyperlinks for this view until it's ready for export?
2. This format seems fine for the PDF export view (minus the web header). Are you expecting that the links would be clickable in the PDF format?

**Comment by akuas** [comment]
1. The read only view will have a table of contents. It would serve a similar function as the side nav in the builder view and will be hyperlinks, but no page numbers. I think having a table of contents in the read only view should preserve the user experience if they choose to review in the browser or choose to print it out. I will post the design for the read only view tomorrow in this ticket.
2. No, the PDF/ export view subheaders are not clickable.

**Comment by akuas** [comment]
@thetif @jeromeleecms I spoke with Tif and regarding the 1st question, I agree it would be best to keep the read only view and export view as consistent as possible. So, for the read only view the only thing that should change is the removal of page numbers and the dot styling associated with it. I also updated the design by making the pages hyperlinks.
 Jerome, can you please let me know what you think of this.

Below is the export view and read only view designs
[Updated export view toc](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=6822%3A43248)
[Read only view toc](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=7277%3A44719)

**Comment by jeromeleecms** [comment]
@akuas This looks good and is in line with what we discussed (with the understanding that the top nav bar will not be part of the PDF export). @thetif Did mention that we could explore making the PDF export links clickable - so let's keep that on the table - if it ends up being a huge lift, we can re-evaluate then.

**Comment by jeromeleecms** [comment]
@thetif ready for dev!

**Comment by jeromeleecms** [comment]
Dev Tickets created!
