### ISSUE TITLE
Create Cost Proposal for Paid Docker Account

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#3597]
Explore and document cost options for a paid Docker account.

### This task is done when...

- [ ] Document has been created outlining the costs and benefits/drawbacks of the different Docker paid account options
- [ ] Identify next steps

**Comment by cthulhuplus** [comment]
![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/647e9cfb-a799-4365-9e98-584319741725)

**Comment by NAretakis** [comment]
@cthulhuplus could we include Fargate to this research? I think we have access to it, which might mean it is more readily usable than purchasing Docker.

**Comment by cthulhuplus** [comment]
Yes, I can definitely look at Fargate as well. The context of this ticket is for pulls to Docker Hub specifically, our pipeline was getting rate limited for too many pulls from Docker Hub over 6 hours.

**Comment by cthulhuplus** [comment]
@NAretakis AWS Fargate is a container orca-stration product, similar to Kubernetes or OpenShift. I believe that adopting Fargate would fall outside of the scope of this Issue. If we decide we want to containerize the application or move towards a serverless infrastructure, then we should reevaluate it then. 

This Issue is to address the issue we were having with reaching our Docker Pull limit. The first option to explore is a paid Docker account, but after having thought about it further I think using some sort of repository mirror may also be a possible route.
