### ISSUE TITLE
[Feature] Update FormAndReviewList to prepare for new sub-form changes

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3646]
**Description and related issues -**

Add a Cancel button. Clicking Cancel should close the form and not save any thing that was changed in the form.

Change the Done button to Save.

Updated FormAndReviewList to not use auto-save. Clicking the Add X button should open a new form and that item should only be saved once the Save button is clicked.

### This task is done when…

This could include:

- [ ] a Cancel button is added
- [ ] Done button has been changed to Save
- [ ] nothing in the form is saved until the user clicks Save

**Comment by tbolt** [comment]
Noting one change in UX with these new updates-
Currently you can have multiple subform items expanded for editing/adding. Each one can be edited independently and saved independently. With this update, you can have multiple forms open but when one is saved, all of the others will be closed.
