### ISSUE TITLE
Add inline validation for Milestones

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3650]
Add inline validation for Milestones

*These validations will be triggered by the error check that is currently being tested. #3488

|Field|Content|Consideration|
|---|---|---|
|Milestone > Name|Provide a name for this Milestone|Should not be blank, planned end date can be blank See #3317|

**Mockup:**. (How error text would fall, underneath the field.)

![Screen Shot 2020-07-15 at 5.27.25 PM.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/47856b38-da9d-47a2-9c01-046df7731bdd)

### This task is done when...

- [ ] Milestone has inline validation

**Comment by jeromeleecms** [comment]
This is duplicate for the scope described here.
