### ISSUE TITLE
[Design Issue] Design export view for locked APD

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3652]
Based on criteria laid out in #3507 for the lock and submit feature:

After an admin check is complete and the APD is locked, a user should be able to export a "finalized" version of the APD. This export view should include:
- version numbers 
- designation that it is a summited version
- every export would increase the whole number (e.g. "final 1.1" or "final 2.1")

### This task is done when...

- [ ]  designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] 508 considerations and/or recommendations are reviewed
- [ ] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

---

**Comment by akuas** [comment]
@jeromeleecms For the cover page design, I added the version number and the status to that page. I also thinking about adding the status, at least to the header, so it will appear on top of each page. Do you see a benefit in this or keeping that information just on the cover page enough?

**Comment by jeromeleecms** [comment]
If we are using the word "locked" and "unlocked" - is it easier to just use version number without statuses?

**Comment by akuas** [comment]
@jeromeleecms @aricka-lewis Sorry for the late reply, if we are keeping the version number without statuses and if we also have the last edited date/time, then I don't think we need to put this information in the header. This information will just be on the cover page.

**Comment by akuas** [comment]
@jeromeleecms We will also have the language on the cover page indicating that an APD is for internal purposes.
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=7477%3A47198

**Comment by jeromeleecms** [comment]
@akuas Do we still need this since we are using the preview PDF as the export view (instead of the export view within the app)? Happy to talk through this in parking lot.

**Comment by akuas** [comment]
@jeromeleecms This work refers to the export view mainly, not the read only view, but I agree that we don't need this ticket anymore.

**Comment by jeromeleecms** [comment]
Sounds good - closing this with the expectation that the updated cover page will be incorporated into a single design for the export while tackling our design debt/Figma cleanup.
