### ISSUE TITLE
[Feature] Design schema for maintaining errors in APD

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3674]
**Description and related issues -**
Because we are going to start displaying the Admin Check to the users, we will need a way to keep track of all of the validation errors for the APD. We will also need to be able to toggle whether or not the users sees the Admin Check help drawer. The system should always be tracking this information regardless of whether the user can see it. It should also be maintained in the APD itself, so that it's visible to the user as soon as they need it and also so it can be shared between users editing the same APD.

The schema should track:
- to do section with
  - fields with errors groups by page
  - name of the fields with errors and the error message
  - fields that recently had errors but have been fixed and fields that still have errors on a page
  - the count of fields that still need to be fixed per page
  - fields and page groups should be displayed int he order they are displayed in the nav bar and the form
- recently completed with
  - the name of the last 5 fields completed grouped by section

**What is the goal or purpose of this ticket?**
Maintain a list of errors in the APD that can be used in the Admin  Check.

**Mockups or link to Figma**
![Screen Shot 2021-12-21 at 2.17.45 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/91b51059-8191-4131-a069-cfc31500fc24)

### This task is done when…

- [ ] a schema has been created to track errors in an APD and added to the APD model

**Comment by tbolt** [comment]
Related documentation- https://github.com/CMSgov/eAPD/wiki/Admin-Check-Notes#front-end-apd-structure
