### ISSUE TITLE
Research any log4j vulnerabilities and/or fixes

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/eAPD#3678]
The purpose of this issue is to research any log4j vulnerabilities or concerns that might impact our app or dev work. This issue will allow us to identify any work needed, which can spawn additional issues as necessary. 

### This task is done when...

- [x] We have identified any impact log4j has on our app or development.
- [x] We have created any necessary issues to triage or patch any part of the app.

**Comment by cthulhuplus** [comment]
There are no log4j packages installed on our servers.
```
$ sudo yum list installed log4j*
Failed to set locale, defaulting to C
Loaded plugins: amazon-id, s3iam, search-disabled-repos
Error: No matching Packages to list
```
```
$ sudo rpm -q log4j*
package log4j* is not installed
```

**Comment by cthulhuplus** [comment]
@NAretakis 
We do not have any log4j packages installed on our servers. I've checked using both the yum tool and the rpm tool, which are both used to manage/install packages on RHEL/CentOS servers.

**Comment by NAretakis** [comment]
Awesome, we can close this out then. Thanks @cthulhuplus

**Comment by cthulhuplus** [comment]
Big yup, was just waiting for your 👍
