### ISSUE TITLE
[Design issue] Design a way to indicate DDI or M&O FFP rates

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3688]
See also #2303, could be designed together, potentially 

FFP rates need to be configured to indicate DDI or M&O when selecting the Federal-State Split in the dropdown OR create a way for the state to indicate the type of cost (DDI/M&O) elsewhere in this section. Either way, this needs to tie to an MBES line number.

Considerations:
- We know that may find this action redundant based on previously completed fields

### This task is done when...

- [x]  designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [x] 508 considerations and/or recommendations are reviewed
- [x] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature
---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by akuas** [comment]
@jeromeleecms @beparticular Below is the designs for the new FFP. I think we should not include the changing the Budget and FFP and the Proposed Budget to keep the scope of this ticket small. Can yall please review the designs?

https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=166%3A8985

**Comment by jeromeleecms** [comment]
Just some initial thoughts:
1) Design, Development, and Installation (DDI) - can we put the acronyms in the tool tips like we did with the IAPD in the create APD page? Or maybe somewhere else?
2) We can keep it written as 90/10 DDI (we don't need to put exclusively)
3) Looking at the language "Select Project Status" with the E E&E language, it might make more sense to indicate "Funding Category"
4) I'm still a little torn about moving the FFP split to the front - can you help me understand your reasoning? I did like the way the table updated on the Budget and FFP page, but I can see how selecting the FFP early can inform authors that they need a separate activity when claiming a different FFP. Was there another reason? 
5) @thetif if we drop the FFP dropdown from the Budget and FFP section, do you need to see a version of the page without the dropdown?
6) For the help text: "Select the match rate for Federal Financial Participation **(FFP)** applicable to this activity...."

**Comment by akuas** [comment]
1. A tooltip is not needed here. Users will need to know what ddi is especially when they are presented with multiple options i.e. DDI, Operations, and Eligibility Worker (out of scope) and I have defined DDI in those situations
2. We don't have to make this decision on whether the FFP should sit in the activity overview or FFP and Budget in order to solve this ticket, so we can just focus on the field itself to see if it meets the requirement of this ticket to add DDI and M&O rates. I have pulled to field out to take a look.
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=166%3A8985

**Comment by jeromeleecms** [comment]
- Let's be consistent with the language then - "DDI" in all the places, or "Design, Development, and Installation"
- Where do validation messages appear in this design?

**Comment by akuas** [comment]
@jeromeleecms The validation messages are below the options and the fields behave like other fields that are _not_ contained in a subform. The 1st message stays the same. I also added "Select a funding category."
If there is no more additions to the content, this ticket should be ready to close after design sync.
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=166%3A8985

**Comment by akuas** [comment]
This is out of scope, but I looked through the MES expansion research and this is what I found to support keeping the FFP in the Activity Overview. @jeromeleecms 
1. Folks wanted their FFP to be populated in the Conditions for Enhanced Funding to indicate that they are requesting enhanced funding.
2. For eligibility worker in the future, it is driven by activity so it would make sense to have it earlier to allow for any branching in the future.
3. " If we getting an IAPD or an OAPD, we usually know what match rate we are getting." - session 5 MES Expansion Research
4. "We would be thinking about FFP as soon as we get a project to determine match rate but we would be thinking about it here too" - Session 5 Expansion 1 Research

**Comment by akuas** [comment]
Closing notes as of July 14th. 2022
1. Out of scope: There is a separate ticket to decide where we will house the FFP, either in the Activity Overview or FFP and Budget and how a change in its placement could affect the FFP and Budget, the Proposed Budget pages or any unconsidered page that will reference the FFP.
2. 90-10 is only DDI. 75-25 and 50-50 will branch out when selected

**Comment by beparticular** [comment]
Moved the considerations from the above comment on moving the FFP field location to ticket #4215

**Comment by beparticular** [comment]
@mirano-darren @thetif 
Darren - can you take a look at this and see if anything needs to be added or questions come up, and write a dev ticket for it? Let me know if you need anything?

**Comment by beparticular** [comment]
dev ticket reviewed - closing the design ticket
