### ISSUE TITLE
[Design issue] Update dashboard to include lockdown and submit features

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3689]
Since an APD can be locked and/or unlocked, we need to provide the following on the dashboard:

- status indicator to show whether an APD is locked or unlocked
- a way to either lock or unlock an APD
- a way to download the last exported version of the APD

Considerations:
- we'll need two different views 1) official submitter view and 2) non-submitter view
- only an official submitter will have the ability to lock or unlock the APD

### This task is done when...

- [x] designs are created, taking into consideration multiple FFY, multiple entries, long entries, weird entries, multiple user types, and/or the export view if applicable
- [x] 508 considerations and/or recommendations are reviewed
- [x] designs are shared
- [ ] designs are approved by product

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by aricka-lewis** [comment]
Updated after discussion in design sync today @akuas

**Comment by jeromeleecms** [comment]
Looks good with revision to add "Lock" option for APDs!

**Comment by thetif** [comment]
@aricka-lewis if a State Staff is view this do they just not see the Lock/Unlock links? @jeromeleecms can a State Staff delete an APD?

**Comment by aricka-lewis** [comment]
@thetif that's something we're going to determine after testing. It's possible that they will be able to lock and unlock -- so this design would change slightly if that's the case. @jeromeleecms am I correct in saying that?

**Comment by thetif** [comment]
never mind, I see what it looks like in this figma https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=7377%3A49325

**Comment by thetif** [comment]
created dev ticket #3840
