### ISSUE TITLE
[Design issue] Add MMIS submit email to the export and submit page

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3691]
We need to provide the appropriate email address depending on the APD funding source. In this instance, we should display the MMIS submit email on the lock and submit page.

MedicaidMMIS@cms.hhs.gov

Final Design:
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=514%3A14637

### This task is done when...

- [x]  designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [x] 508 considerations and/or recommendations are reviewed
- [x] designs are shared
- [x] designs are approved by product
- [x] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature
---

**Comment by beparticular** [comment]
MedicaidMMIS@cms.hhs.gov

**Comment by akuas** [comment]
@beparticular Thanks

**Comment by akuas** [comment]
The email is now updated for export and submit. I also updated the email for the lock and submit prototype on the MMIS file
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=514%3A14637

**Comment by akuas** [comment]
@beparticular Can you please review this ticket?

**Comment by akuas** [comment]
@jeromeleecms Yes, that a good point, depending on what funding type you select this page should show the appropriate email.

**Comment by akuas** [comment]
Spring Planning: Sept 1 2022
To recap, we want the system to provide the correct email depending on their funding source selection instead of hard coding the email in.

**Comment by akuas** [comment]
@thetif @mirano-darren @itsonlydio This ticket is ready for dev.

**Comment by jeromeleecms** [comment]
Dev ticket works for me, just bolded the note that this should occur automatically.
