### ISSUE TITLE
[Design issue] Determine language for APD statuses

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3697]
Once an APD has gone through an Admin Check and no validation errors remain, an APD can be locked. It is not assumed that it has been sent to CMS since that happens outside of the system.

Considerations:
- an APD can be "locked" once the admin check is complete
- an APD can be "unlocked" by any user with permission

All potential statuses are in quotes. Must solidify language before completing designs for #3653.

### This task is done when...

- [x] Meet to brainstorm names for export types
- [ ] Document final decision and add to #3653

---

**Comment by jeromeleecms** [comment]
That works for me. By leveraging versioning, we can align to using the name of those APDs so we know exactly which version we are working from as well.

**Comment by aricka-lewis** [comment]
@jeromeleecms wonderful! Closing this one.
