### ISSUE TITLE
[Bug] Unclickable login button after clicking "Cancel" upon stateadmin login

### ISSUE THREAD

**Issue by mirano-darren** [CMSgov/eAPD#3707]
**Description-**
After logging in as stateadmin, choosing the cancel option on the state select screen results going back to the login screen. The login button is stuck on "Logging in" and becomes unclickable. 

I believe I found this during my internship, but I looked through the current bugs and couldn't find this issue. Apologies if this matter has already been discussed.  
**Type of Bug-**

- [ ] Accessibility
- [ ] Functional
- [X] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

1. Login as stateadmin
2. On the state selection page, click cancel
3. Verify you are sent back to the login page with the login button turned into "Logging in"

**Role Affected-**

- [ ] All
- [ ] Federal Admin
- [X] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [ ] All
- [ ] PR #\_\_\_\_
- [X] Staging
- [ ] Production

**Browser-**

- [ ] Firefox
- [X] Chrome
- [ ] IE

**Expected results-**
When sent back to the login page, the login button should be clickable
**Actual results-**
The login button turns into an unclickable "Logging in"

**Additional information-** (optional)
Refreshing the page acts as if the default state was chosen, and brings you to that state's dashboard. 

Is a cancel button necessary on the state selection screen? A simple solution could be not giving the option to cancel the state selection during the login process. 
**Logs or error output/Screenshot/Video-** (at least 1 of these)
![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/18b98477-bdb4-4ef1-86aa-4959daab3623)

**Comment by akuas** [comment]
That's interesting. When I recreated the action, the cancel button directed me to the dashboard, but Im aware thats not the expected behavior. I don't think there needs to be a cancel, we can have a APD Home hyperlink like the manage account page or the Back to Dashboard button. I think I prefer the former for consistency. I think we should have two sorts of way to dismiss/get out of this page; one in the header and another in the buttons  in the main content.

**Comment by akuas** [comment]
Talked to Ty and it seems like the cancel button isn't really cancelling anything its just resetting to your previous state selection, so I agree we should remove the cancel button. We should probably go this route.
