### ISSUE TITLE
[Testing] Exploratory testing on session timeout

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3713]
There is some weird issues right now with session timeout. Please explore how this is working and determine if anything is happening and what triggers is.

### This task is done when...

- [x] session timeout has been determined to be working correctly or bug tickets have been made for any issues found

**Comment by mirano-darren** [comment]
**Will ultimately put this is the correct test cases format**
Format: GIVEN | WHEN | THEN | PASS/FAIL

![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/257219f2-3b70-4318-9658-1c0e4b64298d)

Three types of tests:
**Sign out via 5 min timeout**

- Change APD name and autosave | Let session timeout timer expire | Should successfully sign out; sign back in and make sure the name change was saved | :white_check_mark:

**Sign out via manually pressing the "Sign out" button**
- Change APD name and autosave | Sign out with the "sign out" button | Should successfully sign out; sign back in and make sure the name change was saved | :white_check_mark:

**Stay signed in via the "Stay signed in button"**
- Change APD name and autosave | Click "Stay signed in" button | Should not be signed out; name should be saved | :white_check_mark:
