### ISSUE TITLE
Determine workflow for unlocking an APD

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3730]
After design sync on 01/27/2022, we determined that there is a need to further explore how unlocking should work in the system. Since locking an APD happens on the export and submit screen once an APD is complete, we should determine when and how an APD should be unlocked. Only state admins will have the ability to unlock, so we need to consider the experience of those who need to edit but don't have permission to unlock.

An APD can be unlocked because:
- CMS has returned feedback
- An error was spotted and an admin has unlocked
- an APD was unintentionally locked

Considerations:
- Experience for those who cannot unlock
- Is there still a need to visit the export and submit page if an APD is locked?
- Use case(s) for unlocking on APD Builder

Unlocking occurs on:
- Dashboard
- APD builder

### This task is done when...

- [ ] Workflow has been created and approved by team
- [ ] Corresponding issues have been created

---

**Comment by aricka-lewis** [comment]
Updated unlock flow 
![Screen Shot 2022-02-01 at 10.57.02 AM.png](https://images.zenhubusercontent.com/6193eb5d55886d5a53ec4aac/c9d87a8e-c067-4822-9868-7230b2e233d4)

**Comment by aricka-lewis** [comment]
@jeromeleecms @akuas above it the updated unlock flow. Please take a look and provide any questions here.

**Comment by jeromeleecms** [comment]
With "Open APD" where does that take the user? Does it take the user to the export view or into the builder view? If they go to the export view, does that redirect them to the builder view?

**Comment by aricka-lewis** [comment]
@jeromeleecms My thinking was that it'd direct them to the builder view since the assumption is that they need to edit or look at something that needs correction. They would still have a way to get to the export/read-only view from there.

**Comment by jeromeleecms** [comment]
Sounds good.

**Comment by jeromeleecms** [comment]
Based on our design sync/parking lot conversations from yesterday - is this done (and now we just need to review the designs that mirror this)?

**Comment by aricka-lewis** [comment]
@jeromeleecms I have some changes to make and will share the design here. Will close once that's uploaded and approved!
