### ISSUE TITLE
[Design Issue] Design Debt: Archive old designs in Figma

### ISSUE THREAD

**Issue by akuas** [CMSgov/eAPD#3735]
Clean up Figma by moving unused trial designs to their corresponding archive pages so that the main pages in Figma reflect how the visual design looks in the UI and future enhancements.

This ticket is related to [#2973](https://github.com/CMSgov/eAPD/issues/2973) 

### This task is done when…

- [x] Archive old designs or future enhancements that are abandoned
- [x] Ensure that new archived designs have a date and ticket number, if possible
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

---

**Comment by akuas** [comment]
Archived designs will now be housed in a separate file. Designs that are not in use or are future enhancement that have since been abandoned will hopefully be archived. 
https://www.figma.com/file/uAboHTFZ1RT4h7bmV6XD80/CMS-eAPD-archive?node-id=5%3A15185

**Comment by akuas** [comment]
I have archived the designs in the archive file. I did leave a few future enhancements in the main file that I would like to explore in the future like the dashboard designs.

**Comment by akuas** [comment]
@aricka-lewis I think this ticket is ready to close, can you please take a look a the archived file.

**Comment by aricka-lewis** [comment]
Looks good! @akuas closing this ticket
