### ISSUE TITLE
[Bug] Creating an MMIS activity does not save the costs throughout the APD

### ISSUE THREAD

**Issue by mirano-darren** [CMSgov/eAPD#3749]
**Description-**
When an MMIS activity is created, none of the costs are saved throughout the APD. For example, in Proposed Budget the combined activity costs table is not updated.
**Type of Bug-**

- [ ] Accessibility
- [ ] Functional
- [X] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

1. Create an activity with a program type of MMIS
2. Verify the cost was not saved by checking the "combined activity costs" table in proposed budget page.

**Role Affected-**

- [X] All
- [ ] Federal Admin
- [ ] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [ ] All
- [ ] PR #\_\_\_\_
- [X] Staging
- [ ] Production

**Browser-**

- [ ] Firefox
- [X] Chrome
- [ ] IE

**Expected results-**
APD should be updated to match the MMIS activity costs
**Actual results-**
APD is not updated
**Logs or error output/Screenshot/Video-** (at least 1 of these)
![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/4869cd43-606d-4b68-87e5-ec82ecaaf559)
![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/80fce1bc-18bb-4b10-90fc-0e19f3c53d3f)
![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/cc2adc84-692b-47c0-9b5f-683eb0416980)

**Comment by jeromeleecms** [comment]
Darren will test in staging to see if this is occurring in production and we will reassess afterwards priority.
