### ISSUE TITLE
Plan for eAPD Discipline Overview Meeting

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#3752]
Plan a meeting to discuss an overview of Design, Dev, DevOps, and Product to discuss the eAPD ecosystem, application, infrastructure, and how it relates to future work and the larger CMS/MACPro ecosystem.

### This task is done when...

- [ ] Design has decided/if/what they want to present/discuss
- [ ] Dev has decided/if/what they want to present/discuss
- [ ] QA has decided/if/what they want to present/discuss
- [ ] DevOps has decided/if/what they want to present/discuss
- [ ] Product has decided/if/what they want to present/discuss
- [ ] Meeting agenda has been formulated
- [ ] Meeting has been scheduled

**Comment by jeromeleecms** [comment]
Will discuss during parking lot on 03/02 or 03/03

**Comment by jeromeleecms** [comment]
Will take parking lot on 03/08/2022 to do a high level discussion on this and decide follow up as appropriate

**Comment by jeromeleecms** [comment]
Issues created to follow-up on this.
