### ISSUE TITLE
[Design Issue] Create a flow explaining how review could be broken up from export and submit.

### ISSUE THREAD

**Issue by akuas** [CMSgov/eAPD#3757]
Display how the  review, export, and submit experience would look like for state admin vs state author.
This ticket came about because we needed a separate flow from state admin to keep state authors from locking and submitting to CMS. In the system, we have Review and Download which could be a place where folks review their APD before exporting and submitting and could house the admin check. The page following is the read only view which also have cta to export and submit. This page could be the final page in the eAPD process.

### This task is done when…

- [ ] any acceptance criteria (not process oriented, requirements of feature)
- [ ] designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] 508 considerations and/or recommendations are reviewed
- [ ] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

**Comment by akuas** [comment]
Im not particular about where the read only view goes, but after thinking about @jeromeleecms comment about having to change things in the future to account for new considerations, we can keep it in the "Export and Submit" page or the last step in the process (we might need to change the name). Using the e-commerce analogy, the read only view is the receipt or the screen stating that you have successfully ordered your item and this is how much it cost. It's not really a primary tool to do an administrative review in my mind.

**Comment by akuas** [comment]
Below is the state admin flow for lock/export/submit.
![20220208_142156.jpg](https://images.zenhubusercontent.com/601acfa212e5437689f6079c/7a7b5320-cec9-4f55-bf79-beb76d122521)

**Comment by akuas** [comment]
![20220208_142418.jpg](https://images.zenhubusercontent.com/601acfa212e5437689f6079c/4def9e45-1ed3-4c40-9ae6-d4ab9b55ea22)
[Uploading... 20220208_085453 (1).jpg]

**Comment by jeromeleecms** [comment]
@akuas Based on our conversations for the last couple days, do you feel like you have enough info to close this and work on the designs themselves? Or did you want to keep to this particular issue open until the designs are done?

**Comment by akuas** [comment]
@jeromeleecms I think this issue is good to close out.

**Comment by jeromeleecms** [comment]
Work will continue in actual designs!
