### ISSUE TITLE
[Bug] Search icon missing in the Select your State Affiliation page. 

### ISSUE THREAD

**Issue by mirano-darren** [CMSgov/eAPD#3777]
**Description-**
The search icon is missing on the select your state affiliation page
**Type of Bug-**

- [X] Accessibility
- [ ] Functional
- [ ] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

1. Log in as no role
2. Get to select your state affiliation page
3. Verify the search icon isn't rendered properly

**Role Affected-**

- [ ] All
- [ ] Federal Admin
- [X] State Admin
- [X] State Staff
- [X] State Contractor
- [ ] System Admin

**Environment-**

- [ ] All
- [ ] PR #\_\_\_\_
- [X] Staging
- [ ] Production

**Browser-**

- [x] Firefox
- [X] Chrome
- [ ] IE

**Expected results-**
Search icon appears
**Actual results-**
Search icon isn't rendered

**Logs or error output/Screenshot/Video-** (at least 1 of these)
![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/1891745a-fd52-4246-a3ab-a6b195504046)
---

**Comment by jeromeleecms** [comment]
This will be included in the patch for the Mongo fixes, closing this out. Check with @thetif to see some of the other items we can have you try and fix. Thanks for your diligence and keen eye, @mirano-darren!
