### ISSUE TITLE
[Feature] move containers into a containers folder

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3796]
**Description and related issues -**
Ensure that the containers folder is only used for components that are actually containers. Here is a list of which components should be in the folder

```
├── containers
    ├── Root
    ├── App
    ├── ApdApplication
    ├── LoginApplication
```

### This task is done when…
- [ ] the containers folder only has components that are containers in it

**Comment by mirano-darren** [comment]
Merged in with #3794
