### ISSUE TITLE
Plan usability testing for Lockdown and Submit

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3800]
As we wrap up designs for the Lockdown and Submit work, we should test interactions and consistency of the feature across pages. 

Considerations and research goals listed in the planning document: 
https://docs.google.com/document/d/1krpU3NY6102B_5r6kMKjggDHdP8B1AMvpmeboQteBG8/edit?usp=sharing

Conversation guide with tasks:
https://docs.google.com/document/d/1UEE0zfRSE4RiWmN-YSsw9zxmX1OO6ogXowmGMSdJnwI/edit?usp=sharing

Lock and Submit Research Dovetail
https://dovetailapp.com/projects/1nzhhQMD4KSXRl9MPzk367/readme

### This task is done when...
- [x] A research plan is created, shared, and approved by product/team 
- [x] A conversation guide is created and approved by team
- [x] Ticket is created to review (relevant) research
- [x] Ticket is created for designing a prototype
- [x] Tickets are created for Recruiting, Conducting, and Analyzing Research

---

**Comment by jeromeleecms** [comment]
Just some minor comments on the conversation guide (the consideration and research goals seem fine). Can we do a dry run of the conversation guide together?

**Comment by aricka-lewis** [comment]
Yes, let's use our 1:1 today @jeromeleecms

**Comment by jeromeleecms** [comment]
Done!
