### ISSUE TITLE
Conduct usability sessions for lockdown and submit

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3802]
Research protocol:
https://docs.google.com/document/d/1UEE0zfRSE4RiWmN-YSsw9zxmX1OO6ogXowmGMSdJnwI/edit?usp=sharing

Mural for synthesis:
https://app.mural.co/t/cmsmural6360/m/cmsmural6360/1599582078303/4d5e496414cbe78e4288c9cbc155b9b9260e74b6

### This task is done when...
- [x] Research planning ticket closed
- [x] Sessions have been conducted
- [x] Team debrief(s) scheduled

---

**Comment by akuas** [comment]
Recording to the sessions will be below
https://dovetailapp.com/projects/1nzhhQMD4KSXRl9MPzk367/data/b/6PFyREJ1WTNaPwOl59nmyP
