### ISSUE TITLE
[Design issue] Create prototype for lockdown and submit testing

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3810]
We're planning to use a clickable prototype to test out the designs created for the lockdown and submit work. The prototype should include:
- export and submit page with interactions
- dashboard with interactions
- locked apd with interactions
- unlocked apd with interactions 

Research plan: https://docs.google.com/document/d/1krpU3NY6102B_5r6kMKjggDHdP8B1AMvpmeboQteBG8/edit?usp=sharing

Conversation guide with tasks:
https://docs.google.com/document/d/1UEE0zfRSE4RiWmN-YSsw9zxmX1OO6ogXowmGMSdJnwI/edit?usp=sharing

Prototype:
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=7643%3A57370

### This task is done when...

- [ ] designs created and tested by team
- [ ] prototype link created and shared to research protocol
- [ ] Designs have been reviewed by appropriate team members

---

**Comment by akuas** [comment]
Below are the prototype designs
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=7643%3A57370

**Comment by akuas** [comment]
@aricka-lewis Can you please take a look at this prototype?

**Comment by aricka-lewis** [comment]
@akuas flow makes sense to me -- there are a couple of edits to be made on the "read-only" view (replacing lorem with real copy) but we can chat about it in our 1:1.

**Comment by jeromeleecms** [comment]
While there were some hiccups during today's testing, is this ready to close?

**Comment by akuas** [comment]
@jeromeleecms I fixed the issue and this ticket is ready to close.

**Comment by jeromeleecms** [comment]
Sounds good! Prototype has been used during testing already (+fixes), so this is done.
