### ISSUE TITLE
[Ops] Evaluate Ponicode or Stryker would be helpful in our system 

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3833]
Evaluate [Ponicode](https://ponicode.com/) and [Stryker Mutator](https://stryker-mutator.io/) to see if they would be valuable to use as part of our testing process.

### This task is done when…
- [ ] we understand the features of both tools
- [ ] a decision has been made about whether or not to use them

**Comment by mirano-darren** [comment]
Moving forward with implementing Stryker, moved Ponicode research to another ticket, 3844
