### ISSUE TITLE
Create a high-level visualization based on Framing Doc

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3845]
Using the [eAPD Framing Document](https://docs.google.com/document/d/11cyPx5MvAL05545BGs0SjyH-sImU6k0QInjx0ydSMY0/edit?usp=sharing) as a guide, create a visualization that illustrates the major goals and steps that make up the eAPD system. Though this document may not be a resource for day to day work, it will serve as a quick/visual way to identify how the strategic goals of eAPD align with the detailed roadmap. It will help visualize the complexity of the system as the number of users and their needs increases.

Major steps in eAPD:
Build ---> Review ---> Submit ---> Update ---> Analyze ---> Audit

This visualization is in the bottom right of the cake layer planning mural:
https://app.mural.co/t/cmsmural6360/m/eapd5455/1588711183071/fbaf128c05c78cbe862b3eb9816b679955bdf1e7

### This task is done when...

- [x] Document created
- [x] Major steps identified
- [x] Cake layer planning can be mapped to this strategy
 
---

**Comment by aricka-lewis** [comment]
Since this is a living/ongoing document, I'm marking this issue as done.

**Comment by beparticular** [comment]
This will be cool to keep around and update on a regular interval. 
The plan moving forward will be to mainly update the wishlist and the ideas for research (and hopefully what's been implemented!). 
We can move the research ideas from the wiki into this and make a note in the research findings wiki page that the ideas for new research can be found in the Roadmap doc. 
We can also link the Mural in Dovetail for people with Dovetail access to see our strategy. 

Once I do all this, I will close this ticket.

**Comment by beparticular** [comment]
@jeromeleecms I've done everything I need to with this issue. We can review the new idea for future research ideas storage in the coming week (I put it in my to do list, so it will not get forgotten)
