### ISSUE TITLE
Quarterly Tabletop Exercise(s)

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#3853]
Schedule and identify subjects for tabletop exercises.

### This task is done when...

- [x] First quarterly tabletop exercise is on the calendar
- [x] First quarterly tabletop exercise topic is identified

**Comment by cthulhuplus** [comment]
Mongo Schema
Reviewing Contingency Plans
Reviewing

**Comment by cthulhuplus** [comment]
Backup & Restore (both in AWS and CPM)
Manually Provision Infrastructure with Scripts
Security/Availability Incident

**Comment by tbolt** [comment]
Some additional ones:
* Doing a Deployment (with or without build issues)
* Hotfix - Could either be an application bug or a vulnerability in the dependency chain

**Comment by thetif** [comment]
- finding documentation and running through it
- deployment
- database back up and restore
- hotfix
- fixing a security vulnerabilty

**Comment by jeromeleecms** [comment]
This will be good to close when the topics are moved to a Google doc @cthulhuplus

**Comment by cthulhuplus** [comment]
Created two documents in Google Drive
