### ISSUE TITLE
Schedule meeting to discuss implementation of the Federal Admin dashboard

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#3857]
As a follow-up to our all disciplines discussion, we are going to do a feature implementation review of the Federal Admin dashboard moving from product inception -> implementation.

This is done when:
- [x] Meeting has been scheduled
- [x] Mural has been created to help document process (Akua)
- [x] Team has conducted meeting
- [x] Any additional follow-up items are created

**Comment by akuas** [comment]
Attached is the multi-discipline exercise for federal admin. It is on the right hand side of the board.
https://app.mural.co/t/cmsmural6360/m/cmsmural6360/1599582144962/61de16ee86eb3f2fac37d070c217fc2d3a5eeabe

**Comment by akuas** [comment]
@jeromeleecms I connected our different roles together in the mural. When possible can you please post the recording either here or on the table top google folder? Is there anything else I should capture on the board from our discussion?
https://app.mural.co/t/cmsmural6360/m/cmsmural6360/1599582144962/61de16ee86eb3f2fac37d070c217fc2d3a5eeabe

**Comment by jeromeleecms** [comment]
I uploaded the recording to our Google Drive and linked to it in the Mural. The flow diagram between our roles is :thumbsup: - I think this is ready to close when you are.

**Comment by akuas** [comment]
@jeromeleecms Im going to close out this ticket then. 😊
