### ISSUE TITLE
Investigate pm2 Starting Despite Vulnerabilities

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#3861]
Describe the task here and link or add dependencies to any applicable issues...

### This task is done when...

- [x] criteria 1
- [x] criteria 2

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by cthulhuplus** [comment]
Ty reported this morning that Prod was up despite not receiving the sec vuln patches that Staging received this week

**Comment by jeromeleecms** [comment]
It's alive! Need to patch some items, but whole system did not fail!
