### ISSUE TITLE
[Bug] "You have securely logged out." message appears when accessing the login page of the app

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#3877]
Loading the app for the first time results in a notification that the user was successfully logged out. This may particularly be confusing to people who are using screen readers and may think that the did something with the app that resulted in them being logged out.

**Type of Bug-**

- [X] Accessibility
- [ ] Functional
- [X] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

1. Go to the eapd.cms.gov
2. Acknowledge the Federal site warning (if applicable)
3. View the message on the log-in page

**Role Affected-**

- [X] All
- [ ] Federal Admin
- [ ] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [X] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

**Browser-**

- [ ] Firefox
- [X] Chrome
- [X] Edge
- [ ] IE

**Expected results-**
If this is the first time logging in, you should not see this message.

**Actual results-**
See screenshot

**Logs or error output/Screenshot/Video-** (at least 1 of these)

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/7d9ea577-f657-4717-b27a-04606ba55b30)
---

**Comment by mirano-darren** [comment]
@jeromeleecms I'm not having this issue? Did the logout message appear after you pressed Accept and continue?![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/a9994315-45f7-4fa6-b12a-0a0376e0c2b2)

**Comment by jeromeleecms** [comment]
Hmm.. now I don't see it on eapd.cms.gov, but I'm seeing it on staging only. Is this maybe related to the current status of staging? If it is, I think we can close this ticket out @mirano-darren ...

**Comment by mirano-darren** [comment]
I'm also not seeing it on staging either. I think you are seeing the message because of session cookies? It might be remembering when you logged out last. What I did to check was use Chrome's incognito mode to get a browser that starts with no cookies.

**Comment by mirano-darren** [comment]
Could no longer re-create the bug

**Comment by jeromeleecms** [comment]
Received notification again on prod and opened the console: 

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/5c9b86e1-fffb-4883-aecd-36f9cdcacc18)

If we don't get a response from the authentication server, we should report that the system is not available.

**Comment by jeromeleecms** [comment]
We need to generate a list of potential error situations and provide better feedback to the user about what is happening. @thetif will spin up a new issue around this.
