### ISSUE TITLE
Create Sandbox Environment for users 

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#3878]
In user testing, people expressed in interest with playing with the application without going into the production site.

Some questions to answer:
1) How/where do we set that up? (Using a preview site?) Cleaner URL needed? (sandbox-eapd.cms.gov?) - Use Staging!
2) How often do we wipe the content out?
3) What logins do we provide? Invite only? 
4) How do we communicate this out? Create documentation for Sandbox? Example: How often do we wipe out data?
5) Anything else?

### This task is done when...

- [x] Sandbox environment set up
- [ ] People informed that sandbox is available

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by cthulhuplus** [comment]
@jeromeleecms 
After talking to Tif, these are our suggested answers to the questions:
1. Use Staging!
2. Same cadence as our user password resets
3. https://impl.reg.idm.cms.gov/registration.html?appid=eapd
4. Newsletter/Office Hours
5. Other: Create Wiki page to share this information and set expectations for use of Staging/Sandbox

**Comment by cthulhuplus** [comment]
Future @jeromeleecms what else would you like to see done to call this work done?
