### ISSUE TITLE
Contingency Planning Document Review: Design Team

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#3889]
From retro, we need to review our contingency plans for when our Design Team Lead/Member is absent.

Current Doc: https://docs.google.com/document/d/1w6ecMW8jFzOSFtdPo9u6_yE6BVJh6L0s4ycpihrRaoE/edit?usp=sharing

### This task is done when...

- [ ] Design Team has reviewed/updated contingency planning document 
- [ ] Entire team has been briefed on any changes/highlights

**Comment by aricka-lewis** [comment]
I updated the sections relevant to me. @beparticular I'll leave it to you to update contact info and meeting times when you get settled.

https://docs.google.com/document/d/1w6ecMW8jFzOSFtdPo9u6_yE6BVJh6L0s4ycpihrRaoE/edit?usp=sharing

**Comment by beparticular** [comment]
@jeromeleecms I've reviewed this update and it's all fine. can this be closed?

**Comment by jeromeleecms** [comment]
Merged contingency plan into a unified document in prep for going over all the docs: https://docs.google.com/document/d/17a0K9vNOc731loJXw_WvZliDgklxWy7nqqylBME2BJQ/edit#heading=h.88btzg331qp5
