### ISSUE TITLE
Contingency Planning Document Review: DevOps

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#3890]
From retro, we need to review our contingency plans for when our DevOps Team Lead/Member is absent.

Current Doc: https://docs.google.com/document/d/1Zv9ctPWvi_UfXoBDJ0h1RrPwv771kP_Ri8Q1v-bVGyg/edit?usp=sharing

### This task is done when...

- [x] DevOps Team has reviewed/updated contingency planning document 
- [x] Entire team has been briefed on any changes/highlights

**Comment by cthulhuplus** [comment]
Look good @jeromeleecms ?

**Comment by jeromeleecms** [comment]
Just a few clarifying questions for your consideration. But this looks like a solid foundation.

**Comment by cthulhuplus** [comment]
@jeromeleecms I updated the document based on your feedback

**Comment by jeromeleecms** [comment]
Looks good - once all the contingency plans have been drafted, I think talking through them during parking lot would be good to elevate teams awareness. Thoughts? Depending on how long each takes, we can either spread it out during the week or do it all in one session.

**Comment by cthulhuplus** [comment]
I am 100% in favor for talking and "walking" through these documents. It is important to know what our various procedures would be. After talking through them it might be beneficial to do tabletop exercises with the parties involved with each plan so that the talking is made slightly more concrete.

**Comment by jeromeleecms** [comment]
I think our brains are in sync with this - that's exactly what I was thinking for next steps after we did the briefing. Know -> Apply!

**Comment by jeromeleecms** [comment]
Merged contingency plan into a unified document in prep for going over all the docs: https://docs.google.com/document/d/17a0K9vNOc731loJXw_WvZliDgklxWy7nqqylBME2BJQ/edit#heading=h.88btzg331qp5
