### ISSUE TITLE
Change "Preview" to "PDF Preview" 

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3917]
Based on the lockdown and submit usability studies, participants had difficulty understanding what version of the APD they would see when clicking "preview." Updating the language to "PDF Preview" will provide clarity that they should expect a PDF version of the APD to open.

This includes:
- preview link on the dashboard
- "preview this APD" on the export and submit page"

Preview findings/synthesis: https://dovetailapp.com/data/Preview-APD-4KPaUHnk1jHGjxRnsYe5dK

### This task is done when...

 - [ ] designs are created, taking into consideration multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
 - [ ] 508 considerations and/or recommendations are reviewed
 - [ ] designs are shared
 - [ ] designs are approved by product

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by akuas** [comment]
Below is the revised dashboard with PDF Preview
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=7370%3A46497

**Comment by aricka-lewis** [comment]
@akuas yes, just update this issue to reflect that

**Comment by akuas** [comment]
@aricka-lewis Thanks, I have made the changes to designs below 
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=198%3A0
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=7370%3A46497

**Comment by akuas** [comment]
@jeromeleecms If there is no objections, I think this is ready to close out

**Comment by jeromeleecms** [comment]
Looks good! Def. helps set the expectation for what to expect when clicking on this button.

**Comment by akuas** [comment]
@jeromeleecms I thought you were taking the day off hehe. Thanks, I am going to close this ticket now.
