### ISSUE TITLE
Dashboard 2.0

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3921]
After lockdown and submit research, we came away with a lot of ideas on how to improve the dashboard for scalability. 

Some concepts to consider when updating the dashboard: 
- packages
- multi-user
- statuses
- active work vs records

Do we lock the APD on dashboard when someone is editing APD?

### This task is done when...

 - [ ] designs are created, taking into consideration multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
 - [ ] 508 considerations and/or recommendations are reviewed
 - [ ] designs are shared
 - [ ] designs are approved by product

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by jeromeleecms** [comment]
Closes this out in favor of #4016. This will surface up later.
