### ISSUE TITLE
Develop Emergency Direct to Staging Deploy

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#3927]
Addressing issues in Staging takes a prohibitively long time currently, being able to deploy directly to staging would be a great boon for testing things that work in Preview, but are broken in Staging.

### This task is done when...

- [x] Can successfully deploy directly to staging

**Comment by cthulhuplus** [comment]
https://github.com/CMSgov/eAPD/wiki/Emergency-Deploy-to-Staging-Runbook

**Comment by cthulhuplus** [comment]
![image.png](https://images.zenhubusercontent.com/5e9749aa5773ead7746338c1/7a44b1c3-701b-48da-bad9-d7a2b94e34ff)

**Comment by jeromeleecms** [comment]
Sounds good @cthulhuplus. Seems like this will be a good tool to in our toolbelt.
