### ISSUE TITLE
Add e2e testing to main/staging deploy/CI pipeline

### ISSUE THREAD

**Issue by tbolt** [CMSgov/eAPD#3946]
As discussed in devsync, we agreed it would be best to have all of our testing coverage run in main/staging as it does in preview builds 

### This task is done when...

- [ ] e2e testing added to CI pipeline

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by cthulhuplus** [comment]
Completed by someone, not sure who
