### ISSUE TITLE
Team testing philosophy document

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3966]
Work together to document how testing will work on our team. This should be based on Fearless standards and modern testing practices. Document how the devs and testers will work together on tickets.

1. Understand the tools we use for testing for each stage of development (unit, e2e, visual, others)?
2. Roles and Responsibilities for Testing 
3. What is the expectations for QA in ticket authoring process
4. How do we measure testing? Codecov? Outputs? Metrics?

Testing document can be found [here](https://github.com/CMSgov/eAPD/wiki/Testing-Philosophies-and-Strategies).

### This task is done when...
- [x] #3967
- [x] the testers have shared their plan at a dev sync

**Comment by mirano-darren** [comment]
Presented at dev sync
