### ISSUE TITLE
[Design Issue] Update subform design to allow for 1 subform to be saved before adding another

### ISSUE THREAD

**Issue by akuas** [CMSgov/eAPD#3968]
We need to update the subform the design to sync information sent from the front end  to the backend. Currently, you can add multiple subforms at a time, and whichever subform you choose to save will be 1st regardless of the order in which it was added. 

Need to update the design for key state personnel first and get a consensus for the rest of the subforms.

### This task is done when…

- [x] Key state personnel subform redesigned
- [x] Consensus achieved with dev
- [x] Other subforms are updated.
- [x] designs are shared
- [x] designs are approved by product
- [x] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [x] a list of changes to be made if this is improving an existing feature

---

**Comment by akuas** [comment]
Yesterday, we decided that we could disable the Add (subform name) button and have copy indicating that they have to save to add another subform. But I went back to @aricka-lewis suggestion on just removing the button (Add Key Personnel) till they save. at first, I was a bit concerned that it would be disorienting to remove content from the page without indicating to users, but I suppose it wouldn't be because the subform is its own section. Im also thinking the previous recommendation to disable the button will require too many changes to implement. So, I just removed the button when the subform is opened to prevent the issue of the last added subform being presented first.

**Comment by akuas** [comment]
@tbolt Below is the design for the key state personnel with the change added. Please let me know what you think.

https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=5604%3A38738

**Comment by akuas** [comment]
@tbolt Yes, save and cancel are your only options once you open a subform. Nice, Im going to bring this ticket back into progress and untag you, so that I make the changes to the rest of the subforms then tag you again when it is ready to review.

**Comment by akuas** [comment]
I updated the other subforms below. They activity schedule is on a separate page from the milestones but the subform is still the same.
[Key State Personnel](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=5548%3A37347)
[Activity Schedule and Milestones](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=5708%3A38501)
[Outcomes and Metrics](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=5554%3A37859)
[State Costs](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=5715%3A39439)
[Private Contractor Costs](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=5713%3A39096)

**Comment by akuas** [comment]
@ty and @jeromeleecms Can you please take a look at this and if there are no issues, I will close the ticket out.

**Comment by jeromeleecms** [comment]
This looks fine @akuas. In the case where the user "edits" a subform, does the "add" button stay or go? From @tbolt description, once it's been assigned a ID in the front end -> back end, saving is not an issue (is that right?). So it seems we could have a form that is being edited AND a subform being added at the same time.

**Comment by tbolt** [comment]
@akuas Looks good to me

@jeromeleecms That's a good point. I didn't think of the Edit. The issue with how we have it coded now is that when anything is saved to the backend (edits or adding a new one) we are re-sync'ing the front-end. So if you start adding an item, then go to edit one, when you save that, it will lose the other content. We'll need to revisit this again I suppose.

**Comment by akuas** [comment]
@jeromeleecms When the subform is open or it is being edited, the add button is gone. From what I understand, designing it this way where a user cannot edit one subform and add other, should prevent the issue of listed subforms ordered incorrectly.

**Comment by akuas** [comment]
@jeromeleecms @ty If there is nothing to change, I think this ticket is ready to close.

**Comment by jeromeleecms** [comment]
Just to reiterate: if you are editing an existing form, the add button will go away. So in the case where you are adding/editing, does that also mean the other "edit" buttons go away? This idea sounds good - just want make sure we cover the cases so people aren't losing data entry.

**Comment by akuas** [comment]
@jeromeleecms Okay, I think I understand what you are asking now. I don't think we should remove the other instances of edit (edit as a hyperlink) when you are adding an APD.  Would there be an issue with keeping the edit button @ty with the backend?
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=5403%3A34595

**Comment by tbolt** [comment]
@akuas currently, yea. Any time any of the subforms are saved the "sync" with the backend happens and any additional open subforms will be lost

**Comment by jeromeleecms** [comment]
OK from standup - we are scoping some tickets very specifically to handle the different cases described here:

1) **Spin up a new bug for multiple edits issues** - Saving an existing form shouldn't affect the other open subforms and should not cause the page to refresh.  As it is now if two sub forms are open, saving will only save  item and clear out any new data that may have been added for an existing form or clear out any new subforms.

2) 3726 exists to to remove the button when adding a new subform item so only one subform can be added at one time.  Once edit bug is fixed, this multiple saving scenario will no longer be a case we have to worry about.

If there is nothing else, I think this one is good to move to Dev to create tickets to reflect needed changes here.

**Comment by akuas** [comment]
@jeromeleecms Looks good to me! Im going to remove the design tag then.

**Comment by akuas** [comment]
I forgot to mention @thetif this ticket is ready for dev

**Comment by thetif** [comment]
dev #3983
