### ISSUE TITLE
Prepare PDR Presentation for 05/26/2022

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#4042]
We are planning to discuss "How the eAPD team works (not working title)" based on our last tabletop exercise. We need to complete this by 05/25/2022.

### This task is done when...

- [ ] Roles assigned
- [ ] Presentation Complete
- [ ] Presentation Presented

**Comment by cthulhuplus** [comment]
@jeromeleecms 
How long do we have for our presentation?

**Comment by jeromeleecms** [comment]
20 minutes @cthulhuplus. We have 25 minutes, but Nick will need 5 to go over the OKRs.

**Comment by jeromeleecms** [comment]
Done!
