### ISSUE TITLE
Content Review of the Example Box Text

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#4050]
A full content review of the example boxes should be conducted to ensure that the use of the example box is consistent across the system. Currently the example box contains examples, instructions, help text, etc.

The example boxes in their current state are documented in Figma: https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2022?node-id=8480%3A26175

### This task is done when...

- [X] Determine if the content is “help text” or other text that is not an example (Done in #3070)
- [x] Determine if an example really needed where one is given or not given
- [x] If so, leave the example as is if it's the correct information.
- [x] If so, create examples if they don’t exist and are needed
- [x] Determine if we wanted to use something standard from the design system as the example box, vs the custom box that appears now.

- [x] Determine if we'd move the help text elsewhere in the section, or would we reduce or rewrite the help text (rewrites should be given their own ticket if it is determined any are needed)
- [x] Should we have components or styles for the following: Help Text, Directives, Policy Information, Examples, etc (If so, this should be broken out into a new ticket)

**Comment by akuas** [comment]
Below is a list of our current example boxes some of example boxes. I am currently making a google sheet with this list with a column does it need to be changed for mmis (yes or no) and is it consistent with our pattern. I feel like that might be a good way to do a content review.
1. APD Overview : HIE Overview
![Screen Shot 2022-10-05 at 2.57.13 PM.png](https://images.zenhubusercontent.com/601acfa212e5437689f6079c/6810d8e2-f4ad-49db-9c92-51232ac760f6)
2. Key State Personnel : Key Personnel & Program Management

**Comment by akuas** [comment]
@jeromeleecms @SGilliamA1M Below is the google sheets I will be working. It is still in progress, so Ill add more as I review the example boxes
https://docs.google.com/spreadsheets/d/1JL52hfdn0cIh1BRkEAYW6-gt3h2vVVCdCFdBTPE1BlY/edit?usp=sharing

**Comment by akuas** [comment]
After reviewing the example boxes, here are my thoughts of what we should do for some of the example boxes. @jeromeleecms @SGilliamA1M 
**Example boxes going away with MMIS:**
1. HIE Overview
2. Statement of alternative considerations and supporting justification
3. Estimated Quarterly Expenditure

**Proposed example box removal because I feel they are not needed:**
1. Cost Allocation: "Include any participating non-Medicaid FTEs" 
2. Cost Allocation: Description of cost allocation methodology

**Examples that could be moved to help text:**
1. Other state expenses : The miscellaneous expenses example can be moved inside the subform as a tooltip or hint text
2. Private Contractor costs: Could replace existing help text for that section

**Comment by akuas** [comment]
@jeromeleecms Can you please let me know whether you agree about the proposed example box removal and examples that should be help text via zenhub comment.
Also, if you have some recommendations on how we could reword some of the examples to appear more like an example than a directive, can you please post a comment on the [Figma example box page](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1303%3A11957) with your copy changes.

**Comment by jeromeleecms** [comment]
1) APD Overview: HIE Overview: Yes, OK to remove
2) Key State Personnel: Key State Personnel & Program Management: Yes, keep and revise example
3) Activity Overview: Alternative Considerations: Maybe tricky to provide a good example using our format. These can be quite long -- maybe consider how we can incorporate this into the help text
4) Outcomes and Milestones: Outcomes and Metrics: Yes, keep. Let's use the examples from the outcomes and metrics GitHub page.
5) State Staff and Expenses: State Staff: Yes. Let's consider how to revise language. 
6) State Staff and Expenses: Other State Expenses: We could potentially expand the dropdown as well to remove the number of examples needed for Misc. Expenses. Will need to consider what we can add, but State Medicaid Director Letter 16-004 can give us some options.
7) Private contract costs: Yes, keep. Let's revise the copy.
8) Cost Allocation: We need to keep, but revise the examples.

Will make comments in the Figma page in a moment.

**Comment by jeromeleecms** [comment]
Comments in the Figma added + some questions. Let me know if you want to talk through them.

**Comment by akuas** [comment]
@SGilliamA1M  Below are the updated copy for the activities dashboard and outcome and metrics. @jeromeleecms What do you think about providing examples about how an activity can be broken up instead of a list of activities?
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1714%3A14215
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1714%3A14214

**Comment by akuas** [comment]
I created [4380](https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/cmsgov/eapd/4380) to redesign the example boxes

**Comment by akuas** [comment]
@jeromeleecms @SGilliamA1M  Can you please review this ticket? If we are good on the outcome and metrics and activities dashboard, I think we are good to close for this ticket. We might have a greater perspective on what to do with example boxes like other state expenses when we work on that page or on 4381.

**Comment by SGilliamA1M** [comment]
Itemized example boxes looks good and okay to close @jeromeleecms

**Comment by jeromeleecms** [comment]
@akuas Added some follow-up comments, please take a look at let me know if you have questions. But once we sort through that, I think this is good to go as well.

**Comment by akuas** [comment]
@jeromeleecms I made changes to the copy based on your suggestions. So, I think this is good to close.

**Comment by jeromeleecms** [comment]
This is done. Refer to the comments in Figma for final closing remarks.
