### ISSUE TITLE
[Feature] LaunchDarkly Implementation

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#4064]
### Description and related issues
CMS has enabled use of LaunchDarkly for feature flags. @thetif and @jeromeleecms will work with the CMS team involved with this to implement. Currently the process requires:

1) Request Job codes for CMS's Launch Darkly instance
2) Have eAPD specific Job code created and added to our team's EUA
3) Have licenses provisioned to our testing team

once this is in place, we'll look to apply launch darkly to our Admin Check - we will also have to discuss how we determine which features will have the feature flags implemented (maybe an update to our Dev template?)

### This task is done when…

- [ ] Request Job codes for CMS's Launch Darkly instance
- [ ] Have eAPD specific Job code created and added to our team's EUA
- [ ] Have licenses provisioned to our testing team
- [ ] We have a process in place to determine how we use/track implementation of feature flags against features
- [ ] Team has been trained on how to implement feature flags (through applying it to one of our features)

**Comment by jeromeleecms** [comment]
Done.
