### ISSUE TITLE
[Quality] Read the MES Testing Guide Framework and create a page in our Quality wiki acknowledging its contents 

### ISSUE THREAD

**Issue by mirano-darren** [CMSgov/eAPD#4072]
Describe the task here and link or add dependencies to any applicable issues...

Medicaid Enterprise Systems (MES) has a Testing Guidance Framework [here](https://www.medicaid.gov/medicaid/data-and-systems/downloads/mes-testing-guidance-framework.pdf). Read through this document and create a page on the wiki of things we have already been doing and things we should adopt. 

### This task is done when...

- [ ] Read through the MES Testing Guidance
- [ ] Information researched has been documented on a [wiki](https://github.com/CMSgov/eAPD/wiki) page

**Comment by jeromeleecms** [comment]
This is pending @itsonlydio to merge his work into the [Google Doc](https://docs.google.com/document/d/1zX3H49wmNIShxgQdAWm4J1CtBdJSiYUuxLPY69rSSno/edit#heading=h.qd5rulujb5x8) before final review with Tif.
