### ISSUE TITLE
[Quality] Document Quality review process in the wiki

### ISSUE THREAD

**Issue by mirano-darren** [CMSgov/eAPD#4074]
Describe the task here and link or add dependencies to any applicable issues...

Our quality process is not written down anywhere. Create a page in the wiki to document the whole process down. 

### This task is done when...

- [x] a wiki page has been written about the Quality process
- [x] work has been reviewed by the Quality team
- [x] work has been reviewed by the Design 
- [x] work has been reviewed by the Dev 
- [x] work has been reviewed by the DevOps
- [x] work has been reviewed by the Product

**Comment by jeromeleecms** [comment]
Per Slack from @mirano-darren - this is going to be presented in a brownbag (#4102) before closing so the team has a chance to review.

**Comment by mirano-darren** [comment]
Presented/reviewed alongside #4102. Link to the wiki page [here](https://github.com/CMSgov/eAPD/wiki/Quality-Process).
