### ISSUE TITLE
Create Documentation: Packer

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#4149]
Create a Wiki article on how to use Packer, how we use Packer, how it fits into our CICD, etc...

### This task is done when...

- [x] Document has been created
- [ ] Document has been walked through

**Comment by cthulhuplus** [comment]
@thetif @tbolt @itsonlydio can I get a review of this document please?
https://github.com/CMSgov/eAPD/wiki/Packer:-Building-AMIs-Runbook

**Comment by cthulhuplus** [comment]
@thetif @tbolt could you review this document and note in the Issue when you've had a look?
https://github.com/CMSgov/eAPD/wiki/Packer:-Building-AMIs-Runbook

**Comment by mirano-darren** [comment]
Instructions are concise and clear!

**Comment by cthulhuplus** [comment]
Updated based on Darren's feedback
