### ISSUE TITLE
[Bug] FTE component does not allow numbers less than 0.1

### ISSUE THREAD

**Issue by Sun-Mountain** [CMSgov/eAPD#4161]
### Description

The FTE component does not allow numbers less than `0.1`. When a user attempts to type in `0.0...` the form defaults to `0`.

### Steps to reproduce

1. Go to Key State Personnel and add Primary Contact
2. For `Does this person have costs directly attributable to this program?` select `Yes`
3. Attempt to put any number in the FTE form component any number that begins `0.0...`

**Expected results-**

To be able to input a number with as many zeros as `0.00001`.

**Actual results-**

It resets to `0`.

### Role Affected

- [ ] All
- [ ] Federal Admin
- [x] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

### Environment

- [x] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

### Browser

- [x] All
- [ ] Firefox
- [ ] Chrome
- [ ] IE

**Related user story/bug-** (if applicable)

**Additional information-** (optional)

**Logs or error output/Screenshot/Video-** (at least 1 of these)

![CPT2206231016-315x97.gif](https://images.zenhubusercontent.com/6168859bc72e6d33b2fd8d84/a27f7984-4237-4862-a11f-de4f4936288f)

**Comment by tbolt** [comment]
@jeromeleecms it does appear there is a workaround where you can enter 0.1 and then add another zero- 0.01

not ideal but might be useful in the event someone encounters this before we deploy a fix
