### ISSUE TITLE
Update Log Rotation Configuration Mongo

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#4168]
The Mongo server ran out of disk space in the /var/log partition. Update the logrotate configuration to prevent this from being a reoccurring problem.

### This task is done when...

- [ ] Update Packer/user-data scripts to update the logrotate configuration
- [ ] Update manually deployed resources to have the new logrotate configuration or redeploy Mongo resources with new config

**Comment by cthulhuplus** [comment]
Logging Guidance:
https://cloud.cms.gov/best-practices-logging-application-development

**Comment by cthulhuplus** [comment]
New AMIs have been created for Preview, Staging, and Production instances.

**Comment by cthulhuplus** [comment]
Staging Mongo has been updated by hand

**Comment by jeromeleecms** [comment]
This was done with #4236!
