### ISSUE TITLE
July 2022 Newsletter / Office Hours

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#4176]
With June Office Hours and the newsletter out, we should turn our sights to July! 

### This task is done when...

- [ ] Agenda for office hours are set
- [ ] Newsletter is drafted / reviewed / distributed

**Comment by jeromeleecms** [comment]
Potential "Did you know?" if you have an existing EUA account with the EUA job code, you automatically have a sandbox account. You still need to be assigned a state through the verification process, but that's one less form to complete and one less password to track.

**Comment by CSwartzHMA** [comment]
Also, we discussed concerns around posting the newsletters outside of Slack. Has there been any further conversation? I wanted to be sure we are making the information accessible, within publication guidelines.

**Comment by tbolt** [comment]
Ideas for the newsletter:
* Upcoming enhancements/features - What to expect from them
* Quick tips - Small tips on how to get more from the system. Kinda like a "Did you know"
* Success highlights - If any of the states are willing to share their success stories we could include them

**Comment by jeromeleecms** [comment]
We had planned to do every month, but if there is nothing to report on, we can extend the duration to every other month until MMIS is close to release. If we have office hours next week, we can probably talk about inline validation and what that offers for the admin check.

**Comment by jeromeleecms** [comment]
No newsletter content for this July/August. August office hours completed. Looking forward to the next one and to improve content collection for next newsletter.
