### ISSUE TITLE
AWS Setup for Quality Team

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#4184]
https://jiraent.cms.gov/browse/CLDSUPSD-14592

The link above is an example of a Jira request asking for an AWS account for the eAPD AWS Account.

```
Project: CMS Cloud Support (CLDSPT)
Issue Type: Service Request
Request Type: Account Creation - AWS
ADO / Application Name: eAPD Hi-C
Summary: AWS Permissions Request / Account Creation
Description: I am a Quality Engineer on the eAPD team and need access to their AWS environment. My privileges should mirror that of B9OS.
1. Name, Last Name: 
2. EUA ID: 
3. Phone text-able #:
4. Email.: 
```

### This task is done when...

- [ ] You can log into the AWS Console: https://aws-hhs-cms-cmcs-hi-c.signin.aws.amazon.com/console
- [ ] You can see the following areas of the AWS Console: EC2, RDS, CloudWatch, etc...

**Comment by mirano-darren** [comment]
Submitted Jira ticket on 7/28. Now waiting for access

**Comment by cthulhuplus** [comment]
@mirano-darren @itsonlydio 

How's this going? Do you have access to eAPD AWS?

**Comment by itsonlydio** [comment]
My login credential are not working in CMS, I reached out to help desk via email and phone with inadequate response.

**Comment by jeromeleecms** [comment]
@itsonlydio Did the helpdesk give you any ideas for next steps?
