### ISSUE TITLE
EUA Job Codes for Quality Team

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#4185]
In order to access Jira and other resources to gain access to AWS you will need to request the following job codes in eua.

https://eua.cms.gov/

```
JIRA_Users
CMS_CLOUD_ACCESS
AWS_EAPD_SPLUNK
AWS_Splunk_User
```

### This task is done when...

- [ ] Can access Jira: https://jiraent.cms.gov/

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by cthulhuplus** [comment]
1. Log into https://eua.cms.gov
2. Click "Modify My Job Codes" on the navigation bar on the left of the page
3. Click the Confirmation box, and click next
4. Click "Add a Job Code"
5. Request these job codes (DevOps Job Codes) https://docs.google.com/document/d/1IghhXKiuZ80W82EnuJoUCVXcDyVLDjfL2pcTHciISnw/edit
6. Select the Job Code you want to add
7. Click Select
8. After you've selected all of your job codes click "Next"
9. Provide the justification, something like "As one of the Test Engineers on the eAPD team, I need access to these tools to perform my duties"
10. Click "Finish"

**Comment by cthulhuplus** [comment]
Darren was only missing 
```
AWS_EAPD_SPLUNK
AWS_Splunk_User
```
and now has them

**Comment by mirano-darren** [comment]
@itsonlydio can you access Jira? If so, I think we can close this out

**Comment by jeromeleecms** [comment]
This is done!
