### ISSUE TITLE
[Design Issue] Create a page in MMIS Figma file to show each validation component in the system 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#4188]
Create a page in MMIS Figma file to show each validation component in the system 

On this page we should document each type of input field in the eAPD system, and show an example of the validation pattern for that input field. We should generally have examples of all fields somewhere in the HITECH Figma file that can be copy/pasted into the MMIS file, and it will be useful to have a page in the MMIS file that documents these components in one place. 

### This task is done when…
- [x] Make a list of all input components 
- [x] In Figma, show validation content and visual pattern for each input component
- [x] Note in the file what the page is for, and how we use the design system for these components (or how we deviate)
- [x] Note in the file which validations we do inline and which we do in the admin check. 
- [ ] Include a link to the admin check pages in Mural? (Maybe)
- [x] Add a link to the validation Mural in #2054 where the validation content and considerations are kept (this Mural is 90+% accurate still, but what is in each validation ticket and coded into the eAPD system should be considered the source of truth at this point) 
- [ ] Add an "important design links" section somewhere in the wiki and link to this new page

**Comment by akuas** [comment]
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=473%3A8498
Above is the validation library @beparticular Can you please review it? Also, @tbolt can you please take a look and see if Im missing anything or whether there is any additional info that may be helpful to devs? I especially wanted to make sure that the admin check and table validation was correct since they are in progress.

**Comment by akuas** [comment]
@jeromeleecms Can you please review the validation library?

**Comment by jeromeleecms** [comment]
@akuas Overall this looks good. 

1) Similar to what we looked at with whole numbers, can we apply that to the $ field? "Provide a dollar value greater than zero. Any cents will be rounded to the nearest dollar."

**Comment by akuas** [comment]
@jeromeleecms I'm not too sure what you are asking here?

**Comment by jeromeleecms** [comment]
@akuas For this field (or any $ fields), add the language "Provide a dollar value greater than zero. Any cents will be rounded to the nearest dollar."
 
![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/116e1ee2-4b52-46e5-b785-898cd17e590b)

**Comment by jeromeleecms** [comment]
@akuas For this field (or any $ fields), add the language "Provide a dollar value greater than zero. Any cents will be rounded to the nearest dollar."
 
![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/116e1ee2-4b52-46e5-b785-898cd17e590b)

**Comment by akuas** [comment]
@jeromeleecms Thanks, I added your note on how we validate $ fields, so we should be good to go now.

**Comment by jeromeleecms** [comment]
This is done!
