### ISSUE TITLE
Fix Logging to Staging/Production

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#4201]
Logging to Staging/Production seems to be busted for Application logs. Fix it.

### This task is done when...

- [ ] Staging and Production are successfully reporting to CloudWatch

**Comment by cthulhuplus** [comment]
@jeromeleecms do we want to wait for a release to confirm that the prod logs are making it to CloudWatch again or are we satisfied that they're making it to Staging (the mechanisms for Prod and Staging are the same)

**Comment by jeromeleecms** [comment]
Pending release - we will review to ensure functionality.

**Comment by cthulhuplus** [comment]
Logs are making it to CloudWatch again, closing ticket
