### ISSUE TITLE
[Feature] Add validation errors to APD model

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#4212]
### Description and related issues
Update the APD module to store the validation errors. This model should match the format expected by redux on the frontend.

### This task is done when…

- [ ] update the APD module to hold validation errors
- [ ] migration created to update APDs with validation errors

**Comment by jeromeleecms** [comment]
Let's verify if we still needs this @thetif @tbolt - if it's not useful lets close this as OBE.

**Comment by thetif** [comment]
decided to not store validation in the APD
