### ISSUE TITLE
[Dev] Update backend for create new APD page

### ISSUE THREAD

**Issue by mirano-darren** [CMSgov/eAPD#4219]
Describe the task here and link or add dependencies to any applicable issues...

Figma link: https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=0%3A1

The addition of the new Create APD page comes with 2 new fields. 
  - Is this APD an update? section
  - Medicaid Business Areas

Update the mongo schema with these fields. 
Is this APD an update? (no subsection when "No, this is a new project" is selected):
![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/77a5086a-dfa9-4dbd-bb97-5f662b4f770b)

Medicaid Business Areas:
![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/d20e9487-46e5-4914-842e-2af4b9dcd1f6)

Update the APD model to add something like:
```
{
    apdType: ['HITECH IAPD', 'MMIS IAPD'],
    isUpdate: ['annual update', 'as-needed update', null],
    medicaidBusinessAreas: {
        waiverSupportSystems: boolean,
        assetVerificationSystem: boolean,
        claimsProcessing: boolean,
        decisionsSupportSystemDataWarehouse: boolean,
        electronicVisitVerification: boolean,
        epsManagedCareSystem: boolean,
        financialManagement: boolean,
        healthInformationExchange: boolean,
        longTermServicesSupports: boolean,
        memberManagement: boolean,
        pbmPOS: boolean,
        programIntegrity: boolean,
        providerManagement: boolean,
        thirdPartyLiability: boolean,
        other: string
    }
}
```

### This task is done when...

- [ ] mongo schema has been updated
- [ ] create a mongoose migration
- [ ] all fields are saved correctly

**Comment by thetif** [comment]
resolved in #4365
