### ISSUE TITLE
[Design Issue] Remove Estimated Quarterly Expenditures table for MMIS 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#4243]
The EQE table is not necessary for MES APD types. 
This table will need to be removed from the FFP and Budget page within Activities. 

Design considerations - will the tables and information on the FFP and Budget page still flow well once these are removed. 

**Final Design:**
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=601%3A12578

### This task is done when…

- [x] any acceptance criteria (not process oriented, requirements of feature)
- [x] designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [x] 508 visual, content, and UX considerations and/or recommendations are reviewed
- [x] designs are shared
- [x] designs are approved by product
- [x] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by akuas** [comment]
Below are the designs for updated Budget and FFP. Currently, we are keeping the FFP on this page, so I keep it there but in the future that may change. @jeromeleecms Can you please review this ticket?
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=601%3A12578

**Comment by akuas** [comment]
@jeromeleecms I feel like this ticket can still be closed with the blocker. We could just remove the FFP if we need to in the future.

**Comment by jeromeleecms** [comment]
Overall looks fine - only thing to note is that the summary table shows the years for FFY 2021 - FFY 2022, but the page only shows the data table for one FFY 2021. 

Also: I don't think we need a blocker because #4215 is something we'll address, but we don't want to stop this ticket from moving forward.

**Comment by akuas** [comment]
@jeromeleecms I made the dates all FFY 2022, so it is consistent now.

**Comment by akuas** [comment]
@mirano-darren @itsonlydio @thetif This ticket is now ready for dev.

**Comment by jeromeleecms** [comment]
The dev ticket is #4304

**Comment by SGilliamA1M** [comment]
@jeromeleecms - Final review of changes have been verified and good to proceed to Dev.

**Comment by jeromeleecms** [comment]
Sounds good.
