### ISSUE TITLE
[Design Issue] Document in Figma all field changes for MMIS

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#4250]
This will be an ongoing effort as we continue to design for the MES expansion/MMIS V1. 

Dev has noted that a page by page list of changes to fields/help text, etc. 
This can exist in the MMIS Figma file on each page of the new designs so that devs know when they are working on tickets for those pages, they can verify they are making the right changes. 

On each Figma page we can show
- What was (a screenshot of the currently released system) 
- what changed (a text changlog), 
- What it's supposed to look like (the existing designs we are working on)

### This task is done when…

- [ ] all MMIS changes are documented

**Comment by beparticular** [comment]
@tbolt we have some examples of this in the MMIS Figma file where we show in the annotation what has changed, what is still up for debate, etc. 

@jeromeleecms the items we annotated on these pages in our convo today will need dev tickets noting the changes we will make for MMIS based on the research done in 2021: 
Activity Overview
Analysis of Alts
Activity Schedule...
Conditions for Enhanced Funding

**Comment by akuas** [comment]
The mmis changes file fulfills what I was expecting for this ticket a master list, page by page list of changes to fields. So, @jeromeleecms I think this ticket is good to close.
https://docs.google.com/spreadsheets/d/1yCB-XfLO6QJL4iugFhoUHZWYJZ7IMtwBI8ZgtVilHmE/edit?pli=1#gid=0

**Comment by jeromeleecms** [comment]
@thetif @mirano-darren Just tagging you both as we close, but this will be a good reference for future work.
