### ISSUE TITLE
Update items in the admin check to appear grey when the corresponding field is filled out

### ISSUE THREAD

**Issue by tbolt** [CMSgov/eAPD#4253]
When the admin check is enabled, the admin check panel will list each field that needs to be filled out. Upon filling out a field, the appearance will change to grey. Only if the admin check is closed and re-ran will the items be removed from the list.

### This task is done when...

- [ ] Items in the admin check panel appear grey when "completed"

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by tbolt** [comment]
@jeromeleecms @thetif I think this ticket is no longer needed

**Comment by jeromeleecms** [comment]
Works for me. Closing.
