### ISSUE TITLE
[Design Issue] Remove fields labeled HIE and HIT for MMIS APDs for Results of Previous Activities 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#4256]
The following fields/elements should be removed in order to implement an MMIS APD. This is currently blocked by MDBT work and decisions. (Other related work is in #3685, this is to set aside Results of Previously activities until MDBT work is done. There is a note on the [MES Expansion Mural ](https://app.mural.co/t/ccs9461/m/cmsmural6360/1595447450055/62389cb615fe3e42a37e34bf0ba2347814e88ba7?sender=48ffe766-9eb7-4806-9af3-6663779ff9a6)that this work would be blocked by the MDBT work.)

**Results of Previous Activities**
- HIT + HIE Federal share 90% FFP
- Funding source in Grand totals

### This task is done when…

- [ ] any acceptance criteria (not process oriented, requirements of feature)
- [ ] designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] 508 visual, content, and UX considerations and/or recommendations are reviewed
- [ ] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by akuas** [comment]
Current design for Results of Previous Activities without HIE + HIT
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=970%3A11404

**Comment by jeromeleecms** [comment]
This is done in #3685.
