### ISSUE TITLE
Introduction to GitHub Actions

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#4274]
GitHub Actions is a DevOps tool that helps deployment. It allows you to build, test, and deploy all based on configurable settings.  Please read some of the official GitHub Actions docs, do the tutorial, and document any ideas for testing, questions on how we use it, ideas on how we can use it better, etc... These tutorials should be doable on an free tier AWS account, please DO NOT use this against the eAPD AWS account.

GitHub Actions "Tutorial:"
https://docs.github.com/en/actions/learn-github-actions

### This task is done when...

- [ ] Once You've Completed the GitHub Actions tutorial

**Comment by itsonlydio** [comment]
link to the drive doc [https://docs.google.com/document/d/1XiyJTTARMXGmysSG6cDCWbM3PwaKQy-ykr7IIaYn6W0/edit?usp=sharing](url)
