### ISSUE TITLE
Prepare Presentation

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#4278]
Prepare a brief presentation on what you've learned with AWS, Packer, Terraform, CircleCI, and GitHub Actions.

### This task is done when...

- [ ] Prepare presentation
- [ ] Present to Bill

**Comment by itsonlydio** [comment]
link to slideshow [https://docs.google.com/presentation/d/1qnZrdI5ZRJ647D01f1XoFNzFrz1UsbOMu2H73Ocg6xA/edit?usp=sharing](url)

**Comment by itsonlydio** [comment]
New link [https://docs.google.com/presentation/d/1iTkTeRFau-BhVwfrtcerzXgMOGOH4rn8/edit?usp=sharing&ouid=100757836723204844393&rtpof=true&sd=true](url)
