### ISSUE TITLE
Create Enterprise-CMCS Test Plan

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#4285]
Create Enterprise-CMCS/eAPD-Test test plan. 

### This task is done when...

- [x] List integration points
- [x] Test integrations
- [x] Mock/Test normal operations

**Comment by cthulhuplus** [comment]
Request approval for new repo by logging into the repo settings > Integrations > Applications > Authorized OAuth Apps > Click on Application > Request

**Comment by cthulhuplus** [comment]
Zenhub
CircleCI
CodeCov
Cypress
Chromatic
Storybook

**Comment by cthulhuplus** [comment]
e2e tests are failing, struggling to figure out the why

**Comment by cthulhuplus** [comment]
Added cms-eapd-bot to eAPD-Forked

**Comment by cthulhuplus** [comment]
Successfully ran through the entire CircleCI workfrlow

**Comment by cthulhuplus** [comment]
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by cthulhuplus** [comment]
@thetif can you review this migration plan document?
https://docs.google.com/document/d/1zRDCe_mOG6pvO8rVo9Tsz1Tnj5gO7qPZdwSaA_QKcGk/edit?usp=sharing

**Comment by thetif** [comment]
looks good to me

**Comment by cthulhuplus** [comment]
@jeromeleecms and @stephanieboydcms can you take a glance at the GitHub Migration plan and give me your thoughts?

**Comment by jeromeleecms** [comment]
This seems fine - it seems like we've accounted for all our third party tools + adding the ones that inspired our migration.

**Comment by cthulhuplus** [comment]
https://jiraent.cms.gov/browse/CLDSPT-37071

**Comment by jeromeleecms** [comment]
This is done!
