### ISSUE TITLE
Add Cypress Axe for APD Builder

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#4287]
Describe the task here and link or add dependencies to any applicable issues...
Install cypress axe. Add axe tests to all pages.

### This task is done when...

- [ ] cypress axe is running on all pages

**Comment by mirano-darren** [comment]
Also need to fix any issues that the cypress-axe test catch. Sizing to a large.

**Comment by mirano-darren** [comment]
Mural for accessibility errors found
https://app.mural.co/t/ccs9461/m/ccs9461/1663781550087/cc724fe946d9a23082cc3fd6c2f45f8df5d586b4?sender=381cf91c-f266-4761-8881-37f602a5f8de
