### ISSUE TITLE
[Documentation] Contingency plan for Quality team

### ISSUE THREAD

**Issue by mirano-darren** [CMSgov/eAPD#4288]
Describe the task here and link or add dependencies to any applicable issues...
Write up a contingency plan in the event the Quality team is out. 

### This task is done when...

- [ ] contingency plan is written
- [ ] contingency plan is documented with the other contingency plans

**Comment by jeromeleecms** [comment]
@itsonlydio Please add the required sections and let the team leads know that it's ready for us to review.

**Comment by mirano-darren** [comment]
@jeromeleecms @thetif Contingency doc is ready for review! 
Link: https://docs.google.com/document/d/17a0K9vNOc731loJXw_WvZliDgklxWy7nqqylBME2BJQ/edit#heading=h.1a9eh1devw4e

**Comment by jeromeleecms** [comment]
@mirano-darren @itsonlydio Added some revision requests + some comments. 

@thetif when you get a chance, please take a look as well.

**Comment by mirano-darren** [comment]
Tif said it looks good to her! Closing this out
