### ISSUE TITLE
AWS: S3 - Buckets

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#4293]
Learn about the S3 section of AWS, focus on; Buckets by going through the AWS documentation for S3 Buckets.
Completed the reading and exercises here:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/GetStartedWithS3.html
Topics:
    Prerequisite: Setting up Amazon S3
    Step 1: Create your first S3 bucket
    Step 2: Upload an object to your bucket
    Step 3: Download an object
    Step 4: Copy your object to a folder
    Step 5: Delete your objects and bucket
    Next steps
    Access control best practices

### This task is done when...

- [x] You have an understanding of what S3 Buckets are
- [x] You have an understanding of how S3 Buckets are used by eAPD

**Comment by itsonlydio** [comment]
Went through to steps in creating and deleting buckets and objects,

**Comment by cthulhuplus** [comment]
Have you looked at the documentation for Next Steps and Access Control Best Practices?
