### ISSUE TITLE
Upgrade RDS Instance Types

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#4296]
Hi Jerome & eAPD team,

I wanted to make you aware that the current eAPD RDS Postgres RIs ri-2021-09-21-16-19-37-041 and ri-2021-09-21-16-17-16-590 that are expiring on 9/20 cannot be renewed because AWS has made those m3 instance types as end of life. Can your team review those RDS instances and create a plan to migrate/update to the comparable recent generation instance type? Please share your plan by the end of next week if possible. In case you need more time, please let us know. 

Best,
Vidit  

### This task is done when...

- [x] RDS Instance Types have been upgraded
- [x] Vidit has been informed of upgrade

---

Add additional labels (design, dev, compliance, BUG, etc) and size before
submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add
it to the "This Sprint" pipeline. Otherwise, all other issues will be
automatically added to the _unprioritized pipeline_ for prioritization in
backlog refinement or sprint planning with Product.

**Comment by cthulhuplus** [comment]
Staging has been upgraded to db.m5.large, smallest available RDS of the current generation

Production upgrade is set to happen during our "scheduled maintenance window" on September 2nd

There were no issues with the Staging upgrade

**Comment by jeromeleecms** [comment]
From Fed admin perspective - this seems to be functioning as expected. Changes related to the bug fixing for matching also came through so I could test if changes were registered after matching.
