### ISSUE TITLE
Upgrade PostGres Staging

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#4301]
PostGresQL 10 is reach EoL soon and we need to upgrade. Testing compatibility with PostGresQL 13.4 worked well in Preview and is the most reason version available in RDS. 

### This task is done when...

- [x] Staging has been upgraded to PostGres 13.4

**Comment by cthulhuplus** [comment]
PostGresQL RDS has been upgraded to 13.4 in Staging, please poke at it to make sure it is working. Properly. @thetif @tbolt @itsonlydio

**Comment by mirano-darren** [comment]
Poked around staging in the APD builder and the fed admin portal. Everything was acting like expected. LGTM
