### ISSUE TITLE
Upgrade PostGres Prod

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#4302]
PostGresQL 10 is reach EoL soon and we need to upgrade. Testing compatibility with PostGresQL 13.4 worked well in Preview and Staging and is the most reason version available in RDS. 

### This task is done when...

- [ ] Production has been upgraded to PostGres 13.4

**Comment by cthulhuplus** [comment]
Staging upgrade appears to be working properly, scheduled Prod upgrade for this weekend.

**Comment by jeromeleecms** [comment]
From Fed Admin side: Unsure if it's related to the migration, but there were some missing field data in the Fed admin dashboard; issue was manually fixed and everything else seems to be working fine.
