### ISSUE TITLE
ATO documentation

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#4303]
Stanley Wilson is the new ISSO for MACPro and eAPD is in scope for ACT coming up in October. He needs access to some documentation from our ATO.

### This task is done when Stanley has links and access to...

- [x] System Design Document
- [x] Request / Complete New Pen Test 
- [x] Software Inventory
- [x] Fill in our parts of the SSP
- [x] Fill in our parts of the CP
- [x] Fill in our parts of the ISRA
- [ ] PIA
~[ ] Authorization Boundary Diagram~
~[ ] SIA's (If Applicable)~
~[ ] Business Description/System Description~
~[ ] any other resources/documents regarding eAPD.~

---

Add additional labels (design, dev, compliance, BUG, etc) and size before
submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add
it to the "This Sprint" pipeline. Otherwise, all other issues will be
automatically added to the _unprioritized pipeline_ for prioritization in
backlog refinement or sprint planning with Product.

**Comment by cthulhuplus** [comment]
@jeromeleecms requested and received the job codes required to access CFACTS

**Comment by jeromeleecms** [comment]
We've done our part, not pending review by ISSO
