### ISSUE TITLE
[Design Issue] Add Activity button clarity

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#4324]
This Add Activity button feels a little out of place. Design a way to add a little clarity to the button

![image.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/bf78feb7-69ea-431c-a603-663f402a3f15)

### This task is done when…

- [ ] context has been added around the button

**Comment by akuas** [comment]
For my reference: Language could say something to the effect of you have reached the end of activity one to create an additional activity select add activity to continue to activity schedule summary select the continue button below.

**Comment by akuas** [comment]
@SGilliamA1M for awareness

**Comment by SGilliamA1M** [comment]
@thetif - there are two proposed design solutions that I've implemented that would address

**Comment by jeromeleecms** [comment]
Option I is fine. Made a small note in the Figma, @SGilliamA1M. Can you make any closing notes and reassign to @mirano-darren to write the dev ticket?

**Comment by SGilliamA1M** [comment]
**Closing Notes:**

**Approved Design I [Activities - Budget and FFP](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1584%3A13652)** 

- Add context above button (leveraging existing design pattern), to provide clearer instructions for adding an additional Activity.

**Comment by jeromeleecms** [comment]
this is done
