### ISSUE TITLE
[Bug] Validation showing in the print view

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#4326]
### Description
The validation highlighting is showing up in the export view.

### Steps to reproduce

1. Create APD
2. Navigate to Export and Submit
3. Click Continue to Review
4. Scroll down to Estimated Quarterly Expenditure

**Expected results-**
Should not show validation highlighting

**Actual results-**
Shows validation highlighting

### Role Affected

- [ ] All
- [ ] Federal Admin
- [x] State Admin
- [x] State Staff
- [x] State Contractor
- [ ] System Admin

### Environment

- [ ] All
- [ ] PR #\_\_\_\_
- [x] Staging
- [ ] Production

### Browser

- [x] All
- [ ] Firefox
- [ ] Chrome
- [ ] IE

**Logs or error output/Screenshot/Video-** (at least 1 of these)
![CleanShot 2022-09-22 at 15.20.20.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/9f258f98-b263-4ffe-b1d4-528716d365e4)

**Comment by mirano-darren** [comment]
Fixed in #4342!

**Comment by jeromeleecms** [comment]
This was done with #4342.
