### ISSUE TITLE
[Cypress] Speed up apd-data test

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#4328]
### Description and related issues
The APD data test is already testing a lot. We need to move the delete test from apd-data to apd-basic (which is already covering a lot. The APD data test should just test adding data and validating that it was added correctly and displays correctly everywhere (including budget values).

We should also remove all of the places where the tests are doing math and replace it with a fixture that has whatever the static value should be. For example in the HIE test:
```
const staffTotal = staff1.costs[i] * staff1.ftes[i] + staff2.costs[i] * staff2.ftes[i];
const expenseTotal = expense1.costs[i] + expense2.costs[i];
const contractorTotal = contractor1.FFYcosts[i] + contractor2.FFYcosts[i][0] * contractor2.FFYcosts[i][1];
const activityTotalCosts = staffTotal + expenseTotal + contractorTotal;
const otherFunding = activityData.costAllocation.costs[i];
```
staffTotal, expenseTotal contractorTotal, activityTotalCosts and otherFunding should just be values that we pull from the HIE fixture.

### This task is done when…

- [x] all of the delete tests have been moved from apd-data to apd-basic
- [x] the math has been removed from the apd-data test

**Comment by mirano-darren** [comment]
Runtime of 03-apd-with-data **before** changes: 14:56
Runtime of 03-apd-with-data **after** changes: 12:56
