### ISSUE TITLE
[Design Issue] Create Usability Testing and Feedback Strategy for the Create a New APD Feature

### ISSUE THREAD

**Issue by SGilliamA1M** [CMSgov/eAPD#4329]
Ceate a usability testing and feedback strategy for the Create a New APD feature. The documented plan will be used for evaluating eAPD's new feature functionality, navigation and task completion efficiently.

### This task is done when…

- [ ] Business objectives and user goals are defined
- [ ] Target participants are defined
- [ ] Identify best-fit prototype method
- [ ] Tasks/use case scenarios are defined
- [ ] Feedback collection (survey, remote interview, etc.) plan defined
- [ ] Data analysis and synthesis report defined
- [ ] Initial strategy presented

**Comment by jeromeleecms** [comment]
@SGilliamA1M Just checking on this one - are we feeling that this is "done enough" for us to try and use as a foundation for implementation? We can close and then revise as we start using it as part of due course.

**Comment by SGilliamA1M** [comment]
@jeromeleecms - The User Research and Feedback doc is from a foundation perspective is good to go. 

- Shared Document: https://docs.google.com/presentation/d/1jP6y9VhV_iv-T-kH3nFMhmx7Ybl1MOTM1Ugj9qSiTa0/edit?usp=sharing

**Comment by jeromeleecms** [comment]
Sounds good - I've added a link to on our Mural board as reference material. Closing this out.
