### ISSUE TITLE
[Design Issue] List out MMIS pages in side navigation

### ISSUE THREAD

**Issue by akuas** [CMSgov/eAPD#4357]
Dev needs a list of MMIS pages in the left side nav to create a schema.
[Final Design](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1515%3A12934)
[Side Navigation Figma Page](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=2%3A4470) (for future reference)

### This task is done when…

- [x] A list of mmis pages including subpages is listed
- [x] left nav design is created
- [ ] 508 visual, content, and UX considerations and/or recommendations are
      reviewed
- [ ] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added
      to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

---

Add additional labels (design, dev, compliance, BUG, etc) and size before
submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add
it to the "This Sprint" pipeline. Otherwise, all other issues will be
automatically added to the _unprioritized pipeline_ for prioritization in
backlog refinement or sprint planning with Product.

**Comment by akuas** [comment]
@mirano-darren Below is the list of the side nav content + the google sheet listing them out. In the design, I show all the subsections expanded. Let me know if you have any questions.
[Updated MMIS side nav: All expanded](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1515%3A12934)
[Left Nav Structure](https://docs.google.com/spreadsheets/d/1yCB-XfLO6QJL4iugFhoUHZWYJZ7IMtwBI8ZgtVilHmE/edit?usp=sharing)

**Comment by jeromeleecms** [comment]
@akuas I don't see a spot in the nav bar for "Security, Interface, Disaster Recover, and Business Continuity Planning" (per the Google sheet). 

@mirano-darren your Dev ticket indicates that the acceptance criteria is determined base don what's in the Figma. Besides the one change mentioned above, that should be fine to leave it a little open ended.

**Comment by jeromeleecms** [comment]
This is done! (8 days later)
