### ISSUE TITLE
Add Mongo Recovery to Contingency Plans

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#4374]
There is no recovery plan for our Mongo instances. We need to create a Mongo Recovery plan.

### This task is done when...

- [x] Create Mongo Recovery plan
- [x] Create followup issue to test Recovery plan

**Comment by cthulhuplus** [comment]
@thetif @jeromeleecms @stephanieboydcms 
This is the untested Mongo Recovery Plan. I spun up an issue to run through it, please take a look and let me know if you have any requests before considering this issue complete.

**Comment by thetif** [comment]
looks good, thank you for listing out all the instructions, looks easy to follow
